class DType(object): ...

class Float16(DType): ...
Half = Float16
class Float32(DType): ...
class Float64(DType): ...
Double = Float64
class BFloat16(DType): ...
class Complex64(DType): ...
class Complex128(DType): ...
class Int8(DType): ...
class UInt8(DType): ...
class UInt16(DType): ...
class UInt32(DType): ...
class UInt64(DType): ...
class Int16(DType): ...
class Int32(DType): ...
class Int64(DType): ...
class Bool(DType): ...
class String(DType): ...
class QInt8(DType): ...
class QUInt8(DType): ...
class QInt16(DType): ...
class QUInt16(DType): ...
class QInt32(DType): ...
class Resource(DType): ...
class Variant(DType): ...

class Float16Ref(DType): ...
HalfRef = Float16Ref
class Float32Ref(DType): ...
class Float64Ref(DType): ...
DoubleRef = Float64Ref
class BFloat16Ref(DType): ...
class Complex64Ref(DType): ...
class Complex128Ref(DType): ...
class Int8Ref(DType): ...
class UInt8Ref(DType): ...
class UInt16Ref(DType): ...
class UInt32Ref(DType): ...
class UInt64Ref(DType): ...
class Int16Ref(DType): ...
class Int32Ref(DType): ...
class Int64Ref(DType): ...
class BoolRef(DType): ...
class StringRef(DType): ...
class QInt8Ref(DType): ...
class QUInt8Ref(DType): ...
class QInt16Ref(DType): ...
class QUInt16Ref(DType): ...
class QInt32Ref(DType): ...
class ResourceRef(DType): ...
class VariantRef(DType): ...


float16: Float16
half: Float16
float32: Float32
float64: Float64
double: Float64
bfloat16: BFloat16
complex64: Complex64
complex128: Complex128
int8: Int8
uint8: UInt8
uint16: UInt16
uint32: UInt32
uint64: UInt64
int16: Int16
int32: Int32
int64: Int64
bool: Bool
string: String
qint8: QInt8
quint8: QUInt8
qint16: QInt16
quint16: QUInt16
qint32: QInt32
resource: Resource
variant: Variant

float16_ref: Float16Ref
half_ref: Float16Ref
float32_ref: Float32Ref
float64_ref: Float64Ref
double_ref: Float64Ref
bfloat16_ref: BFloat16Ref
complex64_ref: Complex64Ref
complex128_ref: Complex128Ref
int8_ref: Int8Ref
uint8_ref: UInt8Ref
uint16_ref: UInt16Ref
uint32_ref: UInt32Ref
uint64_ref: UInt64Ref
int16_ref: Int16Ref
int32_ref: Int32Ref
int64_ref: Int64Ref
bool_ref: BoolRef
string_ref: StringRef
qint8_ref: QInt8Ref
quint8_ref: QUInt8Ref
qint16_ref: QInt16Ref
quint16_ref: QUInt16Ref
qint32_ref: QInt32Ref
resource_ref: ResourceRef
variant_ref: VariantRef
