class DType(object): ...

class Float16(DType): ...
Half = Float16
class Float32(DType): ...
class Float64(DType): ...
Double = Float64
class BFloat16(DType): ...
class Complex64(DType): ...
class Complex128(DType): ...
class Int8(DType): ...
class UInt8(DType): ...
class UInt16(DType): ...
class UInt32(DType): ...
class UInt64(DType): ...
class Int16(DType): ...
class Int32(DType): ...
class Int64(DType): ...
class Bool(DType): ...
class String(DType): ...
class QInt8(DType): ...
class QUInt8(DType): ...
class QInt16(DType): ...
class QUInt16(DType): ...
class QInt32(DType): ...
class Resource(DType): ...
class Variant(DType): ...

class Float16_Ref(DType): ...
Half_Ref = Float16_Ref
class Float32_Ref(DType): ...
class Float64_Ref(DType): ...
Double_Ref = Float64_Ref
class BFloat16_Ref(DType): ...
class Complex64_Ref(DType): ...
class Complex128_Ref(DType): ...
class Int8_Ref(DType): ...
class UInt8_Ref(DType): ...
class UInt16_Ref(DType): ...
class UInt32_Ref(DType): ...
class UInt64_Ref(DType): ...
class Int16_Ref(DType): ...
class Int32_Ref(DType): ...
class Int64_Ref(DType): ...
class Bool_Ref(DType): ...
class String_Ref(DType): ...
class QInt8_Ref(DType): ...
class QUInt8_Ref(DType): ...
class QInt16_Ref(DType): ...
class QUInt16_Ref(DType): ...
class QInt32_Ref(DType): ...
class Resource_Ref(DType): ...
class Variant_Ref(DType): ...


float16: Float16
half: Float16
float32: Float32
float64: Float64
double: Float64
bfloat16: BFloat16
complex64: Complex64
complex128: Complex128
int8: Int8
uint8: UInt8
uint16: UInt16
uint32: UInt32
uint64: UInt64
int16: Int16
int32: Int32
int64: Int64
bool: Bool
string: String
qint8: QInt8
quint8: QUInt8
qint16: QInt16
quint16: QUInt16
qint32: QInt32
resource: Resource
variant: Variant

float16_ref: Float16_Ref
half_ref: Float16_Ref
float32_ref: Float32_Ref
float64_ref: Float64_Ref
double_ref: Float64_Ref
bfloat16_ref: BFloat16_Ref
complex64_ref: Complex64_Ref
complex128_ref: Complex128_Ref
int8_ref: Int8_Ref
uint8_ref: UInt8_Ref
uint16_ref: UInt16_Ref
uint32_ref: UInt32_Ref
uint64_ref: UInt64_Ref
int16_ref: Int16_Ref
int32_ref: Int32_Ref
int64_ref: Int64_Ref
bool_ref: Bool_Ref
string_ref: String_Ref
qint8_ref: QInt8_Ref
quint8_ref: QUInt8_Ref
qint16_ref: QInt16_Ref
quint16_ref: QUInt16_Ref
qint32_ref: QInt32_Ref
resource_ref: Resource_Ref
variant_ref: Variant_Ref
