# Description:
# Old string tensors data packages.

load("//tensorflow:tensorflow.bzl", "filegroup")

package(
    licenses = ["notice"],
)

filegroup(
    name = "old_string_tensors_testdata",
    srcs = [
        "foo.data-00000-of-00001",
        "foo.index",
    ],
    visibility = ["//visibility:public"],
)
