# Description:
# bmp test data package alias.

package(
    licenses = ["notice"],  # Apache 2.0
)

alias(
    name = "bmp_testdata",
    actual = "//tensorflow/core/lib/bmp/testdata:bmp_testdata",
    visibility = ["//visibility:public"],
)
