package(
    default_visibility = [
        "//tensorflow/core:__pkg__",
    ],
    licenses = ["notice"],  # Apache 2.0
)

alias(
    name = "testdata",
    actual = "//tensorflow/core/lib/psnr/testdata:psnr_testdata",
)
