#include "CEVA_TFLM_lib.h"
#define CEVA_TFLM_KERNELS_SCRATCH_SIZE_VAL_DEF 32768
int32_t CEVA_TFLM_KERNELS_SCRATCH_SIZE_VAL = 32768;
#ifndef WIN32
__attribute__((section(".MODEL_DATA")))
#endif
int32_t CEVA_TFLM_KERNELS_SCRATCH[CEVA_TFLM_KERNELS_SCRATCH_SIZE_VAL_DEF];

// namespace
