pipeline:
  name: tensorflow pr pipeline chaining
  identifier: tensorflow_pr_pipeline_chaining
  projectIdentifier: parson
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: Testing
        identifier: Testing
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |
                      echo "trigger.prNumber: <+trigger.prNumber>"
                      echo "trigger.branch: <+trigger.branch>"
                      echo "pipeline var: <+variablepipeline.variables.triggerPrNumber>"
    - stage:
        name: Child 1
        identifier: Child_1
        description: ""
        type: Pipeline
        spec:
          org: SE_Sandbox
          pipeline: tensorflow_chained_child_pipeline_1
          project: parson
          outputs: []
          inputSetReferences:
            - childinputsetprnumber
        tags: {}
        variables: []
  variables:
    - name: triggerPrNumber
      type: String
      description: ""
      value: <+input>
