# Description:
# BUILD rules for the frontend libraries in TensorBoard.

package(default_visibility = [
    "//tensorflow:internal",
])

licenses(["notice"])  # Apache 2.0

exports_files([
    "LICENSE",
])
