// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: hlo-opt %s --platform=gpu --xla_gpu_mlir_emitter_level=0 --xla_gpu_mlir_emitter_level=0 --stage=llvm-before-optimizations --xla_gpu_target_config_filename=%S/../../../tools/hlo_opt/gpu_specs/%{GPU}.txtpb --split-input-file | FileCheck --check-prefixes=CHECK,CHECK-%{PTX} %s

HloModule Transpose, is_scheduled=true

%fused_computation {
  %p0 = f32[2,16,17]{2,1,0} parameter(0)
  ROOT %transpose = f32[2,17,16]{2,1,0} transpose(%p0), dimensions={0,2,1}
}

ENTRY main {
  %param = f32[2,16,17]{2,1,0} parameter(0)
  ROOT %fusion = f32[2,17,16] fusion(%param), kind=kInput, calls=%fused_computation
}

// CHECK-LABEL: entry:
// CHECK:         %[[VAL_0:.*]] = alloca i32, align 4
// CHECK:         %[[VAL_1:.*]] = alloca i32, align 4
// CHECK:         %[[VAL_2:.*]] = alloca i32, align 4
// CHECK:         %[[VAL_3:.*]] = alloca i32, align 4
// CHECK-PTX:     %thread.id.x = call i32 @llvm.nvvm.read.ptx.sreg.tid.x(), !range !2
// CHECK-GCN:     %thread.id.x = call i32 @llvm.amdgcn.workitem.id.x
// CHECK-PTX:     %block.id.x = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x(), !range !3
// CHECK-GCN:     %block.id.x = call i32 @llvm.amdgcn.workgroup.id.x
// CHECK:         %[[VAL_4:.*]] = udiv i32 %thread.id.x, 32
// CHECK:         %thread.id.1 = urem i32 %[[VAL_4]], 4
// CHECK:         %thread.id.2 = urem i32 %thread.id.x, 32
// CHECK:         %lane_id = urem i32 %thread.id.x, 32
// CHECK:         %[[VAL_5:.*]] = udiv i32 %block.id.x, 1
// CHECK:         %[[VAL_6:.*]] = urem i32 %[[VAL_5]], 1
// CHECK:         %[[VAL_7:.*]] = udiv i32 %block.id.x, 1
// CHECK:         %[[VAL_8:.*]] = urem i32 %[[VAL_7]], 1
// CHECK:         %[[VAL_9:.*]] = udiv i32 %block.id.x, 1
// CHECK:         %[[VAL_10:.*]] = icmp eq i32 %[[VAL_8]], 0
// CHECK:         %tile_bound.1 = select i1 %[[VAL_10]], i32 16, i32 32
// CHECK:         %[[VAL_11:.*]] = icmp eq i32 %[[VAL_6]], 0
// CHECK:         %tile_bound.2 = select i1 %[[VAL_11]], i32 17, i32 32
// CHECK:         %tile_origin.0 = mul i32 %[[VAL_9]], 1
// CHECK:         %tile_origin.1 = mul i32 %[[VAL_8]], 32
// CHECK:         %tile_origin.2 = mul i32 %[[VAL_6]], 32
// CHECK:         store i32 %thread.id.1, ptr{{.*}} %[[VAL_3]], align 4
// CHECK:         br label %[[VAL_12:.*]]
// CHECK:       loop1.loop_header:                                ; preds = %[[VAL_13:.*]], %[[VAL_14:.*]]
// CHECK:         %[[VAL_15:.*]] = load i32, ptr{{.*}} %[[VAL_3]], align 4
// CHECK:         %[[VAL_16:.*]] = icmp uge i32 %[[VAL_15]], %tile_bound.1
// CHECK:         br i1 %[[VAL_16]], label %[[VAL_17:.*]], label %[[VAL_18:.*]]
// CHECK:       loop1.loop_body:                                  ; preds = %[[VAL_12]]
// CHECK:         %[[VAL_19:.*]] = add nuw nsw i32 %[[VAL_15]], 4
// CHECK:         store i32 %[[VAL_19]], ptr{{.*}} %[[VAL_3]], align 4
// CHECK:         store i32 %thread.id.2, ptr{{.*}} %[[VAL_2]], align 4
// CHECK:         br label %[[VAL_21:.*]]
// CHECK:       loop2.loop_header:                                ; preds = %[[VAL_22:.*]], %[[VAL_18]]
// CHECK:         %[[VAL_23:.*]] = load i32, ptr{{.*}} %[[VAL_2]], align 4
// CHECK:         %[[VAL_24:.*]] = icmp uge i32 %[[VAL_23]], %tile_bound.2
// CHECK:         br i1 %[[VAL_24]], label %[[VAL_13]], label %[[VAL_22]]
// CHECK:       loop2.loop_body:                                  ; preds = %[[VAL_21]]
// CHECK:         %[[VAL_25:.*]] = add nuw nsw i32 %[[VAL_23]], 32
// CHECK:         store i32 %[[VAL_25]], ptr{{.*}} %[[VAL_2]], align 4
// CHECK:         %[[VAL_27:.*]] = add i32 %tile_origin.0, 0
// CHECK:         %[[VAL_28:.*]] = add i32 %tile_origin.1, %[[VAL_15]]
// CHECK:         %[[VAL_29:.*]] = add i32 %tile_origin.2, %[[VAL_23]]
// CHECK:         %[[VAL_30:.*]] = getelementptr{{.*}} inbounds [2 x [16 x [17 x float]]], ptr{{.*}} %[[VAL_31:.*]], i32 0, i32 %[[VAL_27]], i32 %[[VAL_28]], i32 %[[VAL_29]]
// CHECK:         %[[VAL_32:.*]] = load float, ptr{{.*}} %[[VAL_30]], align 4, !invariant.load !{{[0-9]}}
// CHECK:         %[[VAL_33:.*]] = getelementptr{{.*}} inbounds [1 x [32 x [33 x float]]], ptr{{.*}} addrspace(3) @tr_tile_0, i32 0, i32 0, i32 %[[VAL_15]], i32 %[[VAL_23]]
// CHECK:         %[[VAL_34:.*]] = addrspacecast ptr{{.*}} addrspace(3) %[[VAL_33]] to ptr
// CHECK:         store float %[[VAL_32]], ptr{{.*}} %[[VAL_34]], align 4
// CHECK:         br label %[[VAL_21]], !llvm.loop !{{[0-9]}}
// CHECK:       loop2.loop_exit:                                  ; preds = %[[VAL_21]]
// CHECK:         br label %[[VAL_12]], !llvm.loop !{{[0-9]}}
// CHECK:       loop1.loop_exit:                                  ; preds = %[[VAL_12]]
// CHECK-PTX:     call void @llvm.nvvm.barrier0()
// CHECK-GCN:     call void @llvm.amdgcn.s.barrier()
// CHECK:         store i32 %thread.id.1, ptr{{.*}} %[[VAL_1]], align 4
// CHECK:         br label %[[VAL_35:.*]]
// CHECK:       loop1.loop_header4:                               ; preds = %[[VAL_36:.*]], %[[VAL_17]]
// CHECK:         %[[VAL_37:.*]] = load i32, ptr{{.*}} %[[VAL_1]], align 4
// CHECK:         %[[VAL_38:.*]] = icmp uge i32 %[[VAL_37]], %tile_bound.2
// CHECK:         br i1 %[[VAL_38]], label %[[VAL_39:.*]], label %[[VAL_40:.*]]
// CHECK:       loop1.loop_body5:                                 ; preds = %[[VAL_35]]
// CHECK:         %[[VAL_41:.*]] = add nuw nsw i32 %[[VAL_37]], 4
// CHECK:         store i32 %[[VAL_41]], ptr{{.*}} %[[VAL_1]], align 4
// CHECK:         store i32 %thread.id.2, ptr{{.*}} %[[VAL_0]], align 4
// CHECK:         br label %[[VAL_43:.*]]
// CHECK:       loop2.loop_header10:                              ; preds = %[[VAL_44:.*]], %[[VAL_40]]
// CHECK:         %[[VAL_45:.*]] = load i32, ptr{{.*}} %[[VAL_0]], align 4
// CHECK:         %[[VAL_46:.*]] = icmp uge i32 %[[VAL_45]], %tile_bound.1
// CHECK:         br i1 %[[VAL_46]], label %[[VAL_36]], label %[[VAL_44]]
// CHECK:       loop2.loop_body11:                                ; preds = %[[VAL_43]]
// CHECK:         %[[VAL_47:.*]] = add nuw nsw i32 %[[VAL_45]], 32
// CHECK:         store i32 %[[VAL_47]], ptr{{.*}} %[[VAL_0]], align 4
// CHECK:         %[[VAL_49:.*]] = add i32 %tile_origin.0, 0
// CHECK:         %[[VAL_50:.*]] = add i32 %tile_origin.2, %[[VAL_37]]
// CHECK:         %[[VAL_51:.*]] = add i32 %tile_origin.1, %[[VAL_45]]
// CHECK:         %[[VAL_52:.*]] = getelementptr{{.*}} inbounds [1 x [32 x [33 x float]]], ptr{{.*}} addrspace(3) @tr_tile_0, i32 0, i32 0, i32 %[[VAL_45]], i32 %[[VAL_37]]
// CHECK:         %[[VAL_53:.*]] = addrspacecast ptr{{.*}} addrspace(3) %[[VAL_52]] to ptr
// CHECK:         %[[VAL_54:.*]] = load float, ptr{{.*}} %[[VAL_53]], align 4
// CHECK:         %[[VAL_55:.*]] = getelementptr{{.*}} inbounds [2 x [17 x [16 x float]]], ptr{{.*}} %[[VAL_56:.*]], i32 0, i32 %[[VAL_49]], i32 %[[VAL_50]], i32 %[[VAL_51]]
// CHECK:         store float %[[VAL_54]], ptr{{.*}} %[[VAL_55]], align 4
// CHECK:         br label %[[VAL_43]], !llvm.loop !{{[0-9]}}
// CHECK:       loop2.loop_exit9:                                 ; preds = %[[VAL_43]]
// CHECK:         br label %[[VAL_35]], !llvm.loop !{{[0-9]}}
// CHECK:       loop1.loop_exit3:                                 ; preds = %[[VAL_35]]
// CHECK:         ret void
