// RUN: xla-translate -hlo-text-to-mlir-hlo  -hlo-import-all-computations %s -o - | FileCheck %s

HloModule entry, entry_computation_layout={(f32[2,3,4]{0,1,2}, f32[2,3,4]{1,2,0}, (f32[1,2]{1,0}, f32[1,2]{0,1}), s32[]{:T(128)})->f32[2,3,4]{2,0,1}}

ENTRY entry {
  p0 = f32[2,3,4]{2,1,0} parameter(0)
  p1 = f32[2,3,4]{2,1,0} parameter(1)
  p2 = (f32[1,2]{1,0}, f32[1,2]{0,1}) parameter(2)
  p3 = s32[]{:T(128)} parameter(3)
  ROOT add = f32[2,3,4]{2,1,0} add(p0, p1)
}

// CHECK: module @entry
// CHECK-SAME: mhlo.xla_entry_computation_parameter_layouts = [
// CHECK-SAME:   dense<[0, 1, 2]> : tensor<3xindex>,
// CHECK-SAME:   dense<[1, 2, 0]> : tensor<3xindex>,
// CHECK-SAME:   [dense<[1, 0]> : tensor<2xindex>,
// CHECK-SAME:    dense<[0, 1]> : tensor<2xindex>],
// CHECK-SAME:   dense<> : tensor<0xindex>]
// CHECK-SAME: mhlo.xla_entry_computation_parameter_tiles = [
// CHECK-SAME:   [],
// CHECK-SAME:   [],
// CHECK-SAME:   [
// CHECK-SAME:     [],
// CHECK-SAME:     []
// CHECK-SAME:   ],
// CHECK-SAME:   [dense<128> : tensor<1xindex>]
// CHECK-SAME: ],
// CHECK-SAME: mhlo.xla_entry_computation_result_layout = dense<[2, 0, 1]> : tensor<3xindex>
// CHECK-SAME: mhlo.xla_entry_computation_result_tiles = []
