# Text form of tensorflow.tfcompile.Config proto.
feed{ id{node_name:"inputs/x_seq_0/read"} shape{dim{size:128}dim{size:1024}} }
feed{ id{node_name:"inputs/x_seq_1/read"} shape{dim{size:128}dim{size:1024}} }
feed{ id{node_name:"inputs/x_seq_2/read"} shape{dim{size:128}dim{size:1024}} }
feed{ id{node_name:"inputs/x_seq_3/read"} shape{dim{size:128}dim{size:1024}} }
feed{ id{node_name:"inputs/x_seq_4/read"} shape{dim{size:128}dim{size:1024}} }
feed{ id{node_name:"inputs/pad_seq_0/read"} shape{dim{size:128}dim{size:1}} }
feed{ id{node_name:"inputs/pad_seq_1/read"} shape{dim{size:128}dim{size:1}} }
feed{ id{node_name:"inputs/pad_seq_2/read"} shape{dim{size:128}dim{size:1}} }
feed{ id{node_name:"inputs/pad_seq_3/read"} shape{dim{size:128}dim{size:1}} }
feed{ id{node_name:"inputs/pad_seq_4/read"} shape{dim{size:128}dim{size:1}} }
feed{ id{node_name:"weights/read"} shape{dim{size:2048}dim{size:4096}} }
feed{ id{node_name:"init_c"} shape{dim{size:128}dim{size:1024}} }
feed{ id{node_name:"init_m"} shape{dim{size:128}dim{size:1024}} }

fetch{ id{node_name:"lstm_0/out"} }
fetch{ id{node_name:"lstm_1/out"} }
fetch{ id{node_name:"lstm_2/out"} }
fetch{ id{node_name:"lstm_3/out"} }
fetch{ id{node_name:"lstm_4/out"} }
