op {
  name: "BeginEpoch"
  input_arg {
    name: "dataset_id"
    type: DT_INT64
  }
  input_arg {
    name: "address"
    type: DT_STRING
  }
  input_arg {
    name: "protocol"
    type: DT_STRING
  }
  output_arg {
    name: "epoch_id"
    type: DT_INT64
  }
}
