op {
  name: "ChooseFastestDataset"
  input_arg {
    name: "input_datasets"
    type: DT_VARIANT
    number_attr: "N"
  }
  output_arg {
    name: "handle"
    type: DT_VARIANT
  }
  attr {
    name: "N"
    type: "int"
    has_minimum: true
    minimum: 2
  }
  attr {
    name: "num_experiments"
    type: "int"
  }
  attr {
    name: "output_types"
    type: "list(type)"
    has_minimum: true
    minimum: 1
  }
  attr {
    name: "output_shapes"
    type: "list(shape)"
    has_minimum: true
    minimum: 1
  }
}
