op {
  name: "InfeedEnqueueTuple"
  input_arg {
    name: "inputs"
    type_list_attr: "dtypes"
  }
  attr {
    name: "dtypes"
    type: "list(type)"
    has_minimum: true
    minimum: 1
  }
  attr {
    name: "shapes"
    type: "list(shape)"
  }
  attr {
    name: "layouts"
    type: "list(int)"
    default_value {
      list {
      }
    }
  }
  attr {
    name: "device_ordinal"
    type: "int"
    default_value {
      i: -1
    }
  }
  is_stateful: true
}
