op {
  name: "IteratorToStringHandle"
  input_arg {
    name: "resource_handle"
    type: DT_RESOURCE
  }
  output_arg {
    name: "string_handle"
    type: DT_STRING
  }
  is_stateful: true
}
