op {
  name: "RaggedRange"
  input_arg {
    name: "starts"
    type_attr: "T"
  }
  input_arg {
    name: "limits"
    type_attr: "T"
  }
  input_arg {
    name: "deltas"
    type_attr: "T"
  }
  output_arg {
    name: "rt_nested_splits"
    type: DT_INT64
  }
  output_arg {
    name: "rt_dense_values"
    type_attr: "T"
  }
  attr {
    name: "T"
    type: "type"
    default_value {
      type: DT_INT32
    }
    allowed_values {
      list {
        type: DT_BFLOAT16
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
op {
  name: "RaggedRange"
  input_arg {
    name: "starts"
    type_attr: "T"
  }
  input_arg {
    name: "limits"
    type_attr: "T"
  }
  input_arg {
    name: "deltas"
    type_attr: "T"
  }
  output_arg {
    name: "rt_nested_splits"
    type_attr: "Tsplits"
  }
  output_arg {
    name: "rt_dense_values"
    type_attr: "T"
  }
  attr {
    name: "T"
    type: "type"
    default_value {
      type: DT_INT32
    }
    allowed_values {
      list {
        type: DT_BFLOAT16
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
  attr {
    name: "Tsplits"
    type: "type"
    default_value {
      type: DT_INT64
    }
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
