op {
  name: "RFFT"
  input_arg {
    name: "input"
    type: DT_FLOAT
  }
  input_arg {
    name: "fft_length"
    type: DT_INT32
  }
  output_arg {
    name: "output"
    type: DT_COMPLEX64
  }
}
op {
  name: "RFFT"
  input_arg {
    name: "input"
    type_attr: "Treal"
  }
  input_arg {
    name: "fft_length"
    type: DT_INT32
  }
  output_arg {
    name: "output"
    type_attr: "Tcomplex"
  }
  attr {
    name: "Treal"
    type: "type"
    default_value {
      type: DT_FLOAT
    }
    allowed_values {
      list {
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }
  }
  attr {
    name: "Tcomplex"
    type: "type"
    default_value {
      type: DT_COMPLEX64
    }
    allowed_values {
      list {
        type: DT_COMPLEX64
        type: DT_COMPLEX128
      }
    }
  }
}
