op {
  name: "SerializeTensor"
  input_arg {
    name: "tensor"
    type_attr: "T"
  }
  output_arg {
    name: "serialized"
    type: DT_STRING
  }
  attr {
    name: "T"
    type: "type"
  }
}
