op {
  name: "SparseMatrixTranspose"
  input_arg {
    name: "input"
    type: DT_VARIANT
  }
  output_arg {
    name: "output"
    type: DT_VARIANT
  }
  attr {
    name: "conjugate"
    type: "bool"
    default_value {
      b: false
    }
  }
  attr {
    name: "type"
    type: "type"
    allowed_values {
      list {
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_COMPLEX64
        type: DT_COMPLEX128
      }
    }
  }
}
