# The version is always required
version: 0
# Top level metadata is always required
metadata:
  name: "TaskCluster TensorFlow build"
  description: "Building CPU & GPU TensorFlow"
  owner: "{{ event.head.user.email }}" # the user who sent the pr/push e-mail will be inserted here
  source: "{{ event.head.repo.url }}"  # the repo where the pr came from will be inserted here
tasks:
  ## PULL REQUEST FOR GPU BUILDS
  # What kind of environment will you need (docker, windows, etc...)
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    # Be careful with spacing under the lines with dashes. Next line should begin under the word, not under the dash.
    # Worker types correspond to particular machine types (aws size, etc...)
    # worker types may be added by priveleged taskcluster users at https://tools.taskcluster.net/aws-provisioner
    workerType: "deepspeech-worker"
    extra:
      github:
        # This must be set in order access GitHub info from inside your environment
        env: true
        # Events that will trigger this task
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 14400
      image: "ubuntu:14.04"
      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          apt-get -qq update && apt-get -qq -y install git &&
          adduser --system --home /home/build-user build-user &&
          cd /home/build-user &&
          echo -e "#!/bin/bash\nset -xe\nenv && id && mkdir ~/DeepSpeech/ && git clone --quiet {{event.head.repo.url}} ~/DeepSpeech/tf/ && cd ~/DeepSpeech/tf && git checkout --quiet {{event.head.sha}}" > /tmp/clone.sh && chmod +x /tmp/clone.sh &&
          sudo -H -u build-user /bin/bash /tmp/clone.sh &&
          /home/build-user/DeepSpeech/tf/tc-apt.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-setup.sh --cuda &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-build.sh --gpu &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-package.sh
      artifacts:
        "public":
          type: "directory"
          path: "/tmp/artifacts/"
          expires: "{{ '7 days' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow GPU"
      description: "Building TensorFlow with GPU support"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  ## PUSH TO MAIN REPO FOR GPU BUILDS
  # What kind of environment will you need (docker, windows, etc...)
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    # Be careful with spacing under the lines with dashes. Next line should begin under the word, not under the dash.
    # Worker types correspond to particular machine types (aws size, etc...)
    # worker types may be added by priveleged taskcluster users at https://tools.taskcluster.net/aws-provisioner
    workerType: "deepspeech-worker"
    extra:
      github:
        # This must be set in order access GitHub info from inside your environment
        env: true
        # Events that will trigger this task
        events:
          - push
        branches:
          - master
    routes:
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.gpu"
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.{{ event.head.sha }}.gpu"
      - "index.project.deepspeech.tensorflow.pip.gpu.{{ event.head.sha }}"
    payload:
      maxRunTime: 14400
      image: "ubuntu:14.04"
      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          apt-get -qq update && apt-get -qq -y install git &&
          adduser --system --home /home/build-user build-user &&
          cd /home/build-user/ &&
          echo -e "#!/bin/bash\nset -xe\nenv && id && mkdir ~/DeepSpeech/ && git clone --quiet {{event.head.repo.url}} ~/DeepSpeech/tf/ && cd ~/DeepSpeech/tf && git checkout --quiet {{event.head.sha}}" > /tmp/clone.sh && chmod +x /tmp/clone.sh &&
          sudo -H -u build-user /bin/bash /tmp/clone.sh &&
          /home/build-user/DeepSpeech/tf/tc-apt.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-setup.sh --cuda &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-build.sh --gpu &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-package.sh
      artifacts:
        "public":
          type: "directory"
          path: "/tmp/artifacts/"
          expires: "{{ '6 months' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow GPU"
      description: "Building TensorFlow with GPU support"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  ## PULL REQUEST FOR CPU BUILDS
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "deepspeech-worker"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 7200
      image: "ubuntu:14.04"
      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          apt-get -qq update && apt-get -qq -y install git &&
          adduser --system --home /home/build-user build-user &&
          cd /home/build-user/ &&
          echo -e "#!/bin/bash\nset -xe\nenv && id && mkdir ~/DeepSpeech/ && git clone --quiet {{event.head.repo.url}} ~/DeepSpeech/tf/ && cd ~/DeepSpeech/tf && git checkout --quiet {{event.head.sha}}" > /tmp/clone.sh && chmod +x /tmp/clone.sh &&
          sudo -H -u build-user /bin/bash /tmp/clone.sh &&
          /home/build-user/DeepSpeech/tf/tc-apt.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-setup.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-build.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-package.sh
      artifacts:
        "public":
          type: "directory"
          path: "/tmp/artifacts/"
          expires: "{{ '7 days' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow CPU only"
      description: "Building TensorFlow with CPU only support"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  ## PUSH TO MAIN REPO FOR CPU BUILDS
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "deepspeech-worker"
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    routes:
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.cpu"
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.{{ event.head.sha }}.cpu"
      - "index.project.deepspeech.tensorflow.pip.cpu.{{ event.head.sha }}"
    payload:
      maxRunTime: 7200
      image: "ubuntu:14.04"
      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          apt-get -qq update && apt-get -qq -y install git &&
          adduser --system --home /home/build-user build-user &&
          cd /home/build-user/ &&
          echo -e "#!/bin/bash\nset -xe\nenv && id && mkdir ~/DeepSpeech/ && git clone --quiet {{event.head.repo.url}} ~/DeepSpeech/tf/ && cd ~/DeepSpeech/tf && git checkout --quiet {{event.head.sha}}" > /tmp/clone.sh && chmod +x /tmp/clone.sh &&
          sudo -H -u build-user /bin/bash /tmp/clone.sh &&
          /home/build-user/DeepSpeech/tf/tc-apt.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-setup.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-build.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-package.sh
      artifacts:
        "public":
          type: "directory"
          path: "/tmp/artifacts/"
          expires: "{{ '6 months' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow CPU only"
      description: "Building TensorFlow with CPU only support"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  ## PULL REQUEST FOR ARM CPU BUILDS
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "deepspeech-worker"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 7200
      image: "ubuntu:14.04"
      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          apt-get -qq update && apt-get -qq -y install git &&
          adduser --system --home /home/build-user build-user &&
          cd /home/build-user/ &&
          echo -e "#!/bin/bash\nset -xe\nenv && id && mkdir ~/DeepSpeech/ && git clone --quiet {{event.head.repo.url}} ~/DeepSpeech/tf/ && cd ~/DeepSpeech/tf && git checkout --quiet {{event.head.sha}}" > /tmp/clone.sh && chmod +x /tmp/clone.sh &&
          sudo -H -u build-user /bin/bash /tmp/clone.sh &&
          /home/build-user/DeepSpeech/tf/tc-apt.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-setup.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-build.sh --arm &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-package.sh
      artifacts:
        "public":
          type: "directory"
          path: "/tmp/artifacts/"
          expires: "{{ '7 days' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow ARM CPU only"
      description: "Building TensorFlow with ARM CPU only support"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  ## PUSH TO MAIN REPO FOR ARM CPU BUILDS
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "deepspeech-worker"
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    routes:
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.arm"
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.{{ event.head.sha }}.arm"
      - "index.project.deepspeech.tensorflow.pip.arm.{{ event.head.sha }}"
    payload:
      maxRunTime: 7200
      image: "ubuntu:14.04"
      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          apt-get -qq update && apt-get -qq -y install git &&
          adduser --system --home /home/build-user build-user &&
          cd /home/build-user/ &&
          echo -e "#!/bin/bash\nset -xe\nenv && id && mkdir ~/DeepSpeech/ && git clone --quiet {{event.head.repo.url}} ~/DeepSpeech/tf/ && cd ~/DeepSpeech/tf && git checkout --quiet {{event.head.sha}}" > /tmp/clone.sh && chmod +x /tmp/clone.sh &&
          sudo -H -u build-user /bin/bash /tmp/clone.sh &&
          /home/build-user/DeepSpeech/tf/tc-apt.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-setup.sh &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-build.sh --arm &&
          sudo -H -u build-user /bin/bash /home/build-user/DeepSpeech/tf/tc-package.sh
      artifacts:
        "public":
          type: "directory"
          path: "/tmp/artifacts/"
          expires: "{{ '6 months' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow ARM CPU only"
      description: "Building TensorFlow with ARM CPU only support"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  ## PULL REQUEST FOR OSX SIERRA CPU BUILDS
  - provisionerId: "localprovisioner"
    workerType: "deepspeech-macos"
    extra:
      github:
        # This must be set in order access GitHub info from inside your environment
        env: true
        # Events that will trigger this task
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 14400
      # There is no VM yet running tasks on OSX
      # so one should install by hand:
      # - brew
      # - xcode (brew would install)
      # - brew install git
      # - brew install pixz
      # - brew cask install java
      # - sudo easy_install pip
      command:
        - - "/bin/bash"
          - "--login"
          - "-cxe"
          - >
            export TASKCLUSTER_ARTIFACTS="$(pwd)/public/" &&
            export TASKCLUSTER_TASK_ROOT="$(pwd)" &&
            export TASKCLUSTER_TASK_DIR="$(dirname `pwd`)/task-${GITHUB_HEAD_SHA}" &&
            mkdir -p ${TASKCLUSTER_TASK_DIR}/DeepSpeech/ &&
            env &&
            git clone --quiet {{event.head.repo.url}} ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/ &&
            cd ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf && git checkout --quiet {{event.head.sha}} && cd ${TASKCLUSTER_TASK_DIR} &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-brew.sh &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-setup.sh &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-build.sh &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-package.sh;
            cd ${TASKCLUSTER_TASK_ROOT} && rm -fr ${TASKCLUSTER_TASK_DIR}
      artifacts:
        - type: "directory"
          path: "public/"
          expires: "{{ '7 days' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow CPU for OSX 10.12"
      description: "Building TensorFlow with CPU only support for OSX 10.12"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"


  ## PUSH TO MAIN REPO FOR OSX SIERRA CPU BUILDS
  - provisionerId: "localprovisioner"
    # Be careful with spacing under the lines with dashes. Next line should begin under the word, not under the dash.
    # Worker types correspond to particular machine types (aws size, etc...)
    # worker types may be added by priveleged taskcluster users at https://tools.taskcluster.net/aws-provisioner
    workerType: "deepspeech-macos"
    extra:
      github:
        # This must be set in order access GitHub info from inside your environment
        env: true
        # Events that will trigger this task
        events:
          - push
        branches:
          - master
    routes:
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.osx"
      - "index.project.deepspeech.tensorflow.pip.{{ event.head.repo.branch }}.{{ event.head.sha }}.osx"
      - "index.project.deepspeech.tensorflow.pip.osx.{{ event.head.sha }}"
    payload:
      maxRunTime: 14400
      # There is no VM yet running tasks on OSX
      # so one should install by hand:
      # - brew
      # - xcode (brew would install)
      # - brew install git
      # - brew install pixz
      # - brew cask install java
      # - sudo easy_install pip
      command:
        - - "/bin/bash"
          - "--login"
          - "-cxe"
          - >
            export TASKCLUSTER_ARTIFACTS="$(pwd)/public/" &&
            export TASKCLUSTER_TASK_ROOT="$(pwd)" &&
            export TASKCLUSTER_TASK_DIR="$(dirname `pwd`)/task-${GITHUB_HEAD_SHA}" &&
            mkdir -p ${TASKCLUSTER_TASK_DIR}/DeepSpeech/ &&
            env &&
            git clone --quiet {{event.head.repo.url}} ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/ &&
            cd ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf && git checkout --quiet {{event.head.sha}} && cd ${TASKCLUSTER_TASK_DIR} &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-brew.sh &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-setup.sh &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-build.sh &&
            ${TASKCLUSTER_TASK_DIR}/DeepSpeech/tf/tc-package.sh;
            cd ${TASKCLUSTER_TASK_ROOT} && rm -fr ${TASKCLUSTER_TASK_DIR}
      artifacts:
        - type: "directory"
          path: "public/"
          expires: "{{ '6 months' | $fromNow }}"
    # Each task also requires explicit metadata
    metadata:
      name: "TaskCluster TensorFlow CPU for OSX 10.12"
      description: "Building TensorFlow with CPU only support for OSX 10.12"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
