# TensorFlow API backwards compatibility test goldens.

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

filegroup(
    name = "api_golden_v1",
    srcs = glob(["v1/*.pbtxt"]),
)

filegroup(
    name = "api_golden_v2",
    srcs = glob(["v2/*.pbtxt"]),
)
