path: "tensorflow.keras.wrappers.scikit_learn"
tf_module {
  member {
    name: "KerasClassifier"
    mtype: "<type \'type\'>"
  }
  member {
    name: "KerasRegressor"
    mtype: "<type \'type\'>"
  }
}
