path: "tensorflow.keras.constraints.Constraint"
tf_class {
  is_instance: "<class \'tensorflow.python.keras._impl.keras.constraints.Constraint\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
