path: "tensorflow.keras.applications"
tf_module {
  member {
    name: "inception_v3"
    mtype: "<type \'module\'>"
  }
  member {
    name: "mobilenet"
    mtype: "<type \'module\'>"
  }
  member {
    name: "resnet50"
    mtype: "<type \'module\'>"
  }
  member {
    name: "vgg16"
    mtype: "<type \'module\'>"
  }
  member {
    name: "vgg19"
    mtype: "<type \'module\'>"
  }
  member {
    name: "xception"
    mtype: "<type \'module\'>"
  }
  member_method {
    name: "InceptionV3"
    argspec: "args=[\'include_top\', \'weights\', \'input_tensor\', \'input_shape\', \'pooling\', \'classes\'], varargs=None, keywords=None, defaults=[\'True\', \'imagenet\', \'None\', \'None\', \'None\', \'1000\'], "
  }
  member_method {
    name: "MobileNet"
    argspec: "args=[\'input_shape\', \'alpha\', \'depth_multiplier\', \'dropout\', \'include_top\', \'weights\', \'input_tensor\', \'pooling\', \'classes\'], varargs=None, keywords=None, defaults=[\'None\', \'1.0\', \'1\', \'0.001\', \'True\', \'imagenet\', \'None\', \'None\', \'1000\'], "
  }
  member_method {
    name: "ResNet50"
    argspec: "args=[\'include_top\', \'weights\', \'input_tensor\', \'input_shape\', \'pooling\', \'classes\'], varargs=None, keywords=None, defaults=[\'True\', \'imagenet\', \'None\', \'None\', \'None\', \'1000\'], "
  }
  member_method {
    name: "VGG16"
    argspec: "args=[\'include_top\', \'weights\', \'input_tensor\', \'input_shape\', \'pooling\', \'classes\'], varargs=None, keywords=None, defaults=[\'True\', \'imagenet\', \'None\', \'None\', \'None\', \'1000\'], "
  }
  member_method {
    name: "VGG19"
    argspec: "args=[\'include_top\', \'weights\', \'input_tensor\', \'input_shape\', \'pooling\', \'classes\'], varargs=None, keywords=None, defaults=[\'True\', \'imagenet\', \'None\', \'None\', \'None\', \'1000\'], "
  }
  member_method {
    name: "Xception"
    argspec: "args=[\'include_top\', \'weights\', \'input_tensor\', \'input_shape\', \'pooling\', \'classes\'], varargs=None, keywords=None, defaults=[\'True\', \'imagenet\', \'None\', \'None\', \'None\', \'1000\'], "
  }
}
