path: "tensorflow.estimator.EstimatorSpec"
tf_class {
  is_instance: "<class \'tensorflow.python.estimator.model_fn.EstimatorSpec\'>"
  is_instance: "<class \'tensorflow.python.estimator.model_fn.EstimatorSpec\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "eval_metric_ops"
    mtype: "<type \'property\'>"
  }
  member {
    name: "evaluation_hooks"
    mtype: "<type \'property\'>"
  }
  member {
    name: "export_outputs"
    mtype: "<type \'property\'>"
  }
  member {
    name: "loss"
    mtype: "<type \'property\'>"
  }
  member {
    name: "predictions"
    mtype: "<type \'property\'>"
  }
  member {
    name: "scaffold"
    mtype: "<type \'property\'>"
  }
  member {
    name: "train_op"
    mtype: "<type \'property\'>"
  }
  member {
    name: "training_chief_hooks"
    mtype: "<type \'property\'>"
  }
  member {
    name: "training_hooks"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
