path: "tensorflow.keras.layers.AvgPool3D"
tf_class {
  is_instance: "<class \'tensorflow.python.keras._impl.keras.layers.pooling.AveragePooling3D\'>"
  is_instance: "<class \'tensorflow.python.layers.pooling.AveragePooling3D\'>"
  is_instance: "<class \'tensorflow.python.layers.pooling._Pooling3D\'>"
  is_instance: "<class \'tensorflow.python.keras._impl.keras.engine.base_layer.Layer\'>"
  is_instance: "<class \'tensorflow.python.layers.base.Layer\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "activity_regularizer"
    mtype: "<type \'property\'>"
  }
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "graph"
    mtype: "<type \'property\'>"
  }
  member {
    name: "inbound_nodes"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input_mask"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input_shape"
    mtype: "<type \'property\'>"
  }
  member {
    name: "losses"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "non_trainable_variables"
    mtype: "<type \'property\'>"
  }
  member {
    name: "non_trainable_weights"
    mtype: "<type \'property\'>"
  }
  member {
    name: "outbound_nodes"
    mtype: "<type \'property\'>"
  }
  member {
    name: "output"
    mtype: "<type \'property\'>"
  }
  member {
    name: "output_mask"
    mtype: "<type \'property\'>"
  }
  member {
    name: "output_shape"
    mtype: "<type \'property\'>"
  }
  member {
    name: "scope_name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "trainable_variables"
    mtype: "<type \'property\'>"
  }
  member {
    name: "trainable_weights"
    mtype: "<type \'property\'>"
  }
  member {
    name: "updates"
    mtype: "<type \'property\'>"
  }
  member {
    name: "variables"
    mtype: "<type \'property\'>"
  }
  member {
    name: "weights"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'pool_size\', \'strides\', \'padding\', \'data_format\'], varargs=None, keywords=kwargs, defaults=[\'(2, 2, 2)\', \'None\', \'valid\', \'None\'], "
  }
  member_method {
    name: "add_loss"
    argspec: "args=[\'self\', \'losses\', \'inputs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "add_update"
    argspec: "args=[\'self\', \'updates\', \'inputs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "add_variable"
    argspec: "args=[\'self\', \'name\', \'shape\', \'dtype\', \'initializer\', \'regularizer\', \'trainable\', \'constraint\', \'partitioner\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'True\', \'None\', \'None\'], "
  }
  member_method {
    name: "add_weight"
    argspec: "args=[\'self\', \'name\', \'shape\', \'dtype\', \'initializer\', \'regularizer\', \'trainable\', \'constraint\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'True\', \'None\'], "
  }
  member_method {
    name: "apply"
    argspec: "args=[\'self\', \'inputs\'], varargs=args, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "build"
    argspec: "args=[\'self\', \'_\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "call"
    argspec: "args=[\'self\', \'inputs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "compute_mask"
    argspec: "args=[\'self\', \'inputs\', \'mask\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "compute_output_shape"
    argspec: "args=[\'self\', \'input_shape\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "count_params"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_config"
    argspec: "args=[\'cls\', \'config\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_input_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_input_mask_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_input_shape_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_losses_for"
    argspec: "args=[\'self\', \'inputs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_mask_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_shape_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_updates_for"
    argspec: "args=[\'self\', \'inputs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_weights"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_weights"
    argspec: "args=[\'self\', \'weights\'], varargs=None, keywords=None, defaults=None"
  }
}
