path: "tensorflow.keras.wrappers.scikit_learn.KerasRegressor"
tf_class {
  is_instance: "<class \'tensorflow.python.keras._impl.keras.wrappers.scikit_learn.KerasRegressor\'>"
  is_instance: "<class \'tensorflow.python.keras._impl.keras.wrappers.scikit_learn.BaseWrapper\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'build_fn\'], varargs=None, keywords=sk_params, defaults=[\'None\'], "
  }
  member_method {
    name: "check_params"
    argspec: "args=[\'self\', \'params\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "filter_sk_params"
    argspec: "args=[\'self\', \'fn\', \'override\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "fit"
    argspec: "args=[\'self\', \'x\', \'y\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "get_params"
    argspec: "args=[\'self\'], varargs=None, keywords=params, defaults=None"
  }
  member_method {
    name: "predict"
    argspec: "args=[\'self\', \'x\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "score"
    argspec: "args=[\'self\', \'x\', \'y\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "set_params"
    argspec: "args=[\'self\'], varargs=None, keywords=params, defaults=None"
  }
}
