path: "tensorflow.keras.Sequential"
tf_class {
  is_instance: "<class \'tensorflow.python.keras._impl.keras.engine.sequential.Sequential\'>"
  is_instance: "<class \'tensorflow.python.keras._impl.keras.engine.training.Model\'>"
  is_instance: "<class \'tensorflow.python.keras._impl.keras.engine.network.Network\'>"
  is_instance: "<class \'tensorflow.python.keras._impl.keras.engine.base_layer.Layer\'>"
  is_instance: "<class \'tensorflow.python.layers.base.Layer\'>"
  is_instance: "<class \'tensorflow.python.training.checkpointable.CheckpointableBase\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "activity_regularizer"
    mtype: "<type \'property\'>"
  }
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "graph"
    mtype: "<type \'property\'>"
  }
  member {
    name: "inbound_nodes"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input_mask"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input_shape"
    mtype: "<type \'property\'>"
  }
  member {
    name: "input_spec"
    mtype: "<type \'property\'>"
  }
  member {
    name: "layers"
    mtype: "<type \'property\'>"
  }
  member {
    name: "losses"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "non_trainable_variables"
    mtype: "<type \'property\'>"
  }
  member {
    name: "non_trainable_weights"
    mtype: "<type \'property\'>"
  }
  member {
    name: "outbound_nodes"
    mtype: "<type \'property\'>"
  }
  member {
    name: "output"
    mtype: "<type \'property\'>"
  }
  member {
    name: "output_mask"
    mtype: "<type \'property\'>"
  }
  member {
    name: "output_shape"
    mtype: "<type \'property\'>"
  }
  member {
    name: "scope_name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "state_updates"
    mtype: "<type \'property\'>"
  }
  member {
    name: "stateful"
    mtype: "<type \'property\'>"
  }
  member {
    name: "trainable_variables"
    mtype: "<type \'property\'>"
  }
  member {
    name: "trainable_weights"
    mtype: "<type \'property\'>"
  }
  member {
    name: "updates"
    mtype: "<type \'property\'>"
  }
  member {
    name: "uses_learning_phase"
    mtype: "<type \'property\'>"
  }
  member {
    name: "variables"
    mtype: "<type \'property\'>"
  }
  member {
    name: "weights"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'layers\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "add"
    argspec: "args=[\'self\', \'layer\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "add_loss"
    argspec: "args=[\'self\'], varargs=args, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "add_update"
    argspec: "args=[\'self\', \'updates\', \'inputs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "add_variable"
    argspec: "args=[\'self\', \'name\', \'shape\', \'dtype\', \'initializer\', \'regularizer\', \'trainable\', \'constraint\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'True\', \'None\'], "
  }
  member_method {
    name: "add_weight"
    argspec: "args=[\'self\', \'name\', \'shape\', \'dtype\', \'initializer\', \'regularizer\', \'trainable\', \'constraint\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'True\', \'None\'], "
  }
  member_method {
    name: "apply"
    argspec: "args=[\'self\', \'inputs\'], varargs=args, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "build"
    argspec: "args=[\'self\', \'input_shape\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "call"
    argspec: "args=[\'self\', \'inputs\', \'training\', \'mask\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "compile"
    argspec: "args=[\'self\', \'optimizer\', \'loss\', \'metrics\', \'loss_weights\', \'sample_weight_mode\', \'weighted_metrics\', \'target_tensors\'], varargs=None, keywords=kwargs, defaults=[\'None\', \'None\', \'None\', \'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "compute_mask"
    argspec: "args=[\'self\', \'inputs\', \'mask\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "compute_output_shape"
    argspec: "args=[\'self\', \'input_shape\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "count_params"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "evaluate"
    argspec: "args=[\'self\', \'x\', \'y\', \'batch_size\', \'verbose\', \'sample_weight\', \'steps\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'1\', \'None\', \'None\'], "
  }
  member_method {
    name: "evaluate_generator"
    argspec: "args=[\'self\', \'generator\', \'steps\', \'max_queue_size\', \'workers\', \'use_multiprocessing\'], varargs=None, keywords=None, defaults=[\'None\', \'10\', \'1\', \'False\'], "
  }
  member_method {
    name: "fit"
    argspec: "args=[\'self\', \'x\', \'y\', \'batch_size\', \'epochs\', \'verbose\', \'callbacks\', \'validation_split\', \'validation_data\', \'shuffle\', \'class_weight\', \'sample_weight\', \'initial_epoch\', \'steps_per_epoch\', \'validation_steps\'], varargs=None, keywords=kwargs, defaults=[\'None\', \'None\', \'None\', \'1\', \'1\', \'None\', \'0.0\', \'None\', \'True\', \'None\', \'None\', \'0\', \'None\', \'None\'], "
  }
  member_method {
    name: "fit_generator"
    argspec: "args=[\'self\', \'generator\', \'steps_per_epoch\', \'epochs\', \'verbose\', \'callbacks\', \'validation_data\', \'validation_steps\', \'class_weight\', \'max_queue_size\', \'workers\', \'use_multiprocessing\', \'shuffle\', \'initial_epoch\'], varargs=None, keywords=None, defaults=[\'None\', \'1\', \'1\', \'None\', \'None\', \'None\', \'None\', \'10\', \'1\', \'False\', \'True\', \'0\'], "
  }
  member_method {
    name: "from_config"
    argspec: "args=[\'cls\', \'config\', \'custom_objects\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_input_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_input_mask_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_input_shape_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_layer"
    argspec: "args=[\'self\', \'name\', \'index\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "get_losses_for"
    argspec: "args=[\'self\', \'inputs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_mask_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_shape_at"
    argspec: "args=[\'self\', \'node_index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_updates_for"
    argspec: "args=[\'self\', \'inputs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_weights"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "load_weights"
    argspec: "args=[\'self\', \'filepath\', \'by_name\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "pop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "predict"
    argspec: "args=[\'self\', \'x\', \'batch_size\', \'verbose\', \'steps\'], varargs=None, keywords=None, defaults=[\'None\', \'0\', \'None\'], "
  }
  member_method {
    name: "predict_classes"
    argspec: "args=[\'self\', \'x\', \'batch_size\', \'verbose\'], varargs=None, keywords=None, defaults=[\'32\', \'0\'], "
  }
  member_method {
    name: "predict_generator"
    argspec: "args=[\'self\', \'generator\', \'steps\', \'max_queue_size\', \'workers\', \'use_multiprocessing\', \'verbose\'], varargs=None, keywords=None, defaults=[\'None\', \'10\', \'1\', \'False\', \'0\'], "
  }
  member_method {
    name: "predict_on_batch"
    argspec: "args=[\'self\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "predict_proba"
    argspec: "args=[\'self\', \'x\', \'batch_size\', \'verbose\'], varargs=None, keywords=None, defaults=[\'32\', \'0\'], "
  }
  member_method {
    name: "reset_states"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "save"
    argspec: "args=[\'self\', \'filepath\', \'overwrite\', \'include_optimizer\'], varargs=None, keywords=None, defaults=[\'True\', \'True\'], "
  }
  member_method {
    name: "save_weights"
    argspec: "args=[\'self\', \'filepath\', \'overwrite\'], varargs=None, keywords=None, defaults=[\'True\'], "
  }
  member_method {
    name: "set_weights"
    argspec: "args=[\'self\', \'weights\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "summary"
    argspec: "args=[\'self\', \'line_length\', \'positions\', \'print_fn\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "test_on_batch"
    argspec: "args=[\'self\', \'x\', \'y\', \'sample_weight\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "to_json"
    argspec: "args=[\'self\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "to_yaml"
    argspec: "args=[\'self\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "train_on_batch"
    argspec: "args=[\'self\', \'x\', \'y\', \'sample_weight\', \'class_weight\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
}
