path: "tensorflow.Variable"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.variables.Variable\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "SaveSliceInfo"
    mtype: "<type \'type\'>"
  }
  member {
    name: "constraint"
    mtype: "<type \'property\'>"
  }
  member {
    name: "device"
    mtype: "<type \'property\'>"
  }
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "graph"
    mtype: "<type \'property\'>"
  }
  member {
    name: "initial_value"
    mtype: "<type \'property\'>"
  }
  member {
    name: "initializer"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "op"
    mtype: "<type \'property\'>"
  }
  member {
    name: "shape"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'initial_value\', \'trainable\', \'collections\', \'validate_shape\', \'caching_device\', \'name\', \'variable_def\', \'dtype\', \'expected_shape\', \'import_scope\', \'constraint\'], varargs=None, keywords=None, defaults=[\'None\', \'True\', \'None\', \'True\', \'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "assign"
    argspec: "args=[\'self\', \'value\', \'use_locking\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "assign_add"
    argspec: "args=[\'self\', \'delta\', \'use_locking\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "assign_sub"
    argspec: "args=[\'self\', \'delta\', \'use_locking\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "count_up_to"
    argspec: "args=[\'self\', \'limit\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "eval"
    argspec: "args=[\'self\', \'session\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "from_proto"
    argspec: "args=[\'variable_def\', \'import_scope\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "get_shape"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "initialized_value"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "load"
    argspec: "args=[\'self\', \'value\', \'session\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "read_value"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "scatter_sub"
    argspec: "args=[\'self\', \'sparse_delta\', \'use_locking\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "set_shape"
    argspec: "args=[\'self\', \'shape\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "to_proto"
    argspec: "args=[\'self\', \'export_scope\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "value"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
