path: "tensorflow.resource_loader"
tf_module {
  member_method {
    name: "get_data_files_path"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_path_to_datafile"
    argspec: "args=[\'path\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_root_dir_with_all_resources"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "load_resource"
    argspec: "args=[\'path\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "readahead_file_path"
    argspec: "args=[\'path\', \'readahead\'], varargs=None, keywords=None, defaults=[\'128M\'], "
  }
}
