path: "tensorflow.ones_initializer"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.init_ops.Ones\'>"
  is_instance: "<class \'tensorflow.python.ops.init_ops.Initializer\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'dtype\'], varargs=None, keywords=None, defaults=[\"<dtype: \'float32\'>\"], "
  }
}
