path: "tensorflow.data.SparseType"
tf_class {
  is_instance: "<class \'tensorflow.python.data.util.sparse.SparseType\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'dtype\'], varargs=None, keywords=None, defaults=None"
  }
}
