path: "tensorflow.InteractiveSession"
tf_class {
  is_instance: "<class \'tensorflow.python.client.session.InteractiveSession\'>"
  is_instance: "<class \'tensorflow.python.client.session.BaseSession\'>"
  is_instance: "<class \'tensorflow.python.client.session.SessionInterface\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "graph"
    mtype: "<type \'property\'>"
  }
  member {
    name: "graph_def"
    mtype: "<type \'property\'>"
  }
  member {
    name: "sess_str"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'target\', \'graph\', \'config\'], varargs=None, keywords=None, defaults=[\'\', \'None\', \'None\'], "
  }
  member_method {
    name: "as_default"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "close"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "make_callable"
    argspec: "args=[\'self\', \'fetches\', \'feed_list\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "partial_run"
    argspec: "args=[\'self\', \'handle\', \'fetches\', \'feed_dict\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "partial_run_setup"
    argspec: "args=[\'self\', \'fetches\', \'feeds\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "run"
    argspec: "args=[\'self\', \'fetches\', \'feed_dict\', \'options\', \'run_metadata\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
}
