op {
  graph_op_name: "FakeQuantWithMinMaxVarsPerChannelGradient"
  endpoint {
    name: "quantization.fake_quant_with_min_max_vars_per_channel_gradient"
  }
  endpoint {
    name: "fake_quant_with_min_max_vars_per_channel_gradient"
    deprecation_version: 2
  }
}
