op {
  graph_op_name: "TFRecordReader"
  visibility: HIDDEN
}
op {
  graph_op_name: "TFRecordReaderV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TakeManySparseFromTensorsMap"
  visibility: HIDDEN
}
op {
  graph_op_name: "Tanh"
  visibility: HIDDEN
}
op {
  graph_op_name: "TanhGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "TemporaryVariable"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArray"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayClose"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayCloseV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayCloseV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayConcat"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayConcatV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayConcatV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayGather"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayGatherV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayGatherV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayGradV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayGradV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayPack"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayRead"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayReadV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayReadV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayScatter"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayScatterV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayScatterV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArraySize"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArraySizeV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArraySizeV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArraySplit"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArraySplitV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArraySplitV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayUnpack"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayWrite"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayWriteV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorArrayWriteV3"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorSummary"
  visibility: HIDDEN
}
op {
  graph_op_name: "TensorSummaryV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TextLineReader"
  visibility: HIDDEN
}
op {
  graph_op_name: "TextLineReaderV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "ThreadUnsafeUnigramCandidateSampler"
  visibility: HIDDEN
}
op {
  graph_op_name: "TileGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "TopK"
  visibility: HIDDEN
}
op {
  graph_op_name: "TopKV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "TruncateDiv"
  visibility: HIDDEN
}
op {
  graph_op_name: "TruncateMod"
  visibility: HIDDEN
}
op {
  graph_op_name: "TruncatedNormal"
  visibility: HIDDEN
}
