op {
  graph_op_name: "Log1p"
  endpoint {
    name: "math.log1p"
  }
  endpoint {
    name: "log1p"
    deprecation_version: 2
  }
  description: <<END
I.e., \\(y = \log_e (1 + x)\\).

Example:
>>> x = tf.constant([0, 0.5, 1, 5])
>>> tf.math.log1p(x)
<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       , 0.4054651, 0.6931472, 1.7917595], dtype=float32)>

END
}
