op {
  graph_op_name: "TensorScatterSub"
  deprecation_message: "Use tensor_scatter_nd_sub instead"
  endpoint {
    name: "tensor_scatter_nd_sub"
  }
  endpoint {
    name: "tensor_scatter_sub"
    deprecation_version: 2
  }
}
