op {
  graph_op_name: "LogicalNot"
  endpoint {
    name: "math.logical_not"
  }
  endpoint {
    name: "logical_not"
  }
  description: <<END
Example:

>>> tf.math.logical_not(tf.constant([True, False]))
<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

END
}
