op {
  graph_op_name: "MatrixBandPart"
  endpoint {
    name: "linalg.band_part"
  }
  endpoint {
    name: "matrix_band_part"
    deprecation_message: "tf.matrix_band_part is deprecated, please use tf.linalg.band_part instead."
  }
}
