op {
  graph_op_name: "MatrixInverse"
  endpoint {
    name: "linalg.inv"
  }
  endpoint {
    name: "matrix_inverse"
    deprecation_message: "tf.matrix_inverse is deprecated, please use tf.linalg.inv instead."
  }
}
