op {
  graph_op_name: "SegmentMax"
  endpoint {
    name: "math.segment_max"
  }
  endpoint {
    name: "segment_max"
    deprecation_message: "tf.segment_max is deprecated, please use tf.math.segment_max instead."
  }
}
