op {
  graph_op_name: "ScatterNd"
  endpoint {
    name: "manip.scatter_nd"
  }
  endpoint {
    name: "scatter_nd"
    deprecation_message: "tf.scatter_nd is deprecated, please use tf.manip.scatter_nd instead."
  }
}
