op {
  graph_op_name: "Barrier"
  visibility: HIDDEN
}
op {
  graph_op_name: "BarrierClose"
  visibility: HIDDEN
}
op {
  graph_op_name: "BarrierIncompleteSize"
  visibility: HIDDEN
}
op {
  graph_op_name: "BarrierInsertMany"
  visibility: HIDDEN
}
op {
  graph_op_name: "BarrierReadySize"
  visibility: HIDDEN
}
op {
  graph_op_name: "BarrierTakeMany"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchCholesky"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchCholeskyGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchFFT"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchFFT2D"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchFFT3D"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchIFFT"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchIFFT2D"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchIFFT3D"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchMatMul"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchMatrixDeterminant"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchMatrixInverse"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchMatrixSolve"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchMatrixSolveLs"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchMatrixTriangularSolve"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchNormWithGlobalNormalization"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchNormWithGlobalNormalizationGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchSelfAdjointEig"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchSelfAdjointEigV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchSvd"
  visibility: HIDDEN
}
op {
  graph_op_name: "BatchToSpace"
  visibility: HIDDEN
}
op {
  graph_op_name: "BiasAdd"
  visibility: HIDDEN
}
op {
  graph_op_name: "BiasAddV1"
  visibility: HIDDEN
}
op {
  graph_op_name: "BitwiseAnd"
  endpoint {
    name: "bitwise.bitwise_and"
  }
}
op {
  graph_op_name: "BitwiseOr"
  endpoint {
    name: "bitwise.bitwise_or"
  }
}
op {
  graph_op_name: "BitwiseXor"
  endpoint {
    name: "bitwise.bitwise_xor"
  }
}
op {
  graph_op_name: "BroadcastArgs"
  visibility: HIDDEN
}
op {
  graph_op_name: "BroadcastGradientArgs"
  visibility: HIDDEN
}
op {
  graph_op_name: "Bucketize"
  visibility: HIDDEN
}
