op {
  graph_op_name: "DepthwiseConv2dNativeBackpropFilter"
  endpoint {
    name: "nn.depthwise_conv2d_native_backprop_filter"
    deprecated: true
    deprecation_version: 2
  }
  endpoint {
    name: "nn.depthwise_conv2d_backprop_filter"
  }
}
