op {
  graph_op_name: "MatMul"
  visibility: HIDDEN
}
op {
  graph_op_name: "MatrixBandPart"
  endpoint {
    name: "linalg.band_part"
  }
  endpoint {
    name: "matrix_band_part"
  }
}
op {
  graph_op_name: "MatrixDeterminant"
  endpoint {
    name: "linalg.det"
  }
  endpoint {
    name: "matrix_determinant"
  }
}
op {
  graph_op_name: "MatrixDiag"
  endpoint {
    name: "linalg.diag"
  }
  endpoint {
    name: "matrix_diag"
  }
}
op {
  graph_op_name: "MatrixDiagPart"
  endpoint {
    name: "linalg.diag_part"
  }
  endpoint {
    name: "matrix_diag_part"
  }
}
op {
  graph_op_name: "MatrixInverse"
  endpoint {
    name: "linalg.inv"
  }
  endpoint {
    name: "matrix_inverse"
  }
}
op {
  graph_op_name: "MatrixSetDiag"
  endpoint {
    name: "linalg.set_diag"
  }
  endpoint {
    name: "matrix_set_diag"
  }
}
op {
  graph_op_name: "MatrixSolve"
  endpoint {
    name: "linalg.solve"
  }
  endpoint {
    name: "matrix_solve"
  }
}
op {
  graph_op_name: "MatrixSolveLs"
  visibility: HIDDEN
}
op {
  graph_op_name: "MatrixTriangularSolve"
  endpoint {
    name: "linalg.triangular_solve"
  }
  endpoint {
    name: "matrix_triangular_solve"
  }
}
op {
  graph_op_name: "Max"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPool"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPool3DGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPool3DGradGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPoolGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPoolGradGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPoolGradGradWithArgmax"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPoolGradWithArgmax"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPoolV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "MaxPoolWithArgmax"
  endpoint {
    name: "nn.max_pool_with_argmax"
  }
}
op {
  graph_op_name: "Mean"
  visibility: HIDDEN
}
op {
  graph_op_name: "Merge"
  visibility: HIDDEN
}
op {
  graph_op_name: "MergeSummary"
  visibility: HIDDEN
}
op {
  graph_op_name: "Min"
  visibility: HIDDEN
}
op {
  graph_op_name: "MirrorPad"
  visibility: HIDDEN
}
op {
  graph_op_name: "MirrorPadGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "Mul"
  visibility: HIDDEN
}
op {
  graph_op_name: "MutableDenseHashTable"
  visibility: HIDDEN
}
op {
  graph_op_name: "MutableDenseHashTableV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "MutableHashTable"
  visibility: HIDDEN
}
op {
  graph_op_name: "MutableHashTableOfTensors"
  visibility: HIDDEN
}
op {
  graph_op_name: "MutableHashTableOfTensorsV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "MutableHashTableV2"
  visibility: HIDDEN
}
