op {
  graph_op_name: "Digamma"
  endpoint {
    name: "math.digamma"
  }
  endpoint {
    name: "digamma"
    deprecation_message: "tf.digamma is deprecated, please use tf.math.digamma instead."
  }
}
