op {
  graph_op_name: "UnsortedSegmentProd"
  endpoint {
    name: "math.unsorted_segment_prod"
  }
  endpoint {
    name: "unsorted_segment_prod"
    deprecation_message: "tf.unsorted_segment_prod is deprecated, please use tf.math.unsorted_segment_prod instead."
  }
}
