op {
  graph_op_name: "Reciprocal"
  endpoint {
    name: "math.reciprocal"
  }
  endpoint {
    name: "reciprocal"
    deprecation_message: "tf.reciprocal is deprecated, please use tf.math.reciprocal instead."
  }
}
