op {
  graph_op_name: "IsInf"
  endpoint {
    name: "debugging.is_inf"
  }
  endpoint {
    name: "is_inf"
    deprecation_message: "tf.is_inf is deprecated, please use tf.debugging.is_inf instead."
  }
}
