op {
  graph_op_name: "AsString"
  endpoint {
    name: "dtypes.as_string"
  }
  endpoint {
    name: "as_string"
    deprecation_message: "tf.as_string is deprecated, please use tf.dtypes.as_string instead."
  }
}
