op {
  graph_op_name: "Minimum"
  endpoint {
    name: "math.minimum"
  }
  endpoint {
    name: "minimum"
    deprecation_message: "tf.minimum is deprecated, please use tf.math.minimum instead."
  }
}
