op {
  graph_op_name: "MatchingFiles"
  endpoint {
    name: "io.matching_files"
  }
  endpoint {
    name: "matching_files"
    deprecation_message: "tf.matching_files is deprecated, please use tf.io.matching_files instead."
  }
}
