op {
  graph_op_name: "GatherNd"
  endpoint {
    name: "manip.gather_nd"
  }
  endpoint {
    name: "gather_nd"
    deprecation_message: "tf.gather_nd is deprecated, please use tf.manip.gather_nd instead."
  }
}
