op {
  graph_op_name: "IFFT3D"
  endpoint {
    name: "signal.ifft3d"
  }
  endpoint {
    name: "spectral.ifft3d"
    deprecation_version: 2
  }
  endpoint {
    name: "ifft3d"
    deprecation_version: 2
  }
}
