op {
  graph_op_name: "EditDistance"
  visibility: HIDDEN
}
op {
  graph_op_name: "Elu"
  endpoint {
    name: "nn.elu"
  }
}
op {
  graph_op_name: "EluGrad"
  visibility: HIDDEN
}
op {
  graph_op_name: "EncodeJpeg"
  endpoint {
    name: "image.encode_jpeg"
  }
}
op {
  graph_op_name: "EncodePng"
  endpoint {
    name: "image.encode_png"
  }
}
op {
  graph_op_name: "Exit"
  visibility: HIDDEN
}
op {
  graph_op_name: "ExpandDims"
  visibility: HIDDEN
}
op {
  graph_op_name: "ExtractGlimpse"
  endpoint {
    name: "image.extract_glimpse"
  }
}
op {
  graph_op_name: "ExtractJpegShape"
  endpoint {
    name: "image.extract_jpeg_shape"
  }
}
