op {
  graph_op_name: "ParseTensor"
  endpoint {
    name: "io.parse_tensor"
  }
  endpoint {
    name: "parse_tensor"
    deprecation_message: "tf.parse_tensor is deprecated, please use tf.io.parse_tensor instead."
  }
}
