op {
  graph_op_name: "FakeQuantWithMinMaxVars"
  endpoint {
    name: "quantization.fake_quant_with_min_max_vars"
  }
  endpoint {
    name: "fake_quant_with_min_max_vars"
    deprecation_version: 2
  }
}
