op {
  graph_op_name: "Pack"
  visibility: HIDDEN
}
op {
  graph_op_name: "Pad"
  visibility: HIDDEN
}
op {
  graph_op_name: "PadV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "PaddingFIFOQueue"
  visibility: HIDDEN
}
op {
  graph_op_name: "PaddingFIFOQueueV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "ParallelConcat"
  visibility: HIDDEN
}
op {
  graph_op_name: "ParameterizedTruncatedNormal"
  visibility: HIDDEN
}
op {
  graph_op_name: "ParseExample"
  visibility: HIDDEN
}
op {
  graph_op_name: "ParseSingleSequenceExample"
  visibility: HIDDEN
}
op {
  graph_op_name: "Placeholder"
  visibility: HIDDEN
}
op {
  graph_op_name: "Pow"
  visibility: HIDDEN
}
op {
  graph_op_name: "Print"
  visibility: HIDDEN
}
op {
  graph_op_name: "PriorityQueue"
  visibility: HIDDEN
}
op {
  graph_op_name: "PriorityQueueV2"
  visibility: HIDDEN
}
op {
  graph_op_name: "Prod"
  visibility: HIDDEN
}
op {
  graph_op_name: "PyFunc"
  visibility: HIDDEN
}
op {
  graph_op_name: "PyFuncStateless"
  visibility: HIDDEN
}
