op {
  graph_op_name: "IsNan"
  endpoint {
    name: "math.is_nan"
  }
  endpoint {
    name: "debugging.is_nan"
    deprecation_version: 2
  }
  endpoint {
    name: "is_nan"
    deprecation_version: 2
  }
}
