op {
  graph_op_name: "UnsortedSegmentSum"
  endpoint {
    name: "math.unsorted_segment_sum"
  }
  endpoint {
    name: "unsorted_segment_sum"
    deprecation_message: "tf.unsorted_segment_sum is deprecated, please use tf.math.unsorted_segment_sum instead."
  }
}
