op {
  graph_op_name: "Qr"
  endpoint {
    name: "linalg.qr"
  }
  endpoint {
    name: "qr"
  }
}
op {
  graph_op_name: "QuantizedAvgPool"
  endpoint {
    name: "nn.quantized_avg_pool"
  }
}
op {
  graph_op_name: "QuantizedMaxPool"
  endpoint {
    name: "nn.quantized_max_pool"
  }
}
op {
  graph_op_name: "QuantizedReluX"
  endpoint {
    name: "nn.quantized_relu_x"
  }
}
