op {
  graph_op_name: "EncodeBase64"
  endpoint {
    name: "io.encode_base64"
  }
  endpoint {
    name: "encode_base64"
    deprecation_message: "tf.encode_base64 is deprecated, please use tf.io.encode_base64 instead."
  }
}
