op {
  graph_op_name: "Reshape"
  endpoint {
    name: "manip.reshape"
  }
  endpoint {
    name: "reshape"
    deprecation_message: "tf.reshape is deprecated, please use tf.manip.reshape instead."
  }
}
