op {
  graph_op_name: "ReverseV2"
  endpoint {
    name: "manip.reverse"
  }
  endpoint {
    name: "reverse"
    deprecation_message: "tf.reverse is deprecated, please use tf.manip.reverse instead."
  }
  endpoint {
    name: "reverse_v2"
    deprecation_message: "tf.reverse_v2 is deprecated, please use tf.manip.reverse instead."
  }
}
