op {
  graph_op_name: "CheckNumerics"
  deprecation_version: 2
  deprecation_message: "Use debugging.assert_all_finite instead"
  endpoint {
    name: "debugging.check_numerics"
  }
  endpoint {
    name: "check_numerics"
    deprecation_version: 2
  }
}
