# RUN: tf-mlir-translate -graphdef-to-mlir %s -o - | FileCheck %s

# This test is intended to verify the tensor_content field on import of an empty
# tensor.
# CHECK:  tf.Const
# CHECK-SAME: value = opaque<"tf", "0x746674656E736F722464747970653A2044545F464C4F41542074656E736F725F7368617065207B2064696D207B2073697A653A2031207D207D">

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 1
          }
        }
      }
    }
  }
}
library {
}
versions {
  producer: 29
}
