# RUN: tf-mlir-translate -graphdef-to-mlir %s -o - | FileCheck %s

node {
  name: "PartitionedCall"
  op: "PartitionedCall"
  attr {
    key: "Tin"
    value {
      list {
      }
    }
  }
  attr {
    key: "Tout"
    value {
      list {
        type: DT_INT32
      }
    }
  }
  attr {
    key: "f"
    value {
      func {
        name: "foo"
      }
    }
  }
}
library {
  function {
    signature {
      name: "foo"
      output_arg {
        name: "identity"
        type: DT_INT32
      }
    }
    node_def {
      name: "Const"
      op: "Const"
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
            }
            int_val: 5
          }
        }
      }
    }
    node_def {
      name: "Identity"
      op: "Identity"
      input: "Const:output:0"
      attr {
        key: "T"
        value {
          type: DT_INT32
        }
      }
    }
    ret {
      key: "identity"
      value: "Identity:output:0"
    }
    # The attribute "experimental_ints_on_device" and the return type INT32
    # ensure that kDeviceRetOp is used instead of kRetOp
    attr {
      key: "experimental_ints_on_device"
      value {
        b: true
      }
    }
  }
}
versions {
  producer: 29
  min_consumer: 12
}

# CHECK:       func @main() {
# CHECK-NEXT:    %0:2 = "_tf.PartitionedCall"() {Tin = [], Tout = ["tfdtype$DT_INT32"], config = "", config_proto = "", device = "", executor_type = "", f = @foo0, name = "PartitionedCall"} : () -> (tensor<*xi32>, !_tf.control)
# CHECK-NEXT:    return
# CHECK-NEXT:  }
# CHECK-EMPTY:
# CHECK-NEXT:  func @foo0() -> tensor<i32>
# CHECK-NEXT:    attributes  {tf.experimental_ints_on_device = true} {
# CHECK-NEXT:    %0:2 = "_tf.Const"() {device = "", dtype = "tfdtype$DT_INT32", name = "Const", value = dense<5> : tensor<i32>} : () -> (tensor<i32>, !_tf.control)
# CHECK-NEXT:    %1:2 = "_tf.Identity"(%0#0) {T = "tfdtype$DT_INT32", device = "", name = "Identity"} : (tensor<i32>) -> (tensor<i32>, !_tf.control)
# CHECK-NEXT:    return %1#0 : tensor<i32>
# CHECK-NEXT:  }
