# RUN: tf-mlir-translate -graphdef-to-mlir -tf-enable-shape-inference-on-import=false %s -o - | FileCheck %s

node {
  name: "Call_foo"
  op: "PartitionedCall"
  attr {
    key: "Tin"
    value {
      list {
      }
    }
  }
  attr {
    key: "Tout"
    value {
      list {
        type: DT_INT32
      }
    }
  }
  attr {
    key: "f"
    value {
      func {
        name: "foo"
      }
    }
  }
}
library {
  function {
    signature {
      name: "foo"
      output_arg {
        name: "identity"
        type: DT_INT32
      }
      is_stateful: true
    }
    node_def {
      name: "Const"
      op: "Const"
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
            }
            int_val: 5
          }
        }
      }
    }
    node_def {
      name: "Identity"
      op: "Identity"
      input: "Const:output:0"
      attr {
        key: "T"
        value {
          type: DT_INT32
        }
      }
    }
    ret {
      key: "identity"
      value: "Identity:output:0"
    }
  }
}
versions {
  producer: 29
  min_consumer: 12
}

# Find PartitionedCall ops in main and match the callee name.
# CHECK: func @main
# CHECK: "tf.PartitionedCall"
# CHECK-SAME: f = @[[FUNCTION_FOO:[a-zA-Z0-9_]*]]

# Find callee and verify it has the stateful attribute set.
# CHECK: func @[[FUNCTION_FOO]]
# CHECK-SAME: attributes
# CHECK-SAME: tf.signature.is_stateful
