# RUN: tf-mlir-translate -graphdef-to-mlir -tf-upgrade-legacy %s

# This test verifies the upgrade function would not error out for functional
# library with unregister op. With lazy loading, some functions might not be
# invoked.

# CHECK-NOT: Op type not registered 'UnregisteredOp'

node {
  name: "input"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
}
library {
  function {
    node_def {
      name: "UnregisteredOp"
      op: "UnregisteredOp"
      input: "input"
    }
  }
}
