library {
  function {
    signature {
      name: "FuncDataset"
      input_arg {
        name: "x"
        type: DT_VARIANT
        experimental_full_type {
          type_id: TFT_DATASET
          args {
            type_id: TFT_FOR_EACH
            args {
              type_id: TFT_PRODUCT
            }
            args {
              type_id: TFT_TENSOR
              args {
                type_id: TFT_VAR
                s: "output_types"
              }
            }
            args {
              type_id: TFT_VAR
              s: "output_types"
            }
          }
        }
      }
      output_arg {
        name: "z0"
        type: DT_VARIANT
        experimental_full_type {
          type_id: TFT_DATASET
          args {
            type_id: TFT_FOR_EACH
            args {
              type_id: TFT_PRODUCT
            }
            args {
              type_id: TFT_TENSOR
              args {
                type_id: TFT_VAR
                s: "output_types"
              }
            }
            args {
              type_id: TFT_VAR
              s: "output_types"
            }
          }
        }
      }
    }
    ret {
      key: "z0"
      value: "x"
    }
  }
}
versions {
  producer: 795
}
