node {
  name: "x"
  op: "_Arg"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index"
    value {
      i: 0
    }
  }
}
node {
  name: "y"
  op: "_Arg"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index"
    value {
      i: 1
    }
  }
}
node {
  name: "output"
  op: "MyMul"
  input: "x"
  input: "y"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_type {
    type_id: TFT_TENSOR
  }
}
node {
  name: "z2_RetVal"
  op: "_Retval"
  input: "output:2"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index"
    value {
      i: 0
    }
  }
}
library {
  function {
    signature {
      name: "MyMul"
      input_arg {
        name: "x"
        type_attr: "T"
        experimental_full_type {
          type_id: TFT_TENSOR
        }
      }
      input_arg {
        name: "y"
        type_attr: "T"
      }
      output_arg {
        name: "z0"
        type_attr: "T"
      }
      output_arg {
        name: "z1"
        type_attr: "T"
      }
      output_arg {
        name: "z2"
        type_attr: "T"
        experimental_full_type {
          type_id: TFT_TENSOR
        }
      }
      attr {
        name: "T"
        type: "type"
        allowed_values {
          list {
            type: DT_FLOAT
            type: DT_INT32
          }
        }
      }
    }
    node_def {
      name: "output0"
      op: "Mul"
      input: "x"
      input: "y"
      attr {
        key: "T"
        value {
          placeholder: "T"
        }
      }
      experimental_type {
        type_id: TFT_TENSOR
      }
    }
    node_def {
      name: "output1"
      op: "Mul"
      input: "x"
      input: "y"
      attr {
        key: "T"
        value {
          placeholder: "T"
        }
      }
    }
    node_def {
      name: "output2"
      op: "Mul"
      input: "x"
      input: "y"
      attr {
        key: "T"
        value {
          placeholder: "T"
        }
      }
    }
    ret {
      key: "z0"
      value: "output0:z:0"
    }
    ret {
      key: "z1"
      value: "output1:z:0"
    }
    ret {
      key: "z2"
      value: "output2:z:0"
    }
    attr {
      key: "_noinline"
      value {
        b: true
      }
    }
  }
}
versions {
  producer: 795
}
