library {
  function {
    signature {
      name: "cluster_train_step_15117945319092382955"
      output_arg {
        name: "identity_0_retval_retval"
        type: DT_UINT8
      }
    }
    node_def {
      name: "Const_2"
      op: "Const"
      device: "/device:TPU_REPLICATED_CORE"
      attr {
        key: "_xla_inferred_shapes"
        value {
          list {
            shape {
              dim {
                size: 1024
              }
              dim {
                size: 1024
              }
              dim {
                size: 1024
              }
              dim {
                size: 1024
              }
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_UINT8
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_UINT8
            tensor_shape {
              dim {
                size: 1024
              }
              dim {
                size: 1024
              }
              dim {
                size: 1024
              }
              dim {
                size: 1024
              }
            }
          }
        }
      }
    }
    node_def {
      name: "strided_slice/stack"
      op: "Const"
      device: "/device:TPU_REPLICATED_CORE"
      attr {
        key: "_xla_inferred_shapes"
        value {
          list {
            shape {
              dim {
                size: 4
              }
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
              dim {
                size: 4
              }
            }
          }
        }
      }
    }
    node_def {
      name: "strided_slice/stack_1"
      op: "Const"
      device: "/device:TPU_REPLICATED_CORE"
      attr {
        key: "_xla_inferred_shapes"
        value {
          list {
            shape {
              dim {
                size: 4
              }
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
              dim {
                size: 4
              }
            }
            int_val: 1
          }
        }
      }
    }
    node_def {
      name: "strided_slice/stack_2"
      op: "Const"
      device: "/device:TPU_REPLICATED_CORE"
      attr {
        key: "_xla_inferred_shapes"
        value {
          list {
            shape {
              dim {
                size: 4
              }
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
              dim {
                size: 4
              }
            }
            int_val: 1
          }
        }
      }
    }
    node_def {
      name: "strided_slice"
      op: "StridedSlice"
      input: "Const_2:output:0"
      input: "strided_slice/stack:output:0"
      input: "strided_slice/stack_1:output:0"
      input: "strided_slice/stack_2:output:0"
      device: "/device:TPU_REPLICATED_CORE"
      attr {
        key: "Index"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "T"
        value {
          type: DT_UINT8
        }
      }
      attr {
        key: "_xla_inferred_shapes"
        value {
          list {
            shape {
              dim {
                size: 1
              }
              dim {
                size: 1
              }
              dim {
                size: 1
              }
              dim {
                size: 1
              }
            }
          }
        }
      }
      attr {
        key: "begin_mask"
        value {
          i: 15
        }
      }
      attr {
        key: "ellipsis_mask"
        value {
          i: 0
        }
      }
      attr {
        key: "end_mask"
        value {
          i: 0
        }
      }
      attr {
        key: "new_axis_mask"
        value {
          i: 0
        }
      }
      attr {
        key: "shrink_axis_mask"
        value {
          i: 0
        }
      }
    }
    node_def {
      name: "NoOp"
      op: "NoOp"
      device: "/device:TPU_REPLICATED_CORE"
      attr {
        key: "_xla_inferred_shapes"
        value {
          list {
          }
        }
      }
    }
    ret {
      key: "identity_0_retval_retval"
      value: "strided_slice:output:0"
    }
  }
}
versions {
  producer: 762
}
