node {
  name: "node_outside_function"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "fused_node_outside_function"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
  experimental_debug_info {
    original_node_names: "n1"
    original_node_names: "n2"
    original_func_names: "f1"
    original_func_names: "f2"
  }
}
node {
  name: "unnamed1"
  op: "foo"
  experimental_debug_info {
  }
}
library {
  function {
    signature {
      name: "foo"
    }
    node_def {
      name: "node_inside_function"
      op: "Const"
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
            }
            int_val: 1
          }
        }
      }
      experimental_debug_info {
      }
    }
  }
}
