node {
  name: "Quantized_Constant"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_QUINT8
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_QUINT8
        tensor_shape {
        }
        int_val: 7
      }
    }
  }
}
library {
}
versions {
  producer: 70
}
