node {
  name: "__inference__creator_1477"
  op: "__inference__creator_1477"
}
library {
  function {
    signature {
      name: "__inference__creator_1477"
      output_arg {
        name: "identity"
        type: DT_RESOURCE
        handle_data {
          dtype: DT_INT32
          shape {
          }
        }
      }
      is_stateful: true
      control_output: "MutableHashTable"
    }
    node_def {
      name: "MutableHashTable"
      op: "MutableHashTableV2"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
            }
          }
        }
      }
      attr {
        key: "key_dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "shared_name"
        value {
          s: "table_1418"
        }
      }
      attr {
        key: "value_dtype"
        value {
          type: DT_INT32
        }
      }
      experimental_debug_info {
        original_node_names: "MutableHashTable"
      }
    }
    node_def {
      name: "Identity"
      op: "Identity"
      input: "MutableHashTable:table_handle:0"
      input: "^NoOp"
      attr {
        key: "T"
        value {
          type: DT_RESOURCE
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
            }
          }
        }
      }
      experimental_debug_info {
        original_node_names: "Identity"
      }
    }
    node_def {
      name: "NoOp"
      op: "NoOp"
      input: "^MutableHashTable"
      attr {
        key: "_output_shapes"
        value {
          list {
          }
        }
      }
      experimental_debug_info {
        original_node_names: "NoOp"
      }
    }
    ret {
      key: "identity"
      value: "Identity:output:0"
    }
    attr {
      key: "_construction_context"
      value {
        s: "kEagerRuntime"
      }
    }
    attr {
      key: "_input_shapes"
      value {
      }
    }
    control_ret {
      key: "MutableHashTable"
      value: "MutableHashTable"
    }
  }
}
versions {
  producer: 728
  min_consumer: 12
}
