node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_UINT8
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_UINT8
        tensor_shape {
          dim {
            size: 4
          }
          dim {
            size: 5
          }
          dim {
            size: 7
          }
          dim {
            size: 1
          }
        }
        tensor_content: "\257\304\031\366C\323\227g\\\271\216\027HYn*\332\210\247\346D\260\177\207\254\000K7\372\006\023\274,\277E8\230\267\265p\373\275\300\"8\311\316&\004\356\211W\343\303HS\260\001\300\220v\237]\254\\\374G\027\n\351#\300=\207\227\\\367\340\225d\243\341C{\333\341\023\233\004\023!{\036\271\345I\335\321\177\237\202S\262\222\025wC\313\272/\020\014]k\351\211LCn\216|\0245\374\217;#0\004+\310\332\3726+\357\327\315\262\'"
      }
    }
  }
}
node {
  name: "img/tag"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
        }
        string_val: "img"
      }
    }
  }
}
node {
  name: "img"
  op: "ImageSummary"
  input: "img/tag"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_UINT8
    }
  }
  attr {
    key: "bad_color"
    value {
      tensor {
        dtype: DT_UINT8
        tensor_shape {
          dim {
            size: 4
          }
        }
        int_val: 255
        int_val: 0
        int_val: 0
        int_val: 255
      }
    }
  }
  attr {
    key: "max_images"
    value {
      i: 3
    }
  }
}
library {
}
versions {
  producer: 728
}
