# RUN: not tfg-translate -graphdef-to-mlir %s 2>&1 | FileCheck %s

# CHECK: empty attr name

node {
  name: "SaveV/"
  op: "PartitionedCall"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: "T"
    value {
      func {
        attr {
          key: ""
          value {
          }
        }
        attr {
          key: "\036"
          value {
          }
        }
        attr {
          key: " "
          value {
          }
        }
        attr {
          key: "1"
          value {
          }
        }
        attr {
          key: "2"
          value {
          }
        }
        attr {
          key: "loc:@c"
          value {
          }
        }
        attr {
          key: "\177"
          value {
            func {
              attr {
                key: ""
                value {
                }
              }
              attr {
                key: "\036"
                value {
                }
              }
              attr {
                key: "1"
                value {
                }
              }
              attr {
                key: "2"
                value {
                }
              }
              attr {
                key: "_class"
                value {
                }
              }
              attr {
                key: "\177"
                value {
                }
              }
              attr {
                key: "\177\177"
                value {
                }
              }
            }
          }
        }
      }
    }
  }
  attr {
    key: "Tin"
    value {
    }
  }
  attr {
    key: "Tout"
    value {
    }
  }
  attr {
    key: "config"
    value {
      s: ""
    }
  }
  attr {
    key: "config_proto"
    value {
      s: ""
    }
  }
  attr {
    key: "executor_type"
    value {
      s: ""
    }
  }
  attr {
    key: "f"
    value {
      func {
        attr {
          key: "E"
          value {
          }
        }
      }
    }
  }
  attr {
    key: "shape"
    value {
    }
  }
}
node {
  name: "serving_default_x"
  op: "Placeholder"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        unknown_rank: true
      }
    }
  }
}
library {
  function {
    signature {
      is_distributed_communication: true
    }
  }
  gradient {
    gradient_func: "\001\000\000\000\000\000\000\000"
  }
}
versions {
}

