# RUN: not tfg-translate -graphdef-to-mlir %s 2>&1 | FileCheck %s

# CHECK: INVALID_ARGUMENT: Duplicated node (or function argument) with the same name: `y`
# CHECK-NEXT: when importing function DuplicatedName

library {
  function {
    signature {
      name: "DuplicatedName"
      input_arg {
        name: "x"
        type_attr: "T"
      }
      output_arg {
        name: "y"
        type_attr: "T"
      }
      attr {
        name: "T"
        type: "type"
        allowed_values {
          list {
            type: DT_FLOAT
            type: DT_DOUBLE
            type: DT_INT32
            type: DT_INT64
          }
        }
      }
    }
    node_def {
      name: "y"
      op: "Identity"
      input: "x"
      attr {
        key: "T"
        value {
          placeholder: "T"
        }
      }
    }
    node_def {
      name: "y"
      op: "Identity"
      input: "x"
      attr {
        key: "T"
        value {
          placeholder: "T"
        }
      }
    }
    ret {
      key: "y"
      value: "y"
    }
  }
}
versions {
  producer: 762
}
