# RUN: not tfg-translate -graphdef-to-mlir %s 2>&1 | FileCheck %s

# CHECK: Node 'y' has an empty input

library {
  function {
    signature {
      name: "foo"
    }
    node_def {
      name: "y"
      input: ""
      op: "Identity"
      attr {
        key: "T"
        value {
          placeholder: "T"
        }
      }
    }
  }
}
