# RUN: not tfg-translate -graphdef-to-mlir %s 2>&1 | FileCheck %s

# CHECK: Invalid function attribute name

library {
  function {
    signature {
      name: "foo"
      input_arg {
        name: "a"
      }
      output_arg {
        name: "d"
      }
    }
    node_def {
      op: "Const"
      attr {
        key: "_b"
        value {
          placeholder: "T"
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_INT32
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT32
            tensor_shape {
            }
          }
        }
      }
    }
    ret {
      key: "d"
      value: "a"
    }
    attr {
      key: ""
      value {
        s: "a"
      }
    }
  }
}
