# RUN: not tfg-translate -graphdef-to-mlir %s 2>&1 | FileCheck %s

# CHECK: empty attr name

node {
  name: "SaveV/"
  op: "PartitionedCall"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: ""
    value {
    }
  }
  attr {
    key: "Tin"
    value {
    }
  }
  attr {
    key: "Tout"
    value {
    }
  }
  attr {
    key: "config"
    value {
      s: ""
    }
  }
  attr {
    key: "config_proto"
    value {
      s: ""
    }
  }
  attr {
    key: "executor_type"
    value {
      s: ""
    }
  }
  attr {
    key: "f"
    value {
      func {
      }
    }
  }
}
library {
  function {
  }
}
versions {
}
