# RUN: not tfg-translate -graphdef-to-mlir %s 2>&1 | FileCheck %s

# CHECK: Output index 18446744073709551615 is invalid (too large)

library {
  function {
    signature {
      name: "foo"
      attr {
        name: "T"
        type: "type"
      }
    }
    node_def {
      name: "two"
      op: "Const"
      attr {
        key: "dtype"
        value {
          type: DT_INT64
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_INT64
            tensor_shape {}
            int64_val: 2
          }
        }
      }
    }
    node_def {
      name: "a"
      op: "Cast"
      input: "two:output:18446744073709551615"
      attr {
        key: "DstT"
        value {
          placeholder: "T"
        }
      }
      attr {
        key: "SrcT"
        value {
          type: DT_INT64
        }
      }
    }
  }
}
