path: "tensorflow.__internal__.CompositeTensor"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.composite_tensor.CompositeTensor\'>"
  is_instance: "<class \'object\'>"
  member_method {
    name: "__init__"
  }
  member_method {
    name: "__tf_tracing_type__"
    argspec: "args=[\'self\', \'context\'], varargs=None, keywords=None, defaults=None"
  }
}
