path: "tensorflow.losses.Reduction"
tf_class {
  is_instance: "<class \'tf_keras.utils.losses_utils.ReductionV2\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "AUTO"
    mtype: "<class \'str\'>"
  }
  member {
    name: "NONE"
    mtype: "<class \'str\'>"
  }
  member {
    name: "SUM"
    mtype: "<class \'str\'>"
  }
  member {
    name: "SUM_OVER_BATCH_SIZE"
    mtype: "<class \'str\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "all"
    argspec: "args=[\'cls\'], varargs=None, keywords=None, defaults=None"
    method_kind: CLASS
  }
  member_method {
    name: "validate"
    argspec: "args=[\'cls\', \'key\'], varargs=None, keywords=None, defaults=None"
    method_kind: CLASS
  }
}
