path: "tensorflow.saved_model"
tf_module {
  member {
    name: "ASSETS_DIRECTORY"
    mtype: "<type \'str\'>"
  }
  member {
    name: "ASSETS_KEY"
    mtype: "<type \'str\'>"
  }
  member {
    name: "CLASSIFY_INPUTS"
    mtype: "<type \'str\'>"
  }
  member {
    name: "CLASSIFY_METHOD_NAME"
    mtype: "<type \'str\'>"
  }
  member {
    name: "CLASSIFY_OUTPUT_CLASSES"
    mtype: "<type \'str\'>"
  }
  member {
    name: "CLASSIFY_OUTPUT_SCORES"
    mtype: "<type \'str\'>"
  }
  member {
    name: "DEFAULT_SERVING_SIGNATURE_DEF_KEY"
    mtype: "<type \'str\'>"
  }
  member {
    name: "GPU"
    mtype: "<type \'str\'>"
  }
  member {
    name: "MAIN_OP_KEY"
    mtype: "<type \'str\'>"
  }
  member {
    name: "PREDICT_INPUTS"
    mtype: "<type \'str\'>"
  }
  member {
    name: "PREDICT_METHOD_NAME"
    mtype: "<type \'str\'>"
  }
  member {
    name: "PREDICT_OUTPUTS"
    mtype: "<type \'str\'>"
  }
  member {
    name: "REGRESS_INPUTS"
    mtype: "<type \'str\'>"
  }
  member {
    name: "REGRESS_METHOD_NAME"
    mtype: "<type \'str\'>"
  }
  member {
    name: "REGRESS_OUTPUTS"
    mtype: "<type \'str\'>"
  }
  member {
    name: "SAVED_MODEL_FILENAME_PB"
    mtype: "<type \'str\'>"
  }
  member {
    name: "SAVED_MODEL_FILENAME_PBTXT"
    mtype: "<type \'str\'>"
  }
  member {
    name: "SAVED_MODEL_SCHEMA_VERSION"
    mtype: "<type \'int\'>"
  }
  member {
    name: "SERVING"
    mtype: "<type \'str\'>"
  }
  member {
    name: "TPU"
    mtype: "<type \'str\'>"
  }
  member {
    name: "TRANING"
    mtype: "<type \'str\'>"
  }
  member {
    name: "VARIABLES_DIRECTORY"
    mtype: "<type \'str\'>"
  }
  member {
    name: "VARIABLES_FILENAME"
    mtype: "<type \'str\'>"
  }
  member_method {
    name: "build_signature_def"
    argspec: "args=[\'inputs\', \'outputs\', \'method_name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "classification_signature_def"
    argspec: "args=[\'examples\', \'classes\', \'scores\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "contains_saved_model"
    argspec: "args=[\'export_dir\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_valid_signature"
    argspec: "args=[\'signature_def\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "predict_signature_def"
    argspec: "args=[\'inputs\', \'outputs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "regression_signature_def"
    argspec: "args=[\'examples\', \'predictions\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "save"
    argspec: "args=[\'obj\', \'export_dir\', \'signatures\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
