path: "tensorflow.__internal__.tracking.TrackableSaver"
tf_class {
  is_instance: "<class \'tensorflow.python.training.tracking.util.TrackableSaver\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'graph_view\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "restore"
    argspec: "args=[\'self\', \'save_path\', \'options\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "save"
    argspec: "args=[\'self\', \'file_prefix\', \'checkpoint_number\', \'session\', \'options\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
}
