path: "tensorflow.image.ResizeMethod"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.image_ops_impl.ResizeMethod\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "AREA"
    mtype: "<type \'str\'>"
  }
  member {
    name: "BICUBIC"
    mtype: "<type \'str\'>"
  }
  member {
    name: "BILINEAR"
    mtype: "<type \'str\'>"
  }
  member {
    name: "GAUSSIAN"
    mtype: "<type \'str\'>"
  }
  member {
    name: "LANCZOS3"
    mtype: "<type \'str\'>"
  }
  member {
    name: "LANCZOS5"
    mtype: "<type \'str\'>"
  }
  member {
    name: "MITCHELLCUBIC"
    mtype: "<type \'str\'>"
  }
  member {
    name: "NEAREST_NEIGHBOR"
    mtype: "<type \'str\'>"
  }
  member_method {
    name: "__init__"
  }
}
