path: "tensorflow.tpu.experimental.embedding.CustomCombiner"
tf_class {
  is_instance: "<class \'tensorflow.python.tpu.tpu_embedding_v2_utils.CustomCombiner\'>"
  is_instance: "<class \'tensorflow.python.tpu.tpu_embedding_v2_utils._WithSlotVariables\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "CUSTOM_COMBINER_SLOT_NAME"
    mtype: "<class \'str\'>"
  }
  member_method {
    name: "__eq__"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'combiner_computation\', \'max_valency\', \'num_weights\', \'initializer\', \'combiner_weights_learning_rate\'], varargs=None, keywords=None, defaults=[\'0\', \'None\', \'0.01\'], "
  }
}
