path: "tensorflow.keras.preprocessing.image.NumpyArrayIterator"
tf_class {
  is_instance: "<class \'tensorflow.python.keras.preprocessing.image.NumpyArrayIterator\'>"
  is_instance: "<class \'tensorflow.python.keras.preprocessing.image.Iterator\'>"
  is_instance: "<class \'tensorflow.python.keras.utils.data_utils.Sequence\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'x\', \'y\', \'image_data_generator\', \'batch_size\', \'shuffle\', \'seed\', \'data_format\', \'save_to_dir\', \'save_prefix\', \'save_format\', \'subset\'], varargs=None, keywords=None, defaults=[\'32\', \'False\', \'None\', \'None\', \'None\', \'\', \'png\', \'None\'], "
  }
  member_method {
    name: "next"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "on_epoch_end"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "reset"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
