path: "tensorflow.__internal__.types.Tensor"
tf_class {
  is_instance: "<class \'tensorflow.python.types.core.Tensor\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "shape"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
}
