path: "tensorflow.keras.callbacks.ReduceLROnPlateau"
tf_class {
  is_instance: "<class \'tensorflow.python.keras.callbacks.ReduceLROnPlateau\'>"
  is_instance: "<class \'tensorflow.python.keras.callbacks.Callback\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'monitor\', \'factor\', \'patience\', \'verbose\', \'mode\', \'min_delta\', \'cooldown\', \'min_lr\'], varargs=None, keywords=kwargs, defaults=[\'val_loss\', \'0.1\', \'10\', \'0\', \'auto\', \'0.0001\', \'0\', \'0\'], "
  }
  member_method {
    name: "in_cooldown"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "on_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_begin"
    argspec: "args=[\'self\', \'epoch\', \'logs\', \'mode\'], varargs=None, keywords=None, defaults=[\'None\', \'train\'], "
  }
  member_method {
    name: "on_epoch_end"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "set_model"
    argspec: "args=[\'self\', \'model\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_params"
    argspec: "args=[\'self\', \'params\'], varargs=None, keywords=None, defaults=None"
  }
}
