path: "tensorflow.__internal__"
tf_module {
  member {
    name: "decorator"
    mtype: "<type \'module\'>"
  }
  member {
    name: "test"
    mtype: "<type \'module\'>"
  }
  member {
    name: "tracking"
    mtype: "<type \'module\'>"
  }
}
