path: "tensorflow.experimental"
tf_module {
  member {
    name: "tensorrt"
    mtype: "<type \'module\'>"
  }
  member_method {
    name: "function_executor_type"
    argspec: "args=[\'executor_type\'], varargs=None, keywords=None, defaults=None"
  }
}
