path: "tensorflow.__internal__.distribute.multi_process_runner.NotInitializedError"
tf_class {
  is_instance: "<class \'tensorflow.python.distribute.multi_process_runner.NotInitializedError\'>"
  is_instance: "<type \'exceptions.RuntimeError\'>"
  member {
    name: "args"
    mtype: "<type \'getset_descriptor\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "add_note"
  }
}
