path: "tensorflow.train.experimental"
tf_module {
  member {
    name: "MaxShardSizePolicy"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "PythonState"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "ShardByTaskPolicy"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "ShardableTensor"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ShardingCallback"
    mtype: "<class \'abc.ABCMeta\'>"
  }
}
