path: "tensorflow.autograph.experimental"
tf_module {
  member {
    name: "Feature"
    mtype: "<class \'enum.EnumType\'>"
  }
  member_method {
    name: "do_not_convert"
    argspec: "args=[\'func\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "set_loop_options"
    argspec: "args=[\'parallel_iterations\', \'swap_memory\', \'maximum_iterations\', \'shape_invariants\'], varargs=None, keywords=None, defaults=[\'<object object instance>\', \'<object object instance>\', \'<object object instance>\', \'<object object instance>\'], "
  }
}
