path: "tensorflow.dtypes.experimental"
tf_module {
  member {
    name: "float8_e4m3b11fnuz"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "float8_e4m3fn"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "float8_e4m3fnuz"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "float8_e5m2"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "float8_e5m2fnuz"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "int2"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "int4"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "uint2"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
  member {
    name: "uint4"
    mtype: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  }
}
