path: "tensorflow.data.experimental.service.WorkerServer"
tf_class {
  is_instance: "<class \'tensorflow.python.data.experimental.service.server_lib.WorkerServer\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'config\', \'start\'], varargs=None, keywords=None, defaults=[\'True\'], "
  }
  member_method {
    name: "join"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "start"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "stop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
