path: "tensorflow.train"
tf_module {
  member {
    name: "AdadeltaOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "AdagradDAOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "AdagradOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "AdamOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "BytesList"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "Checkpoint"
    mtype: "<type \'type\'>"
  }
  member {
    name: "CheckpointManager"
    mtype: "<type \'type\'>"
  }
  member {
    name: "CheckpointSaverHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "CheckpointSaverListener"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ChiefSessionCreator"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ClusterDef"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "ClusterSpec"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Coordinator"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Example"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "ExponentialMovingAverage"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Feature"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "FeatureList"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "FeatureLists"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "Features"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "FeedFnHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "FinalOpsHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "FloatList"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "FtrlOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "GlobalStepWaiterHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "GradientDescentOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Int64List"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "JobDef"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "LoggingTensorHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "LooperThread"
    mtype: "<type \'type\'>"
  }
  member {
    name: "MomentumOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "MonitoredSession"
    mtype: "<type \'type\'>"
  }
  member {
    name: "NanLossDuringTrainingError"
    mtype: "<type \'type\'>"
  }
  member {
    name: "NanTensorHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Optimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ProximalAdagradOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ProximalGradientDescentOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RMSPropOptimizer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Scaffold"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SecondOrStepTimer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SequenceExample"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "Server"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ServerDef"
    mtype: "<class \'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType\'>"
  }
  member {
    name: "SessionCreator"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SessionManager"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SessionRunArgs"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SessionRunContext"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SessionRunHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SessionRunValues"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SingularMonitoredSession"
    mtype: "<type \'type\'>"
  }
  member {
    name: "StepCounterHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "StopAtStepHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "SummarySaverHook"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Supervisor"
    mtype: "<type \'type\'>"
  }
  member {
    name: "VocabInfo"
    mtype: "<type \'type\'>"
  }
  member {
    name: "WorkerSessionCreator"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "cosine_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'alpha\', \'name\'], varargs=None, keywords=None, defaults=[\'0.0\', \'None\'], "
  }
  member_method {
    name: "cosine_decay_restarts"
    argspec: "args=[\'learning_rate\', \'global_step\', \'first_decay_steps\', \'t_mul\', \'m_mul\', \'alpha\', \'name\'], varargs=None, keywords=None, defaults=[\'2.0\', \'1.0\', \'0.0\', \'None\'], "
  }
  member_method {
    name: "exponential_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'decay_rate\', \'staircase\', \'name\'], varargs=None, keywords=None, defaults=[\'False\', \'None\'], "
  }
  member_method {
    name: "get_checkpoint_state"
    argspec: "args=[\'checkpoint_dir\', \'latest_filename\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "inverse_time_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'decay_rate\', \'staircase\', \'name\'], varargs=None, keywords=None, defaults=[\'False\', \'None\'], "
  }
  member_method {
    name: "latest_checkpoint"
    argspec: "args=[\'checkpoint_dir\', \'latest_filename\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "linear_cosine_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'num_periods\', \'alpha\', \'beta\', \'name\'], varargs=None, keywords=None, defaults=[\'0.5\', \'0.0\', \'0.001\', \'None\'], "
  }
  member_method {
    name: "list_variables"
    argspec: "args=[\'ckpt_dir_or_file\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "load_checkpoint"
    argspec: "args=[\'ckpt_dir_or_file\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "load_variable"
    argspec: "args=[\'ckpt_dir_or_file\', \'name\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "natural_exp_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'decay_rate\', \'staircase\', \'name\'], varargs=None, keywords=None, defaults=[\'False\', \'None\'], "
  }
  member_method {
    name: "noisy_linear_cosine_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'initial_variance\', \'variance_decay\', \'num_periods\', \'alpha\', \'beta\', \'name\'], varargs=None, keywords=None, defaults=[\'1.0\', \'0.55\', \'0.5\', \'0.0\', \'0.001\', \'None\'], "
  }
  member_method {
    name: "piecewise_constant"
    argspec: "args=[\'x\', \'boundaries\', \'values\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "polynomial_decay"
    argspec: "args=[\'learning_rate\', \'global_step\', \'decay_steps\', \'end_learning_rate\', \'power\', \'cycle\', \'name\'], varargs=None, keywords=None, defaults=[\'0.0001\', \'1.0\', \'False\', \'None\'], "
  }
  member_method {
    name: "sdca_fprint"
    argspec: "args=[\'input\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "sdca_optimizer"
    argspec: "args=[\'sparse_example_indices\', \'sparse_feature_indices\', \'sparse_feature_values\', \'dense_features\', \'example_weights\', \'example_labels\', \'sparse_indices\', \'sparse_weights\', \'dense_weights\', \'example_state_data\', \'loss_type\', \'l1\', \'l2\', \'num_loss_partitions\', \'num_inner_iterations\', \'adaptative\', \'name\'], varargs=None, keywords=None, defaults=[\'True\', \'None\'], "
  }
  member_method {
    name: "sdca_shrink_l1"
    argspec: "args=[\'weights\', \'l1\', \'l2\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "summary_iterator"
    argspec: "args=[\'path\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "warm_start"
    argspec: "args=[\'ckpt_to_initialize_from\', \'vars_to_warm_start\', \'var_name_to_vocab_info\', \'var_name_to_prev_var_name\'], varargs=None, keywords=None, defaults=[\'.*\', \'None\', \'None\'], "
  }
}
