path: "tensorflow.summary.experimental"
tf_module {
  member_method {
    name: "get_step"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_step"
    argspec: "args=[\'step\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "summary_scope"
    argspec: "args=[\'name\', \'default_name\', \'values\'], varargs=None, keywords=None, defaults=[\'summary\', \'None\'], "
  }
  member_method {
    name: "write_raw_pb"
    argspec: "args=[\'tensor\', \'step\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
}
