path: "tensorflow.saved_model.experimental"
tf_module {
  member {
    name: "TrackableResource"
    mtype: "<class \'tensorflow.python.training.tracking.resource._ResourceMetaclass\'>"
  }
  member {
    name: "VariablePolicy"
    mtype: "<class \'enum.EnumMeta\'>"
  }
}
