path: "tensorflow.tpu.experimental"
tf_module {
  member_method {
    name: "initialize_tpu_system"
    argspec: "args=[\'cluster_resolver\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
