path: "tensorflow.experimental.tensorrt.ConversionParams"
tf_class {
  is_instance: "<class \'tensorflow.python.compiler.tensorrt.trt_convert.TrtConversionParams\'>"
  is_instance: "<class \'tensorflow.python.compiler.tensorrt.trt_convert.TrtConversionParams\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "allow_build_at_runtime"
    mtype: "<type \'property\'>"
  }
  member {
    name: "max_workspace_size_bytes"
    mtype: "<type \'property\'>"
  }
  member {
    name: "maximum_cached_engines"
    mtype: "<type \'property\'>"
  }
  member {
    name: "minimum_segment_size"
    mtype: "<type \'property\'>"
  }
  member {
    name: "precision_mode"
    mtype: "<type \'property\'>"
  }
  member {
    name: "use_calibration"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
