path: "tensorflow.random_uniform_initializer"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.init_ops_v2.RandomUniform\'>"
  is_instance: "<class \'tensorflow.python.ops.init_ops_v2.Initializer\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'minval\', \'maxval\', \'seed\'], varargs=None, keywords=None, defaults=[\'-0.05\', \'0.05\', \'None\'], "
  }
  member_method {
    name: "from_config"
    argspec: "args=[\'cls\', \'config\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
