path: "tensorflow.estimator.SessionRunContext"
tf_class {
  is_instance: "<class \'tensorflow.python.training.session_run_hook.SessionRunContext\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "original_args"
    mtype: "<type \'property\'>"
  }
  member {
    name: "session"
    mtype: "<type \'property\'>"
  }
  member {
    name: "stop_requested"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'original_args\', \'session\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "request_stop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
