path: "tensorflow.data.IteratorSpec"
tf_class {
  is_instance: "<class \'tensorflow.python.data.ops.iterator_ops.IteratorSpec\'>"
  is_instance: "<class \'tensorflow.python.framework.type_spec.TypeSpec\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "value_type"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'element_spec\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_value"
    argspec: "args=[\'value\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_compatible_with"
    argspec: "args=[\'self\', \'spec_or_value\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "most_specific_compatible_type"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
}
