path: "tensorflow.__internal__"
tf_module {
  member {
    name: "CompositeTensor"
    mtype: "<type \'type\'>"
  }
  member {
    name: "decorator"
    mtype: "<type \'module\'>"
  }
  member {
    name: "dispatch"
    mtype: "<type \'module\'>"
  }
  member {
    name: "distribute"
    mtype: "<type \'module\'>"
  }
  member {
    name: "nest"
    mtype: "<type \'module\'>"
  }
  member {
    name: "test"
    mtype: "<type \'module\'>"
  }
  member {
    name: "tf2"
    mtype: "<type \'module\'>"
  }
  member {
    name: "tracking"
    mtype: "<type \'module\'>"
  }
  member_method {
    name: "execute_fn_for_device"
    argspec: "args=[\'device_branch_fns\', \'default_fn\', \'name\'], varargs=None, keywords=None, defaults=[\'execute_fn\'], "
  }
}
