path: "tensorflow.__internal__.feature_column.SequenceDenseColumn.TensorSequenceLengthPair"
tf_class {
  is_instance: "<class \'tensorflow.python.feature_column.feature_column_v2.TensorSequenceLengthPair\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "dense_tensor"
    mtype: "<type \'property\'>"
  }
  member {
    name: "sequence_length"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
