path: "tensorflow.data.IteratorSpec"
tf_class {
  is_instance: "<class \'tensorflow.python.data.ops.iterator_ops.IteratorSpec\'>"
  is_instance: "<class \'tensorflow.python.framework.type_spec.TypeSpec\'>"
  is_instance: "<class \'tensorflow.python.types.internal.TypeSpec\'>"
  is_instance: "<class \'tensorflow.python.types.trace.TraceType\'>"
  is_instance: "<class \'tensorflow.core.function.trace_type.serialization.Serializable\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "value_type"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'element_spec\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "cast"
    argspec: "args=[\'self\', \'value\', \'casting_context\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "experimental_as_proto"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "experimental_from_proto"
    argspec: "args=[\'cls\', \'proto\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "experimental_type_proto"
    argspec: "args=[\'cls\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "flatten"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_tensors"
    argspec: "args=[\'self\', \'tensors\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_value"
    argspec: "args=[\'value\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_compatible_with"
    argspec: "args=[\'self\', \'spec_or_value\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_subtype_of"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "most_specific_common_supertype"
    argspec: "args=[\'self\', \'others\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "most_specific_compatible_type"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "placeholder_value"
    argspec: "args=[\'self\', \'placeholder_context\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "to_tensors"
    argspec: "args=[\'self\', \'value\'], varargs=None, keywords=None, defaults=None"
  }
}
