path: "tensorflow.__internal__.saved_model.StructureCoder"
tf_class {
  is_instance: "<class \'tensorflow.python.saved_model.nested_structure_coder.StructureCoder\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
  }
  member_method {
    name: "can_encode"
    argspec: "args=[\'self\', \'nested_structure\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "decode_proto"
    argspec: "args=[\'self\', \'proto\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "encode_structure"
    argspec: "args=[\'self\', \'nested_structure\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "register_codec"
    argspec: "args=[\'cls\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
}
