path: "tensorflow.data"
tf_module {
  member {
    name: "AUTOTUNE"
    mtype: "<class \'int\'>"
  }
  member {
    name: "Dataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "DatasetSpec"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "FixedLengthRecordDataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "INFINITE_CARDINALITY"
    mtype: "<class \'int\'>"
  }
  member {
    name: "Iterator"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "IteratorSpec"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "NumpyIterator"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Options"
    mtype: "<class \'type\'>"
  }
  member {
    name: "TFRecordDataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "TextLineDataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "ThreadingOptions"
    mtype: "<class \'type\'>"
  }
  member {
    name: "UNKNOWN_CARDINALITY"
    mtype: "<class \'int\'>"
  }
  member {
    name: "experimental"
    mtype: "<class \'module\'>"
  }
}
