path: "tensorflow.__internal__.test.combinations.NamedObject"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.test_combinations.NamedObject\'>"
  is_instance: "<class \'object\'>"
  member_method {
    name: "__call__"
    argspec: "args=[\'self\'], varargs=args, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "__getattr__"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'name\', \'obj\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__iter__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
