path: "tensorflow.data.experimental.service.DispatchServer"
tf_class {
  is_instance: "<class \'tensorflow.python.data.experimental.service.server_lib.DispatchServer\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "target"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'config\', \'start\'], varargs=None, keywords=None, defaults=[\'None\', \'True\'], "
  }
  member_method {
    name: "join"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "start"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
