path: "tensorflow.train.experimental"
tf_module {
  member {
    name: "DynamicLossScale"
    mtype: "<type \'type\'>"
  }
  member {
    name: "FixedLossScale"
    mtype: "<type \'type\'>"
  }
  member {
    name: "LossScale"
    mtype: "<type \'type\'>"
  }
  member {
    name: "PythonState"
    mtype: "<type \'type\'>"
  }
}
