path: "tensorflow.experimental.ExtensionType"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.extension_type.ExtensionType\'>"
  is_instance: "<class \'tensorflow.python.framework.composite_tensor.CompositeTensor\'>"
  is_instance: "<class \'object\'>"
  member_method {
    name: "__eq__"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__getattr__"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\'], varargs=args, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "__ne__"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__tf_tracing_type__"
    argspec: "args=[\'self\', \'context\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__validate__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
