path: "tensorflow.config.LogicalDeviceConfiguration"
tf_class {
  is_instance: "<class \'tensorflow.python.eager.context.LogicalDeviceConfiguration\'>"
  is_instance: "<class \'tensorflow.python.eager.context.LogicalDeviceConfiguration\'>"
  is_instance: "<class \'tuple\'>"
  member {
    name: "experimental_device_ordinal"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "experimental_priority"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "memory_limit"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "__new__"
    argspec: "args=[\'cls\', \'memory_limit\', \'experimental_priority\', \'experimental_device_ordinal\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
