path: "tensorflow.RunOptions.Experimental"
tf_proto {
  descriptor {
    name: "Experimental"
    field {
      name: "collective_graph_key"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_INT64
    }
  }
}
