path: "tensorflow.io.SparseFeature"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.parsing_config.SparseFeature\'>"
  is_instance: "<class \'tensorflow.python.ops.parsing_config.SparseFeature\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "already_sorted"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "dtype"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "index_key"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "size"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "value_key"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
