path: "tensorflow.keras.layers.experimental.preprocessing"
tf_module {
  member {
    name: "CategoryCrossing"
    mtype: "<type \'type\'>"
  }
  member {
    name: "CenterCrop"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Normalization"
    mtype: "<type \'type\'>"
  }
  member {
    name: "PreprocessingLayer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomContrast"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomCrop"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomFlip"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomHeight"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomRotation"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomTranslation"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RandomWidth"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Rescaling"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Resizing"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TextVectorization"
    mtype: "<type \'type\'>"
  }
}
