path: "tensorflow.keras.__internal__"
tf_module {
  member {
    name: "backend"
    mtype: "<type \'module\'>"
  }
  member {
    name: "losses"
    mtype: "<type \'module\'>"
  }
  member {
    name: "models"
    mtype: "<type \'module\'>"
  }
}
