path: "tensorflow.lite"
tf_module {
  member {
    name: "Interpreter"
    mtype: "<type \'type\'>"
  }
  member {
    name: "OpsSet"
    mtype: "<class \'enum.EnumMeta\'>"
  }
  member {
    name: "Optimize"
    mtype: "<class \'enum.EnumMeta\'>"
  }
  member {
    name: "RepresentativeDataset"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TFLiteConverter"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TargetSpec"
    mtype: "<type \'type\'>"
  }
}
