path: "tensorflow.data.experimental.service"
tf_module {
  member {
    name: "MasterServer"
    mtype: "<type \'type\'>"
  }
  member {
    name: "WorkerServer"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "distribute"
    argspec: "args=[\'processing_mode\', \'service\', \'job_name\', \'max_outstanding_requests\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
}
