path: "tensorflow.DType"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.dtypes.DType\'>"
  is_instance: "<class \'tensorflow.python.framework._dtypes.DType\'>"
  is_instance: "<class \'pybind11_builtins.pybind11_object\'>"
  member {
    name: "as_datatype_enum"
    mtype: "<type \'property\'>"
  }
  member {
    name: "as_numpy_dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "base_dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_bool"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_complex"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_floating"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_integer"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_numpy_compatible"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_quantized"
    mtype: "<type \'property\'>"
  }
  member {
    name: "is_unsigned"
    mtype: "<type \'property\'>"
  }
  member {
    name: "limits"
    mtype: "<type \'property\'>"
  }
  member {
    name: "max"
    mtype: "<type \'property\'>"
  }
  member {
    name: "min"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "real_dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "size"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "is_compatible_with"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
}
