path: "tensorflow.data.Iterator"
tf_class {
  is_instance: "<class \'tensorflow.python.data.ops.iterator_ops.IteratorBase\'>"
  is_instance: "<class \'collections.abc.Iterator\'>"
  member {
    name: "element_spec"
    mtype: "<class \'abc.abstractproperty\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "get_next"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_next_as_optional"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
