path: "tensorflow.experimental.tensorrt"
tf_module {
  member {
    name: "ConversionParams"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Converter"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TrtPrecisionMode"
    mtype: "<class \'tensorflow.python.compiler.tensorrt.types._EnumMeta\'>"
  }
  member {
    name: "TrtProfileStrategy"
    mtype: "<class \'tensorflow.python.compiler.tensorrt.types._EnumMeta\'>"
  }
}
