path: "tensorflow.data"
tf_module {
  member {
    name: "Dataset"
    mtype: "<type \'type\'>"
  }
  member {
    name: "FixedLengthRecordDataset"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Options"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TFRecordDataset"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TextLineDataset"
    mtype: "<type \'type\'>"
  }
  member {
    name: "experimental"
    mtype: "<type \'module\'>"
  }
}
