path: "tensorflow.experimental.tensorrt"
tf_module {
  member {
    name: "ConversionParams"
    mtype: "<type \'type\'>"
  }
  member {
    name: "Converter"
    mtype: "<type \'type\'>"
  }
}
