path: "tensorflow.__internal__.dispatch"
tf_module {
  member {
    name: "GlobalOpDispatcher"
    mtype: "<type \'type\'>"
  }
  member {
    name: "OpDispatcher"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "add_dispatch_support"
    argspec: "args=[\'target\'], varargs=None, keywords=None, defaults=None"
  }
}
