path: "tensorflow.config.LogicalDeviceConfiguration"
tf_class {
  is_instance: "<class \'tensorflow.python.eager.context.LogicalDeviceConfiguration\'>"
  is_instance: "<class \'tensorflow.python.eager.context.LogicalDeviceConfiguration\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "memory_limit"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
