path: "tensorflow.Tensor"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.tensor.Tensor\'>"
  is_instance: "<class \'tensorflow.python.types.internal.NativeObject\'>"
  is_instance: "<class \'tensorflow.python.types.core.Symbol\'>"
  is_instance: "<class \'tensorflow.python.types.core.Tensor\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "OVERLOADABLE_OPERATORS"
    mtype: "<class \'set\'>"
  }
  member {
    name: "dtype"
    mtype: "<class \'property\'>"
  }
  member {
    name: "name"
    mtype: "<class \'property\'>"
  }
  member {
    name: "ndim"
    mtype: "<class \'property\'>"
  }
  member {
    name: "shape"
    mtype: "<class \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "eval"
    argspec: "args=[\'self\', \'feed_dict\', \'session\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "experimental_ref"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_shape"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "ref"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_shape"
    argspec: "args=[\'self\', \'shape\'], varargs=None, keywords=None, defaults=None"
  }
}
