path: "tensorflow.distribute.cluster_resolver.SimpleClusterResolver"
tf_class {
  is_instance: "<class \'tensorflow.python.distribute.cluster_resolver.cluster_resolver.SimpleClusterResolver\'>"
  is_instance: "<class \'tensorflow.python.distribute.cluster_resolver.cluster_resolver.ClusterResolver\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "environment"
    mtype: "<type \'property\'>"
  }
  member {
    name: "rpc_layer"
    mtype: "<type \'property\'>"
  }
  member {
    name: "task_id"
    mtype: "<type \'property\'>"
  }
  member {
    name: "task_type"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'cluster_spec\', \'master\', \'task_type\', \'task_id\', \'environment\', \'num_accelerators\', \'rpc_layer\'], varargs=None, keywords=None, defaults=[\'\', \'None\', \'None\', \'\', \'None\', \'None\'], "
  }
  member_method {
    name: "cluster_spec"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "master"
    argspec: "args=[\'self\', \'task_type\', \'task_id\', \'rpc_layer\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "num_accelerators"
    argspec: "args=[\'self\', \'task_type\', \'task_id\', \'config_proto\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
}
