path: "tensorflow.experimental.dtensor.Layout"
tf_class {
  is_instance: "<class \'tensorflow.dtensor.python.layout.Layout\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'sharding_specs\', \'mesh\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "as_proto"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "batch_sharded"
    argspec: "args=[\'mesh\', \'batch_dim\', \'rank\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "delete"
    argspec: "args=[\'self\', \'dims\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_str"
    argspec: "args=[\'layout_str\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_string"
    argspec: "args=[\'layout_str\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "inner_sharded"
    argspec: "args=[\'mesh\', \'inner_dim\', \'rank\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_fully_replicated"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "mesh_proto"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "num_shards"
    argspec: "args=[\'self\', \'idx\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "offset_to_shard"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "offset_tuple_to_global_index"
    argspec: "args=[\'self\', \'offset_tuple\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "replicated"
    argspec: "args=[\'mesh\', \'rank\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "serialized_string"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "to_string"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "unravel"
    argspec: "args=[\'self\', \'unpacked_tensors\'], varargs=None, keywords=None, defaults=None"
  }
}
