op {
  name: "AnonymousIteratorV2"
  output_arg {
    name: "handle"
    type: DT_RESOURCE
  }
  output_arg {
    name: "deleter"
    type: DT_VARIANT
  }
  attr {
    name: "output_types"
    type: "list(type)"
    has_minimum: true
    minimum: 1
  }
  attr {
    name: "output_shapes"
    type: "list(shape)"
    has_minimum: true
    minimum: 1
  }
  is_stateful: true
}
