op 	 {
  name: "AnonymousMutableHashTable"
  output_arg {
    name: "table_handle"
    type: DT_RESOURCE
  }
  attr {
    name: "key_dtype"
    type: "type"
  }
  attr {
    name: "value_dtype"
    type: "type"
  }
  is_stateful: true
}
