op {
  name: "CompositeTensorVariantFromComponents"
  input_arg {
    name: "components"
    type_list_attr: "Tcomponents"
  }
  output_arg {
    name: "encoded"
    type: DT_VARIANT
  }
  attr {
    name: "metadata"
    type: "string"
  }
  attr {
    name: "Tcomponents"
    type: "list(type)"
    has_minimum: true
  }
}
