op 	 {
  name: "ExperimentalThreadPoolHandle"
  output_arg {
    name: "handle"
    type: DT_RESOURCE
  }
  attr {
    name: "num_threads"
    type: "int"
  }
  attr {
    name: "max_intra_op_parallelism"
    type: "int"
    default_value {
      i: 1
    }
  }
  attr {
    name: "display_name"
    type: "string"
  }
  attr {
    name: "container"
    type: "string"
    default_value {
      s: ""
    }
  }
  attr {
    name: "shared_name"
    type: "string"
    default_value {
      s: ""
    }
  }
  is_stateful: true
}
