op {
  name: "ExperimentalCSVDataset"
  input_arg {
    name: "filenames"
    type: DT_STRING
  }
  input_arg {
    name: "compression_type"
    type: DT_STRING
  }
  input_arg {
    name: "buffer_size"
    type: DT_INT64
  }
  input_arg {
    name: "header"
    type: DT_BOOL
  }
  input_arg {
    name: "field_delim"
    type: DT_STRING
  }
  input_arg {
    name: "use_quote_delim"
    type: DT_BOOL
  }
  input_arg {
    name: "na_value"
    type: DT_STRING
  }
  input_arg {
    name: "select_cols"
    type: DT_INT64
  }
  input_arg {
    name: "record_defaults"
    type_list_attr: "output_types"
  }
  output_arg {
    name: "handle"
    type: DT_VARIANT
  }
  attr {
    name: "output_types"
    type: "list(type)"
    has_minimum: true
    minimum: 1
    allowed_values {
      list {
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_INT32
        type: DT_INT64
        type: DT_STRING
      }
    }
  }
  attr {
    name: "output_shapes"
    type: "list(shape)"
    has_minimum: true
    minimum: 1
  }
  is_stateful: true
}
