op {
  name: "FinalizeTPUEmbeddingV2"
  input_arg {
    name: "common_config"
    type: DT_STRING
  }
  input_arg {
    name: "memory_config"
    type: DT_STRING
  }
  output_arg {
    name: "embedding_partitions"
    type: DT_STRING
  }
  output_arg {
    name: "hbm_buffers_config"
    type: DT_STRING
  }
  is_stateful: true
}
