op {
  name: "ImageProjectiveTransformV2"
  input_arg {
    name: "images"
    type_attr: "dtype"
  }
  input_arg {
    name: "transforms"
    type: DT_FLOAT
  }
  input_arg {
    name: "output_shape"
    type: DT_INT32
  }
  output_arg {
    name: "transformed_images"
    type_attr: "dtype"
  }
  attr {
    name: "dtype"
    type: "type"
    allowed_values {
      list {
        type: DT_UINT8
        type: DT_INT32
        type: DT_INT64
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }
  }
  attr {
    name: "interpolation"
    type: "string"
  }
  attr {
    name: "fill_mode"
    type: "string"
    default_value {
      s: "CONSTANT"
    }
  }
}
