op 	 {
  name: "InterleaveTensorsToXLATuple"
  input_arg {
    name: "indices"
    type_attr: "indices_type"
  }
  input_arg {
    name: "values"
    type_attr: "values_type"
  }
  output_arg {
    name: "output"
    type: DT_VARIANT
  }
  attr {
    name: "indices_type"
    type: "type"
    default_value {
      type: DT_INT32
    }
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
  attr {
    name: "values_type"
    type: "type"
    allowed_values {
      list {
        type: DT_HALF
        type: DT_BFLOAT16
        type: DT_FLOAT
        type: DT_INT32
        type: DT_UINT32
        type: DT_INT64
      }
    }
  }
}
