op 	 {
  name: "LookupTableRemoveV2"
  input_arg {
    name: "table_handle"
    type: DT_RESOURCE
  }
  input_arg {
    name: "keys"
    type_attr: "Tin"
  }
  attr {
    name: "Tin"
    type: "type"
  }
  is_stateful: true
}
