op {
  name: "MatrixDiagV2"
  input_arg {
    name: "diagonal"
    type_attr: "T"
  }
  input_arg {
    name: "k"
    type: DT_INT32
  }
  input_arg {
    name: "num_rows"
    type: DT_INT32
  }
  input_arg {
    name: "num_cols"
    type: DT_INT32
  }
  input_arg {
    name: "padding_value"
    type_attr: "T"
  }
  output_arg {
    name: "output"
    type_attr: "T"
  }
  attr {
    name: "T"
    type: "type"
  }
}
