op 	 {
  name: "MatrixSetDiagV3"
  input_arg {
    name: "input"
    type_attr: "T"
  }
  input_arg {
    name: "diagonal"
    type_attr: "T"
  }
  input_arg {
    name: "k"
    type: DT_INT32
  }
  output_arg {
    name: "output"
    type_attr: "T"
  }
  attr {
    name: "T"
    type: "type"
  }
  attr {
    name: "align"
    type: "string"
    default_value {
      s: "RIGHT_LEFT"
    }
    allowed_values {
      list {
        s: "LEFT_RIGHT"
        s: "RIGHT_LEFT"
        s: "LEFT_LEFT"
        s: "RIGHT_RIGHT"
      }
    }
  }
}
