op {
  name: "NonDeterministicInts"
  input_arg {
    name: "shape"
    type_attr: "shape_dtype"
  }
  output_arg {
    name: "output"
    type_attr: "dtype"
  }
  attr {
    name: "dtype"
    type: "type"
    default_value {
      type: DT_INT64
    }
  }
  attr {
    name: "shape_dtype"
    type: "type"
    default_value {
      type: DT_INT64
    }
  }
  is_stateful: true
}
