op {
  name: "PrintV2"
  input_arg {
    name: "input"
    type: DT_STRING
  }
  attr {
    name: "output_stream"
    type: "string"
    default_value {
      s: "stderr"
    }
    allowed_values {
      list {
        s: "stdout"
        s: "stderr"
        s: "log(info)"
        s: "log(warning)"
        s: "log(error)"
      }
    }
  }
  is_stateful: true
}
op {
  name: "PrintV2"
  input_arg {
    name: "input"
    type: DT_STRING
  }
  attr {
    name: "output_stream"
    type: "string"
    default_value {
      s: "stderr"
    }
  }
  is_stateful: true
}
op {
  name: "PrintV2"
  input_arg {
    name: "input"
    type: DT_STRING
  }
  attr {
    name: "output_stream"
    type: "string"
    default_value {
      s: "stderr"
    }
  }
  attr {
    name: "end"
    type: "string"
    default_value {
      s: "\n"
    }
  }
  is_stateful: true
}
