op {
  name: "RiscBinaryComparison"
  input_arg {
    name: "x"
    type_attr: "T"
  }
  input_arg {
    name: "y"
    type_attr: "T"
  }
  output_arg {
    name: "z"
    type: DT_BOOL
  }
  attr {
    name: "op_type"
    type: "string"
    allowed_values {
      list {
        s: "EQ"
        s: "NE"
        s: "GE"
        s: "GT"
        s: "LE"
        s: "LT"
      }
    }
  }
  attr {
    name: "T"
    type: "type"
    allowed_values {
      list {
        type: DT_BFLOAT16
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }
  }
}
