op {
  name: "RiscCondition"
  input_arg {
    name: "pred"
    type: DT_BOOL
  }
  input_arg {
    name: "input_true"
    type_attr: "SrcT"
  }
  input_arg {
    name: "input_false"
    type_attr: "SrcT"
  }
  output_arg {
    name: "output"
    type_attr: "DstT"
  }
  attr {
    name: "func_true"
    type: "func"
  }
  attr {
    name: "func_false"
    type: "func"
  }
  attr {
    name: "SrcT"
    type: "type"
    allowed_values {
      list {
        type: DT_BFLOAT16
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }
  }
  attr {
    name: "DstT"
    type: "type"
    allowed_values {
      list {
        type: DT_BFLOAT16
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }
  }
}
