op {
  name: "RngReadAndSkip"
  input_arg {
    name: "resource"
    type: DT_RESOURCE
  }
  input_arg {
    name: "alg"
    type: DT_INT32
  }
  input_arg {
    name: "delta"
    type: DT_UINT64
  }
  output_arg {
    name: "value"
    type: DT_INT64
  }
  is_stateful: true
}
