op 	 {
  name: "SparseMatrixZeros"
  input_arg {
    name: "dense_shape"
    type: DT_INT64
  }
  output_arg {
    name: "sparse_matrix"
    type: DT_VARIANT
  }
  attr {
    name: "type"
    type: "type"
    allowed_values {
      list {
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_COMPLEX64
        type: DT_COMPLEX128
      }
    }
  }
}
