op {
  name: "TensorListSetItem"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "index"
    type: DT_INT32
  }
  input_arg {
    name: "item"
    type_attr: "element_dtype"
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
}
op {
  name: "TensorListSetItem"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "index"
    type: DT_INT32
  }
  input_arg {
    name: "item"
    type_attr: "element_dtype"
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
    experimental_full_type {
      type_id: TFT_ARRAY
      args {
        type_id: TFT_VAR
        s: "element_dtype"
      }
    }
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
}
op {
  name: "TensorListSetItem"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "index"
    type: DT_INT32
  }
  input_arg {
    name: "item"
    type_attr: "element_dtype"
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
    experimental_full_type {
      type_id: TFT_ARRAY
      args {
        type_id: TFT_TENSOR
        args {
          type_id: TFT_VAR
          s: "element_dtype"
        }
      }
    }
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
}
op {
  name: "TensorListSetItem"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "index"
    type: DT_INT32
  }
  input_arg {
    name: "item"
    type_attr: "element_dtype"
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
    experimental_full_type {
      type_id: TFT_ARRAY
      args {
        type_id: TFT_TENSOR
        args {
          type_id: TFT_VAR
          s: "element_dtype"
        }
      }
    }
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
  attr {
    name: "resize_if_index_out_of_bounds"
    type: "bool"
    default_value {
      b: false
    }
  }
}
