op {
  name: "TensorListStack"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "element_shape"
    type: DT_INT32
  }
  output_arg {
    name: "tensor"
    type_attr: "element_dtype"
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
  attr {
    name: "num_elements"
    type: "int"
    default_value {
      i: -1
    }
  }
}
