op 	 {
  name: "TensorListElementShape"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  output_arg {
    name: "element_shape"
    type_attr: "shape_type"
  }
  attr {
    name: "shape_type"
    type: "type"
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
