op 	 {
  name: "TensorListSplit"
  input_arg {
    name: "tensor"
    type_attr: "element_dtype"
  }
  input_arg {
    name: "element_shape"
    type_attr: "shape_type"
  }
  input_arg {
    name: "lengths"
    type: DT_INT64
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
  attr {
    name: "shape_type"
    type: "type"
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
op {
  name: "TensorListSplit"
  input_arg {
    name: "tensor"
    type_attr: "element_dtype"
  }
  input_arg {
    name: "element_shape"
    type_attr: "shape_type"
  }
  input_arg {
    name: "lengths"
    type: DT_INT64
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
    experimental_full_type {
      type_id: TFT_ARRAY
      args {
        type_id: TFT_VAR
        s: "element_dtype"
      }
    }
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
  attr {
    name: "shape_type"
    type: "type"
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
op {
  name: "TensorListSplit"
  input_arg {
    name: "tensor"
    type_attr: "element_dtype"
  }
  input_arg {
    name: "element_shape"
    type_attr: "shape_type"
  }
  input_arg {
    name: "lengths"
    type: DT_INT64
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
    experimental_full_type {
      type_id: TFT_ARRAY
      args {
        type_id: TFT_TENSOR
        args {
          type_id: TFT_VAR
          s: "element_dtype"
        }
      }
    }
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
  attr {
    name: "shape_type"
    type: "type"
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
