op {
  name: "TensorMapErase"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "key"
    type_attr: "key_dtype"
  }
  output_arg {
    name: "output_handle"
    type: DT_VARIANT
  }
  attr {
    name: "key_dtype"
    type: "type"
  }
  attr {
    name: "value_dtype"
    type: "type"
  }
}
