op 	 {
  name: "TensorListConcatV2"
  input_arg {
    name: "input_handle"
    type: DT_VARIANT
  }
  input_arg {
    name: "element_shape"
    type_attr: "shape_type"
  }
  input_arg {
    name: "leading_dims"
    type: DT_INT64
  }
  output_arg {
    name: "tensor"
    type_attr: "element_dtype"
  }
  output_arg {
    name: "lengths"
    type: DT_INT64
  }
  attr {
    name: "element_dtype"
    type: "type"
  }
  attr {
    name: "shape_type"
    type: "type"
    allowed_values {
      list {
        type: DT_INT32
        type: DT_INT64
      }
    }
  }
}
