op {
  name: "TPUCompile"
  input_arg {
    name: "dynamic_shapes"
    type: DT_INT64
    number_attr: "NumDynamicShapes"
  }
  input_arg {
    name: "guaranteed_constants"
    type_list_attr: "Tguaranteed_constants"
  }
  output_arg {
    name: "compilation_status"
    type: DT_STRING
  }
  output_arg {
    name: "program"
    type: DT_STRING
    number_attr: "num_computations"
  }
  output_arg {
    name: "may_modify_variables"
    type: DT_BOOL
    number_attr: "num_computations"
  }
  attr {
    name: "num_computations"
    type: "int"
    has_minimum: true
  }
  attr {
    name: "function"
    type: "func"
  }
  attr {
    name: "metadata"
    type: "string"
  }
  attr {
    name: "NumDynamicShapes"
    type: "int"
    has_minimum: true
  }
  attr {
    name: "Tguaranteed_constants"
    type: "list(type)"
    has_minimum: true
  }
  is_stateful: true
}
