op {
  name: "TPUExecuteAndUpdateVariables"
  input_arg {
    name: "args"
    type_list_attr: "Targs"
  }
  input_arg {
    name: "key"
    type: DT_STRING
  }
  output_arg {
    name: "results"
    type_list_attr: "Tresults"
  }
  attr {
    name: "Targs"
    type: "list(type)"
    has_minimum: true
  }
  attr {
    name: "Tresults"
    type: "list(type)"
    has_minimum: true
  }
  attr {
    name: "device_var_reads_indices"
    type: "list(int)"
    has_minimum: true
  }
  attr {
    name: "device_var_updates_indices"
    type: "list(int)"
    has_minimum: true
  }
  is_stateful: true
}
