op 	 {
  name: "TPUExecute"
  input_arg {
    name: "args"
    type_list_attr: "Targs"
  }
  input_arg {
    name: "key"
    type: DT_STRING
  }
  output_arg {
    name: "results"
    type_list_attr: "Tresults"
  }
  attr {
    name: "Targs"
    type: "list(type)"
    has_minimum: true
  }
  attr {
    name: "Tresults"
    type: "list(type)"
    has_minimum: true
  }
  is_stateful: true
}
op {
  name: "TPUExecute"
  input_arg {
    name: "args"
    type_list_attr: "Targs"
  }
  input_arg {
    name: "key"
    type: DT_STRING
  }
  output_arg {
    name: "results"
    type_list_attr: "Tresults"
  }
  attr {
    name: "Targs"
    type: "list(type)"
    has_minimum: true
  }
  attr {
    name: "Tresults"
    type: "list(type)"
    has_minimum: true
  }
  is_stateful: true
  is_distributed_communication: true
}
