op 	 {
  name: "UnicodeTranscode"
  input_arg {
    name: "input"
    type: DT_STRING
  }
  output_arg {
    name: "output"
    type: DT_STRING
  }
  attr {
    name: "input_encoding"
    type: "string"
  }
  attr {
    name: "output_encoding"
    type: "string"
    allowed_values {
      list {
        s: "UTF-8"
        s: "UTF-16-BE"
        s: "UTF-32-BE"
      }
    }
  }
  attr {
    name: "errors"
    type: "string"
    default_value {
      s: "replace"
    }
    allowed_values {
      list {
        s: "strict"
        s: "replace"
        s: "ignore"
      }
    }
  }
  attr {
    name: "replacement_char"
    type: "int"
    default_value {
      i: 65533
    }
  }
  attr {
    name: "replace_control_characters"
    type: "bool"
    default_value {
      b: false
    }
  }
}
