op 	 {
  name: "UniformQuantizedConvolutionHybrid"
  input_arg {
    name: "lhs"
    type_attr: "Tlhs"
  }
  input_arg {
    name: "rhs"
    type_attr: "Trhs"
  }
  input_arg {
    name: "rhs_scales"
    type: DT_FLOAT
  }
  input_arg {
    name: "rhs_zero_points"
    type: DT_INT32
  }
  output_arg {
    name: "output"
    type_attr: "Tout"
  }
  attr {
    name: "Tlhs"
    type: "type"
    allowed_values {
      list {
        type: DT_FLOAT
      }
    }
  }
  attr {
    name: "Trhs"
    type: "type"
    allowed_values {
      list {
        type: DT_QINT8
      }
    }
  }
  attr {
    name: "Tout"
    type: "type"
    allowed_values {
      list {
        type: DT_FLOAT
      }
    }
  }
  attr {
    name: "window_strides"
    type: "list(int)"
    default_value {
      list {
      }
    }
  }
  attr {
    name: "padding"
    type: "string"
  }
  attr {
    name: "explicit_padding"
    type: "list(int)"
    default_value {
      list {
      }
    }
  }
  attr {
    name: "lhs_dilation"
    type: "list(int)"
    default_value {
      list {
      }
    }
  }
  attr {
    name: "rhs_dilation"
    type: "list(int)"
    default_value {
      list {
      }
    }
  }
  attr {
    name: "batch_group_count"
    type: "int"
    default_value {
      i: 1
    }
  }
  attr {
    name: "feature_group_count"
    type: "int"
    default_value {
      i: 1
    }
  }
  attr {
    name: "dimension_numbers"
    type: "string"
    default_value {
      s: ""
    }
  }
  attr {
    name: "rhs_quantization_axis"
    type: "int"
    default_value {
      i: -1
    }
  }
  attr {
    name: "rhs_quantization_min_val"
    type: "int"
  }
  attr {
    name: "rhs_quantization_max_val"
    type: "int"
  }
}
