op 	 {
  name: "WriteAudioSummary"
  input_arg {
    name: "writer"
    type: DT_RESOURCE
  }
  input_arg {
    name: "step"
    type: DT_INT64
  }
  input_arg {
    name: "tag"
    type: DT_STRING
  }
  input_arg {
    name: "tensor"
    type: DT_FLOAT
  }
  input_arg {
    name: "sample_rate"
    type: DT_FLOAT
  }
  attr {
    name: "max_outputs"
    type: "int"
    default_value {
      i: 3
    }
    has_minimum: true
    minimum: 1
  }
  is_stateful: true
}
