op {
  name: "XlaSendTPUEmbeddingGradientsV2"
  input_arg {
    name: "gradients"
    type: DT_FLOAT
    number_attr: "NumTables"
  }
  input_arg {
    name: "learning_rates"
    type: DT_FLOAT
    number_attr: "NumLearningRateTags"
  }
  input_arg {
    name: "deduplication_data"
    type: DT_VARIANT
  }
  attr {
    name: "NumTables"
    type: "int"
    has_minimum: true
    minimum: 1
  }
  attr {
    name: "NumLearningRateTags"
    type: "int"
    default_value {
      i: 0
    }
    has_minimum: true
  }
  attr {
    name: "config"
    type: "string"
  }
  attr {
    name: "embedding_partitions"
    type: "string"
  }
  attr {
    name: "hbm_buffers_config"
    type: "string"
  }
  attr {
    name: "tpu_topology"
    type: "string"
  }
  is_stateful: true
}
