op {
  name: "XlaSparseDenseMatmulCustomCombinerOnTcGradWithFtrlAndCsrInput"
  input_arg {
    name: "row_pointers"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_sample_ids"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_token_ids"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_pos_ids"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_gains"
    type: DT_FLOAT
  }
  input_arg {
    name: "weights"
    type: DT_FLOAT
  }
  input_arg {
    name: "preserved_valencies"
    type: DT_INT32
  }
  input_arg {
    name: "preserved_vectors"
    type: DT_FLOAT
  }
  input_arg {
    name: "preserved_weights"
    type: DT_FLOAT
  }
  input_arg {
    name: "activation_gradients"
    type: DT_FLOAT
  }
  input_arg {
    name: "learning_rate"
    type: DT_FLOAT
  }
  input_arg {
    name: "combiner_weights_learning_rate"
    type: DT_FLOAT
  }
  input_arg {
    name: "embedding_table"
    type: DT_FLOAT
  }
  input_arg {
    name: "accumulator"
    type: DT_FLOAT
  }
  input_arg {
    name: "linear"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_embedding_table"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_accumulator"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_linear"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_weights"
    type: DT_FLOAT
  }
  attr {
    name: "multiply_linear_by_learning_rate"
    type: "bool"
  }
  attr {
    name: "beta"
    type: "float"
  }
  attr {
    name: "learning_rate_power"
    type: "float"
  }
  attr {
    name: "l1_regularization_strength"
    type: "float"
  }
  attr {
    name: "l2_regularization_strength"
    type: "float"
  }
  attr {
    name: "clip_weight_min"
    type: "float"
    default_value {
      f: -inf
    }
  }
  attr {
    name: "clip_weight_max"
    type: "float"
    default_value {
      f: inf
    }
  }
  attr {
    name: "max_valency"
    type: "int"
    has_minimum: true
  }
  attr {
    name: "num_weights"
    type: "int"
    has_minimum: true
  }
  attr {
    name: "combiner_table_vjp_computation"
    type: "func"
  }
  attr {
    name: "combiner_weights_vjp_computation"
    type: "func"
  }
  attr {
    name: "table_name"
    type: "string"
  }
}
op {
  name: "XlaSparseDenseMatmulCustomCombinerOnTcGradWithFtrlAndCsrInput"
  input_arg {
    name: "row_pointers"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_sample_ids"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_token_ids"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_pos_ids"
    type: DT_INT32
  }
  input_arg {
    name: "sorted_gains"
    type: DT_FLOAT
  }
  input_arg {
    name: "weights"
    type: DT_FLOAT
  }
  input_arg {
    name: "preserved_valencies"
    type: DT_INT32
  }
  input_arg {
    name: "preserved_vectors"
    type: DT_FLOAT
  }
  input_arg {
    name: "preserved_weights"
    type: DT_FLOAT
  }
  input_arg {
    name: "activation_gradients"
    type: DT_FLOAT
  }
  input_arg {
    name: "learning_rate"
    type: DT_FLOAT
  }
  input_arg {
    name: "combiner_weights_learning_rate"
    type: DT_FLOAT
  }
  input_arg {
    name: "embedding_table"
    type: DT_FLOAT
  }
  input_arg {
    name: "accumulator"
    type: DT_FLOAT
  }
  input_arg {
    name: "linear"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_embedding_table"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_accumulator"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_linear"
    type: DT_FLOAT
  }
  output_arg {
    name: "updated_weights"
    type: DT_FLOAT
  }
  attr {
    name: "multiply_linear_by_learning_rate"
    type: "bool"
  }
  attr {
    name: "beta"
    type: "float"
  }
  attr {
    name: "learning_rate_power"
    type: "float"
  }
  attr {
    name: "l1_regularization_strength"
    type: "float"
  }
  attr {
    name: "l2_regularization_strength"
    type: "float"
  }
  attr {
    name: "clip_weight_min"
    type: "float"
    default_value {
      f: -inf
    }
  }
  attr {
    name: "clip_weight_max"
    type: "float"
    default_value {
      f: inf
    }
  }
  attr {
    name: "max_valency"
    type: "int"
    has_minimum: true
  }
  attr {
    name: "num_weights"
    type: "int"
    has_minimum: true
  }
  attr {
    name: "combiner_table_vjp_computation"
    type: "func"
  }
  attr {
    name: "combiner_weights_vjp_computation"
    type: "func"
  }
  attr {
    name: "table_name"
    type: "string"
  }
  attr {
    name: "num_sparsecores_per_device"
    type: "int"
    default_value {
      i: -1
    }
  }
}
