# TODO(suharshs): Write quantize_weights tests that use small exportable files.
# Then we can remove this file.
package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

load("//tensorflow/contrib/lite:build_def.bzl", "tflite_copts")
