# Description:
# PSNR test data packages.

load("//tensorflow:tensorflow.default.bzl", "filegroup")

package(
    # copybara:uncomment default_applicable_licenses = ["//tensorflow:license"],
    default_visibility = [
        "//tensorflow/core/lib/psnr:__pkg__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "psnr_testdata",
    srcs = [
        "cat_q20.jpg",
        "cat_q72.jpg",
        "cat_q95.jpg",
    ],
)
