# RUN: tfg-translate -graphdef-to-mlir %s | FileCheck %s

# Since there are no uses of the output for the Add node, it is imported without any output.
# CHECK:      tfg.graph
# CHECK-DAG: %Add, %{{.*}} = Add(%Placeholder, %Placeholder_0) name("Add") {T = i32} : (tensor<*xi32>, tensor<*xi32>) -> (tensor<*xi32>)
# CHECK-DAG: %Placeholder, %{{.*}} = Placeholder name("input0") {dtype = i32, shape = #tf_type.shape<*>} : () -> (tensor<*xi32>)
# CHECK-DAG: %Placeholder_0, %{{.*}} = Placeholder name("input1") {dtype = i32, shape = #tf_type.shape<*>} : () -> (tensor<*xi32>)

node {
  name: "Add"
  op: "Add"
  input: "input0"
  input: "input1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "input0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "input1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
}
