package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "rpc",
    srcs = [
        "__init__.py",
    ],
    deps = ["//tensorflow/contrib/rpc/python/ops:rpc_op_py"],
)
