// Code generated by protoc-gen-go.
// source: tensorflow/core/framework/log_memory.proto
// DO NOT EDIT!

package tensorflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MemoryLogStep struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// Handle describing the feeds and fetches of the step.
	Handle string `protobuf:"bytes,2,opt,name=handle" json:"handle,omitempty"`
}

func (m *MemoryLogStep) Reset()                    { *m = MemoryLogStep{} }
func (m *MemoryLogStep) String() string            { return proto.CompactTextString(m) }
func (*MemoryLogStep) ProtoMessage()               {}
func (*MemoryLogStep) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type MemoryLogTensorAllocation struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// Name of the kernel making the allocation as set in GraphDef,
	// e.g., "affine2/weights/Assign".
	KernelName string `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName" json:"kernel_name,omitempty"`
	// Allocated tensor details.
	Tensor *TensorDescription `protobuf:"bytes,3,opt,name=tensor" json:"tensor,omitempty"`
}

func (m *MemoryLogTensorAllocation) Reset()                    { *m = MemoryLogTensorAllocation{} }
func (m *MemoryLogTensorAllocation) String() string            { return proto.CompactTextString(m) }
func (*MemoryLogTensorAllocation) ProtoMessage()               {}
func (*MemoryLogTensorAllocation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *MemoryLogTensorAllocation) GetTensor() *TensorDescription {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type MemoryLogTensorDeallocation struct {
	// Id of the tensor buffer being deallocated, used to match to a
	// corresponding allocation.
	AllocationId int64 `protobuf:"varint,1,opt,name=allocation_id,json=allocationId" json:"allocation_id,omitempty"`
	// Name of the allocator used.
	AllocatorName string `protobuf:"bytes,2,opt,name=allocator_name,json=allocatorName" json:"allocator_name,omitempty"`
}

func (m *MemoryLogTensorDeallocation) Reset()                    { *m = MemoryLogTensorDeallocation{} }
func (m *MemoryLogTensorDeallocation) String() string            { return proto.CompactTextString(m) }
func (*MemoryLogTensorDeallocation) ProtoMessage()               {}
func (*MemoryLogTensorDeallocation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

type MemoryLogTensorOutput struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// Name of the kernel producing an output as set in GraphDef, e.g.,
	// "affine2/weights/Assign".
	KernelName string `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName" json:"kernel_name,omitempty"`
	// Index of the output being set.
	Index int32 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	// Output tensor details.
	Tensor *TensorDescription `protobuf:"bytes,4,opt,name=tensor" json:"tensor,omitempty"`
}

func (m *MemoryLogTensorOutput) Reset()                    { *m = MemoryLogTensorOutput{} }
func (m *MemoryLogTensorOutput) String() string            { return proto.CompactTextString(m) }
func (*MemoryLogTensorOutput) ProtoMessage()               {}
func (*MemoryLogTensorOutput) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *MemoryLogTensorOutput) GetTensor() *TensorDescription {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type MemoryLogRawAllocation struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// Name of the operation making the allocation.
	Operation string `protobuf:"bytes,2,opt,name=operation" json:"operation,omitempty"`
	// Number of bytes in the allocation.
	NumBytes int64 `protobuf:"varint,3,opt,name=num_bytes,json=numBytes" json:"num_bytes,omitempty"`
	// Address of the allocation.
	Ptr uint64 `protobuf:"varint,4,opt,name=ptr" json:"ptr,omitempty"`
	// Id of the tensor buffer being allocated, used to match to a
	// corresponding deallocation.
	AllocationId int64 `protobuf:"varint,5,opt,name=allocation_id,json=allocationId" json:"allocation_id,omitempty"`
	// Name of the allocator used.
	AllocatorName string `protobuf:"bytes,6,opt,name=allocator_name,json=allocatorName" json:"allocator_name,omitempty"`
}

func (m *MemoryLogRawAllocation) Reset()                    { *m = MemoryLogRawAllocation{} }
func (m *MemoryLogRawAllocation) String() string            { return proto.CompactTextString(m) }
func (*MemoryLogRawAllocation) ProtoMessage()               {}
func (*MemoryLogRawAllocation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

type MemoryLogRawDeallocation struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// Name of the operation making the deallocation.
	Operation string `protobuf:"bytes,2,opt,name=operation" json:"operation,omitempty"`
	// Id of the tensor buffer being deallocated, used to match to a
	// corresponding allocation.
	AllocationId int64 `protobuf:"varint,3,opt,name=allocation_id,json=allocationId" json:"allocation_id,omitempty"`
	// Name of the allocator used.
	AllocatorName string `protobuf:"bytes,4,opt,name=allocator_name,json=allocatorName" json:"allocator_name,omitempty"`
	// True if the deallocation is queued and will be performed later,
	// e.g. for GPU lazy freeing of buffers.
	Deferred bool `protobuf:"varint,5,opt,name=deferred" json:"deferred,omitempty"`
}

func (m *MemoryLogRawDeallocation) Reset()                    { *m = MemoryLogRawDeallocation{} }
func (m *MemoryLogRawDeallocation) String() string            { return proto.CompactTextString(m) }
func (*MemoryLogRawDeallocation) ProtoMessage()               {}
func (*MemoryLogRawDeallocation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func init() {
	proto.RegisterType((*MemoryLogStep)(nil), "tensorflow.MemoryLogStep")
	proto.RegisterType((*MemoryLogTensorAllocation)(nil), "tensorflow.MemoryLogTensorAllocation")
	proto.RegisterType((*MemoryLogTensorDeallocation)(nil), "tensorflow.MemoryLogTensorDeallocation")
	proto.RegisterType((*MemoryLogTensorOutput)(nil), "tensorflow.MemoryLogTensorOutput")
	proto.RegisterType((*MemoryLogRawAllocation)(nil), "tensorflow.MemoryLogRawAllocation")
	proto.RegisterType((*MemoryLogRawDeallocation)(nil), "tensorflow.MemoryLogRawDeallocation")
}

var fileDescriptor6 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xf1, 0x9c, 0x78, 0xc9, 0xc9, 0xb2, 0x0d, 0xb3, 0x65, 0x5e, 0xb2, 0xb1, 0xe1, 0x31,
	0x18, 0x83, 0x26, 0x90, 0xd2, 0xfb, 0x36, 0xe4, 0xa6, 0xd0, 0x3f, 0x41, 0xed, 0xbd, 0x71, 0xe2,
	0x93, 0xd4, 0xc4, 0xb6, 0x8c, 0xac, 0x90, 0xe6, 0x1d, 0xfa, 0x0c, 0x7d, 0x8f, 0xbe, 0x42, 0x9f,
	0xaa, 0xb2, 0x65, 0x2c, 0x37, 0x7f, 0x20, 0x6d, 0xaf, 0xec, 0xef, 0x93, 0x74, 0xce, 0xef, 0x3b,
	0x42, 0xf0, 0x9f, 0x63, 0x94, 0x50, 0x36, 0x0d, 0xe8, 0xb2, 0x37, 0xa1, 0x0c, 0x7b, 0x53, 0xe6,
	0x86, 0xb8, 0xa4, 0x6c, 0xde, 0x0b, 0xe8, 0xcc, 0x09, 0x31, 0xa4, 0x6c, 0xd5, 0x8d, 0x19, 0xe5,
	0xd4, 0x04, 0xb5, 0xb7, 0xdd, 0xdf, 0x7d, 0x4e, 0xae, 0x38, 0x1e, 0x26, 0x13, 0xe6, 0xc7, 0xdc,
	0xa7, 0x91, 0x3c, 0x6f, 0x1f, 0x43, 0xf3, 0x3c, 0xab, 0x77, 0x46, 0x67, 0x57, 0x1c, 0x63, 0xf3,
	0x1b, 0xbc, 0x4f, 0xc4, 0xd7, 0xf1, 0x3d, 0x4b, 0xfb, 0xad, 0xfd, 0xd3, 0x89, 0x91, 0xca, 0x53,
	0xcf, 0x6c, 0x81, 0x71, 0xe3, 0x46, 0x5e, 0x80, 0xd6, 0x3b, 0xe1, 0xd7, 0x49, 0xae, 0xec, 0x3b,
	0x0d, 0xbe, 0x17, 0x25, 0xae, 0xb3, 0x3e, 0x27, 0x41, 0x40, 0x27, 0x6e, 0xda, 0x65, 0x77, 0xb9,
	0x5f, 0xd0, 0x98, 0x23, 0x8b, 0x30, 0x70, 0x22, 0x01, 0x99, 0xd7, 0x04, 0x69, 0x5d, 0x08, 0xc7,
	0x3c, 0x02, 0x43, 0x52, 0x5b, 0xba, 0x58, 0x6b, 0xf4, 0x7f, 0x76, 0x55, 0xbc, 0xae, 0xec, 0x33,
	0x54, 0x71, 0x48, 0xbe, 0xd9, 0xf6, 0xa1, 0xb3, 0x46, 0x33, 0x44, 0x57, 0xf1, 0xfc, 0x81, 0xa6,
	0x52, 0x8a, 0xea, 0x83, 0x32, 0x05, 0xdb, 0x5f, 0xf8, 0x98, 0x6b, 0x31, 0xb3, 0x12, 0x5e, 0xb3,
	0x70, 0x53, 0x42, 0xfb, 0x5e, 0x83, 0xaf, 0x6b, 0xbd, 0x2e, 0x17, 0x3c, 0x5e, 0xf0, 0x37, 0xa4,
	0xfe, 0x02, 0x55, 0x3f, 0xf2, 0xf0, 0x36, 0x0b, 0x5d, 0x25, 0x52, 0x94, 0x66, 0x51, 0x79, 0xc9,
	0x2c, 0x1e, 0x35, 0x68, 0x15, 0x80, 0xc4, 0x5d, 0xee, 0x73, 0x2f, 0x3f, 0xa0, 0x4e, 0x63, 0x64,
	0xd9, 0xae, 0x9c, 0x4f, 0x19, 0x66, 0x07, 0xea, 0xd1, 0x22, 0x74, 0xc6, 0x2b, 0x8e, 0x49, 0x86,
	0xa8, 0x93, 0x9a, 0x30, 0x06, 0xa9, 0x36, 0x3f, 0x83, 0x1e, 0x73, 0x89, 0x58, 0x21, 0xe9, 0xef,
	0xe6, 0xb4, 0xab, 0x7b, 0x4d, 0xdb, 0xd8, 0x36, 0xed, 0x07, 0x0d, 0xac, 0x72, 0x98, 0x67, 0xd7,
	0xfa, 0xca, 0x38, 0x1b, 0x7c, 0xfa, 0x5e, 0x7c, 0x95, 0x2d, 0x7c, 0x66, 0x1b, 0x6a, 0x1e, 0x4e,
	0x91, 0x31, 0x94, 0x31, 0x6b, 0xa4, 0xd0, 0x83, 0x03, 0xb0, 0x28, 0x9b, 0x95, 0x2f, 0xad, 0x78,
	0x9a, 0x83, 0x4f, 0x22, 0x8e, 0xcc, 0x35, 0x4a, 0x5f, 0x64, 0x32, 0xd2, 0xc6, 0x46, 0xf6, 0x36,
	0x0f, 0x9f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0xbc, 0x78, 0x92, 0x09, 0x04, 0x00, 0x00,
}
