# Tensorflow default + linux implementations of tensorflow/core/profiler libraries.

package(
    default_visibility = [
        "//tensorflow/core/profiler:internal",
    ],
    licenses = ["notice"],
)
