# Copyright 2023 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

def AddByteSplit(arg0: int) -> None: ...
def AddByteSplitByOffsets(arg0: int) -> None: ...
def AddFastBertNormalize(arg0: int) -> None: ...
def AddFastSentencepieceDetokenize(arg0: int) -> None: ...
def AddFastSentencepieceTokenize(arg0: int) -> None: ...
def AddFastWordpieceDetokenize(arg0: int) -> None: ...
def AddFastWordpieceTokenize(arg0: int) -> None: ...
def AddNgramsStringJoin(arg0: int) -> None: ...
def AddRaggedTensorToTensor(arg0: int) -> None: ...
def AddRoundRobinGenerateMasks(arg0: int) -> None: ...
def AddRoundRobinTrim(arg0: int) -> None: ...
def AddSentenceFragmenterV2(arg0: int) -> None: ...
def AddUtf8Binarize(arg0: int) -> None: ...
def AddWhitespaceTokenize(arg0: int) -> None: ...
