package(default_visibility = ["//visibility:public"])

py_library(
    # the name attribute was set to "py_utils" which is incorrect. 
    # It is always a good practice to keep the "target" same as the 
    # file name to avoid confusion and run-time issues.
    name = "utils",
    srcs = [
        "utils.py",
    ],
)
