// Code generated by protoc-gen-go.
// source: tensorflow/core/framework/allocation_description.proto
// DO NOT EDIT!

/*
Package tensorflow is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/framework/allocation_description.proto
	tensorflow/core/framework/attr_value.proto
	tensorflow/core/framework/config.proto
	tensorflow/core/framework/device_attributes.proto
	tensorflow/core/framework/function.proto
	tensorflow/core/framework/graph.proto
	tensorflow/core/framework/kernel_def.proto
	tensorflow/core/framework/op_def.proto
	tensorflow/core/framework/step_stats.proto
	tensorflow/core/framework/summary.proto
	tensorflow/core/framework/tensor.proto
	tensorflow/core/framework/tensor_description.proto
	tensorflow/core/framework/tensor_shape.proto
	tensorflow/core/framework/tensor_slice.proto
	tensorflow/core/framework/types.proto

It has these top-level messages:
	AllocationDescription
	AttrValue
	NameAttrList
	GPUOptions
	GraphOptions
	ConfigProto
	DeviceAttributes
	FunctionDefLibrary
	FunctionDef
	GraphDef
	NodeDef
	KernelDef
	OpDef
	OpList
	AllocatorMemoryUsed
	NodeOutput
	NodeExecStats
	DeviceStepStats
	StepStats
	HistogramProto
	Summary
	TensorProto
	TensorDescription
	TensorShapeProto
	TensorSliceProto
*/
package tensorflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type AllocationDescription struct {
	// Total number of bytes requested
	RequestedBytes int64 `protobuf:"varint,1,opt,name=requested_bytes" json:"requested_bytes,omitempty"`
	// Total number of bytes allocated if known
	AllocatedBytes int64 `protobuf:"varint,2,opt,name=allocated_bytes" json:"allocated_bytes,omitempty"`
	// Name of the allocator used
	AllocatorName string `protobuf:"bytes,3,opt,name=allocator_name" json:"allocator_name,omitempty"`
}

func (m *AllocationDescription) Reset()                    { *m = AllocationDescription{} }
func (m *AllocationDescription) String() string            { return proto.CompactTextString(m) }
func (*AllocationDescription) ProtoMessage()               {}
func (*AllocationDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*AllocationDescription)(nil), "tensorflow.AllocationDescription")
}

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x2b, 0x49, 0xcd, 0x2b,
	0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x4f, 0x2b, 0x4a, 0xcc,
	0x4d, 0x2d, 0xcf, 0x2f, 0xca, 0xd6, 0x4f, 0xcc, 0xc9, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf,
	0x8b, 0x4f, 0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x2c, 0x00, 0xb1, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0xb8, 0x10, 0xfa, 0x94, 0x12, 0xb9, 0x44, 0x1d, 0xe1, 0x6a, 0x5d, 0x10, 0x4a, 0x85, 0xc4,
	0xb9, 0xf8, 0x8b, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x52, 0x53, 0xe2, 0x93, 0x2a, 0x4b, 0x52,
	0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x41, 0x12, 0x50, 0xd3, 0xe1, 0x12, 0x4c, 0x60, 0x09,
	0x31, 0x2e, 0x3e, 0xa8, 0x44, 0x7e, 0x51, 0x7c, 0x1e, 0xd0, 0x25, 0x12, 0xcc, 0x40, 0x71, 0xce,
	0x24, 0x36, 0xb0, 0xad, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x0d, 0xe9, 0xab, 0xaf,
	0x00, 0x00, 0x00,
}
