# The ssim testdata package.
load("//tensorflow:tensorflow.default.bzl", "filegroup")

package(
    # copybara:uncomment default_applicable_licenses = ["//tensorflow:license"],
    default_visibility = [
        "//tensorflow/core/lib/ssim:__pkg__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "testdata",
    srcs = [
        "checkerboard1.png",
        "checkerboard2.png",
        "checkerboard3.png",
    ],
)
