package(
    # copybara:uncomment default_applicable_licenses = ["//tensorflow:license"],
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

py_binary(
    name = "stack_trace_example",
    srcs = ["stack_trace_example.py"],
    python_version = "PY3",
    deps = ["//tensorflow:tensorflow_py"],
)
