# RUN: tf_tfjs_translate %s -tf-input-arrays=input0 -tf-input-data-types=DT_FLOAT -tf-input-shapes=10 -tf-output-arrays=Add -tf-custom-opdefs="name: 'Prelu' input_arg: { name: 'x' type: DT_FLOAT } input_arg: { name: 'alpha' type: DT_FLOAT } output_arg: { name: 'c' type: DT_FLOAT }" -o - | FileCheck %s --dump-input-on-failure
# Add two tensor<4xi32> inputs and return the result

node {
  name: "input0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "alpha"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.5
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "Relu"
  op: "Relu"
  input: "input0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "Neg"
  op: "Neg"
  input: "input0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "Relu1"
  op: "Relu"
  input: "Neg"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "Mul"
  op: "Mul"
  input: "alpha"
  input: "Relu1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Relu"
  input: "Mul"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "main"
  op: "_Retval"
  input: "Add"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index"
    value {
      i: 0
    }
  }
}
library {
}
versions {
  producer: 344
}

# CHECK: "node":
# CHECK: "name": "input0",
# CHECK-NEXT: "op": "Placeholder",
# CHECK-NEXT: "attr":
# CHECK: "type": "DT_FLOAT"
# CHECK: "name": "Add.Relu.Neg.Relu1.Mul",
# CHECK-NEXT: "op": "Const",
# CHECK-NEXT: "attr":
# CHECK: "value":
# CHECK: "tensor":
# CHECK: "dtype": "DT_FLOAT",
# CHECK: "tensorShape": {},
# CHECK: "floatVal":
# CHECK: -0.5
# CHECK: "name": "Add.Relu.Neg.Relu1.Mul1",
# CHECK-NEXT: "op": "Prelu",
# CHECK-NEXT: "input":
# CHECK: "input0",
# CHECK: "Add.Relu.Neg.Relu1.Mul"
# CHECK: "attr":
# CHECK: "_output_shapes":
# CHECK: "list":
# CHECK: "shape":
# CHECK: "dim":
# CHECK: "size": "10"
# CHECK: "experimentalDebugInfo": {}
# CHECK: "name": "Add",
# CHECK-NEXT: "op": "_Retval",
# CHECK-NEXT: "input":
# CHECK: "Add.Relu.Neg.Relu1.Mul1"
# CHECK: "attr":
# CHECK: "T":
# CHECK: "type": "DT_FLOAT"
# CHECK: "library": {},
# CHECK: "versions":
# CHECK: "producer": 344

