# Description:
#   Ops that process audio and/or video files using FFmpeg.
#   (https://www.ffmpeg.org/)

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

package(default_visibility = ["//tensorflow:__subpackages__"])
