path: "tensorflow.lookup.experimental.MutableHashTable"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.lookup_ops.MutableHashTable\'>"
  is_instance: "<class \'tensorflow.python.ops.lookup_ops.LookupInterface\'>"
  is_instance: "<class \'tensorflow.python.training.tracking.resource.TrackableResource\'>"
  is_instance: "<class \'tensorflow.python.training.tracking.resource.CapturableResource\'>"
  is_instance: "<class \'tensorflow.python.training.tracking.base.Trackable\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "key_dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "resource_handle"
    mtype: "<type \'property\'>"
  }
  member {
    name: "value_dtype"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'key_dtype\', \'value_dtype\', \'default_value\', \'name\', \'checkpoint\', \'experimental_is_anonymous\'], varargs=None, keywords=None, defaults=[\'MutableHashTable\', \'True\', \'False\'], "
  }
  member_method {
    name: "export"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "insert"
    argspec: "args=[\'self\', \'keys\', \'values\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "lookup"
    argspec: "args=[\'self\', \'keys\', \'dynamic_default_values\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "remove"
    argspec: "args=[\'self\', \'keys\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "size"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
