path: "tensorflow.data.experimental.service.WorkerConfig"
tf_class {
  is_instance: "<class \'tensorflow.python.data.experimental.service.server_lib.WorkerConfig\'>"
  is_instance: "<class \'tensorflow.python.data.experimental.service.server_lib.WorkerConfig\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "data_transfer_address"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "data_transfer_protocol"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "dispatcher_address"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "dispatcher_timeout_ms"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "heartbeat_interval_ms"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "port"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "protocol"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member {
    name: "worker_address"
    mtype: "<class \'collections._tuplegetter\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
