path: "tensorflow.data"
tf_module {
  member {
    name: "AUTOTUNE"
    mtype: "<class \'int\'>"
  }
  member {
    name: "Dataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "DatasetSpec"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "FixedLengthRecordDataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "INFINITE_CARDINALITY"
    mtype: "<class \'int\'>"
  }
  member {
    name: "Iterator"
    mtype: "<class \'type\'>"
  }
  member {
    name: "NumpyIterator"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Options"
    mtype: "<class \'type\'>"
  }
  member {
    name: "TFRecordDataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "TextLineDataset"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "ThreadingOptions"
    mtype: "<class \'type\'>"
  }
  member {
    name: "UNKNOWN_CARDINALITY"
    mtype: "<class \'int\'>"
  }
  member {
    name: "experimental"
    mtype: "<class \'module\'>"
  }
  member_method {
    name: "get_output_classes"
    argspec: "args=[\'dataset_or_iterator\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_shapes"
    argspec: "args=[\'dataset_or_iterator\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_output_types"
    argspec: "args=[\'dataset_or_iterator\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "make_initializable_iterator"
    argspec: "args=[\'dataset\', \'shared_name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "make_one_shot_iterator"
    argspec: "args=[\'dataset\'], varargs=None, keywords=None, defaults=None"
  }
}
