path: "tensorflow.estimator.export.ServingInputReceiver"
tf_class {
  is_instance: "<class \'tensorflow_estimator.python.estimator.export.export.ServingInputReceiver\'>"
  is_instance: "<class \'tensorflow_estimator.python.estimator.export.export.ServingInputReceiver\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "features"
    mtype: "<type \'property\'>"
  }
  member {
    name: "receiver_tensors"
    mtype: "<type \'property\'>"
  }
  member {
    name: "receiver_tensors_alternatives"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
