path: "tensorflow.keras.callbacks.EarlyStopping"
tf_class {
  is_instance: "<class \'tensorflow.python.keras.callbacks.EarlyStopping\'>"
  is_instance: "<class \'tensorflow.python.keras.callbacks.Callback\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'monitor\', \'min_delta\', \'patience\', \'verbose\', \'mode\', \'baseline\', \'restore_best_weights\'], varargs=None, keywords=None, defaults=[\'val_loss\', \'0\', \'0\', \'0\', \'auto\', \'None\', \'False\'], "
  }
  member_method {
    name: "get_monitor_value"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "on_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_begin"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_end"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "set_model"
    argspec: "args=[\'self\', \'model\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_params"
    argspec: "args=[\'self\', \'params\'], varargs=None, keywords=None, defaults=None"
  }
}
