path: "tensorflow.summary.FileWriterCache"
tf_class {
  is_instance: "<class \'tensorflow.python.summary.writer.writer_cache.FileWriterCache\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
  }
  member_method {
    name: "clear"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get"
    argspec: "args=[\'logdir\'], varargs=None, keywords=None, defaults=None"
  }
}
