path: "tensorflow.IndexedSlices"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.indexed_slices.IndexedSlices\'>"
  is_instance: "<class \'tensorflow.python.types.internal.IndexedSlices\'>"
  is_instance: "<class \'tensorflow.python.types.internal.NativeObject\'>"
  is_instance: "<class \'tensorflow.python.framework.composite_tensor.CompositeTensor\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "dense_shape"
    mtype: "<type \'property\'>"
  }
  member {
    name: "device"
    mtype: "<type \'property\'>"
  }
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "graph"
    mtype: "<type \'property\'>"
  }
  member {
    name: "indices"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member {
    name: "op"
    mtype: "<type \'property\'>"
  }
  member {
    name: "shape"
    mtype: "<type \'property\'>"
  }
  member {
    name: "values"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'values\', \'indices\', \'dense_shape\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "consumers"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
