path: "tensorflow.train.LooperThread"
tf_class {
  is_instance: "<class \'tensorflow.python.training.coordinator.LooperThread\'>"
  is_instance: "<class \'threading.Thread\'>"
  member {
    name: "daemon"
    mtype: "<type \'property\'>"
  }
  member {
    name: "ident"
    mtype: "<type \'property\'>"
  }
  member {
    name: "name"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'coord\', \'timer_interval_secs\', \'target\', \'args\', \'kwargs\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "getName"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "isDaemon"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_alive"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "loop"
    argspec: "args=[\'coord\', \'timer_interval_secs\', \'target\', \'args\', \'kwargs\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "run"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "run_loop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "setDaemon"
    argspec: "args=[\'self\', \'daemonic\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "setName"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "start"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "start_loop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "stop_loop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
