path: "tensorflow.keras.constraints.MinMaxNorm"
tf_class {
  is_instance: "<class \'tensorflow.python.keras.constraints.MinMaxNorm\'>"
  is_instance: "<class \'tensorflow.python.keras.constraints.Constraint\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'min_value\', \'max_value\', \'rate\', \'axis\'], varargs=None, keywords=None, defaults=[\'0.0\', \'1.0\', \'1.0\', \'0\'], "
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
