path: "tensorflow.SummaryMetadata"
tf_proto {
  descriptor {
    name: "SummaryMetadata"
    field {
      name: "plugin_data"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_MESSAGE
      type_name: ".tensorflow.SummaryMetadata.PluginData"
    }
    field {
      name: "display_name"
      number: 2
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    field {
      name: "summary_description"
      number: 3
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    field {
      name: "data_class"
      number: 4
      label: LABEL_OPTIONAL
      type: TYPE_ENUM
      type_name: ".tensorflow.DataClass"
    }
    nested_type {
      name: "PluginData"
      field {
        name: "plugin_name"
        number: 1
        label: LABEL_OPTIONAL
        type: TYPE_STRING
      }
      field {
        name: "content"
        number: 2
        label: LABEL_OPTIONAL
        type: TYPE_BYTES
      }
    }
  }
}
