path: "tensorflow.saved_model.builder.SavedModelBuilder"
tf_class {
  is_instance: "<class \'tensorflow.python.saved_model.builder_impl.SavedModelBuilder\'>"
  is_instance: "<class \'tensorflow.python.saved_model.builder_impl._SavedModelBuilder\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'export_dir\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "add_meta_graph"
    argspec: "args=[\'self\', \'tags\', \'signature_def_map\', \'assets_collection\', \'legacy_init_op\', \'clear_devices\', \'main_op\', \'strip_default_attrs\', \'saver\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'False\', \'None\', \'False\', \'None\'], "
  }
  member_method {
    name: "add_meta_graph_and_variables"
    argspec: "args=[\'self\', \'sess\', \'tags\', \'signature_def_map\', \'assets_collection\', \'legacy_init_op\', \'clear_devices\', \'main_op\', \'strip_default_attrs\', \'saver\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\', \'False\', \'None\', \'False\', \'None\'], "
  }
  member_method {
    name: "save"
    argspec: "args=[\'self\', \'as_text\', \'experimental_image_format\'], varargs=None, keywords=None, defaults=[\'False\', \'False\'], "
  }
}
