path: "tensorflow.keras.utils.custom_object_scope"
tf_class {
  is_instance: "<class \'tensorflow.python.keras.utils.generic_utils.CustomObjectScope\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\'], varargs=args, keywords=None, defaults=None"
  }
}
