path: "tensorflow.train.MonitoredSession.StepContext"
tf_class {
  is_instance: "<class \'tensorflow.python.training.monitored_session.StepContext\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "session"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'session\', \'run_with_hooks_fn\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "request_stop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "run_with_hooks"
    argspec: "args=[\'self\'], varargs=args, keywords=kwargs, defaults=None"
  }
}
