path: "tensorflow.distribute.experimental.CollectiveCommunication"
tf_class {
  is_instance: "<enum \'CommunicationImplemenation\'>"
  member {
    name: "AUTO"
    mtype: "<enum \'CommunicationImplemenation\'>"
  }
  member {
    name: "NCCL"
    mtype: "<enum \'CommunicationImplemenation\'>"
  }
  member {
    name: "RING"
    mtype: "<enum \'CommunicationImplemenation\'>"
  }
}
