path: "tensorflow.data.experimental.AutotuneOptions"
tf_class {
  is_instance: "<class \'tensorflow.python.data.ops.options.AutotuneOptions\'>"
  is_instance: "<class \'tensorflow.python.data.util.options.OptionsBase\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "autotune_algorithm"
    mtype: "<type \'property\'>"
  }
  member {
    name: "cpu_budget"
    mtype: "<type \'property\'>"
  }
  member {
    name: "enabled"
    mtype: "<type \'property\'>"
  }
  member {
    name: "initial_parallelism"
    mtype: "<type \'property\'>"
  }
  member {
    name: "ram_budget"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
