path: "tensorflow.FixedLenSequenceFeature"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.parsing_config.FixedLenSequenceFeature\'>"
  is_instance: "<class \'tensorflow.python.ops.parsing_config.FixedLenSequenceFeature\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "allow_missing"
    mtype: "<type \'property\'>"
  }
  member {
    name: "default_value"
    mtype: "<type \'property\'>"
  }
  member {
    name: "dtype"
    mtype: "<type \'property\'>"
  }
  member {
    name: "shape"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
