path: "tensorflow.keras.callbacks.TensorBoard"
tf_class {
  is_instance: "<class \'tensorflow.python.keras.callbacks_v1.TensorBoard\'>"
  is_instance: "<class \'tensorflow.python.keras.callbacks.TensorBoard\'>"
  is_instance: "<class \'tensorflow.python.keras.callbacks.Callback\'>"
  is_instance: "<class \'tensorflow.python.keras.utils.version_utils.TensorBoardVersionSelector\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'log_dir\', \'histogram_freq\', \'batch_size\', \'write_graph\', \'write_grads\', \'write_images\', \'embeddings_freq\', \'embeddings_layer_names\', \'embeddings_metadata\', \'embeddings_data\', \'update_freq\', \'profile_batch\'], varargs=None, keywords=None, defaults=[\'./logs\', \'0\', \'32\', \'True\', \'False\', \'False\', \'0\', \'None\', \'None\', \'None\', \'epoch\', \'2\'], "
  }
  member_method {
    name: "on_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_begin"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_end"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "set_model"
    argspec: "args=[\'self\', \'model\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_params"
    argspec: "args=[\'self\', \'params\'], varargs=None, keywords=None, defaults=None"
  }
}
