path: "tensorflow.estimator.export"
tf_module {
  member {
    name: "ClassificationOutput"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ExportOutput"
    mtype: "<type \'type\'>"
  }
  member {
    name: "PredictOutput"
    mtype: "<type \'type\'>"
  }
  member {
    name: "RegressionOutput"
    mtype: "<type \'type\'>"
  }
  member {
    name: "ServingInputReceiver"
    mtype: "<type \'type\'>"
  }
  member {
    name: "TensorServingInputReceiver"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "build_parsing_serving_input_receiver_fn"
    argspec: "args=[\'feature_spec\', \'default_batch_size\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "build_raw_serving_input_receiver_fn"
    argspec: "args=[\'features\', \'default_batch_size\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
