path: "tensorflow.saved_model.experimental"
tf_module {
  member_method {
    name: "save"
    argspec: "args=[\'obj\', \'export_dir\', \'signatures\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
