path: "tensorflow.saved_model.signature_def_utils.MethodNameUpdater"
tf_class {
  is_instance: "<class \'tensorflow.python.saved_model.method_name_updater.MethodNameUpdater\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'export_dir\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "replace_method_name"
    argspec: "args=[\'self\', \'signature_key\', \'method_name\', \'tags\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "save"
    argspec: "args=[\'self\', \'new_export_dir\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
