path: "tensorflow.estimator.SecondOrStepTimer"
tf_class {
  is_instance: "<class \'tensorflow.python.training.basic_session_run_hooks.SecondOrStepTimer\'>"
  is_instance: "<class \'tensorflow.python.training.basic_session_run_hooks._HookTimer\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'every_secs\', \'every_steps\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "last_triggered_step"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "reset"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "should_trigger_for_step"
    argspec: "args=[\'self\', \'step\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "update_last_triggered_step"
    argspec: "args=[\'self\', \'step\'], varargs=None, keywords=None, defaults=None"
  }
}
