path: "tensorflow.train.CheckpointOptions"
tf_class {
  is_instance: "<class \'tensorflow.python.checkpoint.checkpoint_options.CheckpointOptions\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "enable_async"
    mtype: "<class \'member_descriptor\'>"
  }
  member {
    name: "experimental_enable_async_checkpoint"
    mtype: "<class \'member_descriptor\'>"
  }
  member {
    name: "experimental_io_device"
    mtype: "<class \'member_descriptor\'>"
  }
  member {
    name: "experimental_sharding_callback"
    mtype: "<class \'member_descriptor\'>"
  }
  member {
    name: "experimental_skip_slot_variables"
    mtype: "<class \'member_descriptor\'>"
  }
  member {
    name: "experimental_write_callbacks"
    mtype: "<class \'member_descriptor\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'experimental_io_device\', \'experimental_enable_async_checkpoint\', \'experimental_write_callbacks\', \'enable_async\', \'experimental_skip_slot_variables\', \'experimental_sharding_callback\'], varargs=None, keywords=None, defaults=[\'None\', \'False\', \'None\', \'False\', \'False\', \'None\'], "
  }
}
