path: "tensorflow.estimator.tpu.TPUEstimatorSpec"
tf_class {
  is_instance: "<class \'tensorflow_estimator.python.estimator.tpu.tpu_estimator.TPUEstimatorSpec\'>"
  is_instance: "<class \'tensorflow_estimator.python.estimator.model_fn._TPUEstimatorSpec\'>"
  is_instance: "<class \'tensorflow_estimator.python.estimator.model_fn.TPUEstimatorSpec\'>"
  is_instance: "<type \'tuple\'>"
  member {
    name: "eval_metrics"
    mtype: "<type \'property\'>"
  }
  member {
    name: "evaluation_hooks"
    mtype: "<type \'property\'>"
  }
  member {
    name: "export_outputs"
    mtype: "<type \'property\'>"
  }
  member {
    name: "host_call"
    mtype: "<type \'property\'>"
  }
  member {
    name: "loss"
    mtype: "<type \'property\'>"
  }
  member {
    name: "mode"
    mtype: "<type \'property\'>"
  }
  member {
    name: "prediction_hooks"
    mtype: "<type \'property\'>"
  }
  member {
    name: "predictions"
    mtype: "<type \'property\'>"
  }
  member {
    name: "scaffold_fn"
    mtype: "<type \'property\'>"
  }
  member {
    name: "train_op"
    mtype: "<type \'property\'>"
  }
  member {
    name: "training_hooks"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "as_estimator_spec"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "count"
  }
  member_method {
    name: "index"
  }
}
