path: "tensorflow.profiler.Profiler"
tf_class {
  is_instance: "<class \'tensorflow.python.profiler.model_analyzer.Profiler\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'graph\', \'op_log\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "add_step"
    argspec: "args=[\'self\', \'step\', \'run_meta\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "advise"
    argspec: "args=[\'self\', \'options\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "profile_graph"
    argspec: "args=[\'self\', \'options\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "profile_name_scope"
    argspec: "args=[\'self\', \'options\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "profile_operations"
    argspec: "args=[\'self\', \'options\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "profile_python"
    argspec: "args=[\'self\', \'options\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "serialize_to_string"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
