path: "tensorflow.train.MonitoredSession"
tf_class {
  is_instance: "<class \'tensorflow.python.training.monitored_session.MonitoredSession\'>"
  is_instance: "<class \'tensorflow.python.training.monitored_session._MonitoredSession\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "StepContext"
    mtype: "<type \'type\'>"
  }
  member {
    name: "graph"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'session_creator\', \'hooks\', \'stop_grace_period_secs\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'120\'], "
  }
  member_method {
    name: "close"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "run"
    argspec: "args=[\'self\', \'fetches\', \'feed_dict\', \'options\', \'run_metadata\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
  }
  member_method {
    name: "run_step_fn"
    argspec: "args=[\'self\', \'step_fn\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "should_stop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
