path: "tensorflow.Module"
tf_class {
  is_instance: "<class \'tensorflow.python.module.module.Module\'>"
  is_instance: "<class \'tensorflow.python.trackable.autotrackable.AutoTrackable\'>"
  is_instance: "<class \'tensorflow.python.trackable.base.Trackable\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "name"
    mtype: "<class \'property\'>"
  }
  member {
    name: "name_scope"
    mtype: "<class \'property\'>"
  }
  member {
    name: "non_trainable_variables"
    mtype: "<class \'property\'>"
  }
  member {
    name: "submodules"
    mtype: "<class \'property\'>"
  }
  member {
    name: "trainable_variables"
    mtype: "<class \'property\'>"
  }
  member {
    name: "variables"
    mtype: "<class \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "with_name_scope"
    argspec: "args=[\'cls\', \'method\'], varargs=None, keywords=None, defaults=None"
  }
}
