path: "tensorflow.TensorInfo"
tf_proto {
  descriptor {
    name: "TensorInfo"
    field {
      name: "name"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_STRING
      oneof_index: 0
    }
    field {
      name: "coo_sparse"
      number: 4
      label: LABEL_OPTIONAL
      type: TYPE_MESSAGE
      type_name: ".tensorflow.TensorInfo.CooSparse"
      oneof_index: 0
    }
    field {
      name: "dtype"
      number: 2
      label: LABEL_OPTIONAL
      type: TYPE_ENUM
      type_name: ".tensorflow.DataType"
    }
    field {
      name: "tensor_shape"
      number: 3
      label: LABEL_OPTIONAL
      type: TYPE_MESSAGE
      type_name: ".tensorflow.TensorShapeProto"
    }
    nested_type {
      name: "CooSparse"
      field {
        name: "values_tensor_name"
        number: 1
        label: LABEL_OPTIONAL
        type: TYPE_STRING
      }
      field {
        name: "indices_tensor_name"
        number: 2
        label: LABEL_OPTIONAL
        type: TYPE_STRING
      }
      field {
        name: "dense_shape_tensor_name"
        number: 3
        label: LABEL_OPTIONAL
        type: TYPE_STRING
      }
    }
    oneof_decl {
      name: "encoding"
    }
  }
}
