path: "tensorflow.quantization.experimental.UnitWiseQuantizationSpec.QuantizationUnit"
tf_proto {
  descriptor {
    name: "QuantizationUnit"
    field {
      name: "op_type"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    field {
      name: "node_name"
      number: 2
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    field {
      name: "func_name"
      number: 3
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
  }
}
