path: "tensorflow.ConfigProto.Experimental"
tf_proto {
  descriptor {
    name: "Experimental"
    field {
      name: "collective_group_leader"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    field {
      name: "executor_type"
      number: 3
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    field {
      name: "recv_buf_max_chunk"
      number: 4
      label: LABEL_OPTIONAL
      type: TYPE_INT32
    }
    field {
      name: "use_numa_affinity"
      number: 5
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "collective_deterministic_sequential_execution"
      number: 6
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "collective_nccl"
      number: 7
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "share_session_state_in_clusterspec_propagation"
      number: 8
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "disable_thread_spinning"
      number: 9
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "share_cluster_devices_in_session"
      number: 10
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "session_metadata"
      number: 11
      label: LABEL_OPTIONAL
      type: TYPE_MESSAGE
      type_name: ".tensorflow.SessionMetadata"
    }
    field {
      name: "optimize_for_static_graph"
      number: 12
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "enable_mlir_bridge"
      number: 13
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "mlir_bridge_rollout"
      number: 17
      label: LABEL_OPTIONAL
      type: TYPE_ENUM
      type_name: ".tensorflow.ConfigProto.Experimental.MlirBridgeRollout"
    }
    field {
      name: "enable_mlir_graph_optimization"
      number: 16
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "disable_output_partition_graphs"
      number: 14
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "xla_fusion_autotuner_thresh"
      number: 15
      label: LABEL_OPTIONAL
      type: TYPE_INT64
    }
    field {
      name: "use_tfrt"
      number: 18
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "enable_multi_host"
      number: 27
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "tfrt_use_ifrt"
      number: 32
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "backend_server_port"
      number: 28
      label: LABEL_OPTIONAL
      type: TYPE_INT32
    }
    field {
      name: "target_tpu"
      number: 29
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "target_gpu"
      number: 30
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "stream_merge_threshold"
      number: 31
      label: LABEL_OPTIONAL
      type: TYPE_INT32
    }
    field {
      name: "disable_functional_ops_lowering"
      number: 21
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "xla_prefer_single_graph_cluster"
      number: 22
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "coordination_config"
      number: 23
      label: LABEL_OPTIONAL
      type: TYPE_MESSAGE
      type_name: ".tensorflow.CoordinationServiceConfig"
    }
    field {
      name: "disable_optimize_for_static_graph"
      number: 24
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "disable_eager_executor_streaming_enqueue"
      number: 26
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "finalize_function_library_runtime"
      number: 33
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "finalize_resource_manager"
      number: 34
      label: LABEL_OPTIONAL
      type: TYPE_BOOL
    }
    field {
      name: "tf2xla_dump_dir"
      number: 35
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
    enum_type {
      name: "MlirBridgeRollout"
      value {
        name: "MLIR_BRIDGE_ROLLOUT_UNSPECIFIED"
        number: 0
      }
      value {
        name: "MLIR_BRIDGE_ROLLOUT_ENABLED"
        number: 1
      }
      value {
        name: "MLIR_BRIDGE_ROLLOUT_DISABLED"
        number: 2
      }
      reserved_range {
        start: 3
        end: 3
      }
      reserved_range {
        start: 4
        end: 4
      }
      reserved_name: "MLIR_BRIDGE_ROLLOUT_SAFE_MODE_ENABLED"
      reserved_name: "MLIR_BRIDGE_ROLLOUT_SAFE_MODE_FALLBACK_ENABLED"
    }
    reserved_range {
      start: 2
      end: 3
    }
    reserved_range {
      start: 19
      end: 20
    }
    reserved_range {
      start: 20
      end: 21
    }
    reserved_range {
      start: 25
      end: 26
    }
  }
}
