path: "tensorflow.Summary.Image"
tf_proto {
  descriptor {
    name: "Image"
    field {
      name: "height"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_INT32
    }
    field {
      name: "width"
      number: 2
      label: LABEL_OPTIONAL
      type: TYPE_INT32
    }
    field {
      name: "colorspace"
      number: 3
      label: LABEL_OPTIONAL
      type: TYPE_INT32
    }
    field {
      name: "encoded_image_string"
      number: 4
      label: LABEL_OPTIONAL
      type: TYPE_BYTES
    }
  }
}
