path: "tensorflow.saved_model.SaveOptions"
tf_class {
  is_instance: "<class \'tensorflow.python.saved_model.save_options.SaveOptions\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "experimental_custom_gradients"
    mtype: "<type \'member_descriptor\'>"
  }
  member {
    name: "experimental_io_device"
    mtype: "<type \'member_descriptor\'>"
  }
  member {
    name: "experimental_variable_policy"
    mtype: "<type \'member_descriptor\'>"
  }
  member {
    name: "function_aliases"
    mtype: "<type \'member_descriptor\'>"
  }
  member {
    name: "namespace_whitelist"
    mtype: "<type \'member_descriptor\'>"
  }
  member {
    name: "save_debug_info"
    mtype: "<type \'member_descriptor\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'namespace_whitelist\', \'save_debug_info\', \'function_aliases\', \'experimental_io_device\', \'experimental_variable_policy\', \'experimental_custom_gradients\'], varargs=None, keywords=None, defaults=[\'None\', \'False\', \'None\', \'None\', \'None\', \'False\'], "
  }
}
