path: "tensorflow.experimental"
tf_module {
  member_method {
    name: "function_executor_type"
    argspec: "args=[\'executor_type\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "output_all_intermediates"
    argspec: "args=[\'state\'], varargs=None, keywords=None, defaults=None"
  }
}
