path: "tensorflow.TypeSpec"
tf_class {
  is_instance: "<class \'tensorflow.python.framework.type_spec.TypeSpec\'>"
  is_instance: "<class \'tensorflow.python.types.trace.TraceType\'>"
  is_instance: "<class \'tensorflow.core.function.trace_type.serialization.Serializable\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "value_type"
    mtype: "<class \'abc.abstractproperty\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "experimental_as_proto"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "experimental_from_proto"
    argspec: "args=[\'cls\', \'proto\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "experimental_type_proto"
    argspec: "args=[\'cls\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_compatible_with"
    argspec: "args=[\'self\', \'spec_or_value\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_subtype_of"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "most_specific_common_supertype"
    argspec: "args=[\'self\', \'others\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "most_specific_compatible_type"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
}
