path: "tensorflow.config.experimental"
tf_module {
  member {
    name: "ClusterDeviceFilters"
    mtype: "<type \'type\'>"
  }
  member {
    name: "VirtualDeviceConfiguration"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "disable_mlir_bridge"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "enable_mlir_bridge"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_device_policy"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_memory_growth"
    argspec: "args=[\'device\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_synchronous_execution"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_virtual_device_configuration"
    argspec: "args=[\'device\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_visible_devices"
    argspec: "args=[\'device_type\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "list_logical_devices"
    argspec: "args=[\'device_type\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "list_physical_devices"
    argspec: "args=[\'device_type\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "set_device_policy"
    argspec: "args=[\'device_policy\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_memory_growth"
    argspec: "args=[\'device\', \'enable\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_synchronous_execution"
    argspec: "args=[\'enable\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_virtual_device_configuration"
    argspec: "args=[\'device\', \'logical_devices\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_visible_devices"
    argspec: "args=[\'devices\', \'device_type\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
}
