path: "tensorflow.tpu.experimental.embedding.TPUEmbedding"
tf_class {
  is_instance: "<class \'tensorflow.python.tpu.tpu_embedding_v2.TPUEmbedding\'>"
  is_instance: "<class \'tensorflow.python.training.tracking.tracking.AutoTrackable\'>"
  is_instance: "<class \'tensorflow.python.training.tracking.base.Trackable\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "embedding_tables"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'feature_config\', \'optimizer\', \'pipeline_execution_with_tensor_core\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "apply_gradients"
    argspec: "args=[\'self\', \'gradients\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "build"
    argspec: "args=[\'self\', \'per_replica_batch_size\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "dequeue"
    argspec: "args=[\'self\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "enqueue"
    argspec: "args=[\'self\', \'features\', \'weights\', \'training\', \'name\', \'device\'], varargs=None, keywords=None, defaults=[\'None\', \'True\', \'None\', \'None\'], "
  }
}
