path: "tensorflow.train.NanLossDuringTrainingError"
tf_class {
  is_instance: "<class \'tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError\'>"
  is_instance: "<class \'RuntimeError\'>"
}
