path: "tensorflow.keras.preprocessing.sequence"
tf_module {
  member {
    name: "TimeseriesGenerator"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "make_sampling_table"
    argspec: "args=[\'size\', \'sampling_factor\'], varargs=None, keywords=None, defaults=[\'1e-05\'], "
  }
  member_method {
    name: "pad_sequences"
    argspec: "args=[\'sequences\', \'maxlen\', \'dtype\', \'padding\', \'truncating\', \'value\'], varargs=None, keywords=None, defaults=[\'None\', \'int32\', \'pre\', \'pre\', \'0.0\'], "
  }
  member_method {
    name: "skipgrams"
    argspec: "args=[\'sequence\', \'vocabulary_size\', \'window_size\', \'negative_samples\', \'shuffle\', \'categorical\', \'sampling_table\', \'seed\'], varargs=None, keywords=None, defaults=[\'4\', \'1.0\', \'True\', \'False\', \'None\', \'None\'], "
  }
}
