// NOTE: Assertions have been autogenerated by hlo/tools/generate_hlo_test_checks.py
// RUN: hlo-opt %s --split-input-file --passes=test-only-algebraic-simplifier-with-onednn-enabled | FileCheck %s

// CHECK-LABEL: HloModule TestBf16ConvolutionRewritableToOnednn, entry_computation_layout={(bf16[8,4,5,5,1]{4,3,2,1,0}, bf16[3,3,3,1,32]{4,3,2,1,0})->bf16[8,4,5,5,32]{4,3,2,1,0}}

// CHECK-LABEL: ENTRY %test_case
// CHECK-NEXT:  %[[input:[^ ]+]] = bf16[8,4,5,5,1]{4,3,2,1,0} parameter(0)
// CHECK-NEXT:  %[[kernel:[^ ]+]] = bf16[3,3,3,1,32]{4,3,2,1,0} parameter(1)
// CHECK-NEXT:  ROOT %[[convolution:[^ ]+]] = bf16[8,4,5,5,32]{4,3,2,1,0} convolution(bf16[8,4,5,5,1]{4,3,2,1,0} %[[input]], bf16[3,3,3,1,32]{4,3,2,1,0} %[[kernel]]), window={size=3x3x3 pad=1_1x1_1x1_1}, dim_labels=b012f_012io->b012f

HloModule TestBf16ConvolutionRewritableToOnednn

ENTRY test_case {
  input = bf16[8,4,5,5,1] parameter(0)
  kernel = bf16[3,3,3,1,32] parameter(1)
  ROOT convolution = bf16[8,4,5,5,32] convolution(input, kernel), window={size=3x3x3 pad=1_1x1_1x1_1}, dim_labels=b012f_012io->b012f
}

// -----

// CHECK-LABEL: HloModule TestBf16ConvolutionNotRewritableToOnednn, entry_computation_layout={(bf16[8,4,5,5,1]{4,3,2,1,0}, bf16[3,3,3,1,32]{4,3,2,1,0})->bf16[4,4,5,5,32]{4,3,2,1,0}}

// CHECK-LABEL: ENTRY %test_case
// CHECK-NEXT:  %[[input:[^ ]+]] = bf16[8,4,5,5,1]{4,3,2,1,0} parameter(0)
// CHECK-NEXT:  %[[convert:[^ ]+]] = f32[8,4,5,5,1]{4,3,2,1,0} convert(bf16[8,4,5,5,1]{4,3,2,1,0} %[[input]])
// CHECK-NEXT:  %[[kernel:[^ ]+]] = bf16[3,3,3,1,32]{4,3,2,1,0} parameter(1)
// CHECK-NEXT:  %[[convert_1:[^ ]+]] = f32[3,3,3,1,32]{4,3,2,1,0} convert(bf16[3,3,3,1,32]{4,3,2,1,0} %[[kernel]])
// CHECK-NEXT:  %[[convolution_1:[^ ]+]] = f32[4,4,5,5,32]{4,3,2,1,0} convolution(f32[8,4,5,5,1]{4,3,2,1,0} %[[convert]], f32[3,3,3,1,32]{4,3,2,1,0} %[[convert_1]]), window={size=3x3x3 pad=-1_-1x1_1x1_1}, dim_labels=b012f_012io->b012f
// CHECK-NEXT:  ROOT %[[convert_2:[^ ]+]] = bf16[4,4,5,5,32]{4,3,2,1,0} convert(f32[4,4,5,5,32]{4,3,2,1,0} %[[convolution_1]])

HloModule TestBf16ConvolutionNotRewritableToOnednn

ENTRY test_case {
  input = bf16[8,4,5,5,1] parameter(0)
  kernel = bf16[3,3,3,1,32] parameter(1)
  ROOT convolution = bf16[4,4,5,5,32] convolution(input, kernel), window={size=3x3x3 pad=-1_-1x1_1x1_1}, dim_labels=b012f_012io->b012f
}
