// NOTE: Assertions have been autogenerated by hlo/tools/generate_hlo_test_checks.py
// RUN: hlo-opt %s --split-input-file --passes=rng-expander | FileCheck %s

// CHECK-LABEL: HloModule TestUniformDistribution, entry_computation_layout={()->f32[]}

// CHECK:       %[[$rng_1:[^ ]+]]
// CHECK-NEXT:  %[[state_1:[^ ]+]] = u64[2]{0} parameter(1)
// CHECK-NEXT:  %[[slice_3:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_10:[^ ]+]] = u64[] reshape(%[[slice_3]])
// CHECK-NEXT:  %[[convert_77:[^ ]+]] = u32[] convert(%[[reshape_10]])
// CHECK-NEXT:  %[[convert_81:[^ ]+]] = u64[] convert(%[[convert_77]])
// CHECK-NEXT:  %[[constant_73:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_27:[^ ]+]] = u64[] shift-right-logical(%[[reshape_10]], %[[constant_73]])
// CHECK-NEXT:  %[[convert_78:[^ ]+]] = u32[] convert(%[[shift_right_logical_27]])
// CHECK-NEXT:  %[[convert_82:[^ ]+]] = u64[] convert(%[[convert_78]])
// CHECK-NEXT:  %[[constant_75:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_2:[^ ]+]] = u64[] shift-left(%[[convert_82]], %[[constant_75]])
// CHECK-NEXT:  %[[or_2:[^ ]+]] = u64[] or(%[[convert_81]], %[[shift_left_2]])
// CHECK-NEXT:  %[[constant_80:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_27:[^ ]+]] = u64[] add(%[[or_2]], %[[constant_80]])
// CHECK-NEXT:  %[[reshape_12:[^ ]+]] = u64[1]{0} reshape(%[[add_27]])
// CHECK-NEXT:  %[[compare_3:[^ ]+]] = pred[] compare(%[[add_27]], %[[or_2]]), direction=LT
// CHECK-NEXT:  %[[slice_4:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[1:2]}
// CHECK-NEXT:  %[[reshape_11:[^ ]+]] = u64[] reshape(%[[slice_4]])
// CHECK-NEXT:  %[[convert_79:[^ ]+]] = u32[] convert(%[[reshape_11]])
// CHECK-NEXT:  %[[convert_83:[^ ]+]] = u64[] convert(%[[convert_79]])
// CHECK-NEXT:  %[[constant_74:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_28:[^ ]+]] = u64[] shift-right-logical(%[[reshape_11]], %[[constant_74]])
// CHECK-NEXT:  %[[convert_80:[^ ]+]] = u32[] convert(%[[shift_right_logical_28]])
// CHECK-NEXT:  %[[convert_84:[^ ]+]] = u64[] convert(%[[convert_80]])
// CHECK-NEXT:  %[[constant_76:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_3:[^ ]+]] = u64[] shift-left(%[[convert_84]], %[[constant_76]])
// CHECK-NEXT:  %[[or_3:[^ ]+]] = u64[] or(%[[convert_83]], %[[shift_left_3]])
// CHECK-NEXT:  %[[constant_81:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_28:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_81]])
// CHECK-NEXT:  %[[broadcast_74:[^ ]+]] = u64[] broadcast(%[[add_28]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_75:[^ ]+]] = u64[] broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_3:[^ ]+]] = u64[] select(%[[compare_3]], %[[broadcast_74]], %[[broadcast_75]])
// CHECK-NEXT:  %[[reshape_13:[^ ]+]] = u64[1]{0} reshape(%[[select_3]])
// CHECK-NEXT:  %[[concatenate_2:[^ ]+]] = u64[2]{0} concatenate(%[[reshape_12]], %[[reshape_13]]), dimensions={0}
// CHECK-NEXT:  %[[key_1:[^ ]+]] = u64[] parameter(0)
// CHECK-NEXT:  %[[convert_75:[^ ]+]] = u32[] convert(%[[key_1]])
// CHECK-NEXT:  %[[constant_86:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_29:[^ ]+]] = u32[] add(%[[convert_75]], %[[constant_86]])
// CHECK-NEXT:  %[[constant_92:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_31:[^ ]+]] = u32[] add(%[[add_29]], %[[constant_92]])
// CHECK-NEXT:  %[[constant_98:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_33:[^ ]+]] = u32[] add(%[[add_31]], %[[constant_98]])
// CHECK-NEXT:  %[[constant_104:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_35:[^ ]+]] = u32[] add(%[[add_33]], %[[constant_104]])
// CHECK-NEXT:  %[[constant_110:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_37:[^ ]+]] = u32[] add(%[[add_35]], %[[constant_110]])
// CHECK-NEXT:  %[[constant_116:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_39:[^ ]+]] = u32[] add(%[[add_37]], %[[constant_116]])
// CHECK-NEXT:  %[[constant_122:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_41:[^ ]+]] = u32[] add(%[[add_39]], %[[constant_122]])
// CHECK-NEXT:  %[[constant_128:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_43:[^ ]+]] = u32[] add(%[[add_41]], %[[constant_128]])
// CHECK-NEXT:  %[[constant_134:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_45:[^ ]+]] = u32[] add(%[[add_43]], %[[constant_134]])
// CHECK-NEXT:  %[[constant_140:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_47:[^ ]+]] = u32[] add(%[[add_45]], %[[constant_140]])
// CHECK-NEXT:  %[[constant_72:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_26:[^ ]+]] = u64[] shift-right-logical(%[[key_1]], %[[constant_72]])
// CHECK-NEXT:  %[[convert_76:[^ ]+]] = u32[] convert(%[[shift_right_logical_26]])
// CHECK-NEXT:  %[[constant_87:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_30:[^ ]+]] = u32[] add(%[[convert_76]], %[[constant_87]])
// CHECK-NEXT:  %[[constant_93:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_32:[^ ]+]] = u32[] add(%[[add_30]], %[[constant_93]])
// CHECK-NEXT:  %[[constant_99:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_34:[^ ]+]] = u32[] add(%[[add_32]], %[[constant_99]])
// CHECK-NEXT:  %[[constant_105:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_36:[^ ]+]] = u32[] add(%[[add_34]], %[[constant_105]])
// CHECK-NEXT:  %[[constant_111:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_38:[^ ]+]] = u32[] add(%[[add_36]], %[[constant_111]])
// CHECK-NEXT:  %[[constant_117:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_40:[^ ]+]] = u32[] add(%[[add_38]], %[[constant_117]])
// CHECK-NEXT:  %[[constant_123:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_42:[^ ]+]] = u32[] add(%[[add_40]], %[[constant_123]])
// CHECK-NEXT:  %[[constant_129:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_44:[^ ]+]] = u32[] add(%[[add_42]], %[[constant_129]])
// CHECK-NEXT:  %[[constant_135:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_46:[^ ]+]] = u32[] add(%[[add_44]], %[[constant_135]])
// CHECK-NEXT:  %[[constant_141:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_48:[^ ]+]] = u32[] add(%[[add_46]], %[[constant_141]])
// CHECK-NEXT:  %[[broadcast_68:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[iota_1:[^ ]+]] = u64[1]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[add_25:[^ ]+]] = u64[1]{0} add(%[[broadcast_68]], %[[iota_1]])
// CHECK-NEXT:  %[[convert_85:[^ ]+]] = u32[1]{0} convert(%[[add_25]])
// CHECK-NEXT:  %[[convert_89:[^ ]+]] = u64[1]{0} convert(%[[convert_85]])
// CHECK-NEXT:  %[[constant_82:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_76:[^ ]+]] = u64[1]{0} broadcast(%[[constant_82]]), dimensions={}
// CHECK-NEXT:  %[[multiply_22:[^ ]+]] = u64[1]{0} multiply(%[[convert_89]], %[[broadcast_76]])
// CHECK-NEXT:  %[[constant_83:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_77:[^ ]+]] = u64[1]{0} broadcast(%[[constant_83]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_31:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_22]], %[[broadcast_77]])
// CHECK-NEXT:  %[[convert_91:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_31]])
// CHECK-NEXT:  %[[broadcast_69:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[compare_2:[^ ]+]] = pred[1]{0} compare(%[[add_25]], %[[broadcast_69]]), direction=LT
// CHECK-NEXT:  %[[constant_77:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_26:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_77]])
// CHECK-NEXT:  %[[broadcast_70:[^ ]+]] = u64[1]{0} broadcast(%[[add_26]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_71:[^ ]+]] = u64[1]{0} broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_2:[^ ]+]] = u64[1]{0} select(%[[compare_2]], %[[broadcast_70]], %[[broadcast_71]])
// CHECK-NEXT:  %[[constant_79:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_73:[^ ]+]] = u64[1]{0} broadcast(%[[constant_79]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_30:[^ ]+]] = u64[1]{0} shift-right-logical(%[[select_2]], %[[broadcast_73]])
// CHECK-NEXT:  %[[convert_88:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_30]])
// CHECK-NEXT:  %[[xor_42:[^ ]+]] = u32[1]{0} xor(%[[convert_91]], %[[convert_88]])
// CHECK-NEXT:  %[[broadcast_81:[^ ]+]] = u32[1]{0} broadcast(%[[convert_76]]), dimensions={}
// CHECK-NEXT:  %[[xor_43:[^ ]+]] = u32[1]{0} xor(%[[xor_42]], %[[broadcast_81]])
// CHECK-NEXT:  %[[convert_98:[^ ]+]] = u64[1]{0} convert(%[[xor_43]])
// CHECK-NEXT:  %[[constant_90:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_84:[^ ]+]] = u64[1]{0} broadcast(%[[constant_90]]), dimensions={}
// CHECK-NEXT:  %[[multiply_25:[^ ]+]] = u64[1]{0} multiply(%[[convert_98]], %[[broadcast_84]])
// CHECK-NEXT:  %[[constant_91:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_85:[^ ]+]] = u64[1]{0} broadcast(%[[constant_91]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_34:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_25]], %[[broadcast_85]])
// CHECK-NEXT:  %[[convert_100:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_34]])
// CHECK-NEXT:  %[[convert_87:[^ ]+]] = u32[1]{0} convert(%[[select_2]])
// CHECK-NEXT:  %[[convert_92:[^ ]+]] = u64[1]{0} convert(%[[convert_87]])
// CHECK-NEXT:  %[[constant_84:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_78:[^ ]+]] = u64[1]{0} broadcast(%[[constant_84]]), dimensions={}
// CHECK-NEXT:  %[[multiply_23:[^ ]+]] = u64[1]{0} multiply(%[[convert_92]], %[[broadcast_78]])
// CHECK-NEXT:  %[[convert_93:[^ ]+]] = u32[1]{0} convert(%[[multiply_23]])
// CHECK-NEXT:  %[[xor_44:[^ ]+]] = u32[1]{0} xor(%[[convert_100]], %[[convert_93]])
// CHECK-NEXT:  %[[broadcast_86:[^ ]+]] = u32[1]{0} broadcast(%[[add_29]]), dimensions={}
// CHECK-NEXT:  %[[xor_45:[^ ]+]] = u32[1]{0} xor(%[[xor_44]], %[[broadcast_86]])
// CHECK-NEXT:  %[[convert_101:[^ ]+]] = u64[1]{0} convert(%[[xor_45]])
// CHECK-NEXT:  %[[constant_94:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_88:[^ ]+]] = u64[1]{0} broadcast(%[[constant_94]]), dimensions={}
// CHECK-NEXT:  %[[multiply_26:[^ ]+]] = u64[1]{0} multiply(%[[convert_101]], %[[broadcast_88]])
// CHECK-NEXT:  %[[constant_95:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_89:[^ ]+]] = u64[1]{0} broadcast(%[[constant_95]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_35:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_26]], %[[broadcast_89]])
// CHECK-NEXT:  %[[convert_103:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_35]])
// CHECK-NEXT:  %[[constant_85:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_79:[^ ]+]] = u64[1]{0} broadcast(%[[constant_85]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_32:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_23]], %[[broadcast_79]])
// CHECK-NEXT:  %[[convert_94:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_32]])
// CHECK-NEXT:  %[[constant_78:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_72:[^ ]+]] = u64[1]{0} broadcast(%[[constant_78]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_29:[^ ]+]] = u64[1]{0} shift-right-logical(%[[add_25]], %[[broadcast_72]])
// CHECK-NEXT:  %[[convert_86:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_29]])
// CHECK-NEXT:  %[[xor_40:[^ ]+]] = u32[1]{0} xor(%[[convert_94]], %[[convert_86]])
// CHECK-NEXT:  %[[broadcast_80:[^ ]+]] = u32[1]{0} broadcast(%[[convert_75]]), dimensions={}
// CHECK-NEXT:  %[[xor_41:[^ ]+]] = u32[1]{0} xor(%[[xor_40]], %[[broadcast_80]])
// CHECK-NEXT:  %[[convert_95:[^ ]+]] = u64[1]{0} convert(%[[xor_41]])
// CHECK-NEXT:  %[[constant_88:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_82:[^ ]+]] = u64[1]{0} broadcast(%[[constant_88]]), dimensions={}
// CHECK-NEXT:  %[[multiply_24:[^ ]+]] = u64[1]{0} multiply(%[[convert_95]], %[[broadcast_82]])
// CHECK-NEXT:  %[[convert_96:[^ ]+]] = u32[1]{0} convert(%[[multiply_24]])
// CHECK-NEXT:  %[[xor_50:[^ ]+]] = u32[1]{0} xor(%[[convert_103]], %[[convert_96]])
// CHECK-NEXT:  %[[broadcast_93:[^ ]+]] = u32[1]{0} broadcast(%[[add_32]]), dimensions={}
// CHECK-NEXT:  %[[xor_51:[^ ]+]] = u32[1]{0} xor(%[[xor_50]], %[[broadcast_93]])
// CHECK-NEXT:  %[[convert_110:[^ ]+]] = u64[1]{0} convert(%[[xor_51]])
// CHECK-NEXT:  %[[constant_102:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_96:[^ ]+]] = u64[1]{0} broadcast(%[[constant_102]]), dimensions={}
// CHECK-NEXT:  %[[multiply_29:[^ ]+]] = u64[1]{0} multiply(%[[convert_110]], %[[broadcast_96]])
// CHECK-NEXT:  %[[constant_103:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_97:[^ ]+]] = u64[1]{0} broadcast(%[[constant_103]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_38:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_29]], %[[broadcast_97]])
// CHECK-NEXT:  %[[convert_112:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_38]])
// CHECK-NEXT:  %[[constant_89:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_83:[^ ]+]] = u64[1]{0} broadcast(%[[constant_89]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_33:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_24]], %[[broadcast_83]])
// CHECK-NEXT:  %[[convert_97:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_33]])
// CHECK-NEXT:  %[[convert_90:[^ ]+]] = u32[1]{0} convert(%[[multiply_22]])
// CHECK-NEXT:  %[[xor_46:[^ ]+]] = u32[1]{0} xor(%[[convert_97]], %[[convert_90]])
// CHECK-NEXT:  %[[broadcast_87:[^ ]+]] = u32[1]{0} broadcast(%[[add_30]]), dimensions={}
// CHECK-NEXT:  %[[xor_47:[^ ]+]] = u32[1]{0} xor(%[[xor_46]], %[[broadcast_87]])
// CHECK-NEXT:  %[[convert_104:[^ ]+]] = u64[1]{0} convert(%[[xor_47]])
// CHECK-NEXT:  %[[constant_96:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_90:[^ ]+]] = u64[1]{0} broadcast(%[[constant_96]]), dimensions={}
// CHECK-NEXT:  %[[multiply_27:[^ ]+]] = u64[1]{0} multiply(%[[convert_104]], %[[broadcast_90]])
// CHECK-NEXT:  %[[convert_105:[^ ]+]] = u32[1]{0} convert(%[[multiply_27]])
// CHECK-NEXT:  %[[xor_52:[^ ]+]] = u32[1]{0} xor(%[[convert_112]], %[[convert_105]])
// CHECK-NEXT:  %[[broadcast_98:[^ ]+]] = u32[1]{0} broadcast(%[[add_33]]), dimensions={}
// CHECK-NEXT:  %[[xor_53:[^ ]+]] = u32[1]{0} xor(%[[xor_52]], %[[broadcast_98]])
// CHECK-NEXT:  %[[convert_113:[^ ]+]] = u64[1]{0} convert(%[[xor_53]])
// CHECK-NEXT:  %[[constant_106:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_100:[^ ]+]] = u64[1]{0} broadcast(%[[constant_106]]), dimensions={}
// CHECK-NEXT:  %[[multiply_30:[^ ]+]] = u64[1]{0} multiply(%[[convert_113]], %[[broadcast_100]])
// CHECK-NEXT:  %[[constant_107:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_101:[^ ]+]] = u64[1]{0} broadcast(%[[constant_107]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_39:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_30]], %[[broadcast_101]])
// CHECK-NEXT:  %[[convert_115:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_39]])
// CHECK-NEXT:  %[[constant_97:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_91:[^ ]+]] = u64[1]{0} broadcast(%[[constant_97]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_36:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_27]], %[[broadcast_91]])
// CHECK-NEXT:  %[[convert_106:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_36]])
// CHECK-NEXT:  %[[convert_99:[^ ]+]] = u32[1]{0} convert(%[[multiply_25]])
// CHECK-NEXT:  %[[xor_48:[^ ]+]] = u32[1]{0} xor(%[[convert_106]], %[[convert_99]])
// CHECK-NEXT:  %[[broadcast_92:[^ ]+]] = u32[1]{0} broadcast(%[[add_31]]), dimensions={}
// CHECK-NEXT:  %[[xor_49:[^ ]+]] = u32[1]{0} xor(%[[xor_48]], %[[broadcast_92]])
// CHECK-NEXT:  %[[convert_107:[^ ]+]] = u64[1]{0} convert(%[[xor_49]])
// CHECK-NEXT:  %[[constant_100:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_94:[^ ]+]] = u64[1]{0} broadcast(%[[constant_100]]), dimensions={}
// CHECK-NEXT:  %[[multiply_28:[^ ]+]] = u64[1]{0} multiply(%[[convert_107]], %[[broadcast_94]])
// CHECK-NEXT:  %[[convert_108:[^ ]+]] = u32[1]{0} convert(%[[multiply_28]])
// CHECK-NEXT:  %[[xor_58:[^ ]+]] = u32[1]{0} xor(%[[convert_115]], %[[convert_108]])
// CHECK-NEXT:  %[[broadcast_105:[^ ]+]] = u32[1]{0} broadcast(%[[add_36]]), dimensions={}
// CHECK-NEXT:  %[[xor_59:[^ ]+]] = u32[1]{0} xor(%[[xor_58]], %[[broadcast_105]])
// CHECK-NEXT:  %[[convert_122:[^ ]+]] = u64[1]{0} convert(%[[xor_59]])
// CHECK-NEXT:  %[[constant_114:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_108:[^ ]+]] = u64[1]{0} broadcast(%[[constant_114]]), dimensions={}
// CHECK-NEXT:  %[[multiply_33:[^ ]+]] = u64[1]{0} multiply(%[[convert_122]], %[[broadcast_108]])
// CHECK-NEXT:  %[[constant_115:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_109:[^ ]+]] = u64[1]{0} broadcast(%[[constant_115]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_42:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_33]], %[[broadcast_109]])
// CHECK-NEXT:  %[[convert_124:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_42]])
// CHECK-NEXT:  %[[constant_101:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_95:[^ ]+]] = u64[1]{0} broadcast(%[[constant_101]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_37:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_28]], %[[broadcast_95]])
// CHECK-NEXT:  %[[convert_109:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_37]])
// CHECK-NEXT:  %[[convert_102:[^ ]+]] = u32[1]{0} convert(%[[multiply_26]])
// CHECK-NEXT:  %[[xor_54:[^ ]+]] = u32[1]{0} xor(%[[convert_109]], %[[convert_102]])
// CHECK-NEXT:  %[[broadcast_99:[^ ]+]] = u32[1]{0} broadcast(%[[add_34]]), dimensions={}
// CHECK-NEXT:  %[[xor_55:[^ ]+]] = u32[1]{0} xor(%[[xor_54]], %[[broadcast_99]])
// CHECK-NEXT:  %[[convert_116:[^ ]+]] = u64[1]{0} convert(%[[xor_55]])
// CHECK-NEXT:  %[[constant_108:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_102:[^ ]+]] = u64[1]{0} broadcast(%[[constant_108]]), dimensions={}
// CHECK-NEXT:  %[[multiply_31:[^ ]+]] = u64[1]{0} multiply(%[[convert_116]], %[[broadcast_102]])
// CHECK-NEXT:  %[[convert_117:[^ ]+]] = u32[1]{0} convert(%[[multiply_31]])
// CHECK-NEXT:  %[[xor_60:[^ ]+]] = u32[1]{0} xor(%[[convert_124]], %[[convert_117]])
// CHECK-NEXT:  %[[broadcast_110:[^ ]+]] = u32[1]{0} broadcast(%[[add_37]]), dimensions={}
// CHECK-NEXT:  %[[xor_61:[^ ]+]] = u32[1]{0} xor(%[[xor_60]], %[[broadcast_110]])
// CHECK-NEXT:  %[[convert_125:[^ ]+]] = u64[1]{0} convert(%[[xor_61]])
// CHECK-NEXT:  %[[constant_118:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_112:[^ ]+]] = u64[1]{0} broadcast(%[[constant_118]]), dimensions={}
// CHECK-NEXT:  %[[multiply_34:[^ ]+]] = u64[1]{0} multiply(%[[convert_125]], %[[broadcast_112]])
// CHECK-NEXT:  %[[constant_119:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_113:[^ ]+]] = u64[1]{0} broadcast(%[[constant_119]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_43:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_34]], %[[broadcast_113]])
// CHECK-NEXT:  %[[convert_127:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_43]])
// CHECK-NEXT:  %[[constant_109:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_103:[^ ]+]] = u64[1]{0} broadcast(%[[constant_109]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_40:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_31]], %[[broadcast_103]])
// CHECK-NEXT:  %[[convert_118:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_40]])
// CHECK-NEXT:  %[[convert_111:[^ ]+]] = u32[1]{0} convert(%[[multiply_29]])
// CHECK-NEXT:  %[[xor_56:[^ ]+]] = u32[1]{0} xor(%[[convert_118]], %[[convert_111]])
// CHECK-NEXT:  %[[broadcast_104:[^ ]+]] = u32[1]{0} broadcast(%[[add_35]]), dimensions={}
// CHECK-NEXT:  %[[xor_57:[^ ]+]] = u32[1]{0} xor(%[[xor_56]], %[[broadcast_104]])
// CHECK-NEXT:  %[[convert_119:[^ ]+]] = u64[1]{0} convert(%[[xor_57]])
// CHECK-NEXT:  %[[constant_112:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_106:[^ ]+]] = u64[1]{0} broadcast(%[[constant_112]]), dimensions={}
// CHECK-NEXT:  %[[multiply_32:[^ ]+]] = u64[1]{0} multiply(%[[convert_119]], %[[broadcast_106]])
// CHECK-NEXT:  %[[convert_120:[^ ]+]] = u32[1]{0} convert(%[[multiply_32]])
// CHECK-NEXT:  %[[xor_66:[^ ]+]] = u32[1]{0} xor(%[[convert_127]], %[[convert_120]])
// CHECK-NEXT:  %[[broadcast_117:[^ ]+]] = u32[1]{0} broadcast(%[[add_40]]), dimensions={}
// CHECK-NEXT:  %[[xor_67:[^ ]+]] = u32[1]{0} xor(%[[xor_66]], %[[broadcast_117]])
// CHECK-NEXT:  %[[convert_134:[^ ]+]] = u64[1]{0} convert(%[[xor_67]])
// CHECK-NEXT:  %[[constant_126:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_120:[^ ]+]] = u64[1]{0} broadcast(%[[constant_126]]), dimensions={}
// CHECK-NEXT:  %[[multiply_37:[^ ]+]] = u64[1]{0} multiply(%[[convert_134]], %[[broadcast_120]])
// CHECK-NEXT:  %[[constant_127:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_121:[^ ]+]] = u64[1]{0} broadcast(%[[constant_127]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_46:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_37]], %[[broadcast_121]])
// CHECK-NEXT:  %[[convert_136:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_46]])
// CHECK-NEXT:  %[[constant_113:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_107:[^ ]+]] = u64[1]{0} broadcast(%[[constant_113]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_41:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_32]], %[[broadcast_107]])
// CHECK-NEXT:  %[[convert_121:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_41]])
// CHECK-NEXT:  %[[convert_114:[^ ]+]] = u32[1]{0} convert(%[[multiply_30]])
// CHECK-NEXT:  %[[xor_62:[^ ]+]] = u32[1]{0} xor(%[[convert_121]], %[[convert_114]])
// CHECK-NEXT:  %[[broadcast_111:[^ ]+]] = u32[1]{0} broadcast(%[[add_38]]), dimensions={}
// CHECK-NEXT:  %[[xor_63:[^ ]+]] = u32[1]{0} xor(%[[xor_62]], %[[broadcast_111]])
// CHECK-NEXT:  %[[convert_128:[^ ]+]] = u64[1]{0} convert(%[[xor_63]])
// CHECK-NEXT:  %[[constant_120:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_114:[^ ]+]] = u64[1]{0} broadcast(%[[constant_120]]), dimensions={}
// CHECK-NEXT:  %[[multiply_35:[^ ]+]] = u64[1]{0} multiply(%[[convert_128]], %[[broadcast_114]])
// CHECK-NEXT:  %[[convert_129:[^ ]+]] = u32[1]{0} convert(%[[multiply_35]])
// CHECK-NEXT:  %[[xor_68:[^ ]+]] = u32[1]{0} xor(%[[convert_136]], %[[convert_129]])
// CHECK-NEXT:  %[[broadcast_122:[^ ]+]] = u32[1]{0} broadcast(%[[add_41]]), dimensions={}
// CHECK-NEXT:  %[[xor_69:[^ ]+]] = u32[1]{0} xor(%[[xor_68]], %[[broadcast_122]])
// CHECK-NEXT:  %[[convert_137:[^ ]+]] = u64[1]{0} convert(%[[xor_69]])
// CHECK-NEXT:  %[[constant_130:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_124:[^ ]+]] = u64[1]{0} broadcast(%[[constant_130]]), dimensions={}
// CHECK-NEXT:  %[[multiply_38:[^ ]+]] = u64[1]{0} multiply(%[[convert_137]], %[[broadcast_124]])
// CHECK-NEXT:  %[[constant_131:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_125:[^ ]+]] = u64[1]{0} broadcast(%[[constant_131]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_47:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_38]], %[[broadcast_125]])
// CHECK-NEXT:  %[[convert_139:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_47]])
// CHECK-NEXT:  %[[constant_121:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_115:[^ ]+]] = u64[1]{0} broadcast(%[[constant_121]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_44:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_35]], %[[broadcast_115]])
// CHECK-NEXT:  %[[convert_130:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_44]])
// CHECK-NEXT:  %[[convert_123:[^ ]+]] = u32[1]{0} convert(%[[multiply_33]])
// CHECK-NEXT:  %[[xor_64:[^ ]+]] = u32[1]{0} xor(%[[convert_130]], %[[convert_123]])
// CHECK-NEXT:  %[[broadcast_116:[^ ]+]] = u32[1]{0} broadcast(%[[add_39]]), dimensions={}
// CHECK-NEXT:  %[[xor_65:[^ ]+]] = u32[1]{0} xor(%[[xor_64]], %[[broadcast_116]])
// CHECK-NEXT:  %[[convert_131:[^ ]+]] = u64[1]{0} convert(%[[xor_65]])
// CHECK-NEXT:  %[[constant_124:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_118:[^ ]+]] = u64[1]{0} broadcast(%[[constant_124]]), dimensions={}
// CHECK-NEXT:  %[[multiply_36:[^ ]+]] = u64[1]{0} multiply(%[[convert_131]], %[[broadcast_118]])
// CHECK-NEXT:  %[[convert_132:[^ ]+]] = u32[1]{0} convert(%[[multiply_36]])
// CHECK-NEXT:  %[[xor_74:[^ ]+]] = u32[1]{0} xor(%[[convert_139]], %[[convert_132]])
// CHECK-NEXT:  %[[broadcast_129:[^ ]+]] = u32[1]{0} broadcast(%[[add_44]]), dimensions={}
// CHECK-NEXT:  %[[xor_75:[^ ]+]] = u32[1]{0} xor(%[[xor_74]], %[[broadcast_129]])
// CHECK-NEXT:  %[[convert_146:[^ ]+]] = u64[1]{0} convert(%[[xor_75]])
// CHECK-NEXT:  %[[constant_138:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_132:[^ ]+]] = u64[1]{0} broadcast(%[[constant_138]]), dimensions={}
// CHECK-NEXT:  %[[multiply_41:[^ ]+]] = u64[1]{0} multiply(%[[convert_146]], %[[broadcast_132]])
// CHECK-NEXT:  %[[constant_139:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_133:[^ ]+]] = u64[1]{0} broadcast(%[[constant_139]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_50:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_41]], %[[broadcast_133]])
// CHECK-NEXT:  %[[convert_148:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_50]])
// CHECK-NEXT:  %[[constant_125:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_119:[^ ]+]] = u64[1]{0} broadcast(%[[constant_125]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_45:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_36]], %[[broadcast_119]])
// CHECK-NEXT:  %[[convert_133:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_45]])
// CHECK-NEXT:  %[[convert_126:[^ ]+]] = u32[1]{0} convert(%[[multiply_34]])
// CHECK-NEXT:  %[[xor_70:[^ ]+]] = u32[1]{0} xor(%[[convert_133]], %[[convert_126]])
// CHECK-NEXT:  %[[broadcast_123:[^ ]+]] = u32[1]{0} broadcast(%[[add_42]]), dimensions={}
// CHECK-NEXT:  %[[xor_71:[^ ]+]] = u32[1]{0} xor(%[[xor_70]], %[[broadcast_123]])
// CHECK-NEXT:  %[[convert_140:[^ ]+]] = u64[1]{0} convert(%[[xor_71]])
// CHECK-NEXT:  %[[constant_132:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_126:[^ ]+]] = u64[1]{0} broadcast(%[[constant_132]]), dimensions={}
// CHECK-NEXT:  %[[multiply_39:[^ ]+]] = u64[1]{0} multiply(%[[convert_140]], %[[broadcast_126]])
// CHECK-NEXT:  %[[convert_141:[^ ]+]] = u32[1]{0} convert(%[[multiply_39]])
// CHECK-NEXT:  %[[xor_76:[^ ]+]] = u32[1]{0} xor(%[[convert_148]], %[[convert_141]])
// CHECK-NEXT:  %[[broadcast_134:[^ ]+]] = u32[1]{0} broadcast(%[[add_45]]), dimensions={}
// CHECK-NEXT:  %[[xor_77:[^ ]+]] = u32[1]{0} xor(%[[xor_76]], %[[broadcast_134]])
// CHECK-NEXT:  %[[reshape_14:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_77]])
// CHECK-NEXT:  %[[convert_147:[^ ]+]] = u32[1]{0} convert(%[[multiply_41]])
// CHECK-NEXT:  %[[reshape_15:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_147]])
// CHECK-NEXT:  %[[constant_133:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_127:[^ ]+]] = u64[1]{0} broadcast(%[[constant_133]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_48:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_39]], %[[broadcast_127]])
// CHECK-NEXT:  %[[convert_142:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_48]])
// CHECK-NEXT:  %[[convert_135:[^ ]+]] = u32[1]{0} convert(%[[multiply_37]])
// CHECK-NEXT:  %[[xor_72:[^ ]+]] = u32[1]{0} xor(%[[convert_142]], %[[convert_135]])
// CHECK-NEXT:  %[[broadcast_128:[^ ]+]] = u32[1]{0} broadcast(%[[add_43]]), dimensions={}
// CHECK-NEXT:  %[[xor_73:[^ ]+]] = u32[1]{0} xor(%[[xor_72]], %[[broadcast_128]])
// CHECK-NEXT:  %[[convert_143:[^ ]+]] = u64[1]{0} convert(%[[xor_73]])
// CHECK-NEXT:  %[[constant_136:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_130:[^ ]+]] = u64[1]{0} broadcast(%[[constant_136]]), dimensions={}
// CHECK-NEXT:  %[[multiply_40:[^ ]+]] = u64[1]{0} multiply(%[[convert_143]], %[[broadcast_130]])
// CHECK-NEXT:  %[[constant_137:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_131:[^ ]+]] = u64[1]{0} broadcast(%[[constant_137]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_49:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_40]], %[[broadcast_131]])
// CHECK-NEXT:  %[[convert_145:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_49]])
// CHECK-NEXT:  %[[convert_138:[^ ]+]] = u32[1]{0} convert(%[[multiply_38]])
// CHECK-NEXT:  %[[xor_78:[^ ]+]] = u32[1]{0} xor(%[[convert_145]], %[[convert_138]])
// CHECK-NEXT:  %[[broadcast_135:[^ ]+]] = u32[1]{0} broadcast(%[[add_46]]), dimensions={}
// CHECK-NEXT:  %[[xor_79:[^ ]+]] = u32[1]{0} xor(%[[xor_78]], %[[broadcast_135]])
// CHECK-NEXT:  %[[reshape_16:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_79]])
// CHECK-NEXT:  %[[convert_144:[^ ]+]] = u32[1]{0} convert(%[[multiply_40]])
// CHECK-NEXT:  %[[reshape_17:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_144]])
// CHECK-NEXT:  %[[concatenate_3:[^ ]+]] = u32[1,4]{1,0} concatenate(%[[reshape_14]], %[[reshape_15]], %[[reshape_16]], %[[reshape_17]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_18:[^ ]+]] = u32[4]{0} reshape(%[[concatenate_3]])
// CHECK-NEXT:  %[[slice_5:[^ ]+]] = u32[1]{0} slice(%[[reshape_18]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_19:[^ ]+]] = u32[] reshape(%[[slice_5]])
// CHECK-NEXT:  %[[constant_142:[^ ]+]] = u32[] constant(9)
// CHECK-NEXT:  %[[shift_right_logical_51:[^ ]+]] = u32[] shift-right-logical(%[[reshape_19]], %[[constant_142]])
// CHECK-NEXT:  %[[convert_149:[^ ]+]] = f32[] convert(%[[shift_right_logical_51]])
// CHECK-NEXT:  %[[constant_143:[^ ]+]] = f32[] constant(1.1920929e-07)
// CHECK-NEXT:  %[[multiply_42:[^ ]+]] = f32[] multiply(%[[convert_149]], %[[constant_143]])
// CHECK-NEXT:  %[[b_or_sigma_1:[^ ]+]] = f32[] parameter(3)
// CHECK-NEXT:  %[[a_or_mean_1:[^ ]+]] = f32[] parameter(2)
// CHECK-NEXT:  %[[subtract_1:[^ ]+]] = f32[] subtract(%[[b_or_sigma_1]], %[[a_or_mean_1]])
// CHECK-NEXT:  %[[multiply_43:[^ ]+]] = f32[] multiply(%[[multiply_42]], %[[subtract_1]])
// CHECK-NEXT:  ROOT %[[add_49:[^ ]+]] = f32[] add(%[[multiply_43]], %[[a_or_mean_1]])

// CHECK-LABEL: ENTRY %test_uniform
// CHECK-NEXT:  %[[shape:[^ ]+]] = u64[3]{0} constant({2, 4, 8})
// CHECK-NEXT:  %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed", frontend_attributes={_xla_cse_safe_zero_operand="true"}
// CHECK-NEXT:  %[[constant:[^ ]+]] = u64[] constant(3)
// CHECK-NEXT:  %[[constant_1:[^ ]+]] = u64[] constant(11400714819323198485)
// CHECK-NEXT:  %[[multiply:[^ ]+]] = u64[] multiply(%[[constant]], %[[constant_1]])
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply]], %[[constant_2]])
// CHECK-NEXT:  %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[replica_id]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])
// CHECK-NEXT:  %[[rng_get_and_update_state:[^ ]+]] = u64[2]{0} rng-get-and-update-state(), delta=1
// CHECK-NEXT:  %[[min:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[max:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  ROOT %[[call:[^ ]+]] = f32[] call(%[[xor_2]], %[[rng_get_and_update_state]], %[[min]], %[[max]]), to_apply=%[[$rng_1]]

HloModule TestUniformDistribution

ENTRY test_uniform {
  min = f32[] constant(0)
  max = f32[] constant(1)
  shape = u64[3] constant({2, 4, 8})
  ROOT result = f32[] rng(min, max, shape), distribution=rng_uniform
}

// -----

// CHECK-LABEL: HloModule TestNormalDistribution, entry_computation_layout={()->f32[]}

// CHECK:       %[[$rng_1:[^ ]+]]
// CHECK-NEXT:  %[[state_1:[^ ]+]] = u64[2]{0} parameter(1)
// CHECK-NEXT:  %[[slice_5:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_11:[^ ]+]] = u64[] reshape(%[[slice_5]])
// CHECK-NEXT:  %[[convert_77:[^ ]+]] = u32[] convert(%[[reshape_11]])
// CHECK-NEXT:  %[[convert_81:[^ ]+]] = u64[] convert(%[[convert_77]])
// CHECK-NEXT:  %[[constant_80:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_27:[^ ]+]] = u64[] shift-right-logical(%[[reshape_11]], %[[constant_80]])
// CHECK-NEXT:  %[[convert_78:[^ ]+]] = u32[] convert(%[[shift_right_logical_27]])
// CHECK-NEXT:  %[[convert_82:[^ ]+]] = u64[] convert(%[[convert_78]])
// CHECK-NEXT:  %[[constant_82:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_2:[^ ]+]] = u64[] shift-left(%[[convert_82]], %[[constant_82]])
// CHECK-NEXT:  %[[or_2:[^ ]+]] = u64[] or(%[[convert_81]], %[[shift_left_2]])
// CHECK-NEXT:  %[[constant_87:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_28:[^ ]+]] = u64[] add(%[[or_2]], %[[constant_87]])
// CHECK-NEXT:  %[[reshape_13:[^ ]+]] = u64[1]{0} reshape(%[[add_28]])
// CHECK-NEXT:  %[[compare_3:[^ ]+]] = pred[] compare(%[[add_28]], %[[or_2]]), direction=LT
// CHECK-NEXT:  %[[slice_6:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[1:2]}
// CHECK-NEXT:  %[[reshape_12:[^ ]+]] = u64[] reshape(%[[slice_6]])
// CHECK-NEXT:  %[[convert_79:[^ ]+]] = u32[] convert(%[[reshape_12]])
// CHECK-NEXT:  %[[convert_83:[^ ]+]] = u64[] convert(%[[convert_79]])
// CHECK-NEXT:  %[[constant_81:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_28:[^ ]+]] = u64[] shift-right-logical(%[[reshape_12]], %[[constant_81]])
// CHECK-NEXT:  %[[convert_80:[^ ]+]] = u32[] convert(%[[shift_right_logical_28]])
// CHECK-NEXT:  %[[convert_84:[^ ]+]] = u64[] convert(%[[convert_80]])
// CHECK-NEXT:  %[[constant_83:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_3:[^ ]+]] = u64[] shift-left(%[[convert_84]], %[[constant_83]])
// CHECK-NEXT:  %[[or_3:[^ ]+]] = u64[] or(%[[convert_83]], %[[shift_left_3]])
// CHECK-NEXT:  %[[constant_88:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_29:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_88]])
// CHECK-NEXT:  %[[broadcast_81:[^ ]+]] = u64[] broadcast(%[[add_29]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_82:[^ ]+]] = u64[] broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_3:[^ ]+]] = u64[] select(%[[compare_3]], %[[broadcast_81]], %[[broadcast_82]])
// CHECK-NEXT:  %[[reshape_14:[^ ]+]] = u64[1]{0} reshape(%[[select_3]])
// CHECK-NEXT:  %[[concatenate_2:[^ ]+]] = u64[2]{0} concatenate(%[[reshape_13]], %[[reshape_14]]), dimensions={0}
// CHECK-NEXT:  %[[key_1:[^ ]+]] = u64[] parameter(0)
// CHECK-NEXT:  %[[convert_75:[^ ]+]] = u32[] convert(%[[key_1]])
// CHECK-NEXT:  %[[constant_93:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_30:[^ ]+]] = u32[] add(%[[convert_75]], %[[constant_93]])
// CHECK-NEXT:  %[[constant_99:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_32:[^ ]+]] = u32[] add(%[[add_30]], %[[constant_99]])
// CHECK-NEXT:  %[[constant_105:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_34:[^ ]+]] = u32[] add(%[[add_32]], %[[constant_105]])
// CHECK-NEXT:  %[[constant_111:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_36:[^ ]+]] = u32[] add(%[[add_34]], %[[constant_111]])
// CHECK-NEXT:  %[[constant_117:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_38:[^ ]+]] = u32[] add(%[[add_36]], %[[constant_117]])
// CHECK-NEXT:  %[[constant_123:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_40:[^ ]+]] = u32[] add(%[[add_38]], %[[constant_123]])
// CHECK-NEXT:  %[[constant_129:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_42:[^ ]+]] = u32[] add(%[[add_40]], %[[constant_129]])
// CHECK-NEXT:  %[[constant_135:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_44:[^ ]+]] = u32[] add(%[[add_42]], %[[constant_135]])
// CHECK-NEXT:  %[[constant_141:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_46:[^ ]+]] = u32[] add(%[[add_44]], %[[constant_141]])
// CHECK-NEXT:  %[[constant_147:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_48:[^ ]+]] = u32[] add(%[[add_46]], %[[constant_147]])
// CHECK-NEXT:  %[[constant_79:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_26:[^ ]+]] = u64[] shift-right-logical(%[[key_1]], %[[constant_79]])
// CHECK-NEXT:  %[[convert_76:[^ ]+]] = u32[] convert(%[[shift_right_logical_26]])
// CHECK-NEXT:  %[[constant_94:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_31:[^ ]+]] = u32[] add(%[[convert_76]], %[[constant_94]])
// CHECK-NEXT:  %[[constant_100:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_33:[^ ]+]] = u32[] add(%[[add_31]], %[[constant_100]])
// CHECK-NEXT:  %[[constant_106:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_35:[^ ]+]] = u32[] add(%[[add_33]], %[[constant_106]])
// CHECK-NEXT:  %[[constant_112:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_37:[^ ]+]] = u32[] add(%[[add_35]], %[[constant_112]])
// CHECK-NEXT:  %[[constant_118:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_39:[^ ]+]] = u32[] add(%[[add_37]], %[[constant_118]])
// CHECK-NEXT:  %[[constant_124:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_41:[^ ]+]] = u32[] add(%[[add_39]], %[[constant_124]])
// CHECK-NEXT:  %[[constant_130:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_43:[^ ]+]] = u32[] add(%[[add_41]], %[[constant_130]])
// CHECK-NEXT:  %[[constant_136:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_45:[^ ]+]] = u32[] add(%[[add_43]], %[[constant_136]])
// CHECK-NEXT:  %[[constant_142:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_47:[^ ]+]] = u32[] add(%[[add_45]], %[[constant_142]])
// CHECK-NEXT:  %[[constant_148:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_49:[^ ]+]] = u32[] add(%[[add_47]], %[[constant_148]])
// CHECK-NEXT:  %[[constant_152:[^ ]+]] = f32[] constant(6.28318548)
// CHECK-NEXT:  %[[broadcast_148:[^ ]+]] = f32[1]{0} broadcast(%[[constant_152]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_75:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[iota_1:[^ ]+]] = u64[1]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[add_26:[^ ]+]] = u64[1]{0} add(%[[broadcast_75]], %[[iota_1]])
// CHECK-NEXT:  %[[convert_85:[^ ]+]] = u32[1]{0} convert(%[[add_26]])
// CHECK-NEXT:  %[[convert_89:[^ ]+]] = u64[1]{0} convert(%[[convert_85]])
// CHECK-NEXT:  %[[constant_89:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_83:[^ ]+]] = u64[1]{0} broadcast(%[[constant_89]]), dimensions={}
// CHECK-NEXT:  %[[multiply_27:[^ ]+]] = u64[1]{0} multiply(%[[convert_89]], %[[broadcast_83]])
// CHECK-NEXT:  %[[constant_90:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_84:[^ ]+]] = u64[1]{0} broadcast(%[[constant_90]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_31:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_27]], %[[broadcast_84]])
// CHECK-NEXT:  %[[convert_91:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_31]])
// CHECK-NEXT:  %[[broadcast_76:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[compare_2:[^ ]+]] = pred[1]{0} compare(%[[add_26]], %[[broadcast_76]]), direction=LT
// CHECK-NEXT:  %[[constant_84:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_27:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_84]])
// CHECK-NEXT:  %[[broadcast_77:[^ ]+]] = u64[1]{0} broadcast(%[[add_27]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_78:[^ ]+]] = u64[1]{0} broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_2:[^ ]+]] = u64[1]{0} select(%[[compare_2]], %[[broadcast_77]], %[[broadcast_78]])
// CHECK-NEXT:  %[[constant_86:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_80:[^ ]+]] = u64[1]{0} broadcast(%[[constant_86]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_30:[^ ]+]] = u64[1]{0} shift-right-logical(%[[select_2]], %[[broadcast_80]])
// CHECK-NEXT:  %[[convert_88:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_30]])
// CHECK-NEXT:  %[[xor_42:[^ ]+]] = u32[1]{0} xor(%[[convert_91]], %[[convert_88]])
// CHECK-NEXT:  %[[broadcast_88:[^ ]+]] = u32[1]{0} broadcast(%[[convert_76]]), dimensions={}
// CHECK-NEXT:  %[[xor_43:[^ ]+]] = u32[1]{0} xor(%[[xor_42]], %[[broadcast_88]])
// CHECK-NEXT:  %[[convert_98:[^ ]+]] = u64[1]{0} convert(%[[xor_43]])
// CHECK-NEXT:  %[[constant_97:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_91:[^ ]+]] = u64[1]{0} broadcast(%[[constant_97]]), dimensions={}
// CHECK-NEXT:  %[[multiply_30:[^ ]+]] = u64[1]{0} multiply(%[[convert_98]], %[[broadcast_91]])
// CHECK-NEXT:  %[[constant_98:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_92:[^ ]+]] = u64[1]{0} broadcast(%[[constant_98]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_34:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_30]], %[[broadcast_92]])
// CHECK-NEXT:  %[[convert_100:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_34]])
// CHECK-NEXT:  %[[convert_87:[^ ]+]] = u32[1]{0} convert(%[[select_2]])
// CHECK-NEXT:  %[[convert_92:[^ ]+]] = u64[1]{0} convert(%[[convert_87]])
// CHECK-NEXT:  %[[constant_91:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_85:[^ ]+]] = u64[1]{0} broadcast(%[[constant_91]]), dimensions={}
// CHECK-NEXT:  %[[multiply_28:[^ ]+]] = u64[1]{0} multiply(%[[convert_92]], %[[broadcast_85]])
// CHECK-NEXT:  %[[convert_93:[^ ]+]] = u32[1]{0} convert(%[[multiply_28]])
// CHECK-NEXT:  %[[xor_44:[^ ]+]] = u32[1]{0} xor(%[[convert_100]], %[[convert_93]])
// CHECK-NEXT:  %[[broadcast_93:[^ ]+]] = u32[1]{0} broadcast(%[[add_30]]), dimensions={}
// CHECK-NEXT:  %[[xor_45:[^ ]+]] = u32[1]{0} xor(%[[xor_44]], %[[broadcast_93]])
// CHECK-NEXT:  %[[convert_101:[^ ]+]] = u64[1]{0} convert(%[[xor_45]])
// CHECK-NEXT:  %[[constant_101:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_95:[^ ]+]] = u64[1]{0} broadcast(%[[constant_101]]), dimensions={}
// CHECK-NEXT:  %[[multiply_31:[^ ]+]] = u64[1]{0} multiply(%[[convert_101]], %[[broadcast_95]])
// CHECK-NEXT:  %[[constant_102:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_96:[^ ]+]] = u64[1]{0} broadcast(%[[constant_102]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_35:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_31]], %[[broadcast_96]])
// CHECK-NEXT:  %[[convert_103:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_35]])
// CHECK-NEXT:  %[[constant_92:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_86:[^ ]+]] = u64[1]{0} broadcast(%[[constant_92]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_32:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_28]], %[[broadcast_86]])
// CHECK-NEXT:  %[[convert_94:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_32]])
// CHECK-NEXT:  %[[constant_85:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_79:[^ ]+]] = u64[1]{0} broadcast(%[[constant_85]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_29:[^ ]+]] = u64[1]{0} shift-right-logical(%[[add_26]], %[[broadcast_79]])
// CHECK-NEXT:  %[[convert_86:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_29]])
// CHECK-NEXT:  %[[xor_40:[^ ]+]] = u32[1]{0} xor(%[[convert_94]], %[[convert_86]])
// CHECK-NEXT:  %[[broadcast_87:[^ ]+]] = u32[1]{0} broadcast(%[[convert_75]]), dimensions={}
// CHECK-NEXT:  %[[xor_41:[^ ]+]] = u32[1]{0} xor(%[[xor_40]], %[[broadcast_87]])
// CHECK-NEXT:  %[[convert_95:[^ ]+]] = u64[1]{0} convert(%[[xor_41]])
// CHECK-NEXT:  %[[constant_95:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_89:[^ ]+]] = u64[1]{0} broadcast(%[[constant_95]]), dimensions={}
// CHECK-NEXT:  %[[multiply_29:[^ ]+]] = u64[1]{0} multiply(%[[convert_95]], %[[broadcast_89]])
// CHECK-NEXT:  %[[convert_96:[^ ]+]] = u32[1]{0} convert(%[[multiply_29]])
// CHECK-NEXT:  %[[xor_50:[^ ]+]] = u32[1]{0} xor(%[[convert_103]], %[[convert_96]])
// CHECK-NEXT:  %[[broadcast_100:[^ ]+]] = u32[1]{0} broadcast(%[[add_33]]), dimensions={}
// CHECK-NEXT:  %[[xor_51:[^ ]+]] = u32[1]{0} xor(%[[xor_50]], %[[broadcast_100]])
// CHECK-NEXT:  %[[convert_110:[^ ]+]] = u64[1]{0} convert(%[[xor_51]])
// CHECK-NEXT:  %[[constant_109:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_103:[^ ]+]] = u64[1]{0} broadcast(%[[constant_109]]), dimensions={}
// CHECK-NEXT:  %[[multiply_34:[^ ]+]] = u64[1]{0} multiply(%[[convert_110]], %[[broadcast_103]])
// CHECK-NEXT:  %[[constant_110:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_104:[^ ]+]] = u64[1]{0} broadcast(%[[constant_110]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_38:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_34]], %[[broadcast_104]])
// CHECK-NEXT:  %[[convert_112:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_38]])
// CHECK-NEXT:  %[[constant_96:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_90:[^ ]+]] = u64[1]{0} broadcast(%[[constant_96]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_33:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_29]], %[[broadcast_90]])
// CHECK-NEXT:  %[[convert_97:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_33]])
// CHECK-NEXT:  %[[convert_90:[^ ]+]] = u32[1]{0} convert(%[[multiply_27]])
// CHECK-NEXT:  %[[xor_46:[^ ]+]] = u32[1]{0} xor(%[[convert_97]], %[[convert_90]])
// CHECK-NEXT:  %[[broadcast_94:[^ ]+]] = u32[1]{0} broadcast(%[[add_31]]), dimensions={}
// CHECK-NEXT:  %[[xor_47:[^ ]+]] = u32[1]{0} xor(%[[xor_46]], %[[broadcast_94]])
// CHECK-NEXT:  %[[convert_104:[^ ]+]] = u64[1]{0} convert(%[[xor_47]])
// CHECK-NEXT:  %[[constant_103:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_97:[^ ]+]] = u64[1]{0} broadcast(%[[constant_103]]), dimensions={}
// CHECK-NEXT:  %[[multiply_32:[^ ]+]] = u64[1]{0} multiply(%[[convert_104]], %[[broadcast_97]])
// CHECK-NEXT:  %[[convert_105:[^ ]+]] = u32[1]{0} convert(%[[multiply_32]])
// CHECK-NEXT:  %[[xor_52:[^ ]+]] = u32[1]{0} xor(%[[convert_112]], %[[convert_105]])
// CHECK-NEXT:  %[[broadcast_105:[^ ]+]] = u32[1]{0} broadcast(%[[add_34]]), dimensions={}
// CHECK-NEXT:  %[[xor_53:[^ ]+]] = u32[1]{0} xor(%[[xor_52]], %[[broadcast_105]])
// CHECK-NEXT:  %[[convert_113:[^ ]+]] = u64[1]{0} convert(%[[xor_53]])
// CHECK-NEXT:  %[[constant_113:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_107:[^ ]+]] = u64[1]{0} broadcast(%[[constant_113]]), dimensions={}
// CHECK-NEXT:  %[[multiply_35:[^ ]+]] = u64[1]{0} multiply(%[[convert_113]], %[[broadcast_107]])
// CHECK-NEXT:  %[[constant_114:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_108:[^ ]+]] = u64[1]{0} broadcast(%[[constant_114]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_39:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_35]], %[[broadcast_108]])
// CHECK-NEXT:  %[[convert_115:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_39]])
// CHECK-NEXT:  %[[constant_104:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_98:[^ ]+]] = u64[1]{0} broadcast(%[[constant_104]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_36:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_32]], %[[broadcast_98]])
// CHECK-NEXT:  %[[convert_106:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_36]])
// CHECK-NEXT:  %[[convert_99:[^ ]+]] = u32[1]{0} convert(%[[multiply_30]])
// CHECK-NEXT:  %[[xor_48:[^ ]+]] = u32[1]{0} xor(%[[convert_106]], %[[convert_99]])
// CHECK-NEXT:  %[[broadcast_99:[^ ]+]] = u32[1]{0} broadcast(%[[add_32]]), dimensions={}
// CHECK-NEXT:  %[[xor_49:[^ ]+]] = u32[1]{0} xor(%[[xor_48]], %[[broadcast_99]])
// CHECK-NEXT:  %[[convert_107:[^ ]+]] = u64[1]{0} convert(%[[xor_49]])
// CHECK-NEXT:  %[[constant_107:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_101:[^ ]+]] = u64[1]{0} broadcast(%[[constant_107]]), dimensions={}
// CHECK-NEXT:  %[[multiply_33:[^ ]+]] = u64[1]{0} multiply(%[[convert_107]], %[[broadcast_101]])
// CHECK-NEXT:  %[[convert_108:[^ ]+]] = u32[1]{0} convert(%[[multiply_33]])
// CHECK-NEXT:  %[[xor_58:[^ ]+]] = u32[1]{0} xor(%[[convert_115]], %[[convert_108]])
// CHECK-NEXT:  %[[broadcast_112:[^ ]+]] = u32[1]{0} broadcast(%[[add_37]]), dimensions={}
// CHECK-NEXT:  %[[xor_59:[^ ]+]] = u32[1]{0} xor(%[[xor_58]], %[[broadcast_112]])
// CHECK-NEXT:  %[[convert_122:[^ ]+]] = u64[1]{0} convert(%[[xor_59]])
// CHECK-NEXT:  %[[constant_121:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_115:[^ ]+]] = u64[1]{0} broadcast(%[[constant_121]]), dimensions={}
// CHECK-NEXT:  %[[multiply_38:[^ ]+]] = u64[1]{0} multiply(%[[convert_122]], %[[broadcast_115]])
// CHECK-NEXT:  %[[constant_122:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_116:[^ ]+]] = u64[1]{0} broadcast(%[[constant_122]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_42:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_38]], %[[broadcast_116]])
// CHECK-NEXT:  %[[convert_124:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_42]])
// CHECK-NEXT:  %[[constant_108:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_102:[^ ]+]] = u64[1]{0} broadcast(%[[constant_108]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_37:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_33]], %[[broadcast_102]])
// CHECK-NEXT:  %[[convert_109:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_37]])
// CHECK-NEXT:  %[[convert_102:[^ ]+]] = u32[1]{0} convert(%[[multiply_31]])
// CHECK-NEXT:  %[[xor_54:[^ ]+]] = u32[1]{0} xor(%[[convert_109]], %[[convert_102]])
// CHECK-NEXT:  %[[broadcast_106:[^ ]+]] = u32[1]{0} broadcast(%[[add_35]]), dimensions={}
// CHECK-NEXT:  %[[xor_55:[^ ]+]] = u32[1]{0} xor(%[[xor_54]], %[[broadcast_106]])
// CHECK-NEXT:  %[[convert_116:[^ ]+]] = u64[1]{0} convert(%[[xor_55]])
// CHECK-NEXT:  %[[constant_115:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_109:[^ ]+]] = u64[1]{0} broadcast(%[[constant_115]]), dimensions={}
// CHECK-NEXT:  %[[multiply_36:[^ ]+]] = u64[1]{0} multiply(%[[convert_116]], %[[broadcast_109]])
// CHECK-NEXT:  %[[convert_117:[^ ]+]] = u32[1]{0} convert(%[[multiply_36]])
// CHECK-NEXT:  %[[xor_60:[^ ]+]] = u32[1]{0} xor(%[[convert_124]], %[[convert_117]])
// CHECK-NEXT:  %[[broadcast_117:[^ ]+]] = u32[1]{0} broadcast(%[[add_38]]), dimensions={}
// CHECK-NEXT:  %[[xor_61:[^ ]+]] = u32[1]{0} xor(%[[xor_60]], %[[broadcast_117]])
// CHECK-NEXT:  %[[convert_125:[^ ]+]] = u64[1]{0} convert(%[[xor_61]])
// CHECK-NEXT:  %[[constant_125:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_119:[^ ]+]] = u64[1]{0} broadcast(%[[constant_125]]), dimensions={}
// CHECK-NEXT:  %[[multiply_39:[^ ]+]] = u64[1]{0} multiply(%[[convert_125]], %[[broadcast_119]])
// CHECK-NEXT:  %[[constant_126:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_120:[^ ]+]] = u64[1]{0} broadcast(%[[constant_126]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_43:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_39]], %[[broadcast_120]])
// CHECK-NEXT:  %[[convert_127:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_43]])
// CHECK-NEXT:  %[[constant_116:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_110:[^ ]+]] = u64[1]{0} broadcast(%[[constant_116]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_40:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_36]], %[[broadcast_110]])
// CHECK-NEXT:  %[[convert_118:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_40]])
// CHECK-NEXT:  %[[convert_111:[^ ]+]] = u32[1]{0} convert(%[[multiply_34]])
// CHECK-NEXT:  %[[xor_56:[^ ]+]] = u32[1]{0} xor(%[[convert_118]], %[[convert_111]])
// CHECK-NEXT:  %[[broadcast_111:[^ ]+]] = u32[1]{0} broadcast(%[[add_36]]), dimensions={}
// CHECK-NEXT:  %[[xor_57:[^ ]+]] = u32[1]{0} xor(%[[xor_56]], %[[broadcast_111]])
// CHECK-NEXT:  %[[convert_119:[^ ]+]] = u64[1]{0} convert(%[[xor_57]])
// CHECK-NEXT:  %[[constant_119:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_113:[^ ]+]] = u64[1]{0} broadcast(%[[constant_119]]), dimensions={}
// CHECK-NEXT:  %[[multiply_37:[^ ]+]] = u64[1]{0} multiply(%[[convert_119]], %[[broadcast_113]])
// CHECK-NEXT:  %[[convert_120:[^ ]+]] = u32[1]{0} convert(%[[multiply_37]])
// CHECK-NEXT:  %[[xor_66:[^ ]+]] = u32[1]{0} xor(%[[convert_127]], %[[convert_120]])
// CHECK-NEXT:  %[[broadcast_124:[^ ]+]] = u32[1]{0} broadcast(%[[add_41]]), dimensions={}
// CHECK-NEXT:  %[[xor_67:[^ ]+]] = u32[1]{0} xor(%[[xor_66]], %[[broadcast_124]])
// CHECK-NEXT:  %[[convert_134:[^ ]+]] = u64[1]{0} convert(%[[xor_67]])
// CHECK-NEXT:  %[[constant_133:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_127:[^ ]+]] = u64[1]{0} broadcast(%[[constant_133]]), dimensions={}
// CHECK-NEXT:  %[[multiply_42:[^ ]+]] = u64[1]{0} multiply(%[[convert_134]], %[[broadcast_127]])
// CHECK-NEXT:  %[[constant_134:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_128:[^ ]+]] = u64[1]{0} broadcast(%[[constant_134]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_46:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_42]], %[[broadcast_128]])
// CHECK-NEXT:  %[[convert_136:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_46]])
// CHECK-NEXT:  %[[constant_120:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_114:[^ ]+]] = u64[1]{0} broadcast(%[[constant_120]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_41:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_37]], %[[broadcast_114]])
// CHECK-NEXT:  %[[convert_121:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_41]])
// CHECK-NEXT:  %[[convert_114:[^ ]+]] = u32[1]{0} convert(%[[multiply_35]])
// CHECK-NEXT:  %[[xor_62:[^ ]+]] = u32[1]{0} xor(%[[convert_121]], %[[convert_114]])
// CHECK-NEXT:  %[[broadcast_118:[^ ]+]] = u32[1]{0} broadcast(%[[add_39]]), dimensions={}
// CHECK-NEXT:  %[[xor_63:[^ ]+]] = u32[1]{0} xor(%[[xor_62]], %[[broadcast_118]])
// CHECK-NEXT:  %[[convert_128:[^ ]+]] = u64[1]{0} convert(%[[xor_63]])
// CHECK-NEXT:  %[[constant_127:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_121:[^ ]+]] = u64[1]{0} broadcast(%[[constant_127]]), dimensions={}
// CHECK-NEXT:  %[[multiply_40:[^ ]+]] = u64[1]{0} multiply(%[[convert_128]], %[[broadcast_121]])
// CHECK-NEXT:  %[[convert_129:[^ ]+]] = u32[1]{0} convert(%[[multiply_40]])
// CHECK-NEXT:  %[[xor_68:[^ ]+]] = u32[1]{0} xor(%[[convert_136]], %[[convert_129]])
// CHECK-NEXT:  %[[broadcast_129:[^ ]+]] = u32[1]{0} broadcast(%[[add_42]]), dimensions={}
// CHECK-NEXT:  %[[xor_69:[^ ]+]] = u32[1]{0} xor(%[[xor_68]], %[[broadcast_129]])
// CHECK-NEXT:  %[[convert_137:[^ ]+]] = u64[1]{0} convert(%[[xor_69]])
// CHECK-NEXT:  %[[constant_137:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_131:[^ ]+]] = u64[1]{0} broadcast(%[[constant_137]]), dimensions={}
// CHECK-NEXT:  %[[multiply_43:[^ ]+]] = u64[1]{0} multiply(%[[convert_137]], %[[broadcast_131]])
// CHECK-NEXT:  %[[constant_138:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_132:[^ ]+]] = u64[1]{0} broadcast(%[[constant_138]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_47:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_43]], %[[broadcast_132]])
// CHECK-NEXT:  %[[convert_139:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_47]])
// CHECK-NEXT:  %[[constant_128:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_122:[^ ]+]] = u64[1]{0} broadcast(%[[constant_128]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_44:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_40]], %[[broadcast_122]])
// CHECK-NEXT:  %[[convert_130:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_44]])
// CHECK-NEXT:  %[[convert_123:[^ ]+]] = u32[1]{0} convert(%[[multiply_38]])
// CHECK-NEXT:  %[[xor_64:[^ ]+]] = u32[1]{0} xor(%[[convert_130]], %[[convert_123]])
// CHECK-NEXT:  %[[broadcast_123:[^ ]+]] = u32[1]{0} broadcast(%[[add_40]]), dimensions={}
// CHECK-NEXT:  %[[xor_65:[^ ]+]] = u32[1]{0} xor(%[[xor_64]], %[[broadcast_123]])
// CHECK-NEXT:  %[[convert_131:[^ ]+]] = u64[1]{0} convert(%[[xor_65]])
// CHECK-NEXT:  %[[constant_131:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_125:[^ ]+]] = u64[1]{0} broadcast(%[[constant_131]]), dimensions={}
// CHECK-NEXT:  %[[multiply_41:[^ ]+]] = u64[1]{0} multiply(%[[convert_131]], %[[broadcast_125]])
// CHECK-NEXT:  %[[convert_132:[^ ]+]] = u32[1]{0} convert(%[[multiply_41]])
// CHECK-NEXT:  %[[xor_74:[^ ]+]] = u32[1]{0} xor(%[[convert_139]], %[[convert_132]])
// CHECK-NEXT:  %[[broadcast_136:[^ ]+]] = u32[1]{0} broadcast(%[[add_45]]), dimensions={}
// CHECK-NEXT:  %[[xor_75:[^ ]+]] = u32[1]{0} xor(%[[xor_74]], %[[broadcast_136]])
// CHECK-NEXT:  %[[convert_146:[^ ]+]] = u64[1]{0} convert(%[[xor_75]])
// CHECK-NEXT:  %[[constant_145:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_139:[^ ]+]] = u64[1]{0} broadcast(%[[constant_145]]), dimensions={}
// CHECK-NEXT:  %[[multiply_46:[^ ]+]] = u64[1]{0} multiply(%[[convert_146]], %[[broadcast_139]])
// CHECK-NEXT:  %[[constant_146:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_140:[^ ]+]] = u64[1]{0} broadcast(%[[constant_146]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_50:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_46]], %[[broadcast_140]])
// CHECK-NEXT:  %[[convert_148:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_50]])
// CHECK-NEXT:  %[[constant_132:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_126:[^ ]+]] = u64[1]{0} broadcast(%[[constant_132]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_45:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_41]], %[[broadcast_126]])
// CHECK-NEXT:  %[[convert_133:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_45]])
// CHECK-NEXT:  %[[convert_126:[^ ]+]] = u32[1]{0} convert(%[[multiply_39]])
// CHECK-NEXT:  %[[xor_70:[^ ]+]] = u32[1]{0} xor(%[[convert_133]], %[[convert_126]])
// CHECK-NEXT:  %[[broadcast_130:[^ ]+]] = u32[1]{0} broadcast(%[[add_43]]), dimensions={}
// CHECK-NEXT:  %[[xor_71:[^ ]+]] = u32[1]{0} xor(%[[xor_70]], %[[broadcast_130]])
// CHECK-NEXT:  %[[convert_140:[^ ]+]] = u64[1]{0} convert(%[[xor_71]])
// CHECK-NEXT:  %[[constant_139:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_133:[^ ]+]] = u64[1]{0} broadcast(%[[constant_139]]), dimensions={}
// CHECK-NEXT:  %[[multiply_44:[^ ]+]] = u64[1]{0} multiply(%[[convert_140]], %[[broadcast_133]])
// CHECK-NEXT:  %[[convert_141:[^ ]+]] = u32[1]{0} convert(%[[multiply_44]])
// CHECK-NEXT:  %[[xor_76:[^ ]+]] = u32[1]{0} xor(%[[convert_148]], %[[convert_141]])
// CHECK-NEXT:  %[[broadcast_141:[^ ]+]] = u32[1]{0} broadcast(%[[add_46]]), dimensions={}
// CHECK-NEXT:  %[[xor_77:[^ ]+]] = u32[1]{0} xor(%[[xor_76]], %[[broadcast_141]])
// CHECK-NEXT:  %[[reshape_15:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_77]])
// CHECK-NEXT:  %[[convert_147:[^ ]+]] = u32[1]{0} convert(%[[multiply_46]])
// CHECK-NEXT:  %[[reshape_16:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_147]])
// CHECK-NEXT:  %[[constant_140:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_134:[^ ]+]] = u64[1]{0} broadcast(%[[constant_140]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_48:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_44]], %[[broadcast_134]])
// CHECK-NEXT:  %[[convert_142:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_48]])
// CHECK-NEXT:  %[[convert_135:[^ ]+]] = u32[1]{0} convert(%[[multiply_42]])
// CHECK-NEXT:  %[[xor_72:[^ ]+]] = u32[1]{0} xor(%[[convert_142]], %[[convert_135]])
// CHECK-NEXT:  %[[broadcast_135:[^ ]+]] = u32[1]{0} broadcast(%[[add_44]]), dimensions={}
// CHECK-NEXT:  %[[xor_73:[^ ]+]] = u32[1]{0} xor(%[[xor_72]], %[[broadcast_135]])
// CHECK-NEXT:  %[[convert_143:[^ ]+]] = u64[1]{0} convert(%[[xor_73]])
// CHECK-NEXT:  %[[constant_143:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_137:[^ ]+]] = u64[1]{0} broadcast(%[[constant_143]]), dimensions={}
// CHECK-NEXT:  %[[multiply_45:[^ ]+]] = u64[1]{0} multiply(%[[convert_143]], %[[broadcast_137]])
// CHECK-NEXT:  %[[constant_144:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_138:[^ ]+]] = u64[1]{0} broadcast(%[[constant_144]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_49:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_45]], %[[broadcast_138]])
// CHECK-NEXT:  %[[convert_145:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_49]])
// CHECK-NEXT:  %[[convert_138:[^ ]+]] = u32[1]{0} convert(%[[multiply_43]])
// CHECK-NEXT:  %[[xor_78:[^ ]+]] = u32[1]{0} xor(%[[convert_145]], %[[convert_138]])
// CHECK-NEXT:  %[[broadcast_142:[^ ]+]] = u32[1]{0} broadcast(%[[add_47]]), dimensions={}
// CHECK-NEXT:  %[[xor_79:[^ ]+]] = u32[1]{0} xor(%[[xor_78]], %[[broadcast_142]])
// CHECK-NEXT:  %[[reshape_17:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_79]])
// CHECK-NEXT:  %[[convert_144:[^ ]+]] = u32[1]{0} convert(%[[multiply_45]])
// CHECK-NEXT:  %[[reshape_18:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_144]])
// CHECK-NEXT:  %[[concatenate_3:[^ ]+]] = u32[1,4]{1,0} concatenate(%[[reshape_15]], %[[reshape_16]], %[[reshape_17]], %[[reshape_18]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_19:[^ ]+]] = u32[4]{0} reshape(%[[concatenate_3]])
// CHECK-NEXT:  %[[slice_7:[^ ]+]] = u32[2]{0} slice(%[[reshape_19]]), slice={[0:2]}
// CHECK-NEXT:  %[[reshape_20:[^ ]+]] = u32[2]{0} reshape(%[[slice_7]])
// CHECK-NEXT:  %[[constant_149:[^ ]+]] = u32[] constant(9)
// CHECK-NEXT:  %[[broadcast_143:[^ ]+]] = u32[2]{0} broadcast(%[[constant_149]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_51:[^ ]+]] = u32[2]{0} shift-right-logical(%[[reshape_20]], %[[broadcast_143]])
// CHECK-NEXT:  %[[convert_149:[^ ]+]] = f32[2]{0} convert(%[[shift_right_logical_51]])
// CHECK-NEXT:  %[[constant_150:[^ ]+]] = f32[] constant(1.1920929e-07)
// CHECK-NEXT:  %[[broadcast_144:[^ ]+]] = f32[2]{0} broadcast(%[[constant_150]]), dimensions={}
// CHECK-NEXT:  %[[multiply_47:[^ ]+]] = f32[2]{0} multiply(%[[convert_149]], %[[broadcast_144]])
// CHECK-NEXT:  %[[constant_78:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  %[[constant_77:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[subtract_1:[^ ]+]] = f32[] subtract(%[[constant_78]], %[[constant_77]])
// CHECK-NEXT:  %[[broadcast_145:[^ ]+]] = f32[2]{0} broadcast(%[[subtract_1]]), dimensions={}
// CHECK-NEXT:  %[[multiply_48:[^ ]+]] = f32[2]{0} multiply(%[[multiply_47]], %[[broadcast_145]])
// CHECK-NEXT:  %[[broadcast_146:[^ ]+]] = f32[2]{0} broadcast(%[[constant_77]]), dimensions={}
// CHECK-NEXT:  %[[add_50:[^ ]+]] = f32[2]{0} add(%[[multiply_48]], %[[broadcast_146]])
// CHECK-NEXT:  %[[slice_9:[^ ]+]] = f32[1]{0} slice(%[[add_50]]), slice={[1:2]}
// CHECK-NEXT:  %[[multiply_49:[^ ]+]] = f32[1]{0} multiply(%[[broadcast_148]], %[[slice_9]])
// CHECK-NEXT:  %[[cosine_1:[^ ]+]] = f32[1]{0} cosine(%[[multiply_49]])
// CHECK-NEXT:  %[[constant_153:[^ ]+]] = f32[] constant(-2)
// CHECK-NEXT:  %[[broadcast_149:[^ ]+]] = f32[1]{0} broadcast(%[[constant_153]]), dimensions={}
// CHECK-NEXT:  %[[slice_8:[^ ]+]] = f32[1]{0} slice(%[[add_50]]), slice={[0:1]}
// CHECK-NEXT:  %[[constant_151:[^ ]+]] = f32[] constant(1e-07)
// CHECK-NEXT:  %[[broadcast_147:[^ ]+]] = f32[1]{0} broadcast(%[[constant_151]]), dimensions={}
// CHECK-NEXT:  %[[maximum_1:[^ ]+]] = f32[1]{0} maximum(%[[slice_8]], %[[broadcast_147]])
// CHECK-NEXT:  %[[log_1:[^ ]+]] = f32[1]{0} log(%[[maximum_1]])
// CHECK-NEXT:  %[[multiply_50:[^ ]+]] = f32[1]{0} multiply(%[[broadcast_149]], %[[log_1]])
// CHECK-NEXT:  %[[sqrt_1:[^ ]+]] = f32[1]{0} sqrt(%[[multiply_50]])
// CHECK-NEXT:  %[[multiply_52:[^ ]+]] = f32[1]{0} multiply(%[[cosine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[a_or_mean_1:[^ ]+]] = f32[] parameter(2)
// CHECK-NEXT:  %[[b_or_sigma_1:[^ ]+]] = f32[] parameter(3)
// CHECK-NEXT:  %[[sine_1:[^ ]+]] = f32[1]{0} sine(%[[multiply_49]])
// CHECK-NEXT:  %[[multiply_51:[^ ]+]] = f32[1]{0} multiply(%[[sine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[reshape_21:[^ ]+]] = f32[] reshape(%[[multiply_51]])
// CHECK-NEXT:  %[[multiply_53:[^ ]+]] = f32[] multiply(%[[b_or_sigma_1]], %[[reshape_21]])
// CHECK-NEXT:  ROOT %[[add_51:[^ ]+]] = f32[] add(%[[a_or_mean_1]], %[[multiply_53]])

// CHECK-LABEL: ENTRY %test_normal
// CHECK-NEXT:  %[[shape:[^ ]+]] = u64[3]{0} constant({8, 4, 2})
// CHECK-NEXT:  %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed", frontend_attributes={_xla_cse_safe_zero_operand="true"}
// CHECK-NEXT:  %[[constant:[^ ]+]] = u64[] constant(3)
// CHECK-NEXT:  %[[constant_1:[^ ]+]] = u64[] constant(11400714819323198485)
// CHECK-NEXT:  %[[multiply:[^ ]+]] = u64[] multiply(%[[constant]], %[[constant_1]])
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply]], %[[constant_2]])
// CHECK-NEXT:  %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[replica_id]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])
// CHECK-NEXT:  %[[rng_get_and_update_state:[^ ]+]] = u64[2]{0} rng-get-and-update-state(), delta=1
// CHECK-NEXT:  %[[mean:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[stdev:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  ROOT %[[call:[^ ]+]] = f32[] call(%[[xor_2]], %[[rng_get_and_update_state]], %[[mean]], %[[stdev]]), to_apply=%[[$rng_1]]

HloModule TestNormalDistribution

ENTRY test_normal {
  mean = f32[] constant(0)
  stdev = f32[] constant(1)
  shape = u64[3] constant({8, 4, 2})
  ROOT result = f32[] rng(mean, stdev, shape), distribution=rng_normal
}

// -----

// CHECK-LABEL: HloModule TestNormalDistribution, entry_computation_layout={()->f32[2,2]{1,0}}

// CHECK:       %[[$rng_1:[^ ]+]]
// CHECK-NEXT:  %[[state_1:[^ ]+]] = u64[2]{0} parameter(1)
// CHECK-NEXT:  %[[slice_5:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_11:[^ ]+]] = u64[] reshape(%[[slice_5]])
// CHECK-NEXT:  %[[convert_77:[^ ]+]] = u32[] convert(%[[reshape_11]])
// CHECK-NEXT:  %[[convert_81:[^ ]+]] = u64[] convert(%[[convert_77]])
// CHECK-NEXT:  %[[constant_80:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_27:[^ ]+]] = u64[] shift-right-logical(%[[reshape_11]], %[[constant_80]])
// CHECK-NEXT:  %[[convert_78:[^ ]+]] = u32[] convert(%[[shift_right_logical_27]])
// CHECK-NEXT:  %[[convert_82:[^ ]+]] = u64[] convert(%[[convert_78]])
// CHECK-NEXT:  %[[constant_82:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_2:[^ ]+]] = u64[] shift-left(%[[convert_82]], %[[constant_82]])
// CHECK-NEXT:  %[[or_2:[^ ]+]] = u64[] or(%[[convert_81]], %[[shift_left_2]])
// CHECK-NEXT:  %[[constant_87:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_28:[^ ]+]] = u64[] add(%[[or_2]], %[[constant_87]])
// CHECK-NEXT:  %[[reshape_13:[^ ]+]] = u64[1]{0} reshape(%[[add_28]])
// CHECK-NEXT:  %[[compare_3:[^ ]+]] = pred[] compare(%[[add_28]], %[[or_2]]), direction=LT
// CHECK-NEXT:  %[[slice_6:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[1:2]}
// CHECK-NEXT:  %[[reshape_12:[^ ]+]] = u64[] reshape(%[[slice_6]])
// CHECK-NEXT:  %[[convert_79:[^ ]+]] = u32[] convert(%[[reshape_12]])
// CHECK-NEXT:  %[[convert_83:[^ ]+]] = u64[] convert(%[[convert_79]])
// CHECK-NEXT:  %[[constant_81:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_28:[^ ]+]] = u64[] shift-right-logical(%[[reshape_12]], %[[constant_81]])
// CHECK-NEXT:  %[[convert_80:[^ ]+]] = u32[] convert(%[[shift_right_logical_28]])
// CHECK-NEXT:  %[[convert_84:[^ ]+]] = u64[] convert(%[[convert_80]])
// CHECK-NEXT:  %[[constant_83:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_3:[^ ]+]] = u64[] shift-left(%[[convert_84]], %[[constant_83]])
// CHECK-NEXT:  %[[or_3:[^ ]+]] = u64[] or(%[[convert_83]], %[[shift_left_3]])
// CHECK-NEXT:  %[[constant_88:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_29:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_88]])
// CHECK-NEXT:  %[[broadcast_83:[^ ]+]] = u64[] broadcast(%[[add_29]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_84:[^ ]+]] = u64[] broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_3:[^ ]+]] = u64[] select(%[[compare_3]], %[[broadcast_83]], %[[broadcast_84]])
// CHECK-NEXT:  %[[reshape_14:[^ ]+]] = u64[1]{0} reshape(%[[select_3]])
// CHECK-NEXT:  %[[concatenate_3:[^ ]+]] = u64[2]{0} concatenate(%[[reshape_13]], %[[reshape_14]]), dimensions={0}
// CHECK-NEXT:  %[[key_1:[^ ]+]] = u64[] parameter(0)
// CHECK-NEXT:  %[[convert_75:[^ ]+]] = u32[] convert(%[[key_1]])
// CHECK-NEXT:  %[[constant_93:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_30:[^ ]+]] = u32[] add(%[[convert_75]], %[[constant_93]])
// CHECK-NEXT:  %[[constant_99:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_32:[^ ]+]] = u32[] add(%[[add_30]], %[[constant_99]])
// CHECK-NEXT:  %[[constant_105:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_34:[^ ]+]] = u32[] add(%[[add_32]], %[[constant_105]])
// CHECK-NEXT:  %[[constant_111:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_36:[^ ]+]] = u32[] add(%[[add_34]], %[[constant_111]])
// CHECK-NEXT:  %[[constant_117:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_38:[^ ]+]] = u32[] add(%[[add_36]], %[[constant_117]])
// CHECK-NEXT:  %[[constant_123:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_40:[^ ]+]] = u32[] add(%[[add_38]], %[[constant_123]])
// CHECK-NEXT:  %[[constant_129:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_42:[^ ]+]] = u32[] add(%[[add_40]], %[[constant_129]])
// CHECK-NEXT:  %[[constant_135:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_44:[^ ]+]] = u32[] add(%[[add_42]], %[[constant_135]])
// CHECK-NEXT:  %[[constant_141:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_46:[^ ]+]] = u32[] add(%[[add_44]], %[[constant_141]])
// CHECK-NEXT:  %[[constant_147:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_48:[^ ]+]] = u32[] add(%[[add_46]], %[[constant_147]])
// CHECK-NEXT:  %[[constant_79:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_26:[^ ]+]] = u64[] shift-right-logical(%[[key_1]], %[[constant_79]])
// CHECK-NEXT:  %[[convert_76:[^ ]+]] = u32[] convert(%[[shift_right_logical_26]])
// CHECK-NEXT:  %[[constant_94:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_31:[^ ]+]] = u32[] add(%[[convert_76]], %[[constant_94]])
// CHECK-NEXT:  %[[constant_100:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_33:[^ ]+]] = u32[] add(%[[add_31]], %[[constant_100]])
// CHECK-NEXT:  %[[constant_106:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_35:[^ ]+]] = u32[] add(%[[add_33]], %[[constant_106]])
// CHECK-NEXT:  %[[constant_112:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_37:[^ ]+]] = u32[] add(%[[add_35]], %[[constant_112]])
// CHECK-NEXT:  %[[constant_118:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_39:[^ ]+]] = u32[] add(%[[add_37]], %[[constant_118]])
// CHECK-NEXT:  %[[constant_124:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_41:[^ ]+]] = u32[] add(%[[add_39]], %[[constant_124]])
// CHECK-NEXT:  %[[constant_130:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_43:[^ ]+]] = u32[] add(%[[add_41]], %[[constant_130]])
// CHECK-NEXT:  %[[constant_136:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_45:[^ ]+]] = u32[] add(%[[add_43]], %[[constant_136]])
// CHECK-NEXT:  %[[constant_142:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_47:[^ ]+]] = u32[] add(%[[add_45]], %[[constant_142]])
// CHECK-NEXT:  %[[constant_148:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_49:[^ ]+]] = u32[] add(%[[add_47]], %[[constant_148]])
// CHECK-NEXT:  %[[a_or_mean_1:[^ ]+]] = f32[] parameter(2)
// CHECK-NEXT:  %[[broadcast_153:[^ ]+]] = f32[2,2]{1,0} broadcast(%[[a_or_mean_1]]), dimensions={}
// CHECK-NEXT:  %[[b_or_sigma_1:[^ ]+]] = f32[] parameter(3)
// CHECK-NEXT:  %[[broadcast_152:[^ ]+]] = f32[2,2]{1,0} broadcast(%[[b_or_sigma_1]]), dimensions={}
// CHECK-NEXT:  %[[constant_152:[^ ]+]] = f32[] constant(6.28318548)
// CHECK-NEXT:  %[[broadcast_150:[^ ]+]] = f32[1,1,2]{2,1,0} broadcast(%[[constant_152]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_77:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[iota_1:[^ ]+]] = u64[1]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[add_26:[^ ]+]] = u64[1]{0} add(%[[broadcast_77]], %[[iota_1]])
// CHECK-NEXT:  %[[convert_85:[^ ]+]] = u32[1]{0} convert(%[[add_26]])
// CHECK-NEXT:  %[[convert_89:[^ ]+]] = u64[1]{0} convert(%[[convert_85]])
// CHECK-NEXT:  %[[constant_89:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_85:[^ ]+]] = u64[1]{0} broadcast(%[[constant_89]]), dimensions={}
// CHECK-NEXT:  %[[multiply_27:[^ ]+]] = u64[1]{0} multiply(%[[convert_89]], %[[broadcast_85]])
// CHECK-NEXT:  %[[constant_90:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_86:[^ ]+]] = u64[1]{0} broadcast(%[[constant_90]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_31:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_27]], %[[broadcast_86]])
// CHECK-NEXT:  %[[convert_91:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_31]])
// CHECK-NEXT:  %[[broadcast_78:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[compare_2:[^ ]+]] = pred[1]{0} compare(%[[add_26]], %[[broadcast_78]]), direction=LT
// CHECK-NEXT:  %[[constant_84:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_27:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_84]])
// CHECK-NEXT:  %[[broadcast_79:[^ ]+]] = u64[1]{0} broadcast(%[[add_27]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_80:[^ ]+]] = u64[1]{0} broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_2:[^ ]+]] = u64[1]{0} select(%[[compare_2]], %[[broadcast_79]], %[[broadcast_80]])
// CHECK-NEXT:  %[[constant_86:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_82:[^ ]+]] = u64[1]{0} broadcast(%[[constant_86]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_30:[^ ]+]] = u64[1]{0} shift-right-logical(%[[select_2]], %[[broadcast_82]])
// CHECK-NEXT:  %[[convert_88:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_30]])
// CHECK-NEXT:  %[[xor_42:[^ ]+]] = u32[1]{0} xor(%[[convert_91]], %[[convert_88]])
// CHECK-NEXT:  %[[broadcast_90:[^ ]+]] = u32[1]{0} broadcast(%[[convert_76]]), dimensions={}
// CHECK-NEXT:  %[[xor_43:[^ ]+]] = u32[1]{0} xor(%[[xor_42]], %[[broadcast_90]])
// CHECK-NEXT:  %[[convert_98:[^ ]+]] = u64[1]{0} convert(%[[xor_43]])
// CHECK-NEXT:  %[[constant_97:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_93:[^ ]+]] = u64[1]{0} broadcast(%[[constant_97]]), dimensions={}
// CHECK-NEXT:  %[[multiply_30:[^ ]+]] = u64[1]{0} multiply(%[[convert_98]], %[[broadcast_93]])
// CHECK-NEXT:  %[[constant_98:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_94:[^ ]+]] = u64[1]{0} broadcast(%[[constant_98]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_34:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_30]], %[[broadcast_94]])
// CHECK-NEXT:  %[[convert_100:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_34]])
// CHECK-NEXT:  %[[convert_87:[^ ]+]] = u32[1]{0} convert(%[[select_2]])
// CHECK-NEXT:  %[[convert_92:[^ ]+]] = u64[1]{0} convert(%[[convert_87]])
// CHECK-NEXT:  %[[constant_91:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_87:[^ ]+]] = u64[1]{0} broadcast(%[[constant_91]]), dimensions={}
// CHECK-NEXT:  %[[multiply_28:[^ ]+]] = u64[1]{0} multiply(%[[convert_92]], %[[broadcast_87]])
// CHECK-NEXT:  %[[convert_93:[^ ]+]] = u32[1]{0} convert(%[[multiply_28]])
// CHECK-NEXT:  %[[xor_44:[^ ]+]] = u32[1]{0} xor(%[[convert_100]], %[[convert_93]])
// CHECK-NEXT:  %[[broadcast_95:[^ ]+]] = u32[1]{0} broadcast(%[[add_30]]), dimensions={}
// CHECK-NEXT:  %[[xor_45:[^ ]+]] = u32[1]{0} xor(%[[xor_44]], %[[broadcast_95]])
// CHECK-NEXT:  %[[convert_101:[^ ]+]] = u64[1]{0} convert(%[[xor_45]])
// CHECK-NEXT:  %[[constant_101:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_97:[^ ]+]] = u64[1]{0} broadcast(%[[constant_101]]), dimensions={}
// CHECK-NEXT:  %[[multiply_31:[^ ]+]] = u64[1]{0} multiply(%[[convert_101]], %[[broadcast_97]])
// CHECK-NEXT:  %[[constant_102:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_98:[^ ]+]] = u64[1]{0} broadcast(%[[constant_102]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_35:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_31]], %[[broadcast_98]])
// CHECK-NEXT:  %[[convert_103:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_35]])
// CHECK-NEXT:  %[[constant_92:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_88:[^ ]+]] = u64[1]{0} broadcast(%[[constant_92]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_32:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_28]], %[[broadcast_88]])
// CHECK-NEXT:  %[[convert_94:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_32]])
// CHECK-NEXT:  %[[constant_85:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_81:[^ ]+]] = u64[1]{0} broadcast(%[[constant_85]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_29:[^ ]+]] = u64[1]{0} shift-right-logical(%[[add_26]], %[[broadcast_81]])
// CHECK-NEXT:  %[[convert_86:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_29]])
// CHECK-NEXT:  %[[xor_40:[^ ]+]] = u32[1]{0} xor(%[[convert_94]], %[[convert_86]])
// CHECK-NEXT:  %[[broadcast_89:[^ ]+]] = u32[1]{0} broadcast(%[[convert_75]]), dimensions={}
// CHECK-NEXT:  %[[xor_41:[^ ]+]] = u32[1]{0} xor(%[[xor_40]], %[[broadcast_89]])
// CHECK-NEXT:  %[[convert_95:[^ ]+]] = u64[1]{0} convert(%[[xor_41]])
// CHECK-NEXT:  %[[constant_95:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_91:[^ ]+]] = u64[1]{0} broadcast(%[[constant_95]]), dimensions={}
// CHECK-NEXT:  %[[multiply_29:[^ ]+]] = u64[1]{0} multiply(%[[convert_95]], %[[broadcast_91]])
// CHECK-NEXT:  %[[convert_96:[^ ]+]] = u32[1]{0} convert(%[[multiply_29]])
// CHECK-NEXT:  %[[xor_50:[^ ]+]] = u32[1]{0} xor(%[[convert_103]], %[[convert_96]])
// CHECK-NEXT:  %[[broadcast_102:[^ ]+]] = u32[1]{0} broadcast(%[[add_33]]), dimensions={}
// CHECK-NEXT:  %[[xor_51:[^ ]+]] = u32[1]{0} xor(%[[xor_50]], %[[broadcast_102]])
// CHECK-NEXT:  %[[convert_110:[^ ]+]] = u64[1]{0} convert(%[[xor_51]])
// CHECK-NEXT:  %[[constant_109:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_105:[^ ]+]] = u64[1]{0} broadcast(%[[constant_109]]), dimensions={}
// CHECK-NEXT:  %[[multiply_34:[^ ]+]] = u64[1]{0} multiply(%[[convert_110]], %[[broadcast_105]])
// CHECK-NEXT:  %[[constant_110:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_106:[^ ]+]] = u64[1]{0} broadcast(%[[constant_110]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_38:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_34]], %[[broadcast_106]])
// CHECK-NEXT:  %[[convert_112:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_38]])
// CHECK-NEXT:  %[[constant_96:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_92:[^ ]+]] = u64[1]{0} broadcast(%[[constant_96]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_33:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_29]], %[[broadcast_92]])
// CHECK-NEXT:  %[[convert_97:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_33]])
// CHECK-NEXT:  %[[convert_90:[^ ]+]] = u32[1]{0} convert(%[[multiply_27]])
// CHECK-NEXT:  %[[xor_46:[^ ]+]] = u32[1]{0} xor(%[[convert_97]], %[[convert_90]])
// CHECK-NEXT:  %[[broadcast_96:[^ ]+]] = u32[1]{0} broadcast(%[[add_31]]), dimensions={}
// CHECK-NEXT:  %[[xor_47:[^ ]+]] = u32[1]{0} xor(%[[xor_46]], %[[broadcast_96]])
// CHECK-NEXT:  %[[convert_104:[^ ]+]] = u64[1]{0} convert(%[[xor_47]])
// CHECK-NEXT:  %[[constant_103:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_99:[^ ]+]] = u64[1]{0} broadcast(%[[constant_103]]), dimensions={}
// CHECK-NEXT:  %[[multiply_32:[^ ]+]] = u64[1]{0} multiply(%[[convert_104]], %[[broadcast_99]])
// CHECK-NEXT:  %[[convert_105:[^ ]+]] = u32[1]{0} convert(%[[multiply_32]])
// CHECK-NEXT:  %[[xor_52:[^ ]+]] = u32[1]{0} xor(%[[convert_112]], %[[convert_105]])
// CHECK-NEXT:  %[[broadcast_107:[^ ]+]] = u32[1]{0} broadcast(%[[add_34]]), dimensions={}
// CHECK-NEXT:  %[[xor_53:[^ ]+]] = u32[1]{0} xor(%[[xor_52]], %[[broadcast_107]])
// CHECK-NEXT:  %[[convert_113:[^ ]+]] = u64[1]{0} convert(%[[xor_53]])
// CHECK-NEXT:  %[[constant_113:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_109:[^ ]+]] = u64[1]{0} broadcast(%[[constant_113]]), dimensions={}
// CHECK-NEXT:  %[[multiply_35:[^ ]+]] = u64[1]{0} multiply(%[[convert_113]], %[[broadcast_109]])
// CHECK-NEXT:  %[[constant_114:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_110:[^ ]+]] = u64[1]{0} broadcast(%[[constant_114]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_39:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_35]], %[[broadcast_110]])
// CHECK-NEXT:  %[[convert_115:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_39]])
// CHECK-NEXT:  %[[constant_104:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_100:[^ ]+]] = u64[1]{0} broadcast(%[[constant_104]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_36:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_32]], %[[broadcast_100]])
// CHECK-NEXT:  %[[convert_106:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_36]])
// CHECK-NEXT:  %[[convert_99:[^ ]+]] = u32[1]{0} convert(%[[multiply_30]])
// CHECK-NEXT:  %[[xor_48:[^ ]+]] = u32[1]{0} xor(%[[convert_106]], %[[convert_99]])
// CHECK-NEXT:  %[[broadcast_101:[^ ]+]] = u32[1]{0} broadcast(%[[add_32]]), dimensions={}
// CHECK-NEXT:  %[[xor_49:[^ ]+]] = u32[1]{0} xor(%[[xor_48]], %[[broadcast_101]])
// CHECK-NEXT:  %[[convert_107:[^ ]+]] = u64[1]{0} convert(%[[xor_49]])
// CHECK-NEXT:  %[[constant_107:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_103:[^ ]+]] = u64[1]{0} broadcast(%[[constant_107]]), dimensions={}
// CHECK-NEXT:  %[[multiply_33:[^ ]+]] = u64[1]{0} multiply(%[[convert_107]], %[[broadcast_103]])
// CHECK-NEXT:  %[[convert_108:[^ ]+]] = u32[1]{0} convert(%[[multiply_33]])
// CHECK-NEXT:  %[[xor_58:[^ ]+]] = u32[1]{0} xor(%[[convert_115]], %[[convert_108]])
// CHECK-NEXT:  %[[broadcast_114:[^ ]+]] = u32[1]{0} broadcast(%[[add_37]]), dimensions={}
// CHECK-NEXT:  %[[xor_59:[^ ]+]] = u32[1]{0} xor(%[[xor_58]], %[[broadcast_114]])
// CHECK-NEXT:  %[[convert_122:[^ ]+]] = u64[1]{0} convert(%[[xor_59]])
// CHECK-NEXT:  %[[constant_121:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_117:[^ ]+]] = u64[1]{0} broadcast(%[[constant_121]]), dimensions={}
// CHECK-NEXT:  %[[multiply_38:[^ ]+]] = u64[1]{0} multiply(%[[convert_122]], %[[broadcast_117]])
// CHECK-NEXT:  %[[constant_122:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_118:[^ ]+]] = u64[1]{0} broadcast(%[[constant_122]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_42:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_38]], %[[broadcast_118]])
// CHECK-NEXT:  %[[convert_124:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_42]])
// CHECK-NEXT:  %[[constant_108:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_104:[^ ]+]] = u64[1]{0} broadcast(%[[constant_108]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_37:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_33]], %[[broadcast_104]])
// CHECK-NEXT:  %[[convert_109:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_37]])
// CHECK-NEXT:  %[[convert_102:[^ ]+]] = u32[1]{0} convert(%[[multiply_31]])
// CHECK-NEXT:  %[[xor_54:[^ ]+]] = u32[1]{0} xor(%[[convert_109]], %[[convert_102]])
// CHECK-NEXT:  %[[broadcast_108:[^ ]+]] = u32[1]{0} broadcast(%[[add_35]]), dimensions={}
// CHECK-NEXT:  %[[xor_55:[^ ]+]] = u32[1]{0} xor(%[[xor_54]], %[[broadcast_108]])
// CHECK-NEXT:  %[[convert_116:[^ ]+]] = u64[1]{0} convert(%[[xor_55]])
// CHECK-NEXT:  %[[constant_115:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_111:[^ ]+]] = u64[1]{0} broadcast(%[[constant_115]]), dimensions={}
// CHECK-NEXT:  %[[multiply_36:[^ ]+]] = u64[1]{0} multiply(%[[convert_116]], %[[broadcast_111]])
// CHECK-NEXT:  %[[convert_117:[^ ]+]] = u32[1]{0} convert(%[[multiply_36]])
// CHECK-NEXT:  %[[xor_60:[^ ]+]] = u32[1]{0} xor(%[[convert_124]], %[[convert_117]])
// CHECK-NEXT:  %[[broadcast_119:[^ ]+]] = u32[1]{0} broadcast(%[[add_38]]), dimensions={}
// CHECK-NEXT:  %[[xor_61:[^ ]+]] = u32[1]{0} xor(%[[xor_60]], %[[broadcast_119]])
// CHECK-NEXT:  %[[convert_125:[^ ]+]] = u64[1]{0} convert(%[[xor_61]])
// CHECK-NEXT:  %[[constant_125:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_121:[^ ]+]] = u64[1]{0} broadcast(%[[constant_125]]), dimensions={}
// CHECK-NEXT:  %[[multiply_39:[^ ]+]] = u64[1]{0} multiply(%[[convert_125]], %[[broadcast_121]])
// CHECK-NEXT:  %[[constant_126:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_122:[^ ]+]] = u64[1]{0} broadcast(%[[constant_126]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_43:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_39]], %[[broadcast_122]])
// CHECK-NEXT:  %[[convert_127:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_43]])
// CHECK-NEXT:  %[[constant_116:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_112:[^ ]+]] = u64[1]{0} broadcast(%[[constant_116]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_40:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_36]], %[[broadcast_112]])
// CHECK-NEXT:  %[[convert_118:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_40]])
// CHECK-NEXT:  %[[convert_111:[^ ]+]] = u32[1]{0} convert(%[[multiply_34]])
// CHECK-NEXT:  %[[xor_56:[^ ]+]] = u32[1]{0} xor(%[[convert_118]], %[[convert_111]])
// CHECK-NEXT:  %[[broadcast_113:[^ ]+]] = u32[1]{0} broadcast(%[[add_36]]), dimensions={}
// CHECK-NEXT:  %[[xor_57:[^ ]+]] = u32[1]{0} xor(%[[xor_56]], %[[broadcast_113]])
// CHECK-NEXT:  %[[convert_119:[^ ]+]] = u64[1]{0} convert(%[[xor_57]])
// CHECK-NEXT:  %[[constant_119:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_115:[^ ]+]] = u64[1]{0} broadcast(%[[constant_119]]), dimensions={}
// CHECK-NEXT:  %[[multiply_37:[^ ]+]] = u64[1]{0} multiply(%[[convert_119]], %[[broadcast_115]])
// CHECK-NEXT:  %[[convert_120:[^ ]+]] = u32[1]{0} convert(%[[multiply_37]])
// CHECK-NEXT:  %[[xor_66:[^ ]+]] = u32[1]{0} xor(%[[convert_127]], %[[convert_120]])
// CHECK-NEXT:  %[[broadcast_126:[^ ]+]] = u32[1]{0} broadcast(%[[add_41]]), dimensions={}
// CHECK-NEXT:  %[[xor_67:[^ ]+]] = u32[1]{0} xor(%[[xor_66]], %[[broadcast_126]])
// CHECK-NEXT:  %[[convert_134:[^ ]+]] = u64[1]{0} convert(%[[xor_67]])
// CHECK-NEXT:  %[[constant_133:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_129:[^ ]+]] = u64[1]{0} broadcast(%[[constant_133]]), dimensions={}
// CHECK-NEXT:  %[[multiply_42:[^ ]+]] = u64[1]{0} multiply(%[[convert_134]], %[[broadcast_129]])
// CHECK-NEXT:  %[[constant_134:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_130:[^ ]+]] = u64[1]{0} broadcast(%[[constant_134]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_46:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_42]], %[[broadcast_130]])
// CHECK-NEXT:  %[[convert_136:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_46]])
// CHECK-NEXT:  %[[constant_120:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_116:[^ ]+]] = u64[1]{0} broadcast(%[[constant_120]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_41:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_37]], %[[broadcast_116]])
// CHECK-NEXT:  %[[convert_121:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_41]])
// CHECK-NEXT:  %[[convert_114:[^ ]+]] = u32[1]{0} convert(%[[multiply_35]])
// CHECK-NEXT:  %[[xor_62:[^ ]+]] = u32[1]{0} xor(%[[convert_121]], %[[convert_114]])
// CHECK-NEXT:  %[[broadcast_120:[^ ]+]] = u32[1]{0} broadcast(%[[add_39]]), dimensions={}
// CHECK-NEXT:  %[[xor_63:[^ ]+]] = u32[1]{0} xor(%[[xor_62]], %[[broadcast_120]])
// CHECK-NEXT:  %[[convert_128:[^ ]+]] = u64[1]{0} convert(%[[xor_63]])
// CHECK-NEXT:  %[[constant_127:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_123:[^ ]+]] = u64[1]{0} broadcast(%[[constant_127]]), dimensions={}
// CHECK-NEXT:  %[[multiply_40:[^ ]+]] = u64[1]{0} multiply(%[[convert_128]], %[[broadcast_123]])
// CHECK-NEXT:  %[[convert_129:[^ ]+]] = u32[1]{0} convert(%[[multiply_40]])
// CHECK-NEXT:  %[[xor_68:[^ ]+]] = u32[1]{0} xor(%[[convert_136]], %[[convert_129]])
// CHECK-NEXT:  %[[broadcast_131:[^ ]+]] = u32[1]{0} broadcast(%[[add_42]]), dimensions={}
// CHECK-NEXT:  %[[xor_69:[^ ]+]] = u32[1]{0} xor(%[[xor_68]], %[[broadcast_131]])
// CHECK-NEXT:  %[[convert_137:[^ ]+]] = u64[1]{0} convert(%[[xor_69]])
// CHECK-NEXT:  %[[constant_137:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_133:[^ ]+]] = u64[1]{0} broadcast(%[[constant_137]]), dimensions={}
// CHECK-NEXT:  %[[multiply_43:[^ ]+]] = u64[1]{0} multiply(%[[convert_137]], %[[broadcast_133]])
// CHECK-NEXT:  %[[constant_138:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_134:[^ ]+]] = u64[1]{0} broadcast(%[[constant_138]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_47:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_43]], %[[broadcast_134]])
// CHECK-NEXT:  %[[convert_139:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_47]])
// CHECK-NEXT:  %[[constant_128:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_124:[^ ]+]] = u64[1]{0} broadcast(%[[constant_128]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_44:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_40]], %[[broadcast_124]])
// CHECK-NEXT:  %[[convert_130:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_44]])
// CHECK-NEXT:  %[[convert_123:[^ ]+]] = u32[1]{0} convert(%[[multiply_38]])
// CHECK-NEXT:  %[[xor_64:[^ ]+]] = u32[1]{0} xor(%[[convert_130]], %[[convert_123]])
// CHECK-NEXT:  %[[broadcast_125:[^ ]+]] = u32[1]{0} broadcast(%[[add_40]]), dimensions={}
// CHECK-NEXT:  %[[xor_65:[^ ]+]] = u32[1]{0} xor(%[[xor_64]], %[[broadcast_125]])
// CHECK-NEXT:  %[[convert_131:[^ ]+]] = u64[1]{0} convert(%[[xor_65]])
// CHECK-NEXT:  %[[constant_131:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_127:[^ ]+]] = u64[1]{0} broadcast(%[[constant_131]]), dimensions={}
// CHECK-NEXT:  %[[multiply_41:[^ ]+]] = u64[1]{0} multiply(%[[convert_131]], %[[broadcast_127]])
// CHECK-NEXT:  %[[convert_132:[^ ]+]] = u32[1]{0} convert(%[[multiply_41]])
// CHECK-NEXT:  %[[xor_74:[^ ]+]] = u32[1]{0} xor(%[[convert_139]], %[[convert_132]])
// CHECK-NEXT:  %[[broadcast_138:[^ ]+]] = u32[1]{0} broadcast(%[[add_45]]), dimensions={}
// CHECK-NEXT:  %[[xor_75:[^ ]+]] = u32[1]{0} xor(%[[xor_74]], %[[broadcast_138]])
// CHECK-NEXT:  %[[convert_146:[^ ]+]] = u64[1]{0} convert(%[[xor_75]])
// CHECK-NEXT:  %[[constant_145:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_141:[^ ]+]] = u64[1]{0} broadcast(%[[constant_145]]), dimensions={}
// CHECK-NEXT:  %[[multiply_46:[^ ]+]] = u64[1]{0} multiply(%[[convert_146]], %[[broadcast_141]])
// CHECK-NEXT:  %[[constant_146:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_142:[^ ]+]] = u64[1]{0} broadcast(%[[constant_146]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_50:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_46]], %[[broadcast_142]])
// CHECK-NEXT:  %[[convert_148:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_50]])
// CHECK-NEXT:  %[[constant_132:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_128:[^ ]+]] = u64[1]{0} broadcast(%[[constant_132]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_45:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_41]], %[[broadcast_128]])
// CHECK-NEXT:  %[[convert_133:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_45]])
// CHECK-NEXT:  %[[convert_126:[^ ]+]] = u32[1]{0} convert(%[[multiply_39]])
// CHECK-NEXT:  %[[xor_70:[^ ]+]] = u32[1]{0} xor(%[[convert_133]], %[[convert_126]])
// CHECK-NEXT:  %[[broadcast_132:[^ ]+]] = u32[1]{0} broadcast(%[[add_43]]), dimensions={}
// CHECK-NEXT:  %[[xor_71:[^ ]+]] = u32[1]{0} xor(%[[xor_70]], %[[broadcast_132]])
// CHECK-NEXT:  %[[convert_140:[^ ]+]] = u64[1]{0} convert(%[[xor_71]])
// CHECK-NEXT:  %[[constant_139:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_135:[^ ]+]] = u64[1]{0} broadcast(%[[constant_139]]), dimensions={}
// CHECK-NEXT:  %[[multiply_44:[^ ]+]] = u64[1]{0} multiply(%[[convert_140]], %[[broadcast_135]])
// CHECK-NEXT:  %[[convert_141:[^ ]+]] = u32[1]{0} convert(%[[multiply_44]])
// CHECK-NEXT:  %[[xor_76:[^ ]+]] = u32[1]{0} xor(%[[convert_148]], %[[convert_141]])
// CHECK-NEXT:  %[[broadcast_143:[^ ]+]] = u32[1]{0} broadcast(%[[add_46]]), dimensions={}
// CHECK-NEXT:  %[[xor_77:[^ ]+]] = u32[1]{0} xor(%[[xor_76]], %[[broadcast_143]])
// CHECK-NEXT:  %[[reshape_15:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_77]])
// CHECK-NEXT:  %[[convert_147:[^ ]+]] = u32[1]{0} convert(%[[multiply_46]])
// CHECK-NEXT:  %[[reshape_16:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_147]])
// CHECK-NEXT:  %[[constant_140:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_136:[^ ]+]] = u64[1]{0} broadcast(%[[constant_140]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_48:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_44]], %[[broadcast_136]])
// CHECK-NEXT:  %[[convert_142:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_48]])
// CHECK-NEXT:  %[[convert_135:[^ ]+]] = u32[1]{0} convert(%[[multiply_42]])
// CHECK-NEXT:  %[[xor_72:[^ ]+]] = u32[1]{0} xor(%[[convert_142]], %[[convert_135]])
// CHECK-NEXT:  %[[broadcast_137:[^ ]+]] = u32[1]{0} broadcast(%[[add_44]]), dimensions={}
// CHECK-NEXT:  %[[xor_73:[^ ]+]] = u32[1]{0} xor(%[[xor_72]], %[[broadcast_137]])
// CHECK-NEXT:  %[[convert_143:[^ ]+]] = u64[1]{0} convert(%[[xor_73]])
// CHECK-NEXT:  %[[constant_143:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_139:[^ ]+]] = u64[1]{0} broadcast(%[[constant_143]]), dimensions={}
// CHECK-NEXT:  %[[multiply_45:[^ ]+]] = u64[1]{0} multiply(%[[convert_143]], %[[broadcast_139]])
// CHECK-NEXT:  %[[constant_144:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_140:[^ ]+]] = u64[1]{0} broadcast(%[[constant_144]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_49:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_45]], %[[broadcast_140]])
// CHECK-NEXT:  %[[convert_145:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_49]])
// CHECK-NEXT:  %[[convert_138:[^ ]+]] = u32[1]{0} convert(%[[multiply_43]])
// CHECK-NEXT:  %[[xor_78:[^ ]+]] = u32[1]{0} xor(%[[convert_145]], %[[convert_138]])
// CHECK-NEXT:  %[[broadcast_144:[^ ]+]] = u32[1]{0} broadcast(%[[add_47]]), dimensions={}
// CHECK-NEXT:  %[[xor_79:[^ ]+]] = u32[1]{0} xor(%[[xor_78]], %[[broadcast_144]])
// CHECK-NEXT:  %[[reshape_17:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_79]])
// CHECK-NEXT:  %[[convert_144:[^ ]+]] = u32[1]{0} convert(%[[multiply_45]])
// CHECK-NEXT:  %[[reshape_18:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_144]])
// CHECK-NEXT:  %[[concatenate_4:[^ ]+]] = u32[1,4]{1,0} concatenate(%[[reshape_15]], %[[reshape_16]], %[[reshape_17]], %[[reshape_18]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_19:[^ ]+]] = u32[4]{0} reshape(%[[concatenate_4]])
// CHECK-NEXT:  %[[slice_7:[^ ]+]] = u32[4]{0} slice(%[[reshape_19]]), slice={[0:4]}
// CHECK-NEXT:  %[[reshape_20:[^ ]+]] = u32[1,2,2]{2,1,0} reshape(%[[slice_7]])
// CHECK-NEXT:  %[[constant_149:[^ ]+]] = u32[] constant(9)
// CHECK-NEXT:  %[[broadcast_145:[^ ]+]] = u32[1,2,2]{2,1,0} broadcast(%[[constant_149]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_51:[^ ]+]] = u32[1,2,2]{2,1,0} shift-right-logical(%[[reshape_20]], %[[broadcast_145]])
// CHECK-NEXT:  %[[convert_149:[^ ]+]] = f32[1,2,2]{2,1,0} convert(%[[shift_right_logical_51]])
// CHECK-NEXT:  %[[constant_150:[^ ]+]] = f32[] constant(1.1920929e-07)
// CHECK-NEXT:  %[[broadcast_146:[^ ]+]] = f32[1,2,2]{2,1,0} broadcast(%[[constant_150]]), dimensions={}
// CHECK-NEXT:  %[[multiply_47:[^ ]+]] = f32[1,2,2]{2,1,0} multiply(%[[convert_149]], %[[broadcast_146]])
// CHECK-NEXT:  %[[constant_78:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  %[[constant_77:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[subtract_1:[^ ]+]] = f32[] subtract(%[[constant_78]], %[[constant_77]])
// CHECK-NEXT:  %[[broadcast_147:[^ ]+]] = f32[1,2,2]{2,1,0} broadcast(%[[subtract_1]]), dimensions={}
// CHECK-NEXT:  %[[multiply_48:[^ ]+]] = f32[1,2,2]{2,1,0} multiply(%[[multiply_47]], %[[broadcast_147]])
// CHECK-NEXT:  %[[broadcast_148:[^ ]+]] = f32[1,2,2]{2,1,0} broadcast(%[[constant_77]]), dimensions={}
// CHECK-NEXT:  %[[add_50:[^ ]+]] = f32[1,2,2]{2,1,0} add(%[[multiply_48]], %[[broadcast_148]])
// CHECK-NEXT:  %[[slice_9:[^ ]+]] = f32[1,1,2]{2,1,0} slice(%[[add_50]]), slice={[0:1], [1:2], [0:2]}
// CHECK-NEXT:  %[[multiply_49:[^ ]+]] = f32[1,1,2]{2,1,0} multiply(%[[broadcast_150]], %[[slice_9]])
// CHECK-NEXT:  %[[sine_1:[^ ]+]] = f32[1,1,2]{2,1,0} sine(%[[multiply_49]])
// CHECK-NEXT:  %[[constant_153:[^ ]+]] = f32[] constant(-2)
// CHECK-NEXT:  %[[broadcast_151:[^ ]+]] = f32[1,1,2]{2,1,0} broadcast(%[[constant_153]]), dimensions={}
// CHECK-NEXT:  %[[slice_8:[^ ]+]] = f32[1,1,2]{2,1,0} slice(%[[add_50]]), slice={[0:1], [0:1], [0:2]}
// CHECK-NEXT:  %[[constant_151:[^ ]+]] = f32[] constant(1e-07)
// CHECK-NEXT:  %[[broadcast_149:[^ ]+]] = f32[1,1,2]{2,1,0} broadcast(%[[constant_151]]), dimensions={}
// CHECK-NEXT:  %[[maximum_1:[^ ]+]] = f32[1,1,2]{2,1,0} maximum(%[[slice_8]], %[[broadcast_149]])
// CHECK-NEXT:  %[[log_1:[^ ]+]] = f32[1,1,2]{2,1,0} log(%[[maximum_1]])
// CHECK-NEXT:  %[[multiply_50:[^ ]+]] = f32[1,1,2]{2,1,0} multiply(%[[broadcast_151]], %[[log_1]])
// CHECK-NEXT:  %[[sqrt_1:[^ ]+]] = f32[1,1,2]{2,1,0} sqrt(%[[multiply_50]])
// CHECK-NEXT:  %[[multiply_51:[^ ]+]] = f32[1,1,2]{2,1,0} multiply(%[[sine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[cosine_1:[^ ]+]] = f32[1,1,2]{2,1,0} cosine(%[[multiply_49]])
// CHECK-NEXT:  %[[multiply_52:[^ ]+]] = f32[1,1,2]{2,1,0} multiply(%[[cosine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[concatenate_5:[^ ]+]] = f32[1,2,2]{2,1,0} concatenate(%[[multiply_51]], %[[multiply_52]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_21:[^ ]+]] = f32[2,2]{1,0} reshape(%[[concatenate_5]])
// CHECK-NEXT:  %[[multiply_53:[^ ]+]] = f32[2,2]{1,0} multiply(%[[broadcast_152]], %[[reshape_21]])
// CHECK-NEXT:  ROOT %[[add_51:[^ ]+]] = f32[2,2]{1,0} add(%[[broadcast_153]], %[[multiply_53]])

// CHECK-LABEL: ENTRY %test_normal_multidim_split
// CHECK-NEXT:  %[[shape:[^ ]+]] = u64[3]{0} constant({8, 4, 2})
// CHECK-NEXT:  %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed", frontend_attributes={_xla_cse_safe_zero_operand="true"}
// CHECK-NEXT:  %[[constant:[^ ]+]] = u64[] constant(3)
// CHECK-NEXT:  %[[constant_1:[^ ]+]] = u64[] constant(11400714819323198485)
// CHECK-NEXT:  %[[multiply:[^ ]+]] = u64[] multiply(%[[constant]], %[[constant_1]])
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply]], %[[constant_2]])
// CHECK-NEXT:  %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[replica_id]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])
// CHECK-NEXT:  %[[rng_get_and_update_state:[^ ]+]] = u64[2]{0} rng-get-and-update-state(), delta=4
// CHECK-NEXT:  %[[mean:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[stdev:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  ROOT %[[call:[^ ]+]] = f32[2,2]{1,0} call(%[[xor_2]], %[[rng_get_and_update_state]], %[[mean]], %[[stdev]]), to_apply=%[[$rng_1]]

HloModule TestNormalDistribution

ENTRY test_normal_multidim_split {
  mean = f32[] constant(0)
  stdev = f32[] constant(1)
  shape = u64[3] constant({8, 4, 2})
  ROOT result = f32[2,2] rng(mean, stdev, shape), distribution=rng_normal
}

// -----

// CHECK-LABEL: HloModule TestNormalDistribution, entry_computation_layout={()->f32[3,5]{1,0}}

// CHECK:       %[[$rng_1:[^ ]+]]
// CHECK-NEXT:  %[[state_1:[^ ]+]] = u64[2]{0} parameter(1)
// CHECK-NEXT:  %[[slice_6:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_11:[^ ]+]] = u64[] reshape(%[[slice_6]])
// CHECK-NEXT:  %[[convert_77:[^ ]+]] = u32[] convert(%[[reshape_11]])
// CHECK-NEXT:  %[[convert_81:[^ ]+]] = u64[] convert(%[[convert_77]])
// CHECK-NEXT:  %[[constant_80:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_27:[^ ]+]] = u64[] shift-right-logical(%[[reshape_11]], %[[constant_80]])
// CHECK-NEXT:  %[[convert_78:[^ ]+]] = u32[] convert(%[[shift_right_logical_27]])
// CHECK-NEXT:  %[[convert_82:[^ ]+]] = u64[] convert(%[[convert_78]])
// CHECK-NEXT:  %[[constant_82:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_2:[^ ]+]] = u64[] shift-left(%[[convert_82]], %[[constant_82]])
// CHECK-NEXT:  %[[or_2:[^ ]+]] = u64[] or(%[[convert_81]], %[[shift_left_2]])
// CHECK-NEXT:  %[[constant_87:[^ ]+]] = u64[] constant(5)
// CHECK-NEXT:  %[[add_28:[^ ]+]] = u64[] add(%[[or_2]], %[[constant_87]])
// CHECK-NEXT:  %[[reshape_13:[^ ]+]] = u64[1]{0} reshape(%[[add_28]])
// CHECK-NEXT:  %[[compare_3:[^ ]+]] = pred[] compare(%[[add_28]], %[[or_2]]), direction=LT
// CHECK-NEXT:  %[[slice_7:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[1:2]}
// CHECK-NEXT:  %[[reshape_12:[^ ]+]] = u64[] reshape(%[[slice_7]])
// CHECK-NEXT:  %[[convert_79:[^ ]+]] = u32[] convert(%[[reshape_12]])
// CHECK-NEXT:  %[[convert_83:[^ ]+]] = u64[] convert(%[[convert_79]])
// CHECK-NEXT:  %[[constant_81:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_28:[^ ]+]] = u64[] shift-right-logical(%[[reshape_12]], %[[constant_81]])
// CHECK-NEXT:  %[[convert_80:[^ ]+]] = u32[] convert(%[[shift_right_logical_28]])
// CHECK-NEXT:  %[[convert_84:[^ ]+]] = u64[] convert(%[[convert_80]])
// CHECK-NEXT:  %[[constant_83:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_3:[^ ]+]] = u64[] shift-left(%[[convert_84]], %[[constant_83]])
// CHECK-NEXT:  %[[or_3:[^ ]+]] = u64[] or(%[[convert_83]], %[[shift_left_3]])
// CHECK-NEXT:  %[[constant_88:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_29:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_88]])
// CHECK-NEXT:  %[[broadcast_83:[^ ]+]] = u64[] broadcast(%[[add_29]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_84:[^ ]+]] = u64[] broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_3:[^ ]+]] = u64[] select(%[[compare_3]], %[[broadcast_83]], %[[broadcast_84]])
// CHECK-NEXT:  %[[reshape_14:[^ ]+]] = u64[1]{0} reshape(%[[select_3]])
// CHECK-NEXT:  %[[concatenate_3:[^ ]+]] = u64[2]{0} concatenate(%[[reshape_13]], %[[reshape_14]]), dimensions={0}
// CHECK-NEXT:  %[[key_1:[^ ]+]] = u64[] parameter(0)
// CHECK-NEXT:  %[[convert_75:[^ ]+]] = u32[] convert(%[[key_1]])
// CHECK-NEXT:  %[[constant_93:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_30:[^ ]+]] = u32[] add(%[[convert_75]], %[[constant_93]])
// CHECK-NEXT:  %[[constant_99:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_32:[^ ]+]] = u32[] add(%[[add_30]], %[[constant_99]])
// CHECK-NEXT:  %[[constant_105:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_34:[^ ]+]] = u32[] add(%[[add_32]], %[[constant_105]])
// CHECK-NEXT:  %[[constant_111:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_36:[^ ]+]] = u32[] add(%[[add_34]], %[[constant_111]])
// CHECK-NEXT:  %[[constant_117:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_38:[^ ]+]] = u32[] add(%[[add_36]], %[[constant_117]])
// CHECK-NEXT:  %[[constant_123:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_40:[^ ]+]] = u32[] add(%[[add_38]], %[[constant_123]])
// CHECK-NEXT:  %[[constant_129:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_42:[^ ]+]] = u32[] add(%[[add_40]], %[[constant_129]])
// CHECK-NEXT:  %[[constant_135:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_44:[^ ]+]] = u32[] add(%[[add_42]], %[[constant_135]])
// CHECK-NEXT:  %[[constant_141:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_46:[^ ]+]] = u32[] add(%[[add_44]], %[[constant_141]])
// CHECK-NEXT:  %[[constant_147:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_48:[^ ]+]] = u32[] add(%[[add_46]], %[[constant_147]])
// CHECK-NEXT:  %[[constant_79:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_26:[^ ]+]] = u64[] shift-right-logical(%[[key_1]], %[[constant_79]])
// CHECK-NEXT:  %[[convert_76:[^ ]+]] = u32[] convert(%[[shift_right_logical_26]])
// CHECK-NEXT:  %[[constant_94:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_31:[^ ]+]] = u32[] add(%[[convert_76]], %[[constant_94]])
// CHECK-NEXT:  %[[constant_100:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_33:[^ ]+]] = u32[] add(%[[add_31]], %[[constant_100]])
// CHECK-NEXT:  %[[constant_106:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_35:[^ ]+]] = u32[] add(%[[add_33]], %[[constant_106]])
// CHECK-NEXT:  %[[constant_112:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_37:[^ ]+]] = u32[] add(%[[add_35]], %[[constant_112]])
// CHECK-NEXT:  %[[constant_118:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_39:[^ ]+]] = u32[] add(%[[add_37]], %[[constant_118]])
// CHECK-NEXT:  %[[constant_124:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_41:[^ ]+]] = u32[] add(%[[add_39]], %[[constant_124]])
// CHECK-NEXT:  %[[constant_130:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_43:[^ ]+]] = u32[] add(%[[add_41]], %[[constant_130]])
// CHECK-NEXT:  %[[constant_136:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_45:[^ ]+]] = u32[] add(%[[add_43]], %[[constant_136]])
// CHECK-NEXT:  %[[constant_142:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_47:[^ ]+]] = u32[] add(%[[add_45]], %[[constant_142]])
// CHECK-NEXT:  %[[constant_148:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_49:[^ ]+]] = u32[] add(%[[add_47]], %[[constant_148]])
// CHECK-NEXT:  %[[a_or_mean_1:[^ ]+]] = f32[] parameter(2)
// CHECK-NEXT:  %[[broadcast_153:[^ ]+]] = f32[3,5]{1,0} broadcast(%[[a_or_mean_1]]), dimensions={}
// CHECK-NEXT:  %[[b_or_sigma_1:[^ ]+]] = f32[] parameter(3)
// CHECK-NEXT:  %[[broadcast_152:[^ ]+]] = f32[3,5]{1,0} broadcast(%[[b_or_sigma_1]]), dimensions={}
// CHECK-NEXT:  %[[constant_152:[^ ]+]] = f32[] constant(6.28318548)
// CHECK-NEXT:  %[[broadcast_150:[^ ]+]] = f32[3,3,1]{2,1,0} broadcast(%[[constant_152]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_77:[^ ]+]] = u64[5]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[iota_1:[^ ]+]] = u64[5]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[add_26:[^ ]+]] = u64[5]{0} add(%[[broadcast_77]], %[[iota_1]])
// CHECK-NEXT:  %[[convert_85:[^ ]+]] = u32[5]{0} convert(%[[add_26]])
// CHECK-NEXT:  %[[convert_89:[^ ]+]] = u64[5]{0} convert(%[[convert_85]])
// CHECK-NEXT:  %[[constant_89:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_85:[^ ]+]] = u64[5]{0} broadcast(%[[constant_89]]), dimensions={}
// CHECK-NEXT:  %[[multiply_27:[^ ]+]] = u64[5]{0} multiply(%[[convert_89]], %[[broadcast_85]])
// CHECK-NEXT:  %[[constant_90:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_86:[^ ]+]] = u64[5]{0} broadcast(%[[constant_90]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_31:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_27]], %[[broadcast_86]])
// CHECK-NEXT:  %[[convert_91:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_31]])
// CHECK-NEXT:  %[[broadcast_78:[^ ]+]] = u64[5]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[compare_2:[^ ]+]] = pred[5]{0} compare(%[[add_26]], %[[broadcast_78]]), direction=LT
// CHECK-NEXT:  %[[constant_84:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_27:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_84]])
// CHECK-NEXT:  %[[broadcast_79:[^ ]+]] = u64[5]{0} broadcast(%[[add_27]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_80:[^ ]+]] = u64[5]{0} broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_2:[^ ]+]] = u64[5]{0} select(%[[compare_2]], %[[broadcast_79]], %[[broadcast_80]])
// CHECK-NEXT:  %[[constant_86:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_82:[^ ]+]] = u64[5]{0} broadcast(%[[constant_86]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_30:[^ ]+]] = u64[5]{0} shift-right-logical(%[[select_2]], %[[broadcast_82]])
// CHECK-NEXT:  %[[convert_88:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_30]])
// CHECK-NEXT:  %[[xor_42:[^ ]+]] = u32[5]{0} xor(%[[convert_91]], %[[convert_88]])
// CHECK-NEXT:  %[[broadcast_90:[^ ]+]] = u32[5]{0} broadcast(%[[convert_76]]), dimensions={}
// CHECK-NEXT:  %[[xor_43:[^ ]+]] = u32[5]{0} xor(%[[xor_42]], %[[broadcast_90]])
// CHECK-NEXT:  %[[convert_98:[^ ]+]] = u64[5]{0} convert(%[[xor_43]])
// CHECK-NEXT:  %[[constant_97:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_93:[^ ]+]] = u64[5]{0} broadcast(%[[constant_97]]), dimensions={}
// CHECK-NEXT:  %[[multiply_30:[^ ]+]] = u64[5]{0} multiply(%[[convert_98]], %[[broadcast_93]])
// CHECK-NEXT:  %[[constant_98:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_94:[^ ]+]] = u64[5]{0} broadcast(%[[constant_98]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_34:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_30]], %[[broadcast_94]])
// CHECK-NEXT:  %[[convert_100:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_34]])
// CHECK-NEXT:  %[[convert_87:[^ ]+]] = u32[5]{0} convert(%[[select_2]])
// CHECK-NEXT:  %[[convert_92:[^ ]+]] = u64[5]{0} convert(%[[convert_87]])
// CHECK-NEXT:  %[[constant_91:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_87:[^ ]+]] = u64[5]{0} broadcast(%[[constant_91]]), dimensions={}
// CHECK-NEXT:  %[[multiply_28:[^ ]+]] = u64[5]{0} multiply(%[[convert_92]], %[[broadcast_87]])
// CHECK-NEXT:  %[[convert_93:[^ ]+]] = u32[5]{0} convert(%[[multiply_28]])
// CHECK-NEXT:  %[[xor_44:[^ ]+]] = u32[5]{0} xor(%[[convert_100]], %[[convert_93]])
// CHECK-NEXT:  %[[broadcast_95:[^ ]+]] = u32[5]{0} broadcast(%[[add_30]]), dimensions={}
// CHECK-NEXT:  %[[xor_45:[^ ]+]] = u32[5]{0} xor(%[[xor_44]], %[[broadcast_95]])
// CHECK-NEXT:  %[[convert_101:[^ ]+]] = u64[5]{0} convert(%[[xor_45]])
// CHECK-NEXT:  %[[constant_101:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_97:[^ ]+]] = u64[5]{0} broadcast(%[[constant_101]]), dimensions={}
// CHECK-NEXT:  %[[multiply_31:[^ ]+]] = u64[5]{0} multiply(%[[convert_101]], %[[broadcast_97]])
// CHECK-NEXT:  %[[constant_102:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_98:[^ ]+]] = u64[5]{0} broadcast(%[[constant_102]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_35:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_31]], %[[broadcast_98]])
// CHECK-NEXT:  %[[convert_103:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_35]])
// CHECK-NEXT:  %[[constant_92:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_88:[^ ]+]] = u64[5]{0} broadcast(%[[constant_92]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_32:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_28]], %[[broadcast_88]])
// CHECK-NEXT:  %[[convert_94:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_32]])
// CHECK-NEXT:  %[[constant_85:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_81:[^ ]+]] = u64[5]{0} broadcast(%[[constant_85]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_29:[^ ]+]] = u64[5]{0} shift-right-logical(%[[add_26]], %[[broadcast_81]])
// CHECK-NEXT:  %[[convert_86:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_29]])
// CHECK-NEXT:  %[[xor_40:[^ ]+]] = u32[5]{0} xor(%[[convert_94]], %[[convert_86]])
// CHECK-NEXT:  %[[broadcast_89:[^ ]+]] = u32[5]{0} broadcast(%[[convert_75]]), dimensions={}
// CHECK-NEXT:  %[[xor_41:[^ ]+]] = u32[5]{0} xor(%[[xor_40]], %[[broadcast_89]])
// CHECK-NEXT:  %[[convert_95:[^ ]+]] = u64[5]{0} convert(%[[xor_41]])
// CHECK-NEXT:  %[[constant_95:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_91:[^ ]+]] = u64[5]{0} broadcast(%[[constant_95]]), dimensions={}
// CHECK-NEXT:  %[[multiply_29:[^ ]+]] = u64[5]{0} multiply(%[[convert_95]], %[[broadcast_91]])
// CHECK-NEXT:  %[[convert_96:[^ ]+]] = u32[5]{0} convert(%[[multiply_29]])
// CHECK-NEXT:  %[[xor_50:[^ ]+]] = u32[5]{0} xor(%[[convert_103]], %[[convert_96]])
// CHECK-NEXT:  %[[broadcast_102:[^ ]+]] = u32[5]{0} broadcast(%[[add_33]]), dimensions={}
// CHECK-NEXT:  %[[xor_51:[^ ]+]] = u32[5]{0} xor(%[[xor_50]], %[[broadcast_102]])
// CHECK-NEXT:  %[[convert_110:[^ ]+]] = u64[5]{0} convert(%[[xor_51]])
// CHECK-NEXT:  %[[constant_109:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_105:[^ ]+]] = u64[5]{0} broadcast(%[[constant_109]]), dimensions={}
// CHECK-NEXT:  %[[multiply_34:[^ ]+]] = u64[5]{0} multiply(%[[convert_110]], %[[broadcast_105]])
// CHECK-NEXT:  %[[constant_110:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_106:[^ ]+]] = u64[5]{0} broadcast(%[[constant_110]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_38:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_34]], %[[broadcast_106]])
// CHECK-NEXT:  %[[convert_112:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_38]])
// CHECK-NEXT:  %[[constant_96:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_92:[^ ]+]] = u64[5]{0} broadcast(%[[constant_96]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_33:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_29]], %[[broadcast_92]])
// CHECK-NEXT:  %[[convert_97:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_33]])
// CHECK-NEXT:  %[[convert_90:[^ ]+]] = u32[5]{0} convert(%[[multiply_27]])
// CHECK-NEXT:  %[[xor_46:[^ ]+]] = u32[5]{0} xor(%[[convert_97]], %[[convert_90]])
// CHECK-NEXT:  %[[broadcast_96:[^ ]+]] = u32[5]{0} broadcast(%[[add_31]]), dimensions={}
// CHECK-NEXT:  %[[xor_47:[^ ]+]] = u32[5]{0} xor(%[[xor_46]], %[[broadcast_96]])
// CHECK-NEXT:  %[[convert_104:[^ ]+]] = u64[5]{0} convert(%[[xor_47]])
// CHECK-NEXT:  %[[constant_103:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_99:[^ ]+]] = u64[5]{0} broadcast(%[[constant_103]]), dimensions={}
// CHECK-NEXT:  %[[multiply_32:[^ ]+]] = u64[5]{0} multiply(%[[convert_104]], %[[broadcast_99]])
// CHECK-NEXT:  %[[convert_105:[^ ]+]] = u32[5]{0} convert(%[[multiply_32]])
// CHECK-NEXT:  %[[xor_52:[^ ]+]] = u32[5]{0} xor(%[[convert_112]], %[[convert_105]])
// CHECK-NEXT:  %[[broadcast_107:[^ ]+]] = u32[5]{0} broadcast(%[[add_34]]), dimensions={}
// CHECK-NEXT:  %[[xor_53:[^ ]+]] = u32[5]{0} xor(%[[xor_52]], %[[broadcast_107]])
// CHECK-NEXT:  %[[convert_113:[^ ]+]] = u64[5]{0} convert(%[[xor_53]])
// CHECK-NEXT:  %[[constant_113:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_109:[^ ]+]] = u64[5]{0} broadcast(%[[constant_113]]), dimensions={}
// CHECK-NEXT:  %[[multiply_35:[^ ]+]] = u64[5]{0} multiply(%[[convert_113]], %[[broadcast_109]])
// CHECK-NEXT:  %[[constant_114:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_110:[^ ]+]] = u64[5]{0} broadcast(%[[constant_114]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_39:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_35]], %[[broadcast_110]])
// CHECK-NEXT:  %[[convert_115:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_39]])
// CHECK-NEXT:  %[[constant_104:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_100:[^ ]+]] = u64[5]{0} broadcast(%[[constant_104]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_36:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_32]], %[[broadcast_100]])
// CHECK-NEXT:  %[[convert_106:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_36]])
// CHECK-NEXT:  %[[convert_99:[^ ]+]] = u32[5]{0} convert(%[[multiply_30]])
// CHECK-NEXT:  %[[xor_48:[^ ]+]] = u32[5]{0} xor(%[[convert_106]], %[[convert_99]])
// CHECK-NEXT:  %[[broadcast_101:[^ ]+]] = u32[5]{0} broadcast(%[[add_32]]), dimensions={}
// CHECK-NEXT:  %[[xor_49:[^ ]+]] = u32[5]{0} xor(%[[xor_48]], %[[broadcast_101]])
// CHECK-NEXT:  %[[convert_107:[^ ]+]] = u64[5]{0} convert(%[[xor_49]])
// CHECK-NEXT:  %[[constant_107:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_103:[^ ]+]] = u64[5]{0} broadcast(%[[constant_107]]), dimensions={}
// CHECK-NEXT:  %[[multiply_33:[^ ]+]] = u64[5]{0} multiply(%[[convert_107]], %[[broadcast_103]])
// CHECK-NEXT:  %[[convert_108:[^ ]+]] = u32[5]{0} convert(%[[multiply_33]])
// CHECK-NEXT:  %[[xor_58:[^ ]+]] = u32[5]{0} xor(%[[convert_115]], %[[convert_108]])
// CHECK-NEXT:  %[[broadcast_114:[^ ]+]] = u32[5]{0} broadcast(%[[add_37]]), dimensions={}
// CHECK-NEXT:  %[[xor_59:[^ ]+]] = u32[5]{0} xor(%[[xor_58]], %[[broadcast_114]])
// CHECK-NEXT:  %[[convert_122:[^ ]+]] = u64[5]{0} convert(%[[xor_59]])
// CHECK-NEXT:  %[[constant_121:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_117:[^ ]+]] = u64[5]{0} broadcast(%[[constant_121]]), dimensions={}
// CHECK-NEXT:  %[[multiply_38:[^ ]+]] = u64[5]{0} multiply(%[[convert_122]], %[[broadcast_117]])
// CHECK-NEXT:  %[[constant_122:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_118:[^ ]+]] = u64[5]{0} broadcast(%[[constant_122]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_42:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_38]], %[[broadcast_118]])
// CHECK-NEXT:  %[[convert_124:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_42]])
// CHECK-NEXT:  %[[constant_108:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_104:[^ ]+]] = u64[5]{0} broadcast(%[[constant_108]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_37:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_33]], %[[broadcast_104]])
// CHECK-NEXT:  %[[convert_109:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_37]])
// CHECK-NEXT:  %[[convert_102:[^ ]+]] = u32[5]{0} convert(%[[multiply_31]])
// CHECK-NEXT:  %[[xor_54:[^ ]+]] = u32[5]{0} xor(%[[convert_109]], %[[convert_102]])
// CHECK-NEXT:  %[[broadcast_108:[^ ]+]] = u32[5]{0} broadcast(%[[add_35]]), dimensions={}
// CHECK-NEXT:  %[[xor_55:[^ ]+]] = u32[5]{0} xor(%[[xor_54]], %[[broadcast_108]])
// CHECK-NEXT:  %[[convert_116:[^ ]+]] = u64[5]{0} convert(%[[xor_55]])
// CHECK-NEXT:  %[[constant_115:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_111:[^ ]+]] = u64[5]{0} broadcast(%[[constant_115]]), dimensions={}
// CHECK-NEXT:  %[[multiply_36:[^ ]+]] = u64[5]{0} multiply(%[[convert_116]], %[[broadcast_111]])
// CHECK-NEXT:  %[[convert_117:[^ ]+]] = u32[5]{0} convert(%[[multiply_36]])
// CHECK-NEXT:  %[[xor_60:[^ ]+]] = u32[5]{0} xor(%[[convert_124]], %[[convert_117]])
// CHECK-NEXT:  %[[broadcast_119:[^ ]+]] = u32[5]{0} broadcast(%[[add_38]]), dimensions={}
// CHECK-NEXT:  %[[xor_61:[^ ]+]] = u32[5]{0} xor(%[[xor_60]], %[[broadcast_119]])
// CHECK-NEXT:  %[[convert_125:[^ ]+]] = u64[5]{0} convert(%[[xor_61]])
// CHECK-NEXT:  %[[constant_125:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_121:[^ ]+]] = u64[5]{0} broadcast(%[[constant_125]]), dimensions={}
// CHECK-NEXT:  %[[multiply_39:[^ ]+]] = u64[5]{0} multiply(%[[convert_125]], %[[broadcast_121]])
// CHECK-NEXT:  %[[constant_126:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_122:[^ ]+]] = u64[5]{0} broadcast(%[[constant_126]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_43:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_39]], %[[broadcast_122]])
// CHECK-NEXT:  %[[convert_127:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_43]])
// CHECK-NEXT:  %[[constant_116:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_112:[^ ]+]] = u64[5]{0} broadcast(%[[constant_116]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_40:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_36]], %[[broadcast_112]])
// CHECK-NEXT:  %[[convert_118:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_40]])
// CHECK-NEXT:  %[[convert_111:[^ ]+]] = u32[5]{0} convert(%[[multiply_34]])
// CHECK-NEXT:  %[[xor_56:[^ ]+]] = u32[5]{0} xor(%[[convert_118]], %[[convert_111]])
// CHECK-NEXT:  %[[broadcast_113:[^ ]+]] = u32[5]{0} broadcast(%[[add_36]]), dimensions={}
// CHECK-NEXT:  %[[xor_57:[^ ]+]] = u32[5]{0} xor(%[[xor_56]], %[[broadcast_113]])
// CHECK-NEXT:  %[[convert_119:[^ ]+]] = u64[5]{0} convert(%[[xor_57]])
// CHECK-NEXT:  %[[constant_119:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_115:[^ ]+]] = u64[5]{0} broadcast(%[[constant_119]]), dimensions={}
// CHECK-NEXT:  %[[multiply_37:[^ ]+]] = u64[5]{0} multiply(%[[convert_119]], %[[broadcast_115]])
// CHECK-NEXT:  %[[convert_120:[^ ]+]] = u32[5]{0} convert(%[[multiply_37]])
// CHECK-NEXT:  %[[xor_66:[^ ]+]] = u32[5]{0} xor(%[[convert_127]], %[[convert_120]])
// CHECK-NEXT:  %[[broadcast_126:[^ ]+]] = u32[5]{0} broadcast(%[[add_41]]), dimensions={}
// CHECK-NEXT:  %[[xor_67:[^ ]+]] = u32[5]{0} xor(%[[xor_66]], %[[broadcast_126]])
// CHECK-NEXT:  %[[convert_134:[^ ]+]] = u64[5]{0} convert(%[[xor_67]])
// CHECK-NEXT:  %[[constant_133:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_129:[^ ]+]] = u64[5]{0} broadcast(%[[constant_133]]), dimensions={}
// CHECK-NEXT:  %[[multiply_42:[^ ]+]] = u64[5]{0} multiply(%[[convert_134]], %[[broadcast_129]])
// CHECK-NEXT:  %[[constant_134:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_130:[^ ]+]] = u64[5]{0} broadcast(%[[constant_134]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_46:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_42]], %[[broadcast_130]])
// CHECK-NEXT:  %[[convert_136:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_46]])
// CHECK-NEXT:  %[[constant_120:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_116:[^ ]+]] = u64[5]{0} broadcast(%[[constant_120]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_41:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_37]], %[[broadcast_116]])
// CHECK-NEXT:  %[[convert_121:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_41]])
// CHECK-NEXT:  %[[convert_114:[^ ]+]] = u32[5]{0} convert(%[[multiply_35]])
// CHECK-NEXT:  %[[xor_62:[^ ]+]] = u32[5]{0} xor(%[[convert_121]], %[[convert_114]])
// CHECK-NEXT:  %[[broadcast_120:[^ ]+]] = u32[5]{0} broadcast(%[[add_39]]), dimensions={}
// CHECK-NEXT:  %[[xor_63:[^ ]+]] = u32[5]{0} xor(%[[xor_62]], %[[broadcast_120]])
// CHECK-NEXT:  %[[convert_128:[^ ]+]] = u64[5]{0} convert(%[[xor_63]])
// CHECK-NEXT:  %[[constant_127:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_123:[^ ]+]] = u64[5]{0} broadcast(%[[constant_127]]), dimensions={}
// CHECK-NEXT:  %[[multiply_40:[^ ]+]] = u64[5]{0} multiply(%[[convert_128]], %[[broadcast_123]])
// CHECK-NEXT:  %[[convert_129:[^ ]+]] = u32[5]{0} convert(%[[multiply_40]])
// CHECK-NEXT:  %[[xor_68:[^ ]+]] = u32[5]{0} xor(%[[convert_136]], %[[convert_129]])
// CHECK-NEXT:  %[[broadcast_131:[^ ]+]] = u32[5]{0} broadcast(%[[add_42]]), dimensions={}
// CHECK-NEXT:  %[[xor_69:[^ ]+]] = u32[5]{0} xor(%[[xor_68]], %[[broadcast_131]])
// CHECK-NEXT:  %[[convert_137:[^ ]+]] = u64[5]{0} convert(%[[xor_69]])
// CHECK-NEXT:  %[[constant_137:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_133:[^ ]+]] = u64[5]{0} broadcast(%[[constant_137]]), dimensions={}
// CHECK-NEXT:  %[[multiply_43:[^ ]+]] = u64[5]{0} multiply(%[[convert_137]], %[[broadcast_133]])
// CHECK-NEXT:  %[[constant_138:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_134:[^ ]+]] = u64[5]{0} broadcast(%[[constant_138]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_47:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_43]], %[[broadcast_134]])
// CHECK-NEXT:  %[[convert_139:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_47]])
// CHECK-NEXT:  %[[constant_128:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_124:[^ ]+]] = u64[5]{0} broadcast(%[[constant_128]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_44:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_40]], %[[broadcast_124]])
// CHECK-NEXT:  %[[convert_130:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_44]])
// CHECK-NEXT:  %[[convert_123:[^ ]+]] = u32[5]{0} convert(%[[multiply_38]])
// CHECK-NEXT:  %[[xor_64:[^ ]+]] = u32[5]{0} xor(%[[convert_130]], %[[convert_123]])
// CHECK-NEXT:  %[[broadcast_125:[^ ]+]] = u32[5]{0} broadcast(%[[add_40]]), dimensions={}
// CHECK-NEXT:  %[[xor_65:[^ ]+]] = u32[5]{0} xor(%[[xor_64]], %[[broadcast_125]])
// CHECK-NEXT:  %[[convert_131:[^ ]+]] = u64[5]{0} convert(%[[xor_65]])
// CHECK-NEXT:  %[[constant_131:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_127:[^ ]+]] = u64[5]{0} broadcast(%[[constant_131]]), dimensions={}
// CHECK-NEXT:  %[[multiply_41:[^ ]+]] = u64[5]{0} multiply(%[[convert_131]], %[[broadcast_127]])
// CHECK-NEXT:  %[[convert_132:[^ ]+]] = u32[5]{0} convert(%[[multiply_41]])
// CHECK-NEXT:  %[[xor_74:[^ ]+]] = u32[5]{0} xor(%[[convert_139]], %[[convert_132]])
// CHECK-NEXT:  %[[broadcast_138:[^ ]+]] = u32[5]{0} broadcast(%[[add_45]]), dimensions={}
// CHECK-NEXT:  %[[xor_75:[^ ]+]] = u32[5]{0} xor(%[[xor_74]], %[[broadcast_138]])
// CHECK-NEXT:  %[[convert_146:[^ ]+]] = u64[5]{0} convert(%[[xor_75]])
// CHECK-NEXT:  %[[constant_145:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_141:[^ ]+]] = u64[5]{0} broadcast(%[[constant_145]]), dimensions={}
// CHECK-NEXT:  %[[multiply_46:[^ ]+]] = u64[5]{0} multiply(%[[convert_146]], %[[broadcast_141]])
// CHECK-NEXT:  %[[constant_146:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_142:[^ ]+]] = u64[5]{0} broadcast(%[[constant_146]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_50:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_46]], %[[broadcast_142]])
// CHECK-NEXT:  %[[convert_148:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_50]])
// CHECK-NEXT:  %[[constant_132:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_128:[^ ]+]] = u64[5]{0} broadcast(%[[constant_132]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_45:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_41]], %[[broadcast_128]])
// CHECK-NEXT:  %[[convert_133:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_45]])
// CHECK-NEXT:  %[[convert_126:[^ ]+]] = u32[5]{0} convert(%[[multiply_39]])
// CHECK-NEXT:  %[[xor_70:[^ ]+]] = u32[5]{0} xor(%[[convert_133]], %[[convert_126]])
// CHECK-NEXT:  %[[broadcast_132:[^ ]+]] = u32[5]{0} broadcast(%[[add_43]]), dimensions={}
// CHECK-NEXT:  %[[xor_71:[^ ]+]] = u32[5]{0} xor(%[[xor_70]], %[[broadcast_132]])
// CHECK-NEXT:  %[[convert_140:[^ ]+]] = u64[5]{0} convert(%[[xor_71]])
// CHECK-NEXT:  %[[constant_139:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_135:[^ ]+]] = u64[5]{0} broadcast(%[[constant_139]]), dimensions={}
// CHECK-NEXT:  %[[multiply_44:[^ ]+]] = u64[5]{0} multiply(%[[convert_140]], %[[broadcast_135]])
// CHECK-NEXT:  %[[convert_141:[^ ]+]] = u32[5]{0} convert(%[[multiply_44]])
// CHECK-NEXT:  %[[xor_76:[^ ]+]] = u32[5]{0} xor(%[[convert_148]], %[[convert_141]])
// CHECK-NEXT:  %[[broadcast_143:[^ ]+]] = u32[5]{0} broadcast(%[[add_46]]), dimensions={}
// CHECK-NEXT:  %[[xor_77:[^ ]+]] = u32[5]{0} xor(%[[xor_76]], %[[broadcast_143]])
// CHECK-NEXT:  %[[reshape_15:[^ ]+]] = u32[5,1]{1,0} reshape(%[[xor_77]])
// CHECK-NEXT:  %[[convert_147:[^ ]+]] = u32[5]{0} convert(%[[multiply_46]])
// CHECK-NEXT:  %[[reshape_16:[^ ]+]] = u32[5,1]{1,0} reshape(%[[convert_147]])
// CHECK-NEXT:  %[[constant_140:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_136:[^ ]+]] = u64[5]{0} broadcast(%[[constant_140]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_48:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_44]], %[[broadcast_136]])
// CHECK-NEXT:  %[[convert_142:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_48]])
// CHECK-NEXT:  %[[convert_135:[^ ]+]] = u32[5]{0} convert(%[[multiply_42]])
// CHECK-NEXT:  %[[xor_72:[^ ]+]] = u32[5]{0} xor(%[[convert_142]], %[[convert_135]])
// CHECK-NEXT:  %[[broadcast_137:[^ ]+]] = u32[5]{0} broadcast(%[[add_44]]), dimensions={}
// CHECK-NEXT:  %[[xor_73:[^ ]+]] = u32[5]{0} xor(%[[xor_72]], %[[broadcast_137]])
// CHECK-NEXT:  %[[convert_143:[^ ]+]] = u64[5]{0} convert(%[[xor_73]])
// CHECK-NEXT:  %[[constant_143:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_139:[^ ]+]] = u64[5]{0} broadcast(%[[constant_143]]), dimensions={}
// CHECK-NEXT:  %[[multiply_45:[^ ]+]] = u64[5]{0} multiply(%[[convert_143]], %[[broadcast_139]])
// CHECK-NEXT:  %[[constant_144:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_140:[^ ]+]] = u64[5]{0} broadcast(%[[constant_144]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_49:[^ ]+]] = u64[5]{0} shift-right-logical(%[[multiply_45]], %[[broadcast_140]])
// CHECK-NEXT:  %[[convert_145:[^ ]+]] = u32[5]{0} convert(%[[shift_right_logical_49]])
// CHECK-NEXT:  %[[convert_138:[^ ]+]] = u32[5]{0} convert(%[[multiply_43]])
// CHECK-NEXT:  %[[xor_78:[^ ]+]] = u32[5]{0} xor(%[[convert_145]], %[[convert_138]])
// CHECK-NEXT:  %[[broadcast_144:[^ ]+]] = u32[5]{0} broadcast(%[[add_47]]), dimensions={}
// CHECK-NEXT:  %[[xor_79:[^ ]+]] = u32[5]{0} xor(%[[xor_78]], %[[broadcast_144]])
// CHECK-NEXT:  %[[reshape_17:[^ ]+]] = u32[5,1]{1,0} reshape(%[[xor_79]])
// CHECK-NEXT:  %[[convert_144:[^ ]+]] = u32[5]{0} convert(%[[multiply_45]])
// CHECK-NEXT:  %[[reshape_18:[^ ]+]] = u32[5,1]{1,0} reshape(%[[convert_144]])
// CHECK-NEXT:  %[[concatenate_4:[^ ]+]] = u32[5,4]{1,0} concatenate(%[[reshape_15]], %[[reshape_16]], %[[reshape_17]], %[[reshape_18]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_19:[^ ]+]] = u32[20]{0} reshape(%[[concatenate_4]])
// CHECK-NEXT:  %[[slice_8:[^ ]+]] = u32[18]{0} slice(%[[reshape_19]]), slice={[0:18]}
// CHECK-NEXT:  %[[reshape_20:[^ ]+]] = u32[3,3,2]{2,1,0} reshape(%[[slice_8]])
// CHECK-NEXT:  %[[constant_149:[^ ]+]] = u32[] constant(9)
// CHECK-NEXT:  %[[broadcast_145:[^ ]+]] = u32[3,3,2]{2,1,0} broadcast(%[[constant_149]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_51:[^ ]+]] = u32[3,3,2]{2,1,0} shift-right-logical(%[[reshape_20]], %[[broadcast_145]])
// CHECK-NEXT:  %[[convert_149:[^ ]+]] = f32[3,3,2]{2,1,0} convert(%[[shift_right_logical_51]])
// CHECK-NEXT:  %[[constant_150:[^ ]+]] = f32[] constant(1.1920929e-07)
// CHECK-NEXT:  %[[broadcast_146:[^ ]+]] = f32[3,3,2]{2,1,0} broadcast(%[[constant_150]]), dimensions={}
// CHECK-NEXT:  %[[multiply_47:[^ ]+]] = f32[3,3,2]{2,1,0} multiply(%[[convert_149]], %[[broadcast_146]])
// CHECK-NEXT:  %[[constant_78:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  %[[constant_77:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[subtract_1:[^ ]+]] = f32[] subtract(%[[constant_78]], %[[constant_77]])
// CHECK-NEXT:  %[[broadcast_147:[^ ]+]] = f32[3,3,2]{2,1,0} broadcast(%[[subtract_1]]), dimensions={}
// CHECK-NEXT:  %[[multiply_48:[^ ]+]] = f32[3,3,2]{2,1,0} multiply(%[[multiply_47]], %[[broadcast_147]])
// CHECK-NEXT:  %[[broadcast_148:[^ ]+]] = f32[3,3,2]{2,1,0} broadcast(%[[constant_77]]), dimensions={}
// CHECK-NEXT:  %[[add_50:[^ ]+]] = f32[3,3,2]{2,1,0} add(%[[multiply_48]], %[[broadcast_148]])
// CHECK-NEXT:  %[[slice_10:[^ ]+]] = f32[3,3,1]{2,1,0} slice(%[[add_50]]), slice={[0:3], [0:3], [1:2]}
// CHECK-NEXT:  %[[multiply_49:[^ ]+]] = f32[3,3,1]{2,1,0} multiply(%[[broadcast_150]], %[[slice_10]])
// CHECK-NEXT:  %[[sine_1:[^ ]+]] = f32[3,3,1]{2,1,0} sine(%[[multiply_49]])
// CHECK-NEXT:  %[[constant_153:[^ ]+]] = f32[] constant(-2)
// CHECK-NEXT:  %[[broadcast_151:[^ ]+]] = f32[3,3,1]{2,1,0} broadcast(%[[constant_153]]), dimensions={}
// CHECK-NEXT:  %[[slice_9:[^ ]+]] = f32[3,3,1]{2,1,0} slice(%[[add_50]]), slice={[0:3], [0:3], [0:1]}
// CHECK-NEXT:  %[[constant_151:[^ ]+]] = f32[] constant(1e-07)
// CHECK-NEXT:  %[[broadcast_149:[^ ]+]] = f32[3,3,1]{2,1,0} broadcast(%[[constant_151]]), dimensions={}
// CHECK-NEXT:  %[[maximum_1:[^ ]+]] = f32[3,3,1]{2,1,0} maximum(%[[slice_9]], %[[broadcast_149]])
// CHECK-NEXT:  %[[log_1:[^ ]+]] = f32[3,3,1]{2,1,0} log(%[[maximum_1]])
// CHECK-NEXT:  %[[multiply_50:[^ ]+]] = f32[3,3,1]{2,1,0} multiply(%[[broadcast_151]], %[[log_1]])
// CHECK-NEXT:  %[[sqrt_1:[^ ]+]] = f32[3,3,1]{2,1,0} sqrt(%[[multiply_50]])
// CHECK-NEXT:  %[[multiply_51:[^ ]+]] = f32[3,3,1]{2,1,0} multiply(%[[sine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[cosine_1:[^ ]+]] = f32[3,3,1]{2,1,0} cosine(%[[multiply_49]])
// CHECK-NEXT:  %[[multiply_52:[^ ]+]] = f32[3,3,1]{2,1,0} multiply(%[[cosine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[concatenate_5:[^ ]+]] = f32[3,3,2]{2,1,0} concatenate(%[[multiply_51]], %[[multiply_52]]), dimensions={2}
// CHECK-NEXT:  %[[reshape_21:[^ ]+]] = f32[3,6]{1,0} reshape(%[[concatenate_5]])
// CHECK-NEXT:  %[[slice_11:[^ ]+]] = f32[3,5]{1,0} slice(%[[reshape_21]]), slice={[0:3], [0:5]}
// CHECK-NEXT:  %[[multiply_53:[^ ]+]] = f32[3,5]{1,0} multiply(%[[broadcast_152]], %[[slice_11]])
// CHECK-NEXT:  ROOT %[[add_51:[^ ]+]] = f32[3,5]{1,0} add(%[[broadcast_153]], %[[multiply_53]])

// CHECK-LABEL: ENTRY %test_normal_multidim_nosplit
// CHECK-NEXT:  %[[shape:[^ ]+]] = u64[3]{0} constant({8, 4, 2})
// CHECK-NEXT:  %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed", frontend_attributes={_xla_cse_safe_zero_operand="true"}
// CHECK-NEXT:  %[[constant:[^ ]+]] = u64[] constant(3)
// CHECK-NEXT:  %[[constant_1:[^ ]+]] = u64[] constant(11400714819323198485)
// CHECK-NEXT:  %[[multiply:[^ ]+]] = u64[] multiply(%[[constant]], %[[constant_1]])
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply]], %[[constant_2]])
// CHECK-NEXT:  %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[replica_id]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])
// CHECK-NEXT:  %[[rng_get_and_update_state:[^ ]+]] = u64[2]{0} rng-get-and-update-state(), delta=15
// CHECK-NEXT:  %[[mean:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[stdev:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  ROOT %[[call:[^ ]+]] = f32[3,5]{1,0} call(%[[xor_2]], %[[rng_get_and_update_state]], %[[mean]], %[[stdev]]), to_apply=%[[$rng_1]]

HloModule TestNormalDistribution

ENTRY test_normal_multidim_nosplit {
  mean = f32[] constant(0)
  stdev = f32[] constant(1)
  shape = u64[3] constant({8, 4, 2})
  ROOT result = f32[3,5] rng(mean, stdev, shape), distribution=rng_normal
}

// -----

// CHECK-LABEL: HloModule TestNormalDistributionSmallFloat, entry_computation_layout={()->f16[]}

// CHECK:       %[[$rng_1:[^ ]+]]
// CHECK-NEXT:  %[[state_1:[^ ]+]] = u64[2]{0} parameter(1)
// CHECK-NEXT:  %[[slice_5:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_11:[^ ]+]] = u64[] reshape(%[[slice_5]])
// CHECK-NEXT:  %[[convert_77:[^ ]+]] = u32[] convert(%[[reshape_11]])
// CHECK-NEXT:  %[[convert_81:[^ ]+]] = u64[] convert(%[[convert_77]])
// CHECK-NEXT:  %[[constant_80:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_27:[^ ]+]] = u64[] shift-right-logical(%[[reshape_11]], %[[constant_80]])
// CHECK-NEXT:  %[[convert_78:[^ ]+]] = u32[] convert(%[[shift_right_logical_27]])
// CHECK-NEXT:  %[[convert_82:[^ ]+]] = u64[] convert(%[[convert_78]])
// CHECK-NEXT:  %[[constant_82:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_2:[^ ]+]] = u64[] shift-left(%[[convert_82]], %[[constant_82]])
// CHECK-NEXT:  %[[or_2:[^ ]+]] = u64[] or(%[[convert_81]], %[[shift_left_2]])
// CHECK-NEXT:  %[[constant_87:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_28:[^ ]+]] = u64[] add(%[[or_2]], %[[constant_87]])
// CHECK-NEXT:  %[[reshape_13:[^ ]+]] = u64[1]{0} reshape(%[[add_28]])
// CHECK-NEXT:  %[[compare_3:[^ ]+]] = pred[] compare(%[[add_28]], %[[or_2]]), direction=LT
// CHECK-NEXT:  %[[slice_6:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[1:2]}
// CHECK-NEXT:  %[[reshape_12:[^ ]+]] = u64[] reshape(%[[slice_6]])
// CHECK-NEXT:  %[[convert_79:[^ ]+]] = u32[] convert(%[[reshape_12]])
// CHECK-NEXT:  %[[convert_83:[^ ]+]] = u64[] convert(%[[convert_79]])
// CHECK-NEXT:  %[[constant_81:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_28:[^ ]+]] = u64[] shift-right-logical(%[[reshape_12]], %[[constant_81]])
// CHECK-NEXT:  %[[convert_80:[^ ]+]] = u32[] convert(%[[shift_right_logical_28]])
// CHECK-NEXT:  %[[convert_84:[^ ]+]] = u64[] convert(%[[convert_80]])
// CHECK-NEXT:  %[[constant_83:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_3:[^ ]+]] = u64[] shift-left(%[[convert_84]], %[[constant_83]])
// CHECK-NEXT:  %[[or_3:[^ ]+]] = u64[] or(%[[convert_83]], %[[shift_left_3]])
// CHECK-NEXT:  %[[constant_88:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_29:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_88]])
// CHECK-NEXT:  %[[broadcast_81:[^ ]+]] = u64[] broadcast(%[[add_29]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_82:[^ ]+]] = u64[] broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_3:[^ ]+]] = u64[] select(%[[compare_3]], %[[broadcast_81]], %[[broadcast_82]])
// CHECK-NEXT:  %[[reshape_14:[^ ]+]] = u64[1]{0} reshape(%[[select_3]])
// CHECK-NEXT:  %[[concatenate_2:[^ ]+]] = u64[2]{0} concatenate(%[[reshape_13]], %[[reshape_14]]), dimensions={0}
// CHECK-NEXT:  %[[key_1:[^ ]+]] = u64[] parameter(0)
// CHECK-NEXT:  %[[convert_75:[^ ]+]] = u32[] convert(%[[key_1]])
// CHECK-NEXT:  %[[constant_93:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_30:[^ ]+]] = u32[] add(%[[convert_75]], %[[constant_93]])
// CHECK-NEXT:  %[[constant_99:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_32:[^ ]+]] = u32[] add(%[[add_30]], %[[constant_99]])
// CHECK-NEXT:  %[[constant_105:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_34:[^ ]+]] = u32[] add(%[[add_32]], %[[constant_105]])
// CHECK-NEXT:  %[[constant_111:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_36:[^ ]+]] = u32[] add(%[[add_34]], %[[constant_111]])
// CHECK-NEXT:  %[[constant_117:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_38:[^ ]+]] = u32[] add(%[[add_36]], %[[constant_117]])
// CHECK-NEXT:  %[[constant_123:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_40:[^ ]+]] = u32[] add(%[[add_38]], %[[constant_123]])
// CHECK-NEXT:  %[[constant_129:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_42:[^ ]+]] = u32[] add(%[[add_40]], %[[constant_129]])
// CHECK-NEXT:  %[[constant_135:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_44:[^ ]+]] = u32[] add(%[[add_42]], %[[constant_135]])
// CHECK-NEXT:  %[[constant_141:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_46:[^ ]+]] = u32[] add(%[[add_44]], %[[constant_141]])
// CHECK-NEXT:  %[[constant_147:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_48:[^ ]+]] = u32[] add(%[[add_46]], %[[constant_147]])
// CHECK-NEXT:  %[[constant_79:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_26:[^ ]+]] = u64[] shift-right-logical(%[[key_1]], %[[constant_79]])
// CHECK-NEXT:  %[[convert_76:[^ ]+]] = u32[] convert(%[[shift_right_logical_26]])
// CHECK-NEXT:  %[[constant_94:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_31:[^ ]+]] = u32[] add(%[[convert_76]], %[[constant_94]])
// CHECK-NEXT:  %[[constant_100:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_33:[^ ]+]] = u32[] add(%[[add_31]], %[[constant_100]])
// CHECK-NEXT:  %[[constant_106:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_35:[^ ]+]] = u32[] add(%[[add_33]], %[[constant_106]])
// CHECK-NEXT:  %[[constant_112:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_37:[^ ]+]] = u32[] add(%[[add_35]], %[[constant_112]])
// CHECK-NEXT:  %[[constant_118:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_39:[^ ]+]] = u32[] add(%[[add_37]], %[[constant_118]])
// CHECK-NEXT:  %[[constant_124:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_41:[^ ]+]] = u32[] add(%[[add_39]], %[[constant_124]])
// CHECK-NEXT:  %[[constant_130:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_43:[^ ]+]] = u32[] add(%[[add_41]], %[[constant_130]])
// CHECK-NEXT:  %[[constant_136:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_45:[^ ]+]] = u32[] add(%[[add_43]], %[[constant_136]])
// CHECK-NEXT:  %[[constant_142:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_47:[^ ]+]] = u32[] add(%[[add_45]], %[[constant_142]])
// CHECK-NEXT:  %[[constant_148:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_49:[^ ]+]] = u32[] add(%[[add_47]], %[[constant_148]])
// CHECK-NEXT:  %[[constant_152:[^ ]+]] = f32[] constant(6.28318548)
// CHECK-NEXT:  %[[broadcast_148:[^ ]+]] = f32[1]{0} broadcast(%[[constant_152]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_75:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[iota_1:[^ ]+]] = u64[1]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[add_26:[^ ]+]] = u64[1]{0} add(%[[broadcast_75]], %[[iota_1]])
// CHECK-NEXT:  %[[convert_85:[^ ]+]] = u32[1]{0} convert(%[[add_26]])
// CHECK-NEXT:  %[[convert_89:[^ ]+]] = u64[1]{0} convert(%[[convert_85]])
// CHECK-NEXT:  %[[constant_89:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_83:[^ ]+]] = u64[1]{0} broadcast(%[[constant_89]]), dimensions={}
// CHECK-NEXT:  %[[multiply_27:[^ ]+]] = u64[1]{0} multiply(%[[convert_89]], %[[broadcast_83]])
// CHECK-NEXT:  %[[constant_90:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_84:[^ ]+]] = u64[1]{0} broadcast(%[[constant_90]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_31:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_27]], %[[broadcast_84]])
// CHECK-NEXT:  %[[convert_91:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_31]])
// CHECK-NEXT:  %[[broadcast_76:[^ ]+]] = u64[1]{0} broadcast(%[[or_2]]), dimensions={}
// CHECK-NEXT:  %[[compare_2:[^ ]+]] = pred[1]{0} compare(%[[add_26]], %[[broadcast_76]]), direction=LT
// CHECK-NEXT:  %[[constant_84:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_27:[^ ]+]] = u64[] add(%[[or_3]], %[[constant_84]])
// CHECK-NEXT:  %[[broadcast_77:[^ ]+]] = u64[1]{0} broadcast(%[[add_27]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_78:[^ ]+]] = u64[1]{0} broadcast(%[[or_3]]), dimensions={}
// CHECK-NEXT:  %[[select_2:[^ ]+]] = u64[1]{0} select(%[[compare_2]], %[[broadcast_77]], %[[broadcast_78]])
// CHECK-NEXT:  %[[constant_86:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_80:[^ ]+]] = u64[1]{0} broadcast(%[[constant_86]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_30:[^ ]+]] = u64[1]{0} shift-right-logical(%[[select_2]], %[[broadcast_80]])
// CHECK-NEXT:  %[[convert_88:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_30]])
// CHECK-NEXT:  %[[xor_42:[^ ]+]] = u32[1]{0} xor(%[[convert_91]], %[[convert_88]])
// CHECK-NEXT:  %[[broadcast_88:[^ ]+]] = u32[1]{0} broadcast(%[[convert_76]]), dimensions={}
// CHECK-NEXT:  %[[xor_43:[^ ]+]] = u32[1]{0} xor(%[[xor_42]], %[[broadcast_88]])
// CHECK-NEXT:  %[[convert_98:[^ ]+]] = u64[1]{0} convert(%[[xor_43]])
// CHECK-NEXT:  %[[constant_97:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_91:[^ ]+]] = u64[1]{0} broadcast(%[[constant_97]]), dimensions={}
// CHECK-NEXT:  %[[multiply_30:[^ ]+]] = u64[1]{0} multiply(%[[convert_98]], %[[broadcast_91]])
// CHECK-NEXT:  %[[constant_98:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_92:[^ ]+]] = u64[1]{0} broadcast(%[[constant_98]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_34:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_30]], %[[broadcast_92]])
// CHECK-NEXT:  %[[convert_100:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_34]])
// CHECK-NEXT:  %[[convert_87:[^ ]+]] = u32[1]{0} convert(%[[select_2]])
// CHECK-NEXT:  %[[convert_92:[^ ]+]] = u64[1]{0} convert(%[[convert_87]])
// CHECK-NEXT:  %[[constant_91:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_85:[^ ]+]] = u64[1]{0} broadcast(%[[constant_91]]), dimensions={}
// CHECK-NEXT:  %[[multiply_28:[^ ]+]] = u64[1]{0} multiply(%[[convert_92]], %[[broadcast_85]])
// CHECK-NEXT:  %[[convert_93:[^ ]+]] = u32[1]{0} convert(%[[multiply_28]])
// CHECK-NEXT:  %[[xor_44:[^ ]+]] = u32[1]{0} xor(%[[convert_100]], %[[convert_93]])
// CHECK-NEXT:  %[[broadcast_93:[^ ]+]] = u32[1]{0} broadcast(%[[add_30]]), dimensions={}
// CHECK-NEXT:  %[[xor_45:[^ ]+]] = u32[1]{0} xor(%[[xor_44]], %[[broadcast_93]])
// CHECK-NEXT:  %[[convert_101:[^ ]+]] = u64[1]{0} convert(%[[xor_45]])
// CHECK-NEXT:  %[[constant_101:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_95:[^ ]+]] = u64[1]{0} broadcast(%[[constant_101]]), dimensions={}
// CHECK-NEXT:  %[[multiply_31:[^ ]+]] = u64[1]{0} multiply(%[[convert_101]], %[[broadcast_95]])
// CHECK-NEXT:  %[[constant_102:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_96:[^ ]+]] = u64[1]{0} broadcast(%[[constant_102]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_35:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_31]], %[[broadcast_96]])
// CHECK-NEXT:  %[[convert_103:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_35]])
// CHECK-NEXT:  %[[constant_92:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_86:[^ ]+]] = u64[1]{0} broadcast(%[[constant_92]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_32:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_28]], %[[broadcast_86]])
// CHECK-NEXT:  %[[convert_94:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_32]])
// CHECK-NEXT:  %[[constant_85:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_79:[^ ]+]] = u64[1]{0} broadcast(%[[constant_85]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_29:[^ ]+]] = u64[1]{0} shift-right-logical(%[[add_26]], %[[broadcast_79]])
// CHECK-NEXT:  %[[convert_86:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_29]])
// CHECK-NEXT:  %[[xor_40:[^ ]+]] = u32[1]{0} xor(%[[convert_94]], %[[convert_86]])
// CHECK-NEXT:  %[[broadcast_87:[^ ]+]] = u32[1]{0} broadcast(%[[convert_75]]), dimensions={}
// CHECK-NEXT:  %[[xor_41:[^ ]+]] = u32[1]{0} xor(%[[xor_40]], %[[broadcast_87]])
// CHECK-NEXT:  %[[convert_95:[^ ]+]] = u64[1]{0} convert(%[[xor_41]])
// CHECK-NEXT:  %[[constant_95:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_89:[^ ]+]] = u64[1]{0} broadcast(%[[constant_95]]), dimensions={}
// CHECK-NEXT:  %[[multiply_29:[^ ]+]] = u64[1]{0} multiply(%[[convert_95]], %[[broadcast_89]])
// CHECK-NEXT:  %[[convert_96:[^ ]+]] = u32[1]{0} convert(%[[multiply_29]])
// CHECK-NEXT:  %[[xor_50:[^ ]+]] = u32[1]{0} xor(%[[convert_103]], %[[convert_96]])
// CHECK-NEXT:  %[[broadcast_100:[^ ]+]] = u32[1]{0} broadcast(%[[add_33]]), dimensions={}
// CHECK-NEXT:  %[[xor_51:[^ ]+]] = u32[1]{0} xor(%[[xor_50]], %[[broadcast_100]])
// CHECK-NEXT:  %[[convert_110:[^ ]+]] = u64[1]{0} convert(%[[xor_51]])
// CHECK-NEXT:  %[[constant_109:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_103:[^ ]+]] = u64[1]{0} broadcast(%[[constant_109]]), dimensions={}
// CHECK-NEXT:  %[[multiply_34:[^ ]+]] = u64[1]{0} multiply(%[[convert_110]], %[[broadcast_103]])
// CHECK-NEXT:  %[[constant_110:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_104:[^ ]+]] = u64[1]{0} broadcast(%[[constant_110]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_38:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_34]], %[[broadcast_104]])
// CHECK-NEXT:  %[[convert_112:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_38]])
// CHECK-NEXT:  %[[constant_96:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_90:[^ ]+]] = u64[1]{0} broadcast(%[[constant_96]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_33:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_29]], %[[broadcast_90]])
// CHECK-NEXT:  %[[convert_97:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_33]])
// CHECK-NEXT:  %[[convert_90:[^ ]+]] = u32[1]{0} convert(%[[multiply_27]])
// CHECK-NEXT:  %[[xor_46:[^ ]+]] = u32[1]{0} xor(%[[convert_97]], %[[convert_90]])
// CHECK-NEXT:  %[[broadcast_94:[^ ]+]] = u32[1]{0} broadcast(%[[add_31]]), dimensions={}
// CHECK-NEXT:  %[[xor_47:[^ ]+]] = u32[1]{0} xor(%[[xor_46]], %[[broadcast_94]])
// CHECK-NEXT:  %[[convert_104:[^ ]+]] = u64[1]{0} convert(%[[xor_47]])
// CHECK-NEXT:  %[[constant_103:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_97:[^ ]+]] = u64[1]{0} broadcast(%[[constant_103]]), dimensions={}
// CHECK-NEXT:  %[[multiply_32:[^ ]+]] = u64[1]{0} multiply(%[[convert_104]], %[[broadcast_97]])
// CHECK-NEXT:  %[[convert_105:[^ ]+]] = u32[1]{0} convert(%[[multiply_32]])
// CHECK-NEXT:  %[[xor_52:[^ ]+]] = u32[1]{0} xor(%[[convert_112]], %[[convert_105]])
// CHECK-NEXT:  %[[broadcast_105:[^ ]+]] = u32[1]{0} broadcast(%[[add_34]]), dimensions={}
// CHECK-NEXT:  %[[xor_53:[^ ]+]] = u32[1]{0} xor(%[[xor_52]], %[[broadcast_105]])
// CHECK-NEXT:  %[[convert_113:[^ ]+]] = u64[1]{0} convert(%[[xor_53]])
// CHECK-NEXT:  %[[constant_113:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_107:[^ ]+]] = u64[1]{0} broadcast(%[[constant_113]]), dimensions={}
// CHECK-NEXT:  %[[multiply_35:[^ ]+]] = u64[1]{0} multiply(%[[convert_113]], %[[broadcast_107]])
// CHECK-NEXT:  %[[constant_114:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_108:[^ ]+]] = u64[1]{0} broadcast(%[[constant_114]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_39:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_35]], %[[broadcast_108]])
// CHECK-NEXT:  %[[convert_115:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_39]])
// CHECK-NEXT:  %[[constant_104:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_98:[^ ]+]] = u64[1]{0} broadcast(%[[constant_104]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_36:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_32]], %[[broadcast_98]])
// CHECK-NEXT:  %[[convert_106:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_36]])
// CHECK-NEXT:  %[[convert_99:[^ ]+]] = u32[1]{0} convert(%[[multiply_30]])
// CHECK-NEXT:  %[[xor_48:[^ ]+]] = u32[1]{0} xor(%[[convert_106]], %[[convert_99]])
// CHECK-NEXT:  %[[broadcast_99:[^ ]+]] = u32[1]{0} broadcast(%[[add_32]]), dimensions={}
// CHECK-NEXT:  %[[xor_49:[^ ]+]] = u32[1]{0} xor(%[[xor_48]], %[[broadcast_99]])
// CHECK-NEXT:  %[[convert_107:[^ ]+]] = u64[1]{0} convert(%[[xor_49]])
// CHECK-NEXT:  %[[constant_107:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_101:[^ ]+]] = u64[1]{0} broadcast(%[[constant_107]]), dimensions={}
// CHECK-NEXT:  %[[multiply_33:[^ ]+]] = u64[1]{0} multiply(%[[convert_107]], %[[broadcast_101]])
// CHECK-NEXT:  %[[convert_108:[^ ]+]] = u32[1]{0} convert(%[[multiply_33]])
// CHECK-NEXT:  %[[xor_58:[^ ]+]] = u32[1]{0} xor(%[[convert_115]], %[[convert_108]])
// CHECK-NEXT:  %[[broadcast_112:[^ ]+]] = u32[1]{0} broadcast(%[[add_37]]), dimensions={}
// CHECK-NEXT:  %[[xor_59:[^ ]+]] = u32[1]{0} xor(%[[xor_58]], %[[broadcast_112]])
// CHECK-NEXT:  %[[convert_122:[^ ]+]] = u64[1]{0} convert(%[[xor_59]])
// CHECK-NEXT:  %[[constant_121:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_115:[^ ]+]] = u64[1]{0} broadcast(%[[constant_121]]), dimensions={}
// CHECK-NEXT:  %[[multiply_38:[^ ]+]] = u64[1]{0} multiply(%[[convert_122]], %[[broadcast_115]])
// CHECK-NEXT:  %[[constant_122:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_116:[^ ]+]] = u64[1]{0} broadcast(%[[constant_122]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_42:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_38]], %[[broadcast_116]])
// CHECK-NEXT:  %[[convert_124:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_42]])
// CHECK-NEXT:  %[[constant_108:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_102:[^ ]+]] = u64[1]{0} broadcast(%[[constant_108]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_37:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_33]], %[[broadcast_102]])
// CHECK-NEXT:  %[[convert_109:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_37]])
// CHECK-NEXT:  %[[convert_102:[^ ]+]] = u32[1]{0} convert(%[[multiply_31]])
// CHECK-NEXT:  %[[xor_54:[^ ]+]] = u32[1]{0} xor(%[[convert_109]], %[[convert_102]])
// CHECK-NEXT:  %[[broadcast_106:[^ ]+]] = u32[1]{0} broadcast(%[[add_35]]), dimensions={}
// CHECK-NEXT:  %[[xor_55:[^ ]+]] = u32[1]{0} xor(%[[xor_54]], %[[broadcast_106]])
// CHECK-NEXT:  %[[convert_116:[^ ]+]] = u64[1]{0} convert(%[[xor_55]])
// CHECK-NEXT:  %[[constant_115:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_109:[^ ]+]] = u64[1]{0} broadcast(%[[constant_115]]), dimensions={}
// CHECK-NEXT:  %[[multiply_36:[^ ]+]] = u64[1]{0} multiply(%[[convert_116]], %[[broadcast_109]])
// CHECK-NEXT:  %[[convert_117:[^ ]+]] = u32[1]{0} convert(%[[multiply_36]])
// CHECK-NEXT:  %[[xor_60:[^ ]+]] = u32[1]{0} xor(%[[convert_124]], %[[convert_117]])
// CHECK-NEXT:  %[[broadcast_117:[^ ]+]] = u32[1]{0} broadcast(%[[add_38]]), dimensions={}
// CHECK-NEXT:  %[[xor_61:[^ ]+]] = u32[1]{0} xor(%[[xor_60]], %[[broadcast_117]])
// CHECK-NEXT:  %[[convert_125:[^ ]+]] = u64[1]{0} convert(%[[xor_61]])
// CHECK-NEXT:  %[[constant_125:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_119:[^ ]+]] = u64[1]{0} broadcast(%[[constant_125]]), dimensions={}
// CHECK-NEXT:  %[[multiply_39:[^ ]+]] = u64[1]{0} multiply(%[[convert_125]], %[[broadcast_119]])
// CHECK-NEXT:  %[[constant_126:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_120:[^ ]+]] = u64[1]{0} broadcast(%[[constant_126]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_43:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_39]], %[[broadcast_120]])
// CHECK-NEXT:  %[[convert_127:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_43]])
// CHECK-NEXT:  %[[constant_116:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_110:[^ ]+]] = u64[1]{0} broadcast(%[[constant_116]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_40:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_36]], %[[broadcast_110]])
// CHECK-NEXT:  %[[convert_118:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_40]])
// CHECK-NEXT:  %[[convert_111:[^ ]+]] = u32[1]{0} convert(%[[multiply_34]])
// CHECK-NEXT:  %[[xor_56:[^ ]+]] = u32[1]{0} xor(%[[convert_118]], %[[convert_111]])
// CHECK-NEXT:  %[[broadcast_111:[^ ]+]] = u32[1]{0} broadcast(%[[add_36]]), dimensions={}
// CHECK-NEXT:  %[[xor_57:[^ ]+]] = u32[1]{0} xor(%[[xor_56]], %[[broadcast_111]])
// CHECK-NEXT:  %[[convert_119:[^ ]+]] = u64[1]{0} convert(%[[xor_57]])
// CHECK-NEXT:  %[[constant_119:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_113:[^ ]+]] = u64[1]{0} broadcast(%[[constant_119]]), dimensions={}
// CHECK-NEXT:  %[[multiply_37:[^ ]+]] = u64[1]{0} multiply(%[[convert_119]], %[[broadcast_113]])
// CHECK-NEXT:  %[[convert_120:[^ ]+]] = u32[1]{0} convert(%[[multiply_37]])
// CHECK-NEXT:  %[[xor_66:[^ ]+]] = u32[1]{0} xor(%[[convert_127]], %[[convert_120]])
// CHECK-NEXT:  %[[broadcast_124:[^ ]+]] = u32[1]{0} broadcast(%[[add_41]]), dimensions={}
// CHECK-NEXT:  %[[xor_67:[^ ]+]] = u32[1]{0} xor(%[[xor_66]], %[[broadcast_124]])
// CHECK-NEXT:  %[[convert_134:[^ ]+]] = u64[1]{0} convert(%[[xor_67]])
// CHECK-NEXT:  %[[constant_133:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_127:[^ ]+]] = u64[1]{0} broadcast(%[[constant_133]]), dimensions={}
// CHECK-NEXT:  %[[multiply_42:[^ ]+]] = u64[1]{0} multiply(%[[convert_134]], %[[broadcast_127]])
// CHECK-NEXT:  %[[constant_134:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_128:[^ ]+]] = u64[1]{0} broadcast(%[[constant_134]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_46:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_42]], %[[broadcast_128]])
// CHECK-NEXT:  %[[convert_136:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_46]])
// CHECK-NEXT:  %[[constant_120:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_114:[^ ]+]] = u64[1]{0} broadcast(%[[constant_120]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_41:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_37]], %[[broadcast_114]])
// CHECK-NEXT:  %[[convert_121:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_41]])
// CHECK-NEXT:  %[[convert_114:[^ ]+]] = u32[1]{0} convert(%[[multiply_35]])
// CHECK-NEXT:  %[[xor_62:[^ ]+]] = u32[1]{0} xor(%[[convert_121]], %[[convert_114]])
// CHECK-NEXT:  %[[broadcast_118:[^ ]+]] = u32[1]{0} broadcast(%[[add_39]]), dimensions={}
// CHECK-NEXT:  %[[xor_63:[^ ]+]] = u32[1]{0} xor(%[[xor_62]], %[[broadcast_118]])
// CHECK-NEXT:  %[[convert_128:[^ ]+]] = u64[1]{0} convert(%[[xor_63]])
// CHECK-NEXT:  %[[constant_127:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_121:[^ ]+]] = u64[1]{0} broadcast(%[[constant_127]]), dimensions={}
// CHECK-NEXT:  %[[multiply_40:[^ ]+]] = u64[1]{0} multiply(%[[convert_128]], %[[broadcast_121]])
// CHECK-NEXT:  %[[convert_129:[^ ]+]] = u32[1]{0} convert(%[[multiply_40]])
// CHECK-NEXT:  %[[xor_68:[^ ]+]] = u32[1]{0} xor(%[[convert_136]], %[[convert_129]])
// CHECK-NEXT:  %[[broadcast_129:[^ ]+]] = u32[1]{0} broadcast(%[[add_42]]), dimensions={}
// CHECK-NEXT:  %[[xor_69:[^ ]+]] = u32[1]{0} xor(%[[xor_68]], %[[broadcast_129]])
// CHECK-NEXT:  %[[convert_137:[^ ]+]] = u64[1]{0} convert(%[[xor_69]])
// CHECK-NEXT:  %[[constant_137:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_131:[^ ]+]] = u64[1]{0} broadcast(%[[constant_137]]), dimensions={}
// CHECK-NEXT:  %[[multiply_43:[^ ]+]] = u64[1]{0} multiply(%[[convert_137]], %[[broadcast_131]])
// CHECK-NEXT:  %[[constant_138:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_132:[^ ]+]] = u64[1]{0} broadcast(%[[constant_138]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_47:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_43]], %[[broadcast_132]])
// CHECK-NEXT:  %[[convert_139:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_47]])
// CHECK-NEXT:  %[[constant_128:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_122:[^ ]+]] = u64[1]{0} broadcast(%[[constant_128]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_44:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_40]], %[[broadcast_122]])
// CHECK-NEXT:  %[[convert_130:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_44]])
// CHECK-NEXT:  %[[convert_123:[^ ]+]] = u32[1]{0} convert(%[[multiply_38]])
// CHECK-NEXT:  %[[xor_64:[^ ]+]] = u32[1]{0} xor(%[[convert_130]], %[[convert_123]])
// CHECK-NEXT:  %[[broadcast_123:[^ ]+]] = u32[1]{0} broadcast(%[[add_40]]), dimensions={}
// CHECK-NEXT:  %[[xor_65:[^ ]+]] = u32[1]{0} xor(%[[xor_64]], %[[broadcast_123]])
// CHECK-NEXT:  %[[convert_131:[^ ]+]] = u64[1]{0} convert(%[[xor_65]])
// CHECK-NEXT:  %[[constant_131:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_125:[^ ]+]] = u64[1]{0} broadcast(%[[constant_131]]), dimensions={}
// CHECK-NEXT:  %[[multiply_41:[^ ]+]] = u64[1]{0} multiply(%[[convert_131]], %[[broadcast_125]])
// CHECK-NEXT:  %[[convert_132:[^ ]+]] = u32[1]{0} convert(%[[multiply_41]])
// CHECK-NEXT:  %[[xor_74:[^ ]+]] = u32[1]{0} xor(%[[convert_139]], %[[convert_132]])
// CHECK-NEXT:  %[[broadcast_136:[^ ]+]] = u32[1]{0} broadcast(%[[add_45]]), dimensions={}
// CHECK-NEXT:  %[[xor_75:[^ ]+]] = u32[1]{0} xor(%[[xor_74]], %[[broadcast_136]])
// CHECK-NEXT:  %[[convert_146:[^ ]+]] = u64[1]{0} convert(%[[xor_75]])
// CHECK-NEXT:  %[[constant_145:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_139:[^ ]+]] = u64[1]{0} broadcast(%[[constant_145]]), dimensions={}
// CHECK-NEXT:  %[[multiply_46:[^ ]+]] = u64[1]{0} multiply(%[[convert_146]], %[[broadcast_139]])
// CHECK-NEXT:  %[[constant_146:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_140:[^ ]+]] = u64[1]{0} broadcast(%[[constant_146]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_50:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_46]], %[[broadcast_140]])
// CHECK-NEXT:  %[[convert_148:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_50]])
// CHECK-NEXT:  %[[constant_132:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_126:[^ ]+]] = u64[1]{0} broadcast(%[[constant_132]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_45:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_41]], %[[broadcast_126]])
// CHECK-NEXT:  %[[convert_133:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_45]])
// CHECK-NEXT:  %[[convert_126:[^ ]+]] = u32[1]{0} convert(%[[multiply_39]])
// CHECK-NEXT:  %[[xor_70:[^ ]+]] = u32[1]{0} xor(%[[convert_133]], %[[convert_126]])
// CHECK-NEXT:  %[[broadcast_130:[^ ]+]] = u32[1]{0} broadcast(%[[add_43]]), dimensions={}
// CHECK-NEXT:  %[[xor_71:[^ ]+]] = u32[1]{0} xor(%[[xor_70]], %[[broadcast_130]])
// CHECK-NEXT:  %[[convert_140:[^ ]+]] = u64[1]{0} convert(%[[xor_71]])
// CHECK-NEXT:  %[[constant_139:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_133:[^ ]+]] = u64[1]{0} broadcast(%[[constant_139]]), dimensions={}
// CHECK-NEXT:  %[[multiply_44:[^ ]+]] = u64[1]{0} multiply(%[[convert_140]], %[[broadcast_133]])
// CHECK-NEXT:  %[[convert_141:[^ ]+]] = u32[1]{0} convert(%[[multiply_44]])
// CHECK-NEXT:  %[[xor_76:[^ ]+]] = u32[1]{0} xor(%[[convert_148]], %[[convert_141]])
// CHECK-NEXT:  %[[broadcast_141:[^ ]+]] = u32[1]{0} broadcast(%[[add_46]]), dimensions={}
// CHECK-NEXT:  %[[xor_77:[^ ]+]] = u32[1]{0} xor(%[[xor_76]], %[[broadcast_141]])
// CHECK-NEXT:  %[[reshape_15:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_77]])
// CHECK-NEXT:  %[[convert_147:[^ ]+]] = u32[1]{0} convert(%[[multiply_46]])
// CHECK-NEXT:  %[[reshape_16:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_147]])
// CHECK-NEXT:  %[[constant_140:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_134:[^ ]+]] = u64[1]{0} broadcast(%[[constant_140]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_48:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_44]], %[[broadcast_134]])
// CHECK-NEXT:  %[[convert_142:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_48]])
// CHECK-NEXT:  %[[convert_135:[^ ]+]] = u32[1]{0} convert(%[[multiply_42]])
// CHECK-NEXT:  %[[xor_72:[^ ]+]] = u32[1]{0} xor(%[[convert_142]], %[[convert_135]])
// CHECK-NEXT:  %[[broadcast_135:[^ ]+]] = u32[1]{0} broadcast(%[[add_44]]), dimensions={}
// CHECK-NEXT:  %[[xor_73:[^ ]+]] = u32[1]{0} xor(%[[xor_72]], %[[broadcast_135]])
// CHECK-NEXT:  %[[convert_143:[^ ]+]] = u64[1]{0} convert(%[[xor_73]])
// CHECK-NEXT:  %[[constant_143:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_137:[^ ]+]] = u64[1]{0} broadcast(%[[constant_143]]), dimensions={}
// CHECK-NEXT:  %[[multiply_45:[^ ]+]] = u64[1]{0} multiply(%[[convert_143]], %[[broadcast_137]])
// CHECK-NEXT:  %[[constant_144:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_138:[^ ]+]] = u64[1]{0} broadcast(%[[constant_144]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_49:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_45]], %[[broadcast_138]])
// CHECK-NEXT:  %[[convert_145:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_49]])
// CHECK-NEXT:  %[[convert_138:[^ ]+]] = u32[1]{0} convert(%[[multiply_43]])
// CHECK-NEXT:  %[[xor_78:[^ ]+]] = u32[1]{0} xor(%[[convert_145]], %[[convert_138]])
// CHECK-NEXT:  %[[broadcast_142:[^ ]+]] = u32[1]{0} broadcast(%[[add_47]]), dimensions={}
// CHECK-NEXT:  %[[xor_79:[^ ]+]] = u32[1]{0} xor(%[[xor_78]], %[[broadcast_142]])
// CHECK-NEXT:  %[[reshape_17:[^ ]+]] = u32[1,1]{1,0} reshape(%[[xor_79]])
// CHECK-NEXT:  %[[convert_144:[^ ]+]] = u32[1]{0} convert(%[[multiply_45]])
// CHECK-NEXT:  %[[reshape_18:[^ ]+]] = u32[1,1]{1,0} reshape(%[[convert_144]])
// CHECK-NEXT:  %[[concatenate_3:[^ ]+]] = u32[1,4]{1,0} concatenate(%[[reshape_15]], %[[reshape_16]], %[[reshape_17]], %[[reshape_18]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_19:[^ ]+]] = u32[4]{0} reshape(%[[concatenate_3]])
// CHECK-NEXT:  %[[slice_7:[^ ]+]] = u32[2]{0} slice(%[[reshape_19]]), slice={[0:2]}
// CHECK-NEXT:  %[[reshape_20:[^ ]+]] = u32[2]{0} reshape(%[[slice_7]])
// CHECK-NEXT:  %[[constant_149:[^ ]+]] = u32[] constant(9)
// CHECK-NEXT:  %[[broadcast_143:[^ ]+]] = u32[2]{0} broadcast(%[[constant_149]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_51:[^ ]+]] = u32[2]{0} shift-right-logical(%[[reshape_20]], %[[broadcast_143]])
// CHECK-NEXT:  %[[convert_149:[^ ]+]] = f32[2]{0} convert(%[[shift_right_logical_51]])
// CHECK-NEXT:  %[[constant_150:[^ ]+]] = f32[] constant(1.1920929e-07)
// CHECK-NEXT:  %[[broadcast_144:[^ ]+]] = f32[2]{0} broadcast(%[[constant_150]]), dimensions={}
// CHECK-NEXT:  %[[multiply_47:[^ ]+]] = f32[2]{0} multiply(%[[convert_149]], %[[broadcast_144]])
// CHECK-NEXT:  %[[constant_78:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  %[[constant_77:[^ ]+]] = f32[] constant(0)
// CHECK-NEXT:  %[[subtract_1:[^ ]+]] = f32[] subtract(%[[constant_78]], %[[constant_77]])
// CHECK-NEXT:  %[[broadcast_145:[^ ]+]] = f32[2]{0} broadcast(%[[subtract_1]]), dimensions={}
// CHECK-NEXT:  %[[multiply_48:[^ ]+]] = f32[2]{0} multiply(%[[multiply_47]], %[[broadcast_145]])
// CHECK-NEXT:  %[[broadcast_146:[^ ]+]] = f32[2]{0} broadcast(%[[constant_77]]), dimensions={}
// CHECK-NEXT:  %[[add_50:[^ ]+]] = f32[2]{0} add(%[[multiply_48]], %[[broadcast_146]])
// CHECK-NEXT:  %[[slice_9:[^ ]+]] = f32[1]{0} slice(%[[add_50]]), slice={[1:2]}
// CHECK-NEXT:  %[[multiply_49:[^ ]+]] = f32[1]{0} multiply(%[[broadcast_148]], %[[slice_9]])
// CHECK-NEXT:  %[[cosine_1:[^ ]+]] = f32[1]{0} cosine(%[[multiply_49]])
// CHECK-NEXT:  %[[constant_153:[^ ]+]] = f32[] constant(-2)
// CHECK-NEXT:  %[[broadcast_149:[^ ]+]] = f32[1]{0} broadcast(%[[constant_153]]), dimensions={}
// CHECK-NEXT:  %[[slice_8:[^ ]+]] = f32[1]{0} slice(%[[add_50]]), slice={[0:1]}
// CHECK-NEXT:  %[[constant_151:[^ ]+]] = f32[] constant(1e-07)
// CHECK-NEXT:  %[[broadcast_147:[^ ]+]] = f32[1]{0} broadcast(%[[constant_151]]), dimensions={}
// CHECK-NEXT:  %[[maximum_1:[^ ]+]] = f32[1]{0} maximum(%[[slice_8]], %[[broadcast_147]])
// CHECK-NEXT:  %[[log_1:[^ ]+]] = f32[1]{0} log(%[[maximum_1]])
// CHECK-NEXT:  %[[multiply_50:[^ ]+]] = f32[1]{0} multiply(%[[broadcast_149]], %[[log_1]])
// CHECK-NEXT:  %[[sqrt_1:[^ ]+]] = f32[1]{0} sqrt(%[[multiply_50]])
// CHECK-NEXT:  %[[multiply_52:[^ ]+]] = f32[1]{0} multiply(%[[cosine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[a_or_mean_1:[^ ]+]] = f32[] parameter(2)
// CHECK-NEXT:  %[[b_or_sigma_1:[^ ]+]] = f32[] parameter(3)
// CHECK-NEXT:  %[[sine_1:[^ ]+]] = f32[1]{0} sine(%[[multiply_49]])
// CHECK-NEXT:  %[[multiply_51:[^ ]+]] = f32[1]{0} multiply(%[[sine_1]], %[[sqrt_1]])
// CHECK-NEXT:  %[[reshape_21:[^ ]+]] = f32[] reshape(%[[multiply_51]])
// CHECK-NEXT:  %[[multiply_53:[^ ]+]] = f32[] multiply(%[[b_or_sigma_1]], %[[reshape_21]])
// CHECK-NEXT:  ROOT %[[add_51:[^ ]+]] = f32[] add(%[[a_or_mean_1]], %[[multiply_53]])

// CHECK-LABEL: ENTRY %test_normal_small_float
// CHECK-NEXT:  %[[shape:[^ ]+]] = f16[3]{0} constant({8, 4, 2})
// CHECK-NEXT:  %[[convert_2:[^ ]+]] = f32[3]{0} convert(%[[shape]])
// CHECK-NEXT:  %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed", frontend_attributes={_xla_cse_safe_zero_operand="true"}
// CHECK-NEXT:  %[[constant:[^ ]+]] = u64[] constant(7)
// CHECK-NEXT:  %[[constant_1:[^ ]+]] = u64[] constant(11400714819323198485)
// CHECK-NEXT:  %[[multiply:[^ ]+]] = u64[] multiply(%[[constant]], %[[constant_1]])
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply]], %[[constant_2]])
// CHECK-NEXT:  %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[replica_id]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])
// CHECK-NEXT:  %[[rng_get_and_update_state:[^ ]+]] = u64[2]{0} rng-get-and-update-state(), delta=1
// CHECK-NEXT:  %[[mean:[^ ]+]] = f16[] constant(0)
// CHECK-NEXT:  %[[convert:[^ ]+]] = f32[] convert(%[[mean]])
// CHECK-NEXT:  %[[stdev:[^ ]+]] = f16[] constant(1)
// CHECK-NEXT:  %[[convert_1:[^ ]+]] = f32[] convert(%[[stdev]])
// CHECK-NEXT:  %[[call:[^ ]+]] = f32[] call(%[[xor_2]], %[[rng_get_and_update_state]], %[[convert]], %[[convert_1]]), to_apply=%[[$rng_1]]
// CHECK-NEXT:  ROOT %[[convert_3:[^ ]+]] = f16[] convert(%[[call]])

HloModule TestNormalDistributionSmallFloat

ENTRY test_normal_small_float {
  mean = f16[] constant(0)
  stdev = f16[] constant(1)
  shape = f16[3] constant({8, 4, 2})
  ROOT result = f16[] rng(mean, stdev, shape), distribution=rng_normal
}

// -----

// CHECK-LABEL: HloModule TestUniformDistributionInt, entry_computation_layout={()->u64[]}

// CHECK:       %[[$rng_1:[^ ]+]]
// CHECK-NEXT:  %[[state_1:[^ ]+]] = u64[2]{0} parameter(1)
// CHECK-NEXT:  %[[slice_3:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_8:[^ ]+]] = u64[] reshape(%[[slice_3]])
// CHECK-NEXT:  %[[convert_80:[^ ]+]] = u32[] convert(%[[reshape_8]])
// CHECK-NEXT:  %[[convert_84:[^ ]+]] = u64[] convert(%[[convert_80]])
// CHECK-NEXT:  %[[constant_74:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_27:[^ ]+]] = u64[] shift-right-logical(%[[reshape_8]], %[[constant_74]])
// CHECK-NEXT:  %[[convert_81:[^ ]+]] = u32[] convert(%[[shift_right_logical_27]])
// CHECK-NEXT:  %[[convert_85:[^ ]+]] = u64[] convert(%[[convert_81]])
// CHECK-NEXT:  %[[constant_76:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_4:[^ ]+]] = u64[] shift-left(%[[convert_85]], %[[constant_76]])
// CHECK-NEXT:  %[[or_4:[^ ]+]] = u64[] or(%[[convert_84]], %[[shift_left_4]])
// CHECK-NEXT:  %[[constant_81:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_28:[^ ]+]] = u64[] add(%[[or_4]], %[[constant_81]])
// CHECK-NEXT:  %[[reshape_10:[^ ]+]] = u64[1]{0} reshape(%[[add_28]])
// CHECK-NEXT:  %[[compare_3:[^ ]+]] = pred[] compare(%[[add_28]], %[[or_4]]), direction=LT
// CHECK-NEXT:  %[[slice_4:[^ ]+]] = u64[1]{0} slice(%[[state_1]]), slice={[1:2]}
// CHECK-NEXT:  %[[reshape_9:[^ ]+]] = u64[] reshape(%[[slice_4]])
// CHECK-NEXT:  %[[convert_82:[^ ]+]] = u32[] convert(%[[reshape_9]])
// CHECK-NEXT:  %[[convert_86:[^ ]+]] = u64[] convert(%[[convert_82]])
// CHECK-NEXT:  %[[constant_75:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_28:[^ ]+]] = u64[] shift-right-logical(%[[reshape_9]], %[[constant_75]])
// CHECK-NEXT:  %[[convert_83:[^ ]+]] = u32[] convert(%[[shift_right_logical_28]])
// CHECK-NEXT:  %[[convert_87:[^ ]+]] = u64[] convert(%[[convert_83]])
// CHECK-NEXT:  %[[constant_77:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_left_5:[^ ]+]] = u64[] shift-left(%[[convert_87]], %[[constant_77]])
// CHECK-NEXT:  %[[or_5:[^ ]+]] = u64[] or(%[[convert_86]], %[[shift_left_5]])
// CHECK-NEXT:  %[[constant_82:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_29:[^ ]+]] = u64[] add(%[[or_5]], %[[constant_82]])
// CHECK-NEXT:  %[[broadcast_76:[^ ]+]] = u64[] broadcast(%[[add_29]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_77:[^ ]+]] = u64[] broadcast(%[[or_5]]), dimensions={}
// CHECK-NEXT:  %[[select_3:[^ ]+]] = u64[] select(%[[compare_3]], %[[broadcast_76]], %[[broadcast_77]])
// CHECK-NEXT:  %[[reshape_11:[^ ]+]] = u64[1]{0} reshape(%[[select_3]])
// CHECK-NEXT:  %[[concatenate_2:[^ ]+]] = u64[2]{0} concatenate(%[[reshape_10]], %[[reshape_11]]), dimensions={0}
// CHECK-NEXT:  %[[key_1:[^ ]+]] = u64[] parameter(0)
// CHECK-NEXT:  %[[convert_78:[^ ]+]] = u32[] convert(%[[key_1]])
// CHECK-NEXT:  %[[constant_87:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_30:[^ ]+]] = u32[] add(%[[convert_78]], %[[constant_87]])
// CHECK-NEXT:  %[[constant_93:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_32:[^ ]+]] = u32[] add(%[[add_30]], %[[constant_93]])
// CHECK-NEXT:  %[[constant_99:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_34:[^ ]+]] = u32[] add(%[[add_32]], %[[constant_99]])
// CHECK-NEXT:  %[[constant_105:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_36:[^ ]+]] = u32[] add(%[[add_34]], %[[constant_105]])
// CHECK-NEXT:  %[[constant_111:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_38:[^ ]+]] = u32[] add(%[[add_36]], %[[constant_111]])
// CHECK-NEXT:  %[[constant_117:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_40:[^ ]+]] = u32[] add(%[[add_38]], %[[constant_117]])
// CHECK-NEXT:  %[[constant_123:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_42:[^ ]+]] = u32[] add(%[[add_40]], %[[constant_123]])
// CHECK-NEXT:  %[[constant_129:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_44:[^ ]+]] = u32[] add(%[[add_42]], %[[constant_129]])
// CHECK-NEXT:  %[[constant_135:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_46:[^ ]+]] = u32[] add(%[[add_44]], %[[constant_135]])
// CHECK-NEXT:  %[[constant_141:[^ ]+]] = u32[] constant(2654435769)
// CHECK-NEXT:  %[[add_48:[^ ]+]] = u32[] add(%[[add_46]], %[[constant_141]])
// CHECK-NEXT:  %[[constant_73:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical_26:[^ ]+]] = u64[] shift-right-logical(%[[key_1]], %[[constant_73]])
// CHECK-NEXT:  %[[convert_79:[^ ]+]] = u32[] convert(%[[shift_right_logical_26]])
// CHECK-NEXT:  %[[constant_88:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_31:[^ ]+]] = u32[] add(%[[convert_79]], %[[constant_88]])
// CHECK-NEXT:  %[[constant_94:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_33:[^ ]+]] = u32[] add(%[[add_31]], %[[constant_94]])
// CHECK-NEXT:  %[[constant_100:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_35:[^ ]+]] = u32[] add(%[[add_33]], %[[constant_100]])
// CHECK-NEXT:  %[[constant_106:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_37:[^ ]+]] = u32[] add(%[[add_35]], %[[constant_106]])
// CHECK-NEXT:  %[[constant_112:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_39:[^ ]+]] = u32[] add(%[[add_37]], %[[constant_112]])
// CHECK-NEXT:  %[[constant_118:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_41:[^ ]+]] = u32[] add(%[[add_39]], %[[constant_118]])
// CHECK-NEXT:  %[[constant_124:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_43:[^ ]+]] = u32[] add(%[[add_41]], %[[constant_124]])
// CHECK-NEXT:  %[[constant_130:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_45:[^ ]+]] = u32[] add(%[[add_43]], %[[constant_130]])
// CHECK-NEXT:  %[[constant_136:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_47:[^ ]+]] = u32[] add(%[[add_45]], %[[constant_136]])
// CHECK-NEXT:  %[[constant_142:[^ ]+]] = u32[] constant(3144134277)
// CHECK-NEXT:  %[[add_49:[^ ]+]] = u32[] add(%[[add_47]], %[[constant_142]])
// CHECK-NEXT:  %[[a_or_mean_1:[^ ]+]] = u64[] parameter(2)
// CHECK-NEXT:  %[[broadcast_70:[^ ]+]] = u64[1]{0} broadcast(%[[or_4]]), dimensions={}
// CHECK-NEXT:  %[[iota_1:[^ ]+]] = u64[1]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[add_26:[^ ]+]] = u64[1]{0} add(%[[broadcast_70]], %[[iota_1]])
// CHECK-NEXT:  %[[convert_88:[^ ]+]] = u32[1]{0} convert(%[[add_26]])
// CHECK-NEXT:  %[[convert_92:[^ ]+]] = u64[1]{0} convert(%[[convert_88]])
// CHECK-NEXT:  %[[constant_83:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_78:[^ ]+]] = u64[1]{0} broadcast(%[[constant_83]]), dimensions={}
// CHECK-NEXT:  %[[multiply_20:[^ ]+]] = u64[1]{0} multiply(%[[convert_92]], %[[broadcast_78]])
// CHECK-NEXT:  %[[constant_84:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_79:[^ ]+]] = u64[1]{0} broadcast(%[[constant_84]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_31:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_20]], %[[broadcast_79]])
// CHECK-NEXT:  %[[convert_94:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_31]])
// CHECK-NEXT:  %[[broadcast_71:[^ ]+]] = u64[1]{0} broadcast(%[[or_4]]), dimensions={}
// CHECK-NEXT:  %[[compare_2:[^ ]+]] = pred[1]{0} compare(%[[add_26]], %[[broadcast_71]]), direction=LT
// CHECK-NEXT:  %[[constant_78:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[add_27:[^ ]+]] = u64[] add(%[[or_5]], %[[constant_78]])
// CHECK-NEXT:  %[[broadcast_72:[^ ]+]] = u64[1]{0} broadcast(%[[add_27]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_73:[^ ]+]] = u64[1]{0} broadcast(%[[or_5]]), dimensions={}
// CHECK-NEXT:  %[[select_2:[^ ]+]] = u64[1]{0} select(%[[compare_2]], %[[broadcast_72]], %[[broadcast_73]])
// CHECK-NEXT:  %[[constant_80:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_75:[^ ]+]] = u64[1]{0} broadcast(%[[constant_80]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_30:[^ ]+]] = u64[1]{0} shift-right-logical(%[[select_2]], %[[broadcast_75]])
// CHECK-NEXT:  %[[convert_91:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_30]])
// CHECK-NEXT:  %[[xor_42:[^ ]+]] = u32[1]{0} xor(%[[convert_94]], %[[convert_91]])
// CHECK-NEXT:  %[[broadcast_83:[^ ]+]] = u32[1]{0} broadcast(%[[convert_79]]), dimensions={}
// CHECK-NEXT:  %[[xor_43:[^ ]+]] = u32[1]{0} xor(%[[xor_42]], %[[broadcast_83]])
// CHECK-NEXT:  %[[convert_101:[^ ]+]] = u64[1]{0} convert(%[[xor_43]])
// CHECK-NEXT:  %[[constant_91:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_86:[^ ]+]] = u64[1]{0} broadcast(%[[constant_91]]), dimensions={}
// CHECK-NEXT:  %[[multiply_23:[^ ]+]] = u64[1]{0} multiply(%[[convert_101]], %[[broadcast_86]])
// CHECK-NEXT:  %[[constant_92:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_87:[^ ]+]] = u64[1]{0} broadcast(%[[constant_92]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_34:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_23]], %[[broadcast_87]])
// CHECK-NEXT:  %[[convert_103:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_34]])
// CHECK-NEXT:  %[[convert_90:[^ ]+]] = u32[1]{0} convert(%[[select_2]])
// CHECK-NEXT:  %[[convert_95:[^ ]+]] = u64[1]{0} convert(%[[convert_90]])
// CHECK-NEXT:  %[[constant_85:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_80:[^ ]+]] = u64[1]{0} broadcast(%[[constant_85]]), dimensions={}
// CHECK-NEXT:  %[[multiply_21:[^ ]+]] = u64[1]{0} multiply(%[[convert_95]], %[[broadcast_80]])
// CHECK-NEXT:  %[[convert_96:[^ ]+]] = u32[1]{0} convert(%[[multiply_21]])
// CHECK-NEXT:  %[[xor_44:[^ ]+]] = u32[1]{0} xor(%[[convert_103]], %[[convert_96]])
// CHECK-NEXT:  %[[broadcast_88:[^ ]+]] = u32[1]{0} broadcast(%[[add_30]]), dimensions={}
// CHECK-NEXT:  %[[xor_45:[^ ]+]] = u32[1]{0} xor(%[[xor_44]], %[[broadcast_88]])
// CHECK-NEXT:  %[[convert_104:[^ ]+]] = u64[1]{0} convert(%[[xor_45]])
// CHECK-NEXT:  %[[constant_95:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_90:[^ ]+]] = u64[1]{0} broadcast(%[[constant_95]]), dimensions={}
// CHECK-NEXT:  %[[multiply_24:[^ ]+]] = u64[1]{0} multiply(%[[convert_104]], %[[broadcast_90]])
// CHECK-NEXT:  %[[constant_96:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_91:[^ ]+]] = u64[1]{0} broadcast(%[[constant_96]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_35:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_24]], %[[broadcast_91]])
// CHECK-NEXT:  %[[convert_106:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_35]])
// CHECK-NEXT:  %[[constant_86:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_81:[^ ]+]] = u64[1]{0} broadcast(%[[constant_86]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_32:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_21]], %[[broadcast_81]])
// CHECK-NEXT:  %[[convert_97:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_32]])
// CHECK-NEXT:  %[[constant_79:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_74:[^ ]+]] = u64[1]{0} broadcast(%[[constant_79]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_29:[^ ]+]] = u64[1]{0} shift-right-logical(%[[add_26]], %[[broadcast_74]])
// CHECK-NEXT:  %[[convert_89:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_29]])
// CHECK-NEXT:  %[[xor_40:[^ ]+]] = u32[1]{0} xor(%[[convert_97]], %[[convert_89]])
// CHECK-NEXT:  %[[broadcast_82:[^ ]+]] = u32[1]{0} broadcast(%[[convert_78]]), dimensions={}
// CHECK-NEXT:  %[[xor_41:[^ ]+]] = u32[1]{0} xor(%[[xor_40]], %[[broadcast_82]])
// CHECK-NEXT:  %[[convert_98:[^ ]+]] = u64[1]{0} convert(%[[xor_41]])
// CHECK-NEXT:  %[[constant_89:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_84:[^ ]+]] = u64[1]{0} broadcast(%[[constant_89]]), dimensions={}
// CHECK-NEXT:  %[[multiply_22:[^ ]+]] = u64[1]{0} multiply(%[[convert_98]], %[[broadcast_84]])
// CHECK-NEXT:  %[[convert_99:[^ ]+]] = u32[1]{0} convert(%[[multiply_22]])
// CHECK-NEXT:  %[[xor_50:[^ ]+]] = u32[1]{0} xor(%[[convert_106]], %[[convert_99]])
// CHECK-NEXT:  %[[broadcast_95:[^ ]+]] = u32[1]{0} broadcast(%[[add_33]]), dimensions={}
// CHECK-NEXT:  %[[xor_51:[^ ]+]] = u32[1]{0} xor(%[[xor_50]], %[[broadcast_95]])
// CHECK-NEXT:  %[[convert_113:[^ ]+]] = u64[1]{0} convert(%[[xor_51]])
// CHECK-NEXT:  %[[constant_103:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_98:[^ ]+]] = u64[1]{0} broadcast(%[[constant_103]]), dimensions={}
// CHECK-NEXT:  %[[multiply_27:[^ ]+]] = u64[1]{0} multiply(%[[convert_113]], %[[broadcast_98]])
// CHECK-NEXT:  %[[constant_104:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_99:[^ ]+]] = u64[1]{0} broadcast(%[[constant_104]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_38:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_27]], %[[broadcast_99]])
// CHECK-NEXT:  %[[convert_115:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_38]])
// CHECK-NEXT:  %[[constant_90:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_85:[^ ]+]] = u64[1]{0} broadcast(%[[constant_90]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_33:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_22]], %[[broadcast_85]])
// CHECK-NEXT:  %[[convert_100:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_33]])
// CHECK-NEXT:  %[[convert_93:[^ ]+]] = u32[1]{0} convert(%[[multiply_20]])
// CHECK-NEXT:  %[[xor_46:[^ ]+]] = u32[1]{0} xor(%[[convert_100]], %[[convert_93]])
// CHECK-NEXT:  %[[broadcast_89:[^ ]+]] = u32[1]{0} broadcast(%[[add_31]]), dimensions={}
// CHECK-NEXT:  %[[xor_47:[^ ]+]] = u32[1]{0} xor(%[[xor_46]], %[[broadcast_89]])
// CHECK-NEXT:  %[[convert_107:[^ ]+]] = u64[1]{0} convert(%[[xor_47]])
// CHECK-NEXT:  %[[constant_97:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_92:[^ ]+]] = u64[1]{0} broadcast(%[[constant_97]]), dimensions={}
// CHECK-NEXT:  %[[multiply_25:[^ ]+]] = u64[1]{0} multiply(%[[convert_107]], %[[broadcast_92]])
// CHECK-NEXT:  %[[convert_108:[^ ]+]] = u32[1]{0} convert(%[[multiply_25]])
// CHECK-NEXT:  %[[xor_52:[^ ]+]] = u32[1]{0} xor(%[[convert_115]], %[[convert_108]])
// CHECK-NEXT:  %[[broadcast_100:[^ ]+]] = u32[1]{0} broadcast(%[[add_34]]), dimensions={}
// CHECK-NEXT:  %[[xor_53:[^ ]+]] = u32[1]{0} xor(%[[xor_52]], %[[broadcast_100]])
// CHECK-NEXT:  %[[convert_116:[^ ]+]] = u64[1]{0} convert(%[[xor_53]])
// CHECK-NEXT:  %[[constant_107:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_102:[^ ]+]] = u64[1]{0} broadcast(%[[constant_107]]), dimensions={}
// CHECK-NEXT:  %[[multiply_28:[^ ]+]] = u64[1]{0} multiply(%[[convert_116]], %[[broadcast_102]])
// CHECK-NEXT:  %[[constant_108:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_103:[^ ]+]] = u64[1]{0} broadcast(%[[constant_108]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_39:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_28]], %[[broadcast_103]])
// CHECK-NEXT:  %[[convert_118:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_39]])
// CHECK-NEXT:  %[[constant_98:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_93:[^ ]+]] = u64[1]{0} broadcast(%[[constant_98]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_36:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_25]], %[[broadcast_93]])
// CHECK-NEXT:  %[[convert_109:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_36]])
// CHECK-NEXT:  %[[convert_102:[^ ]+]] = u32[1]{0} convert(%[[multiply_23]])
// CHECK-NEXT:  %[[xor_48:[^ ]+]] = u32[1]{0} xor(%[[convert_109]], %[[convert_102]])
// CHECK-NEXT:  %[[broadcast_94:[^ ]+]] = u32[1]{0} broadcast(%[[add_32]]), dimensions={}
// CHECK-NEXT:  %[[xor_49:[^ ]+]] = u32[1]{0} xor(%[[xor_48]], %[[broadcast_94]])
// CHECK-NEXT:  %[[convert_110:[^ ]+]] = u64[1]{0} convert(%[[xor_49]])
// CHECK-NEXT:  %[[constant_101:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_96:[^ ]+]] = u64[1]{0} broadcast(%[[constant_101]]), dimensions={}
// CHECK-NEXT:  %[[multiply_26:[^ ]+]] = u64[1]{0} multiply(%[[convert_110]], %[[broadcast_96]])
// CHECK-NEXT:  %[[convert_111:[^ ]+]] = u32[1]{0} convert(%[[multiply_26]])
// CHECK-NEXT:  %[[xor_58:[^ ]+]] = u32[1]{0} xor(%[[convert_118]], %[[convert_111]])
// CHECK-NEXT:  %[[broadcast_107:[^ ]+]] = u32[1]{0} broadcast(%[[add_37]]), dimensions={}
// CHECK-NEXT:  %[[xor_59:[^ ]+]] = u32[1]{0} xor(%[[xor_58]], %[[broadcast_107]])
// CHECK-NEXT:  %[[convert_125:[^ ]+]] = u64[1]{0} convert(%[[xor_59]])
// CHECK-NEXT:  %[[constant_115:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_110:[^ ]+]] = u64[1]{0} broadcast(%[[constant_115]]), dimensions={}
// CHECK-NEXT:  %[[multiply_31:[^ ]+]] = u64[1]{0} multiply(%[[convert_125]], %[[broadcast_110]])
// CHECK-NEXT:  %[[constant_116:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_111:[^ ]+]] = u64[1]{0} broadcast(%[[constant_116]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_42:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_31]], %[[broadcast_111]])
// CHECK-NEXT:  %[[convert_127:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_42]])
// CHECK-NEXT:  %[[constant_102:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_97:[^ ]+]] = u64[1]{0} broadcast(%[[constant_102]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_37:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_26]], %[[broadcast_97]])
// CHECK-NEXT:  %[[convert_112:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_37]])
// CHECK-NEXT:  %[[convert_105:[^ ]+]] = u32[1]{0} convert(%[[multiply_24]])
// CHECK-NEXT:  %[[xor_54:[^ ]+]] = u32[1]{0} xor(%[[convert_112]], %[[convert_105]])
// CHECK-NEXT:  %[[broadcast_101:[^ ]+]] = u32[1]{0} broadcast(%[[add_35]]), dimensions={}
// CHECK-NEXT:  %[[xor_55:[^ ]+]] = u32[1]{0} xor(%[[xor_54]], %[[broadcast_101]])
// CHECK-NEXT:  %[[convert_119:[^ ]+]] = u64[1]{0} convert(%[[xor_55]])
// CHECK-NEXT:  %[[constant_109:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_104:[^ ]+]] = u64[1]{0} broadcast(%[[constant_109]]), dimensions={}
// CHECK-NEXT:  %[[multiply_29:[^ ]+]] = u64[1]{0} multiply(%[[convert_119]], %[[broadcast_104]])
// CHECK-NEXT:  %[[convert_120:[^ ]+]] = u32[1]{0} convert(%[[multiply_29]])
// CHECK-NEXT:  %[[xor_60:[^ ]+]] = u32[1]{0} xor(%[[convert_127]], %[[convert_120]])
// CHECK-NEXT:  %[[broadcast_112:[^ ]+]] = u32[1]{0} broadcast(%[[add_38]]), dimensions={}
// CHECK-NEXT:  %[[xor_61:[^ ]+]] = u32[1]{0} xor(%[[xor_60]], %[[broadcast_112]])
// CHECK-NEXT:  %[[convert_128:[^ ]+]] = u64[1]{0} convert(%[[xor_61]])
// CHECK-NEXT:  %[[constant_119:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_114:[^ ]+]] = u64[1]{0} broadcast(%[[constant_119]]), dimensions={}
// CHECK-NEXT:  %[[multiply_32:[^ ]+]] = u64[1]{0} multiply(%[[convert_128]], %[[broadcast_114]])
// CHECK-NEXT:  %[[constant_120:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_115:[^ ]+]] = u64[1]{0} broadcast(%[[constant_120]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_43:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_32]], %[[broadcast_115]])
// CHECK-NEXT:  %[[convert_130:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_43]])
// CHECK-NEXT:  %[[constant_110:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_105:[^ ]+]] = u64[1]{0} broadcast(%[[constant_110]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_40:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_29]], %[[broadcast_105]])
// CHECK-NEXT:  %[[convert_121:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_40]])
// CHECK-NEXT:  %[[convert_114:[^ ]+]] = u32[1]{0} convert(%[[multiply_27]])
// CHECK-NEXT:  %[[xor_56:[^ ]+]] = u32[1]{0} xor(%[[convert_121]], %[[convert_114]])
// CHECK-NEXT:  %[[broadcast_106:[^ ]+]] = u32[1]{0} broadcast(%[[add_36]]), dimensions={}
// CHECK-NEXT:  %[[xor_57:[^ ]+]] = u32[1]{0} xor(%[[xor_56]], %[[broadcast_106]])
// CHECK-NEXT:  %[[convert_122:[^ ]+]] = u64[1]{0} convert(%[[xor_57]])
// CHECK-NEXT:  %[[constant_113:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_108:[^ ]+]] = u64[1]{0} broadcast(%[[constant_113]]), dimensions={}
// CHECK-NEXT:  %[[multiply_30:[^ ]+]] = u64[1]{0} multiply(%[[convert_122]], %[[broadcast_108]])
// CHECK-NEXT:  %[[convert_123:[^ ]+]] = u32[1]{0} convert(%[[multiply_30]])
// CHECK-NEXT:  %[[xor_66:[^ ]+]] = u32[1]{0} xor(%[[convert_130]], %[[convert_123]])
// CHECK-NEXT:  %[[broadcast_119:[^ ]+]] = u32[1]{0} broadcast(%[[add_41]]), dimensions={}
// CHECK-NEXT:  %[[xor_67:[^ ]+]] = u32[1]{0} xor(%[[xor_66]], %[[broadcast_119]])
// CHECK-NEXT:  %[[convert_137:[^ ]+]] = u64[1]{0} convert(%[[xor_67]])
// CHECK-NEXT:  %[[constant_127:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_122:[^ ]+]] = u64[1]{0} broadcast(%[[constant_127]]), dimensions={}
// CHECK-NEXT:  %[[multiply_35:[^ ]+]] = u64[1]{0} multiply(%[[convert_137]], %[[broadcast_122]])
// CHECK-NEXT:  %[[constant_128:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_123:[^ ]+]] = u64[1]{0} broadcast(%[[constant_128]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_46:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_35]], %[[broadcast_123]])
// CHECK-NEXT:  %[[convert_139:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_46]])
// CHECK-NEXT:  %[[constant_114:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_109:[^ ]+]] = u64[1]{0} broadcast(%[[constant_114]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_41:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_30]], %[[broadcast_109]])
// CHECK-NEXT:  %[[convert_124:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_41]])
// CHECK-NEXT:  %[[convert_117:[^ ]+]] = u32[1]{0} convert(%[[multiply_28]])
// CHECK-NEXT:  %[[xor_62:[^ ]+]] = u32[1]{0} xor(%[[convert_124]], %[[convert_117]])
// CHECK-NEXT:  %[[broadcast_113:[^ ]+]] = u32[1]{0} broadcast(%[[add_39]]), dimensions={}
// CHECK-NEXT:  %[[xor_63:[^ ]+]] = u32[1]{0} xor(%[[xor_62]], %[[broadcast_113]])
// CHECK-NEXT:  %[[convert_131:[^ ]+]] = u64[1]{0} convert(%[[xor_63]])
// CHECK-NEXT:  %[[constant_121:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_116:[^ ]+]] = u64[1]{0} broadcast(%[[constant_121]]), dimensions={}
// CHECK-NEXT:  %[[multiply_33:[^ ]+]] = u64[1]{0} multiply(%[[convert_131]], %[[broadcast_116]])
// CHECK-NEXT:  %[[convert_132:[^ ]+]] = u32[1]{0} convert(%[[multiply_33]])
// CHECK-NEXT:  %[[xor_68:[^ ]+]] = u32[1]{0} xor(%[[convert_139]], %[[convert_132]])
// CHECK-NEXT:  %[[broadcast_124:[^ ]+]] = u32[1]{0} broadcast(%[[add_42]]), dimensions={}
// CHECK-NEXT:  %[[xor_69:[^ ]+]] = u32[1]{0} xor(%[[xor_68]], %[[broadcast_124]])
// CHECK-NEXT:  %[[convert_140:[^ ]+]] = u64[1]{0} convert(%[[xor_69]])
// CHECK-NEXT:  %[[constant_131:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_126:[^ ]+]] = u64[1]{0} broadcast(%[[constant_131]]), dimensions={}
// CHECK-NEXT:  %[[multiply_36:[^ ]+]] = u64[1]{0} multiply(%[[convert_140]], %[[broadcast_126]])
// CHECK-NEXT:  %[[constant_132:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_127:[^ ]+]] = u64[1]{0} broadcast(%[[constant_132]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_47:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_36]], %[[broadcast_127]])
// CHECK-NEXT:  %[[convert_142:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_47]])
// CHECK-NEXT:  %[[constant_122:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_117:[^ ]+]] = u64[1]{0} broadcast(%[[constant_122]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_44:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_33]], %[[broadcast_117]])
// CHECK-NEXT:  %[[convert_133:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_44]])
// CHECK-NEXT:  %[[convert_126:[^ ]+]] = u32[1]{0} convert(%[[multiply_31]])
// CHECK-NEXT:  %[[xor_64:[^ ]+]] = u32[1]{0} xor(%[[convert_133]], %[[convert_126]])
// CHECK-NEXT:  %[[broadcast_118:[^ ]+]] = u32[1]{0} broadcast(%[[add_40]]), dimensions={}
// CHECK-NEXT:  %[[xor_65:[^ ]+]] = u32[1]{0} xor(%[[xor_64]], %[[broadcast_118]])
// CHECK-NEXT:  %[[convert_134:[^ ]+]] = u64[1]{0} convert(%[[xor_65]])
// CHECK-NEXT:  %[[constant_125:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_120:[^ ]+]] = u64[1]{0} broadcast(%[[constant_125]]), dimensions={}
// CHECK-NEXT:  %[[multiply_34:[^ ]+]] = u64[1]{0} multiply(%[[convert_134]], %[[broadcast_120]])
// CHECK-NEXT:  %[[convert_135:[^ ]+]] = u32[1]{0} convert(%[[multiply_34]])
// CHECK-NEXT:  %[[xor_74:[^ ]+]] = u32[1]{0} xor(%[[convert_142]], %[[convert_135]])
// CHECK-NEXT:  %[[broadcast_131:[^ ]+]] = u32[1]{0} broadcast(%[[add_45]]), dimensions={}
// CHECK-NEXT:  %[[xor_75:[^ ]+]] = u32[1]{0} xor(%[[xor_74]], %[[broadcast_131]])
// CHECK-NEXT:  %[[convert_149:[^ ]+]] = u64[1]{0} convert(%[[xor_75]])
// CHECK-NEXT:  %[[constant_139:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_134:[^ ]+]] = u64[1]{0} broadcast(%[[constant_139]]), dimensions={}
// CHECK-NEXT:  %[[multiply_39:[^ ]+]] = u64[1]{0} multiply(%[[convert_149]], %[[broadcast_134]])
// CHECK-NEXT:  %[[constant_140:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_135:[^ ]+]] = u64[1]{0} broadcast(%[[constant_140]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_50:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_39]], %[[broadcast_135]])
// CHECK-NEXT:  %[[convert_151:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_50]])
// CHECK-NEXT:  %[[constant_126:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_121:[^ ]+]] = u64[1]{0} broadcast(%[[constant_126]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_45:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_34]], %[[broadcast_121]])
// CHECK-NEXT:  %[[convert_136:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_45]])
// CHECK-NEXT:  %[[convert_129:[^ ]+]] = u32[1]{0} convert(%[[multiply_32]])
// CHECK-NEXT:  %[[xor_70:[^ ]+]] = u32[1]{0} xor(%[[convert_136]], %[[convert_129]])
// CHECK-NEXT:  %[[broadcast_125:[^ ]+]] = u32[1]{0} broadcast(%[[add_43]]), dimensions={}
// CHECK-NEXT:  %[[xor_71:[^ ]+]] = u32[1]{0} xor(%[[xor_70]], %[[broadcast_125]])
// CHECK-NEXT:  %[[convert_143:[^ ]+]] = u64[1]{0} convert(%[[xor_71]])
// CHECK-NEXT:  %[[constant_133:[^ ]+]] = u64[] constant(3449720151)
// CHECK-NEXT:  %[[broadcast_128:[^ ]+]] = u64[1]{0} broadcast(%[[constant_133]]), dimensions={}
// CHECK-NEXT:  %[[multiply_37:[^ ]+]] = u64[1]{0} multiply(%[[convert_143]], %[[broadcast_128]])
// CHECK-NEXT:  %[[convert_144:[^ ]+]] = u32[1]{0} convert(%[[multiply_37]])
// CHECK-NEXT:  %[[xor_76:[^ ]+]] = u32[1]{0} xor(%[[convert_151]], %[[convert_144]])
// CHECK-NEXT:  %[[broadcast_136:[^ ]+]] = u32[1]{0} broadcast(%[[add_46]]), dimensions={}
// CHECK-NEXT:  %[[xor_77:[^ ]+]] = u32[1]{0} xor(%[[xor_76]], %[[broadcast_136]])
// CHECK-NEXT:  %[[convert_152:[^ ]+]] = u64[1]{0} convert(%[[xor_77]])
// CHECK-NEXT:  %[[convert_150:[^ ]+]] = u32[1]{0} convert(%[[multiply_39]])
// CHECK-NEXT:  %[[convert_153:[^ ]+]] = u64[1]{0} convert(%[[convert_150]])
// CHECK-NEXT:  %[[constant_143:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_138:[^ ]+]] = u64[1]{0} broadcast(%[[constant_143]]), dimensions={}
// CHECK-NEXT:  %[[shift_left_6:[^ ]+]] = u64[1]{0} shift-left(%[[convert_153]], %[[broadcast_138]])
// CHECK-NEXT:  %[[or_6:[^ ]+]] = u64[1]{0} or(%[[convert_152]], %[[shift_left_6]])
// CHECK-NEXT:  %[[reshape_12:[^ ]+]] = u64[1,1]{1,0} reshape(%[[or_6]])
// CHECK-NEXT:  %[[constant_134:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_129:[^ ]+]] = u64[1]{0} broadcast(%[[constant_134]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_48:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_37]], %[[broadcast_129]])
// CHECK-NEXT:  %[[convert_145:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_48]])
// CHECK-NEXT:  %[[convert_138:[^ ]+]] = u32[1]{0} convert(%[[multiply_35]])
// CHECK-NEXT:  %[[xor_72:[^ ]+]] = u32[1]{0} xor(%[[convert_145]], %[[convert_138]])
// CHECK-NEXT:  %[[broadcast_130:[^ ]+]] = u32[1]{0} broadcast(%[[add_44]]), dimensions={}
// CHECK-NEXT:  %[[xor_73:[^ ]+]] = u32[1]{0} xor(%[[xor_72]], %[[broadcast_130]])
// CHECK-NEXT:  %[[convert_146:[^ ]+]] = u64[1]{0} convert(%[[xor_73]])
// CHECK-NEXT:  %[[constant_137:[^ ]+]] = u64[] constant(3528531795)
// CHECK-NEXT:  %[[broadcast_132:[^ ]+]] = u64[1]{0} broadcast(%[[constant_137]]), dimensions={}
// CHECK-NEXT:  %[[multiply_38:[^ ]+]] = u64[1]{0} multiply(%[[convert_146]], %[[broadcast_132]])
// CHECK-NEXT:  %[[constant_138:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_133:[^ ]+]] = u64[1]{0} broadcast(%[[constant_138]]), dimensions={}
// CHECK-NEXT:  %[[shift_right_logical_49:[^ ]+]] = u64[1]{0} shift-right-logical(%[[multiply_38]], %[[broadcast_133]])
// CHECK-NEXT:  %[[convert_148:[^ ]+]] = u32[1]{0} convert(%[[shift_right_logical_49]])
// CHECK-NEXT:  %[[convert_141:[^ ]+]] = u32[1]{0} convert(%[[multiply_36]])
// CHECK-NEXT:  %[[xor_78:[^ ]+]] = u32[1]{0} xor(%[[convert_148]], %[[convert_141]])
// CHECK-NEXT:  %[[broadcast_137:[^ ]+]] = u32[1]{0} broadcast(%[[add_47]]), dimensions={}
// CHECK-NEXT:  %[[xor_79:[^ ]+]] = u32[1]{0} xor(%[[xor_78]], %[[broadcast_137]])
// CHECK-NEXT:  %[[convert_154:[^ ]+]] = u64[1]{0} convert(%[[xor_79]])
// CHECK-NEXT:  %[[convert_147:[^ ]+]] = u32[1]{0} convert(%[[multiply_38]])
// CHECK-NEXT:  %[[convert_155:[^ ]+]] = u64[1]{0} convert(%[[convert_147]])
// CHECK-NEXT:  %[[constant_144:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[broadcast_139:[^ ]+]] = u64[1]{0} broadcast(%[[constant_144]]), dimensions={}
// CHECK-NEXT:  %[[shift_left_7:[^ ]+]] = u64[1]{0} shift-left(%[[convert_155]], %[[broadcast_139]])
// CHECK-NEXT:  %[[or_7:[^ ]+]] = u64[1]{0} or(%[[convert_154]], %[[shift_left_7]])
// CHECK-NEXT:  %[[reshape_13:[^ ]+]] = u64[1,1]{1,0} reshape(%[[or_7]])
// CHECK-NEXT:  %[[concatenate_3:[^ ]+]] = u64[1,2]{1,0} concatenate(%[[reshape_12]], %[[reshape_13]]), dimensions={1}
// CHECK-NEXT:  %[[reshape_14:[^ ]+]] = u64[2]{0} reshape(%[[concatenate_3]])
// CHECK-NEXT:  %[[slice_5:[^ ]+]] = u64[1]{0} slice(%[[reshape_14]]), slice={[0:1]}
// CHECK-NEXT:  %[[reshape_15:[^ ]+]] = u64[] reshape(%[[slice_5]])
// CHECK-NEXT:  %[[b_or_sigma_1:[^ ]+]] = u64[] parameter(3)
// CHECK-NEXT:  %[[bitcast_convert_4:[^ ]+]] = u64[] bitcast-convert(%[[b_or_sigma_1]])
// CHECK-NEXT:  %[[bitcast_convert_5:[^ ]+]] = u64[] bitcast-convert(%[[a_or_mean_1]])
// CHECK-NEXT:  %[[subtract_2:[^ ]+]] = u64[] subtract(%[[bitcast_convert_4]], %[[bitcast_convert_5]])
// CHECK-NEXT:  %[[remainder_1:[^ ]+]] = u64[] remainder(%[[reshape_15]], %[[subtract_2]])
// CHECK-NEXT:  %[[constant_145:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  %[[shift_right_logical_51:[^ ]+]] = u64[] shift-right-logical(%[[remainder_1]], %[[constant_145]])
// CHECK-NEXT:  %[[bitcast_convert_6:[^ ]+]] = u64[] bitcast-convert(%[[shift_right_logical_51]])
// CHECK-NEXT:  %[[add_50:[^ ]+]] = u64[] add(%[[a_or_mean_1]], %[[bitcast_convert_6]])
// CHECK-NEXT:  %[[subtract_3:[^ ]+]] = u64[] subtract(%[[remainder_1]], %[[shift_right_logical_51]])
// CHECK-NEXT:  %[[bitcast_convert_7:[^ ]+]] = u64[] bitcast-convert(%[[subtract_3]])
// CHECK-NEXT:  ROOT %[[add_51:[^ ]+]] = u64[] add(%[[add_50]], %[[bitcast_convert_7]])

// CHECK-LABEL: ENTRY %test_uniform_int
// CHECK-NEXT:  %[[shape:[^ ]+]] = u64[3]{0} constant({8, 4, 2})
// CHECK-NEXT:  %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed", frontend_attributes={_xla_cse_safe_zero_operand="true"}
// CHECK-NEXT:  %[[constant:[^ ]+]] = u64[] constant(3)
// CHECK-NEXT:  %[[constant_1:[^ ]+]] = u64[] constant(11400714819323198485)
// CHECK-NEXT:  %[[multiply:[^ ]+]] = u64[] multiply(%[[constant]], %[[constant_1]])
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK-NEXT:  %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply]], %[[constant_2]])
// CHECK-NEXT:  %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[replica_id]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])
// CHECK-NEXT:  %[[rng_get_and_update_state:[^ ]+]] = u64[2]{0} rng-get-and-update-state(), delta=2
// CHECK-NEXT:  %[[mean:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[stdev:[^ ]+]] = u64[] constant(1)
// CHECK-NEXT:  ROOT %[[call:[^ ]+]] = u64[] call(%[[xor_2]], %[[rng_get_and_update_state]], %[[mean]], %[[stdev]]), to_apply=%[[$rng_1]]

HloModule TestUniformDistributionInt

ENTRY test_uniform_int {
  mean = u64[] constant(0)
  stdev = u64[] constant(1)
  shape = u64[3] constant({8, 4, 2})
  ROOT result = u64[] rng(mean, stdev, shape), distribution=rng_uniform
}

// -----

// CHECK-LABEL: HloModule TestMultiDevice

// CHECK:       %[[custom_call:[^ ]+]] = u64[] custom-call(), custom_call_target="GetRngSeed"
// CHECK:       %[[constant_2:[^ ]+]] = u64[] constant(32)
// CHECK:       %[[shift_right_logical:[^ ]+]] = u64[] shift-right-logical(%[[multiply:[^ ]+]], %[[constant_2]])
// CHECK:       %[[xor:[^ ]+]] = u64[] xor(%[[custom_call]], %[[shift_right_logical]])
// CHECK-NEXT:  %[[replica_id:[^ ]+]] = u32[] replica-id()
// CHECK-NEXT:  %[[convert:[^ ]+]] = u64[] convert(%[[replica_id]])
// CHECK-NEXT:  %[[xor_1:[^ ]+]] = u64[] xor(%[[xor]], %[[convert]])
// CHECK-NEXT:  %[[partition_id:[^ ]+]] = u64[] constant(0)
// CHECK-NEXT:  %[[shift_left:[^ ]+]] = u64[] shift-left(%[[partition_id]], %[[constant_2]])
// CHECK-NEXT:  %[[xor_2:[^ ]+]] = u64[] xor(%[[xor_1]], %[[shift_left]])

HloModule TestMultiDevice, replica_count=2, num_partitions=2

ENTRY test_multi_device {
  min = f32[] constant(0)
  max = f32[] constant(1)
  shape = u64[3] constant({2, 4, 8})
  ROOT result = f32[] rng(min, max, shape), distribution=rng_uniform
}