# Description:
# spectrogram test data packages.
load("//tensorflow:tensorflow.bzl", "filegroup")

package(
    licenses = ["notice"],
)

filegroup(
    name = "spectrogram_test_data",
    srcs = [
        "short_test_segment.wav",
        "short_test_segment_spectrogram.csv.bin",
        "short_test_segment_spectrogram_400_200.csv.bin",
    ],
    visibility = ["//visibility:public"],
)
