# Description:
# gtl subtle packages.

load("//tensorflow:tensorflow.bzl", "filegroup")

package(
    licenses = ["notice"],
)

filegroup(
    name = "map_traits",
    srcs = [
        "map_traits.h",
    ],
    visibility = ["//tensorflow/core/lib/gtl:__pkg__"],
)
