load("//tensorflow:tensorflow.bzl", "py_strict_test")

licenses(["notice"])

py_strict_test(
    name = "multiple_results_test",
    srcs = ["multiple_results_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_binary_bcast_test",
    srcs = ["tf_binary_bcast_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_const_test",
    srcs = ["tf_const_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_log1p_test",
    srcs = ["tf_log1p_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_math_ops_test",
    srcs = ["tf_math_ops_test.py"],
    python_version = "PY3",
    tags = ["no_pip"],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow:tensorflow_py",
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
        "@absl_py//absl/flags",
    ],
)

py_strict_test(
    name = "tf_matmul_test",
    srcs = ["tf_matmul_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_mean_test",
    srcs = ["tf_mean_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_metadata_ops_test",
    srcs = ["tf_metadata_ops_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_pack_test",
    srcs = ["tf_pack_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_reshape_test",
    srcs = ["tf_reshape_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_select_test",
    srcs = ["tf_select_test.py"],
    python_version = "PY3",
    tags = ["no_pip"],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_strided_slice_test",
    srcs = ["tf_strided_slice_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_transpose_test",
    srcs = ["tf_transpose_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_reduction_test",
    srcs = ["tf_reduction_test.py"],
    python_version = "PY3",
    tags = [
        "no_oss",
        "no_pip",
    ],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//third_party/py/numpy",
    ],
)

py_strict_test(
    name = "tf_compile_test",
    srcs = ["tf_compile_test.py"],
    data = glob(
        ["regression_tests/*"],
        exclude = ["regression_tests/*.disabled.mlir"],
    ),
    python_version = "PY3",
    tags = ["no_pip"],  # TODO(b/201803253): TFRT pybindings not in OSS.
    deps = [
        "//tensorflow/compiler/mlir/tfrt/jit/python_binding:tf_cpurt",
        "//tensorflow/python:client_testlib",
        "//tensorflow/python/platform",
    ],
)
