op {
  graph_op_name: "Variable"
  endpoint {
    name: "Variable"
  }
  summary: "Use VariableV2 instead."
}
op {
  graph_op_name: "VariableV2"
  endpoint {
    name: "VariableV2"
  }
  summary: "Holds state in the form of a tensor that persists across steps."
  description: <<END
Outputs a ref to the tensor state so it may be read or modified.
TODO(zhifengc/mrry): Adds a pointer to a more detail document
about sharing states in tensorflow.
END
}
