op {
  graph_op_name: "SparseMatrixNNZ"
  visibility: HIDDEN
  in_arg {
    name: "sparse_matrix"
    description: "A CSRSparseMatrix."
  }
  out_arg {
    name: "nnz"
    description: "The number of nonzeroes of `sparse_matrix`."
  }
  summary: "Returns the number of nonzeroes of `sparse_matrix`."
}
