op {
  graph_op_name: "SamplingDataset"
  visibility: HIDDEN
  in_arg {
    name: "rate"
    description: <<END
A scalar representing the sample rate. Each element of `input_dataset` is
retained with this probability, independent of all other elements.
END
  }
  in_arg {
    name: "seed"
    description: <<END
A scalar representing seed of random number generator.
END
  }
  in_arg {
    name: "seed2"
    description: <<END
A scalar representing seed2 of random number generator.
END
  }
  summary: "Creates a dataset that takes a Bernoulli sample of the contents of another dataset."
  description: <<END
There is no transformation in the `tf.data` Python API for creating this dataset.
Instead, it is created as a result of the `filter_with_random_uniform_fusion`
static optimization. Whether this optimization is performed is determined by the
`experimental_optimization.filter_with_random_uniform_fusion` option of
`tf.data.Options`.
END
}
