op {
  graph_op_name: "GuaranteeConst"
  summary: "Gives a guarantee to the TF runtime that the input tensor is a constant."
  description: <<END
The runtime is then free to make optimizations based on this.

Only accepts value typed tensors as inputs and rejects resource variable handles
as input.

Returns the input tensor without modification.
END
}
