op {
  graph_op_name: "Size"
  summary: "Returns the size of a tensor."
  description: <<END
This operation returns an integer representing the number of elements in
`input`.

For example:

```
# 't' is [[[1, 1,, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]]
size(t) ==> 12
```
END
}
