op {
  graph_op_name: "MakeUnique"
  summary: "Make all elements in the non-Batch dimension unique, but \\\"close\\\" to"
  description: <<END
their initial value. Never returns a sub-normal number. Never returns
zero. The sign of each input element is always identical to the sign
of the corresponding output element. Behavior for infinite elements is
undefined. Behavior for subnormal elements is undefined.
END
}
