op {
  graph_op_name: "DisableCopyOnRead"
  visibility: HIDDEN
  in_arg {
    name: "resource"
    description: <<END
The resource handle of the resource variable.
END
  }
  summary: "Turns off the copy-on-read mode."
  description: <<END
Turns off the copy-on-read mode of a resource variable. If the variable is not in copy-on-read mode, this op has no effect.  
END
}
