op {
  graph_op_name: "XlaRecvFromHost"
  summary: "An op to receive a tensor from the host."
  description: <<END
output: the tensor that will be received from the host.
Toutput: element type for output.
shape: shape for output.
key: A unique identifier for this region used to match up host transfers.
END
}
