op {
  graph_op_name: "RetrieveTPUEmbeddingFrequencyEstimatorParameters"
  visibility: HIDDEN
  out_arg {
    name: "parameters"
    description: <<END
Parameter parameters updated by the frequency estimator optimization algorithm.
END
  }
  out_arg {
    name: "last_hit_step"
    description: <<END
Parameter last_hit_step updated by the frequency estimator optimization
algorithm.
END
  }
  summary: "Retrieve frequency estimator embedding parameters."
  description: <<END
An op that retrieves optimization parameters from embedding to host
memory. Must be preceded by a ConfigureTPUEmbeddingHost op that sets up
the correct embedding table configuration. For example, this op is
used to retrieve updated parameters before saving a checkpoint.
END
}
