op {
  graph_op_name: "QueueIsClosedV2"
  in_arg {
    name: "handle"
    description: <<END
The handle to a queue.
END
  }
  summary: "Returns true if queue is closed."
  description: <<END
This operation returns true if the queue is closed and false if the queue
is open.
END
}
