op {
  graph_op_name: "DebugIdentity"
  visibility: HIDDEN
  in_arg {
    name: "input"
    description: <<END
Input tensor, non-Reference type
END
  }
  attr {
    name: "device_name"
    description: <<END
Name of the device on which the tensor resides.
END
  }
  attr {
    name: "tensor_name"
    description: <<END
Name of the input tensor.
END
  }
  attr {
    name: "debug_urls"
    description: <<END
List of URLs to debug targets, e.g.,
  file:///foo/tfdbg_dump, grpc:://localhost:11011
END
  }
  attr {
    name: "gated_grpc"
    description: <<END
Whether this op will be gated. If any of the debug_urls of this
  debug node is of the grpc:// scheme, when the value of this attribute is set
  to True, the data will not actually be sent via the grpc stream unless this
  debug op has been enabled at the debug_url. If all of the debug_urls of this
  debug node are of the grpc:// scheme and the debug op is enabled at none of
  them, the output will be an empty Tensor.
END
  }
  summary: "Provides an identity mapping of the non-Ref type input tensor for debugging."
  description: <<END
Provides an identity mapping of the non-Ref type input tensor for debugging.
END
}
