op {
  graph_op_name: "MulNoNan"
  endpoint {
    name: "MulNoNan"
  }
  summary: "Returns x * y element-wise. Returns zero if y is zero, even if x if infinite or NaN."
  description: <<END
*NOTE*: `MulNoNan` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
