op {
  graph_op_name: "Polygamma"
  summary: "Compute the polygamma function \\\\(\\psi^{(n)}(x)\\\\)."
  description: <<END
The polygamma function is defined as:


\\(\psi^{(a)}(x) = \frac{d^a}{dx^a} \psi(x)\\)

where \\(\psi(x)\\) is the digamma function.
The polygamma function is defined only for non-negative integer orders \\a\\.
END
}
