op {
  graph_op_name: "UnsortedSegmentMin"
  in_arg {
    name: "segment_ids"
    description: <<END
A 1-D tensor whose rank is equal to the rank of `data`'s
first dimension.
END
  }
  out_arg {
    name: "output"
    description: <<END
Has same shape as data, except for dimension 0 which
has size `num_segments`.
END
  }
  summary: "Computes the minimum along segments of a tensor."
  description: <<END
Read @{$math_ops#segmentation$the section on segmentation} for an explanation of
segments.

This operator is similar to the unsorted segment sum operator found
[(here)](../../../api_docs/python/math_ops.md#UnsortedSegmentSum).
Instead of computing the sum over segments, it computes the minimum such that:

\\(output_i = \min_j data_j\\) where min is over `j` such
that `segment_ids[j] == i`.

If the minimum is empty for a given segment ID `i`, it outputs the largest
possible value for the specific numeric type,
`output[i] = numeric_limits<T>::max()`.
END
}
