op {
  graph_op_name: "Mul"
  endpoint {
    name: "Multiply"
  }
  endpoint {
    name: "Mul"
  }
  summary: "Returns x * y element-wise."
  description: <<END
*NOTE*: `Mul` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
