op {
  graph_op_name: "ShutdownTPUSystem"
  out_arg {
    name: "success"
    description: <<END
A boolean that indicates if the shut down process succeeds.
END
  }
  summary: "An op that shuts down the TPU system."
}
