op {
  graph_op_name: "TPUCompile"
  summary: "Compiles a computations for execution on one or more TPU devices."
  description: <<END
For the internal use of the distributed TPU compiler.

'num_computations' is the number of computations to be compiled.
'function' is a function containing the computation to compile.
'dynamic_shapes' contains dynamic shapes of arguments whose shapes were not
known statically at TPUReplication rewrite time.
'guaranteed_constants' is a list of tensors which have been guaranteed to not
change their values during the session lifetime. These contain tensors marked as
constant using the GuaranteeConstOp.
'metadata' is a serialized TPUCompileMetadataProto describing
the shapes and types of the inputs to the computation, as well as a mapping onto
the TPU pod topology.
Each 'program' output is a string key that is passed to the _TPUExecute op and
used to look up the program in the compilation cache.
'may_modify_variables' indicates whether variables may be modified.
END
}
