op {
  graph_op_name: "Igammac"
  summary: "Compute the upper regularized incomplete Gamma function `Q(a, x)`."
  description: <<END
The upper regularized incomplete Gamma function is defined as:

\\(Q(a, x) = Gamma(a, x) / Gamma(a) = 1 - P(a, x)\\)

where

\\(Gamma(a, x) = \int_{x}^{\infty} t^{a-1} exp(-t) dt\\)

is the upper incomplete Gamma function.

Note, above `P(a, x)` (`Igamma`) is the lower regularized complete
Gamma function.
END
}
