op {
  graph_op_name: "Iterator"
  out_arg {
    name: "handle"
    description: <<END
A handle to the iterator that can be passed to a "MakeIterator"
or "IteratorGetNext" op.
END
  }
  summary: "A container for an iterator resource."
}
