op {
  graph_op_name: "TensorForestTreeIsInitializedOp"
  visibility: HIDDEN
  in_arg {
    name: "tree_handle"
    description: <<END
Handle to the tree.
END
  }
  out_arg {
    name: "is_initialized"
    description: <<END
Whether the tree is initialized.
END
  }
  summary: "Checks whether a tree has been initialized."
}
