op {
  graph_op_name: "AddN"
  summary: "Add all input tensors element wise."
  description: <<END
  Inputs must be of same size and shape.

  ```python
  x = [9, 7, 10]
  tf.math.add_n(x) ==> 26
  ```
END
}
