op {
  graph_op_name: "VarIsInitializedOp"
  in_arg {
    name: "resource"
    description: <<END
the input resource handle.
END
  }
  out_arg {
    name: "is_initialized"
    description: <<END
a scalar boolean which is true if the variable has been
initialized.
END
  }
  summary: "Checks whether a resource handle-based variable has been initialized."
}
