op {
  graph_op_name: "TPUReplicatedOutput"
  visibility: HIDDEN
  summary: "Connects N outputs from an N-way replicated TPU computation."
  description: <<END
This operation holds a replicated output from a `tpu.replicate()` computation subgraph.
Each replicated output has the same shape and type alongside the input.

For example:
```
%computation = "tf.Computation"()
%replicated_output:2 = "tf.TPUReplicatedOutput"(%computation)
```
The above computation has a replicated output of two replicas.
END
}
