op {
  graph_op_name: "AssertPrevDataset"
  visibility: HIDDEN
  in_arg {
    name: "input_dataset"
    description: <<END
A variant tensor representing the input dataset.
`AssertPrevDataset` passes through the outputs of its input dataset.
END
  }
  in_arg {
  name: "transformations"
  description: <<END
A `tf.string` vector `tf.Tensor` identifying the transformations, with optional
attribute name-value pairs, that are expected to have happened previously.
END
  }
  summary: "A transformation that asserts which transformations happened previously."
  description: <<END
This transformation checks the names and, optionally, the attribute name-value
pairs in the `transformations` argument against those of the transformations
that preceded this transformation.  If there is a mismatch, the transformation
raises an exception.

The check occurs when iterating over the contents of the dataset, which
means that the check happens *after* any static optimizations are applied
to the dataset graph.
END
}
