op {
  graph_op_name: "DebugGradientRefIdentity"
  summary: "Identity op for gradient debugging."
  description: <<END
This op is hidden from public in Python. It is used by TensorFlow Debugger to
register gradient tensors for gradient debugging.
This op operates on reference-type tensors.
END
}
