op {
  graph_op_name: "Sign"
  summary: "Returns an element-wise indication of the sign of a number."
  description: <<END
`y = sign(x) = -1` if `x < 0`; 0 if `x == 0`; 1 if `x > 0`.

For complex numbers, `y = sign(x) = x / |x|` if `x != 0`, otherwise `y = 0`.
END
}
