op {
  graph_op_name: "StringJoin"
  in_arg {
    name: "inputs"
    description: <<END
A list of string tensors.  The tensors must all have the same shape,
or be scalars.  Scalars may be mixed in; these will be broadcast to the shape
of non-scalar inputs.
END
  }
  attr {
    name: "separator"
    description: <<END
string, an optional join separator.
END
  }
  summary: "Joins the strings in the given list of string tensors into one tensor;"
  description: <<END
with the given separator (default is an empty separator).

Examples:
>>> s = ["hello", "world", "tensorflow"]
>>> tf.strings.join(s, " ")
<tf.Tensor: id=11, shape=(), dtype=string, numpy=b'hello world tensorflow'>
END
}
