op {
  graph_op_name: "LookupTableSizeV2"
  endpoint {
    name: "LookupTableSize"
  }
  in_arg {
    name: "table_handle"
    description: <<END
Handle to the table.
END
  }
  out_arg {
    name: "size"
    description: <<END
Scalar that contains number of elements in the table.
END
  }
  summary: "Computes the number of elements in the given table."
}
