op {
  graph_op_name: "StatelessRandomGammaV2"
  visibility: HIDDEN
  in_arg {
    name: "shape"
    description: <<END
The shape of the output tensor.
END
  }
  in_arg {
    name: "seed"
    description: <<END
2 seeds (shape [2]).
END
  }
  in_arg {
    name: "alpha"
    description: <<END
The concentration of the gamma distribution. Shape must match the rightmost
dimensions of `shape`.
END
  }
  out_arg {
    name: "output"
    description: <<END
Random values with specified shape.
END
  }
  attr {
    name: "dtype"
    description: <<END
The type of the output.
END
  }
  summary: "Outputs deterministic pseudorandom random numbers from a gamma distribution."
  description: <<END
Outputs random values from a gamma distribution.

The outputs are a deterministic function of `shape`, `seed`, and `alpha`.
END
}
