op {
  graph_op_name: "TensorListPopBack"
  summary: "Returns the last element of the input list as well as a list with all but that element."
  description: <<END
Fails if the list is empty.

input_handle: the input list
tensor: the withdrawn last element of the list
element_dtype: the type of elements in the list
element_shape: the shape of the output tensor
END
}
