op {
  graph_op_name: "VariableShape"
  summary: "Returns the shape of the variable pointed to by `resource`."
  description: <<END
This operation returns a 1-D integer tensor representing the shape of `input`.

For example:

```
# 't' is [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
shape(t) ==> [2, 2, 3]
```
END
}
