op {
  graph_op_name: "StatsAggregatorHandleV2"
  attr {
    name: "container"
    description: <<END
A non-empty `container` name must start with `'.'`, a letter, or a digit, and may contain only `'-'`, `'.'`, `'/'`, letters, and digits.
END
  }
  visibility: HIDDEN
}
