op {
  graph_op_name: "Minimum"
  summary: "Returns the min of x and y (i.e. x < y ? x : y) element-wise."
  description: <<END
*NOTE*: `Minimum` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
