op {
  graph_op_name: "RiscAdd"
  visibility: HIDDEN
  summary: "Returns x + y element-wise."
  description: <<END
*NOTE*: `RiscAdd` does not supports broadcasting.

Given two input tensors, the `tf.risc_add` operation computes the sum for every element in the tensor.

Both input and output have a range `(-inf, inf)`.

END
}
