op {
  graph_op_name: "RegexMatch"
  in_arg {
    name: "input"
    description: <<END
The text to be processed.
END
  }
  in_arg {
    name: "pattern"
    description: <<END
The regular expression to match the input.
END
  }
  out_arg {
    name: "output"
    description: <<END
The same tensor shape as `input`.
END
  }
  summary: "Check if the input matches the regex pattern."
}
