op {
  graph_op_name: "LessEqual"
  summary: "Returns the truth value of (x <= y) element-wise."
  description: <<END
*NOTE*: `LessEqual` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
