op {
  graph_op_name: "BarrierReadySize"
  in_arg {
    name: "handle"
    description: <<END
The handle to a barrier.
END
  }
  out_arg {
    name: "size"
    description: <<END
The number of complete elements (i.e. those with all of their value
components set) in the barrier.
END
  }
  summary: "Computes the number of complete elements in the given barrier."
}
