op {
  graph_op_name: "DeviceIndex"
  visibility: HIDDEN
  summary: "Return the index of device the op runs."
  description: <<END
Given a list of device names, this operation returns the index of the device
this op runs. The length of the list is returned in two cases:
(1) Device does not exist in the given device list.
(2) It is in XLA compilation.
END
}
