op {
  graph_op_name: "QuantizedDepthwiseConv2D"
  visibility: HIDDEN
  in_arg {
    name: "input"
    description: "The original input tensor."
  }
  in_arg {
    name: "filter"
    description: "The original filter tensor."
  }
  in_arg {
    name: "min_input"
    description: <<END
The float value that the minimum quantized input value represents.
END
  }
  in_arg {
    name: "max_input"
    description: <<END
The float value that the maximum quantized input value represents.
END
  }
  in_arg {
    name: "min_filter"
    description: <<END
The float value that the minimum quantized filter value represents.
END
  }
  in_arg {
    name: "max_filter"
    description: <<END
The float value that the maximum quantized filter value represents.
END
  }
  out_arg {
    name: "output"
    description: "The output tensor."
  }
  out_arg {
    name: "min_output"
    description: <<END
The float value that the minimum quantized output value represents.
END
  }
  out_arg {
    name: "max_output"
    description: <<END
The float value that the maximum quantized output value represents.
END
  }
  attr {
    name: "Tinput"
    description: "The type of the input."
  }
  attr {
    name: "Tfilter"
    description: "The type of the filter."
  }
  attr {
    name: "out_type"
    description: "The type of the output."
  }
  attr {
    name: "strides"
    description: "List of stride values."
  }
  attr {
    name: "dilations"
    description: "List of dilation values."
  }
  summary: "Computes quantized depthwise Conv2D."
}
