op {
  graph_op_name: "AnonymousIterator"
  out_arg {
    name: "handle"
    description: <<END
A handle to the iterator that can be passed to a "MakeIterator" or
"IteratorGetNext" op. In contrast to Iterator, AnonymousIterator prevents
resource sharing by name, and does not keep a reference to the resource
container.
END
  }
  summary: "A container for an iterator resource."
}
