op {
  graph_op_name: "ConfigureTPUEmbedding"
  visibility: HIDDEN
  attr {
    name: "config"
    description: <<END
Serialized tensorflow.tpu.TPUEmbeddingConfiguration that
describes the embedding lookups of the program.
END
  }
  summary: "Sets up TPUEmbedding in a distributed TPU system."
}
