op {
  graph_op_name: "LogicalOr"
  summary: "Returns the truth value of x OR y element-wise."
  description: <<END
*NOTE*: `LogicalOr` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
