op {
  graph_op_name: "AnonymousMutableHashTable"
  visibility: HIDDEN
  out_arg {
    name: "table_handle"
    description: <<END
The resource handle to the newly created hash-table resource.
END
  }
  attr {
    name: "key_dtype"
    description: <<END
Type of the table keys.
END
  }
  attr {
    name: "value_dtype"
    description: <<END
Type of the table values.
END
  }
  summary: "Creates an empty anonymous mutable hash table."
  description: <<END
This op creates a new anonymous mutable hash table (as a resource) everytime
it is executed, with the specified dtype of its keys and values,
returning the resource handle. Each value must be a scalar.
Data can be inserted into the table using
the insert operations. It does not support the initialization operation.
The table is anonymous in the sense that it can only be
accessed by the returned resource handle (e.g. it cannot be looked up
by a name in a resource manager). The table will be automatically
deleted when all resource handles pointing to it are gone.
END
}
