op {
  graph_op_name: "TensorListConcat"
  summary: "Concats all tensors in the list along the 0th dimension."
  description: <<END
Requires that all tensors have the same shape except the first dimension.

input_handle: The input list.
tensor: The concated result.
lengths: Output tensor containing sizes of the 0th dimension of tensors in the list, used for computing the gradient.

END
}
