op {
  graph_op_name: "EnqueueTPUEmbeddingBatch"
  visibility: HIDDEN
  in_arg {
    name: "batch"
    description: <<END
A list of 1D tensors, one for each embedding table, containing the
batch inputs encoded as dist_belief.SparseFeatures protos. If the weight
field in the SparseFeatures proto is not populated for an ID, a weight of
1.0 is assumed.
END
  }
  in_arg {
    name: "mode_override"
    description: <<END
A string input that overrides the mode specified in the
TPUEmbeddingConfiguration. Supported values are {'unspecified', 'inference',
'training', 'backward_pass_only'}. When set to 'unspecified', the mode set
in TPUEmbeddingConfiguration is used, otherwise mode_override is used.
END
  }
  attr {
    name: "device_ordinal"
    description: <<END
The TPU device to use. This should be -1 when the Op
is running on a TPU device, and >= 0 when the Op is running on the CPU
device.
END
  }
  attr {
    name: "combiners"
    description: <<END
A list of string scalars, one for each embedding table that specify
how to normalize the embedding activations after weighted summation.
Supported combiners are 'mean', 'sum', or 'sqrtn'. It is invalid to have
the sum of the weights be 0 for 'mean' or the sum of the squared weights be
0 for 'sqrtn'. If combiners isn't passed, the default is to use 'sum' for
all tables.
END
  }
  summary: "An op that enqueues a list of input batch tensors to TPUEmbedding."
  description: <<END
An op that enqueues a list of input batch tensors to TPUEmbedding.
END
}
