op {
  graph_op_name: "EmptyTensorList"
  summary: "Creates and returns an empty tensor list."
  description: <<END
All list elements must be tensors of dtype element_dtype and shape compatible
with element_shape.

handle: an empty tensor list.
element_dtype: the type of elements in the list.
element_shape: a shape compatible with that of elements in the list.
END
}
