op {
  graph_op_name: "ReaderSerializeState"
  visibility: SKIP
  in_arg {
    name: "reader_handle"
    description: <<END
Handle to a Reader.
END
  }
  summary: "Produce a string tensor that encodes the state of a Reader."
  description: <<END
Not all Readers support being serialized, so this can produce an
Unimplemented error.
END
}
