op {
  graph_op_name: "Sin"
  summary: "Computes sine of x element-wise."
  description: << END
  Given an input tensor, this function computes sine of every
  element in the tensor. Input range is (-infinity, infinity) and
  output range is [-1,1].
  ```python
  x = tf.constant([-9, -0.5, 1, 1.2, 200, 10000])
  tf.math.sin(x, name ='sin') ==> [-0.4121185  -0.47942555  0.84147096  0.9320391  -0.8732973  -0.5440211]
  ```
END
}
