op {
  graph_op_name: "BoostedTreesFlushQuantileSummaries"
  deprecation_message: "Boosted Trees kernels in TF are deprecated. Please use TensorFlow Decision Forests instead (https://github.com/tensorflow/decision-forests)"
  visibility: HIDDEN
  in_arg {
    name: "quantile_stream_resource_handle"
    description: <<END
resource handle referring to a QuantileStreamResource.
END
  }
  summary: "Flush the quantile summaries from each quantile stream resource."
  description: <<END
An op that outputs a list of quantile summaries of a quantile stream resource.
Each summary Tensor is rank 2, containing summaries (value, weight, min_rank,
max_rank) for a single feature.
END
}
