op {
  graph_op_name: "Maximum"
  summary: "Returns the max of x and y (i.e. x > y ? x : y) element-wise."
  description: <<END
*NOTE*: `Maximum` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
