op {
  graph_op_name: "TensorListStack"
  summary: "Stacks all tensors in the list."
  description: <<END
Requires that all tensors have the same shape.

input_handle: the input list
tensor: the gathered result
num_elements: optional. If not -1, the number of elements in the list.

END
}
