op {
  graph_op_name: "FinalizeTPUEmbedding"
  in_arg {
    name: "common_config"
    description: <<END
A string-encoded common configuration proto containing metadata
about the TPUEmbedding partitioner output and the HBM size (in bytes) required
for operation.
END
  }
  in_arg {
    name: "memory_config"
    description: <<END
A string-encoded memory config proto containing metadata about
the memory allocations reserved for TPUEmbedding.
END
  }
  summary: "An op that finalizes the TPUEmbedding configuration."
}
