op {
  graph_op_name: "Log1p"
  summary: "Computes natural logarithm of (1 + x) element-wise."
  description: <<END
I.e., \\(y = \log_e (1 + x)\\).

Example:

```python
x = tf.constant([0, 0.5, 1, 5])
tf.math.log1p(x) ==> [0., 0.4054651, 0.6931472, 1.7917595]
```
END
}
