op {
  graph_op_name: "FakeQuantWithMinMaxVars"
  summary: "Fake-quantize the \'inputs\' tensor of type float via global float scalars `min`"
  description: <<END
and `max` to 'outputs' tensor of same shape as `inputs`.

`[min; max]` define the clamping range for the `inputs` data.
`inputs` values are quantized into the quantization range (`[0; 2^num_bits - 1]`
when `narrow_range` is false and `[1; 2^num_bits - 1]` when it is true) and
then de-quantized and output as floats in `[min; max]` interval.
`num_bits` is the bitwidth of the quantization; between 2 and 16, inclusive.

This operation has a gradient and thus allows for training `min` and `max`
values.
END
}
