op {
  graph_op_name: "InvGrad"
  visibility: HIDDEN
  summary: "Computes the gradient for the inverse of `x` wrt its input."
  description: <<END
Specifically, `grad = -dy * y*y`, where `y = 1/x`, and `dy`
is the corresponding input gradient.
END
}
