op {
  graph_op_name: "TensorListFromTensor"
  summary: "Creates a TensorList which, when stacked, has the value of `tensor`."
  description: <<END
Each tensor in the result list corresponds to one row of the input tensor.

tensor: The input tensor.
output_handle: The list.
END
}
