op {
  graph_op_name: "Equal"
  summary: "Returns the truth value of (x == y) element-wise."
  description: <<END
*NOTE*: `Equal` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
