op {
  graph_op_name: "MapAndBatchDataset"
  in_arg {
    name: "batch_size"
    description: <<END
A scalar representing the number of elements to accumulate in a
batch. It determines the number of concurrent invocations of `f` that process
elements from `input_dataset` in parallel.
END
  }
  in_arg {
    name: "num_parallel_batches"
    description: <<END
A scalar representing the number of batches to create in
parallel. Processing multiple batches in parallel benefits workloads prone to
stragglers.
END
  }
  summary: "Creates a dataset that applies `f` to the outputs of `input_dataset` and then"
  description: <<END
batches `batch_size` of them.

Unlike a "MapDataset", which applies `f` sequentially, this dataset invokes up
to `batch_size * num_parallel_batches` copies of `f` in parallel.
END
}
