op {
  graph_op_name: "TensorMapInsert"
  summary: "Returns a map that is the 'input_handle' with the given key-value pair inserted."
  description: <<END
input_handle: the original map
output_handle: the map with key and value inserted
key: the key to be inserted
value: the value to be inserted
END
}