op {
  graph_op_name: "DTensorSetGlobalTPUArray"
  in_arg {
    name: "topology"
    description: <<END
A serialized tensorflow.tpu.TopologyProto that describes the TPU topology.
END
  }
  summary: "An op that informs a host of the global ids of all the of TPUs in the system."
  description: <<END
END
}
