op {
  graph_op_name: "Send"
  visibility: HIDDEN
  in_arg {
    name: "tensor"
    description: <<END
The tensor to send.
END
  }
  attr {
    name: "tensor_name"
    description: <<END
The name of the tensor to send.
END
  }
  attr {
    name: "send_device"
    description: <<END
The name of the device sending the tensor.
END
  }
  attr {
    name: "send_device_incarnation"
    description: <<END
The current incarnation of send_device.
END
  }
  attr {
    name: "recv_device"
    description: <<END
The name of the device receiving the tensor.
END
  }
  attr {
    name: "client_terminated"
    description: <<END
If set to true, this indicates that the node was added
to the graph as a result of a client-side feed or fetch of Tensor data,
in which case the corresponding send or recv is expected to be managed
locally by the caller.
END
  }
  summary: "Sends the named tensor from send_device to recv_device."
}
