op {
  graph_op_name: "RepeatDataset"
  in_arg {
    name: "count"
    description: <<END
A scalar representing the number of times that `input_dataset` should
be repeated. A value of `-1` indicates that it should be repeated infinitely.
END
  }
  summary: "Creates a dataset that emits the outputs of `input_dataset` `count` times."
}
