op {
  graph_op_name: "DeserializeSparse"
  in_arg {
    name: "serialized_sparse"
    description: <<END
1-D, The serialized `SparseTensor` object. Must have 3 columns.
END
  }
  attr {
    name: "dtype"
    description: <<END
The `dtype` of the serialized `SparseTensor` object.
END
  }
  summary: "Deserialize `SparseTensor` from a (serialized) string 3-vector (1-D `Tensor`)"
  description: <<END
object.
END
}
