op {
  graph_op_name: "ReaderReset"
  visibility: SKIP
  in_arg {
    name: "reader_handle"
    description: <<END
Handle to a Reader.
END
  }
  summary: "Restore a Reader to its initial clean state."
}
