op {
  graph_op_name: "TensorArrayCloseV3"
  endpoint {
    name: "TensorArrayClose"
  }
  in_arg {
    name: "handle"
    description: <<END
The handle to a TensorArray (output of TensorArray or TensorArrayGrad).
END
  }
  summary: "Delete the TensorArray from its resource container."
  description: <<END
This enables the user to close and release the resource in the middle
of a step/run.
END
}
