op {
  graph_op_name: "TensorScatterMin"
  in_arg {
    name: "tensor"
    description: <<END
Tensor to update.
END
  }
  in_arg {
    name: "indices"
    description: <<END
Index tensor.
END
  }
  in_arg {
    name: "updates"
    description: <<END
Updates to scatter into output.
END
  }
  out_arg {
    name: "output"
    description: <<END
A new tensor copied from tensor whose values are element-wise minimum between tensor and updates according to the indices.
END
 }
}
