op {
  graph_op_name: "DeleteMultiDeviceIterator"
  visibility: HIDDEN
  in_arg {
    name: "multi_device_iterator"
    description: "A handle to the multi device iterator to delete."
  }
  in_arg {
    name: "iterators"
    description:
      "A list of iterator handles (unused). This is added so that "
      "automatic control dependencies get added during function tracing that "
      "ensure this op runs after all the dependent iterators are deleted."
  }
  in_arg {
    name: "deleter"
    description: "A variant deleter."
  }
  summary: "A container for an iterator resource."
}
