op {
  graph_op_name: "IdentityDataset"
  visibility: HIDDEN
  in_arg {
    name: "input_dataset"
    description: <<END
A variant tensor representing the input dataset.
END
  }
  summary: "A placeholder for input pipeline graph optimizations."
  description: <<END
A placeholder for input pipeline graph optimizations.
END
}
