op {
  graph_op_name: "QuantizeAndDequantizeV4"
in_arg {
    name: "input"
    description: <<END
Tensor to quantize and then dequantize.
END
  }
  in_arg {
    name: "input_min"
    description: <<END
If `range_given == True`, this specifies the minimum input value that needs to
be represented, otherwise it is determined from the min value of the `input`
tensor.
END
  }
  in_arg {
    name: "input_max"
    description: <<END
If `range_given == True`, this specifies the maximum input value that needs to
be represented, otherwise it is determined from the max value of the `input`
tensor.
END
  }
  attr {
    name: "signed_input"
    description: <<END
Whether the quantization is signed or unsigned. (actually this parameter should
have been called <b>`signed_output`</b>)
END
  }
  attr {
    name: "num_bits"
    description: <<END
The bitwidth of the quantization.
END
  }
  attr {
    name: "range_given"
    description: <<END
Whether the range is given or should be determined from the `input` tensor.
END
  }
  attr {
    name: "round_mode"
    description: <<END
The 'round_mode' attribute controls which rounding tie-breaking algorithm is
used when rounding float values to their quantized equivalents. The following
rounding modes are currently supported:

*   HALF_TO_EVEN: this is the default round_mode.
*   HALF_UP: round towards positive. In this mode 7.5 rounds up to 8 and -7.5
    rounds up to -7.

END
  }
  attr {
    name: "narrow_range"
    description: <<END
If True, then the absolute value of the quantized minimum value is the same as
the quantized maximum value, instead of 1 greater.
i.e. for 8 bit quantization, the minimum value is -127 instead of -128.
END
  }
  attr {
    name: "axis"
    description: <<END
If specified, this axis is treated as a channel or slice axis, and a separate
quantization range is used for each channel or slice along this axis.
END
  }
  summary: "Quantizes then dequantizes a tensor."
  description: <<END
This is almost identical to QuantizeAndDequantizeV2, except that it returns a
gradient of 1 for inputs that are within the quantization range, or 0 otherwise.
END
}
