op {
  graph_op_name: "ModelDataset"
  visibility: HIDDEN
  in_arg {
    name: "input_dataset"
    description: <<END
A variant tensor representing the input dataset.
END
  }
  summary: "Identity transformation that models performance."
  description: <<END
Identity transformation that models performance.
END
}
