op {
  graph_op_name: "QueueSize"
  visibility: SKIP
  in_arg {
    name: "handle"
    description: <<END
The handle to a queue.
END
  }
  out_arg {
    name: "size"
    description: <<END
The number of elements in the given queue.
END
  }
  summary: "Computes the number of elements in the given queue."
}
