op {
  graph_op_name: "BarrierIncompleteSize"
  in_arg {
    name: "handle"
    description: <<END
The handle to a barrier.
END
  }
  out_arg {
    name: "size"
    description: <<END
The number of incomplete elements (i.e. those with some of their value
components not set) in the barrier.
END
  }
  summary: "Computes the number of incomplete elements in the given barrier."
}
