op {
  graph_op_name: "CompositeTensorVariantFromComponents"
  visibility: HIDDEN
  in_arg {
    name: "components"
    description: "The component tensors for the extension type value."
  }
  out_arg {
    name: "encoded"
    description: "A `variant` Tensor that containing the encoded value."
  }
  attr {
    name: "metadata"
    description: <<END
String serialization for the TypeSpec.  (Note: the encoding for the TypeSpec
may change in future versions of TensorFlow.)
END
  }
  summary: "Encodes an `ExtensionType` value into a `variant` scalar Tensor."
  description: <<END
Returns a scalar variant tensor containing a single `CompositeTensorVariant`
with the specified Tensor components and TypeSpec.
END
}
