op {
  graph_op_name: "Acos"
  summary: "Computes acos of x element-wise."
  description: <<END
Given a tensor `x`, this operation returns a tensor containing the 
arccosine of each element in `x` or in other words it returns the 
inverse of cos of the value.

For Example :

>>> x = tf.constant([1,0], dtype=tf.float16) 
>>> y = tf.math.acos(x)
<tf.Tensor: shape=(2,), dtype=float16, numpy=array([0.  , 1.57], dtype=float16)>
END
}
