op {
  graph_op_name: "Acos"
  summary: "Computes acos of x element-wise."
  description: <<END

  Provided an input tensor, the `tf.math.acos` operation returns the inverse cosine of each element of the tensor. If `y = tf.math.cos(x)` then, `x = tf.math.acos(y)`.

  Input range is `[-1, 1]` and the output has a range of `[0, pi]`.

END
}
