op {
  graph_op_name: "StringLower"
  description: <<END

Examples:
>>> tf.strings.lower(["HELLO", "TensorFlow"])
<tf.Tensor: id=369, shape=(2,), dtype=string, numpy=array([b'hello', b'tensorflow'], dtype=object)>
END
}
