op {
  graph_op_name: "DeserializeIterator"
  in_arg {
    name: "resource_handle"
    description: <<END
A handle to an iterator resource.
END
  }
  in_arg {
    name: "serialized"
    description: <<END
A variant tensor storing the state of the iterator contained in the
resource.
END
  }
  summary: "Converts the given variant tensor to an iterator and stores it in the given resource."
}
