op {
  graph_op_name: "IsInf"
  summary: "Returns which elements of x are Inf."
  description: <<END
@compatibility(numpy)
Equivalent to np.isinf
@end_compatibility

Example:

```python
x = tf.constant([5.0, np.inf, 6.8, np.inf])
tf.math.is_inf(x) ==> [False, True, False, True]
```
END
}
