op {
  graph_op_name: "FloorDiv"
  summary: "Returns x // y element-wise."
  description: <<END
*NOTE*: `FloorDiv` supports broadcasting. More about broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
END
}
