op {
  graph_op_name: "ZerosLike"
  endpoint {
    name: "ZerosLike"
  }
  summary: "Returns a tensor of zeros with the same shape and type as x."
}
op {
  graph_op_name: "Zeta"
  endpoint {
    name: "Zeta"
  }
  summary: "Compute the Hurwitz zeta function \\\\(\\zeta(x, q)\\\\)."
  description: <<END
The Hurwitz zeta function is defined as:


\\(\zeta(x, q) = \sum_{n=0}^{\infty} (q + n)^{-x}\\)
END
}
op {
  graph_op_name: "ZipDataset"
  endpoint {
    name: "ZipDataset"
  }
  summary: "Creates a dataset that zips together `input_datasets`."
}
