# Text form of tensorflow.tf2xla.Config proto.
feed {
  id { node_name: "x" }
  shape {
    dim { size: 2 }
    dim { size: 2 }
  }
}
feed {
  id { node_name: "y" }
  shape {
    dim { size: 2 }
    dim { size: 2 }
  }
}
fetch {
  id { node_name: "result" }
}
