# Description:
# TensorFlow is a computational framework, primarily for use in machine
# learning applications.

licenses(["notice"])  # Apache 2.0

sh_binary(
    name = "parallel_gpu_execute",
    srcs = ["parallel_gpu_execute.sh"],
)
