# Copyright 2026 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
name: CI

on:
  pull_request:
    branches:
      - master
      - r2.**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for master branches.
  cancel-in-progress: ${{ github.ref != 'master' }}

jobs:
  build-linux-x86-cpu:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: 'linux-x86-n2-16'
      tfci: 'py313,linux_x86,rbe,no_docker'

  build-linux-x86-cuda:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: 'linux-x86-n2-16'
      tfci: 'py313,linux_x86_cuda,rbe,no_docker'

  build-arm64:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: 'linux-x86-n2-16'
      tfci: 'py313,linux_arm64_cross_compile,rbe,no_docker,enable_pycpp_build'
      job_name: 'build-only'

  build-windows-x86:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: 'windows-x86-n2-16'
      tfci: 'py313,windows_x86_ml_actions,rbe'
